### ISSUE TITLE
No output even after 10 minutes

### ISSUE THREAD

**Issue by vishaltelangre** [robotframework/robotframework#2398] opened 2016-06-11 08:03 UTC
Here's my stack:

```
robotframework==2.9.2
robotframework-selenium2library==1.7.4
```

This is an example Robot file I have:

```robot
*** Settings ***
Library  Selenium2Library  10

*** Test Cases ***
Dummy Test
    Open Browser  http://google.com  browser=chrome
    # ... omitted keywords below
```
Here's how I run it:

```sh
pybot dummy_suite.robot
```

### Trial 1:

Only this much output I see for more than 10 minutes:

```
==============================================================================

Dummy Suite                                                                        

==============================================================================
```

A blank log.xml file gets generated. No log.html and report.html generated for this trial.
And here's the gist of syslog: https://gist.github.com/vishaltelangre/2ff5ae72e5618c6142703051af8b507c#file-syslog-trial-1-txt

### Trial 2:

In trial 2, for the same test, it finishes in a few second successfully:

```
==============================================================================

Dummy Suite                                                     

==============================================================================

Dummy Test                                                                    | PASS |

1 critical test, 1 passed, 0 failed

1 test total, 1 passed, 0 failed

==============================================================================

Output:  /home/vishal/tmp/log.xml

Log:     /home/vishal/tmp/log.html

Report:  /home/vishal/tmp/report.html
```

Here's the syslog for trial 2: https://gist.github.com/vishaltelangre/2ff5ae72e5618c6142703051af8b507c#file-syslog-trial-2-txt

---

As you can see, no reason why trial 1 was not responding (for more than 10 minutes), but when retried it worked in trial 2 (just in few seconds). 

This behaviour is not reproducible, but happened so many times with me.

Can anybody help me to understand (by looking at the syslog), whether there is any issue with the pybot (or robot framework) itself or not?

**Comment by akshbn** [comment] 2016-06-12 13:03
From the logs, I understand that in **trial 1** robot is stuck at finding/importing selenium. Hence the excess time taken. Since the test cases are not run the xml is empty. 

My 2 cents.

**Comment by vishaltelangre** [comment] 2016-06-12 14:26
With some more trials today, I was able to get the same test to stuck for more than 10 minutes with the [`--debugfile`](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#debug-file) option to pybot command. I was able to retry it successfully in the previous and next tries.

To understand it clearly, I have used the same terms, viz. **trial 1** and **trial 2** alike above. Here are the generated debug files to shed more light on this issue:

- Debug file for trial 1: https://gist.github.com/vishaltelangre/9daf5efe96541d59870012c4d69a9022#file-debugfile-of-trial-1-txt
- Debug file for trial 2: https://gist.github.com/vishaltelangre/9daf5efe96541d59870012c4d69a9022#file-debugfile-of-trial-2-txt

Beside this, I have noticed no difference between the syslog files (and xml files) generated this time with the ones which I had mentioned in the description of this issue earlier.

**Comment by pekkaklarck** [comment] 2016-06-13 08:56
For some reason execution hangs in Open Browser keyword. Apparently there's an issue launching the browser via Selenium and Selenium2Library. Keyword not returning is not a bug in Robot and thus I close this issue. Things you could try:

- Try reproducing the issue with Selenium only. If the same problem occurs also then, please submit an issue to Selenium issue tracker.
- Investigate could Open Browser keyword get an optional timeout argument to control how long to wait for the browser to open.
- Use Robot's [timeout functionality](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#timeouts) to stop the hanging keyword. Notice that a problem with timeouts is that killed keywords may leave resources hanging behind even if test execution would continue.

**Closed by pekkaklarck** 2016-06-13 08:56 UTC

**Comment by vishaltelangre** [comment] 2016-06-13 09:54
@pekkaklarck Thanks a lot for detailed explanation. 

It appears that open browser keyword may be having some issues. I will look into wrapping it up with a timeout in an user keyword as suggested.

**Comment by pekkaklarck** [comment] 2016-06-15 13:28
Yeah, using timeouts ought to be an OK workaround. It would be great if you had time to debug the problem further, though. Based on the findings either Selenium or Selenium2Library could then be enhanced.
