### ISSUE TITLE
robot-jenkins plugin fails to parse output.xml on 2.9b1

### ISSUE THREAD

**Issue by sherif84** [robotframework/robotframework#2054] opened 2015-06-30 20:49 UTC
once i upgraded from 2.9a1 to 2.9b1 the robot-jenkins plugin failed to parse the output.xml , I reverted back to 2.9a1 and it now works fine , below is the error the plugin output , 

it seems to be complaining about a missing xml 'tags' ?  

the error says : "Could not find element tags"

full stacktrace : 
hudson.remoting.Channel@32ba2858:<>: java.io.IOException: Parsing of output xml failed!
	at hudson.FilePath.act(FilePath.java:985)
	at hudson.FilePath.act(FilePath.java:967)
	at hudson.plugins.robot.RobotParser.parse(RobotParser.java:46)
	at hudson.plugins.robot.RobotPublisher.parse(RobotPublisher.java:218)
	at hudson.plugins.robot.RobotPublisher.perform(RobotPublisher.java:241)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:761)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:721)
	at hudson.model.Build$BuildExecution.post2(Build.java:183)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:670)
	at hudson.model.Run.execute(Run.java:1743)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:89)
	at hudson.model.Executor.run(Executor.java:240)
Caused by: java.io.IOException: Parsing of output xml failed!
	at hudson.plugins.robot.RobotParser$RobotParserCallable.invoke(RobotParser.java:100)
	at hudson.plugins.robot.RobotParser$RobotParserCallable.invoke(RobotParser.java:51)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:2688)
	at hudson.remoting.UserRequest.perform(UserRequest.java:121)
	at hudson.remoting.UserRequest.perform(UserRequest.java:49)
	at hudson.remoting.Request$2.run(Request.java:324)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
	at ......remote call to lautomation04(Native Method)
	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1356)
	at hudson.remoting.UserResponse.retrieve(UserRequest.java:221)
	at hudson.remoting.Channel.call(Channel.java:752)
	at hudson.FilePath.act(FilePath.java:978)
	... 13 more
Caused by: javax.xml.stream.XMLStreamException: Could not find element tags (at line: 2212 column: 1)
	at hudson.plugins.robot.RobotParser$RobotParserCallable.xmlException(RobotParser.java:164)
	at hudson.plugins.robot.RobotParser$RobotParserCallable.ignoreUntilStarts(RobotParser.java:205)
	at hudson.plugins.robot.RobotParser$RobotParserCallable.processTest(RobotParser.java:255)
	at hudson.plugins.robot.RobotParser$RobotParserCallable.processSuite(RobotParser.java:145)
	at hudson.plugins.robot.RobotParser$RobotParserCallable.processSuite(RobotParser.java:143)
	at hudson.plugins.robot.RobotParser$RobotParserCallable.processSuite(RobotParser.java:143)
	at hudson.plugins.robot.RobotParser$RobotParserCallable.parseResult(RobotParser.java:119)
	at hudson.plugins.robot.RobotParser$RobotParserCallable.invoke(RobotParser.java:95)
	at hudson.plugins.robot.RobotParser$RobotParserCallable.invoke(RobotParser.java:51)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:2688)
	at hudson.remoting.UserRequest.perform(UserRequest.java:121)
	at hudson.remoting.UserRequest.perform(UserRequest.java:49)
	at hudson.remoting.Request$2.run(Request.java:324)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by pekkaklarck** [comment] 2015-06-30 22:01
Is this the latest Jenkins plugin version?

We changed output.xml so that empty elements are not written there (#2020), so code that expects tests to always contain `<tags>` will fail. We are using Jenkins plugin ourselves without problems, but it could be that all our tests have tags. Could you @jussimalinen test this? We may need an urgent Jenkins plugin release.

**Comment by molsky** [comment] 2015-07-01 07:22
We have also this same problem with 2.9a3 and later versions. Funny thing is that when we tested to run test scripts one by one from our Jenkins job and only some specific tests fails when parsing output.xml file.

**Comment by sherif84** [comment] 2015-07-01 14:48
@pekkaklarck 
"Is this the latest Jenkins plugin version?" 
yes its with the latest Robot Plugin ( v1.6.0) . and yes my test cases don't have tags at this time.

**Comment by jussimalinen** [comment] 2015-07-01 15:30
Right, I better make a new release with a fix as soon as possible.

**Comment by jussimalinen** [comment] 2015-07-02 07:23
https://issues.jenkins-ci.org/browse/JENKINS-29178

**Comment by jussimalinen** [comment] 2015-07-02 07:39
As this is really a Jenkins Plugin issue, I will close this.

**Closed by jussimalinen** 2015-07-02 07:39 UTC

**Comment by simplyviks** [comment] 2020-02-28 10:22
just to confirm have we not reverted this change from RF side.?
i still see this issue with RF 3.1.2 and jenkins robot plugin 1.6.5 , i understand its a jenkins plugin issue just thought of mentioning here.



11:18:53 Failed! 11:18:53 java.io.IOException: Parsing of output xml failed! 11:18:53 at hudson.plugins.robot.RobotParser$RobotParserCallable.setRobotResult(RobotParser.java:151) 11:18:53 at hudson.plugins.robot.RobotParser$RobotParserCallable.invoke(RobotParser.java:82) 11:18:53 at hudson.plugins.robot.RobotParser$RobotParserCallable.invoke(RobotParser.java:58) 11:18:53 at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3052) 11:18:53 at hudson.remoting.UserRequest.perform(UserRequest.java:212) 11:18:53 at hudson.remoting.UserRequest.perform(UserRequest.java:54) 11:18:53 at hudson.remoting.Request$2.run(Request.java:369) 11:18:53 at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72) 11:18:53 at java.util.concurrent.FutureTask.run(FutureTask.java:266) 11:18:53 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 11:18:53 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 11:18:53 at java.lang.Thread.run(Thread.java:748) 11:18:53 Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to 10.133.166.10 - Finland-Cloud1 11:18:53 at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1743) 11:18:53 at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357) 11:18:53 at hudson.remoting.Channel.call(Channel.java:957) 11:18:53 at hudson.FilePath.act(FilePath.java:1072) 11:18:53 at hudson.FilePath.act(FilePath.java:1061) 11:18:53 at hudson.plugins.robot.RobotParser.parse(RobotParser.java:53) 11:18:53 at hudson.plugins.robot.RobotPublisher.parse(RobotPublisher.java:223) 11:18:53 at hudson.plugins.robot.RobotPublisher.perform(RobotPublisher.java:247) 11:18:53 at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:80) 11:18:53 at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:67) 11:18:53 at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47) 11:18:53 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 11:18:53 at java.util.concurrent.FutureTask.run(FutureTask.java:266) 11:18:53 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) 11:18:53 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) 11:18:53 at java.lang.Thread.run(Thread.java:745) 11:18:53 Caused by: javax.xml.stream.XMLStreamException: Could not find elements [doc] (at line: 110165 column: 1) 11:18:53 at hudson.plugins.robot.RobotParser$RobotParserCallable.xmlException(RobotParser.java:254) 11:18:53 at hudson.plugins.robot.RobotParser$RobotParserCallable.ignoreUntilStarts(RobotParser.java:292) 11:18:53 at hudson.plugins.robot.RobotParser$RobotParserCallable.processTest(RobotParser.java:351) 11:18:53 at hudson.plugins.robot.RobotParser$RobotParserCallable.processSuite(RobotParser.java:213) 11:18:53 at hudson.plugins.robot.RobotParser$RobotParserCallable.processSuite(RobotParser.java:211) 11:18:53 at hudson.plugins.robot.RobotParser$RobotParserCallable.processSuite(RobotParser.java:211) 11:18:53 at hudson.plugins.robot.RobotParser$RobotParserCallable.processSuite(RobotParser.java:211) 11:18:53 at hudson.plugins.robot.RobotParser$RobotParserCallable.processSuite(RobotParser.java:211) 11:18:53 at hudson.plugins.robot.RobotParser$RobotParserCallable.processSuite(RobotParser.java:211) 11:18:53 at hudson.plugins.robot.RobotParser$RobotParserCallable.processSuite(RobotParser.java:211) 11:18:53 at hudson.plugins.robot.RobotParser$RobotParserCallable.parseResult(RobotParser.java:169) 11:18:53 at hudson.plugins.robot.RobotParser$RobotParserCallable.setRobotResult(RobotParser.java:145) 11:18:53 ... 11 more
--
