### ISSUE TITLE
Programmatically re-running failed tests prevents subsequent Robot and Rebot usage in same process

### ISSUE THREAD

**Issue by krizex** [robotframework/robotframework#2437] opened 2016-08-31 06:45 UTC
When we use `RobotFramework.main` to execute test suites, we get a `output.xml` result file, then we use `RobotFramework.main` and the `output.xml` to rerun the failed cases in the same process, we get the second result file, naming it `output_rerun.xml`. After that, we use `rebot` api to merge the `output.xml` and `output_rerun.xml` to one result file, naming `output_all.xml`. We find that `output_all.xml` just contains the execution result of the failed cases.

So we checked the source code of robotframework, and we found the error code in robot/conf/settings.py:83
![image](https://cloud.githubusercontent.com/assets/3365993/18118696/1458c010-6f89-11e6-875e-748424215768.png)

We found that code will change the default value of the items of _BaseSettings._cli_opts.
The root cause of this issue is `self['TestNames']` and `_BaseSettings._cli_opts['TestNames'][1]` reference the same list, when execute `self['TestNames'] += self['ReRunFailed']`, equal to change the value of `_BaseSettings._cli_opts['TestNames'][1]`

**Comment by pekkaklarck** [comment] 2016-08-31 19:46
This looks nasty. I want to reproduce this myself before merging the PR. I'll make sure this is included in RF 3.0.1, but it may still take a little time before I have a possibility to concentrate on that release.

**Comment by krizex** [comment] 2016-09-01 00:58
I have added some UT in the PR, you can use it as a reference for your reproducing.

**Comment by Direl** [comment] 2016-09-20 20:16
I too have had this problem when calling both robot.run and robot.rebot from the same Python program.  The attached files demonstrate this problem.  Python (version 2.7) script test2.py runs flip.robot which always passes the first test case run and fails the second.  The outputs from the first run are out1.xml and log1.html.  It then reruns the failed tests in out1.xml producing outputs out2.xml and log2.html.  Finally it tries to merge out1.xml and out2.xml into log3.html.  However log3.html only contains the result of the rerun tests not all of the tests.

The suggested fix for this bug in robot/conf/settings.py also solves my problem. 

[Friday.zip](https://github.com/robotframework/robotframework/files/483512/Friday.zip)

**Comment by pekkaklarck** [comment] 2016-09-20 20:31
Seems to be a more common problem. Updated priority accordingly.

**Comment by pekkaklarck** [comment] 2016-09-22 21:08
Looking at the added unit tests, I noticed there's a similar test added when a similar issue #881 was fixed five years ago. Strange that nobody had encountered this variation earlier.

**Comment by pekkaklarck** [comment] 2016-09-22 22:41
Thanks a lot for the bug report and PR @krizex! The PR was merged as 9f1490e7a9bae5b61484ca8d5be05f4fb4799137 and I did some enhancements to it in c45a051b9964e694f848f78d1c228bd7cd175369. This issue is done.

**Closed by pekkaklarck** 2016-09-22 22:41 UTC
Labels: bug, prio-high

**Comment by krizex** [comment] 2016-09-23 01:26
> UPDATE: This problem seems to only occur when using --rerunfailed option. It updates TestNames setting inplace while others seem to replace values altogether. This would explain why nobody has encountered this before at least before --rerunfailed existed. If this is the only option causing the issue, I'll update the title of this issue accordingly.

@pekkaklarck  Yes, you figure out the root cause. I think it's better to separate the instance's attributes and class's attributes, so I copy the value from class to instance as the PR did rather than just modify the code of updating `TestNames`

Thanks for your enhancements.

**Comment by pekkaklarck** [comment] 2016-09-23 08:31
@krizex: I agree it's better to avoid all potential problems with mutable objects rather than just fixing the issue with `--rerunfailed` updating `TestNames`. I wanted anyway to change the issue title to match the actual problem.

**Comment by krizex** [comment] 2016-09-23 09:16
I am agree with you, the title you changed is ok.
