### ISSUE TITLE
[Bug] robot:flatten shows log lines while log level is set to NONE

### ISSUE THREAD

**Issue by MobyNL** [robotframework/robotframework#4986] opened 2023-12-19 12:30 UTC
I think there might be a bug in the usage of robot:flatten as a keyword.

If I use robot:flatten as a tag on a keyword, in combina
![image](https://github.com/robotframework/robotframework/assets/59473010/c14baee9-1dcd-43f2-9988-f36e11b21f26)
tion with `Set Log Level  NONE`, I can still see all logging from keywords that are run in my parent keyword.
See this convo in the slack for more explanation https://robotframework.slack.com/archives/C3C28F9DF/p1702978282275129

I used the following code to test this

```
*** Test Cases ***
Test For Flatten
    Do Something Without Logging

*** Keywords ***
Do Something Without Logging
    [Tags]              robot:flatten  #this can be commented for the 2 situations
    Set Log Level       NONE
    FOR    ${_}    IN RANGE    0    10
        Log             Text
        ${variable}     Set Variable    7
    END
    Set Log Level       INFO
    Log                 This Should Be Logged ${variable}
```

I would except the logging to show:
`Log level set to None
This Should Be Logged 7`

However. All of the `Log  Text` and variable returns etc. are also logged. If I use `--flattenkeywords` from the CLI, this (wrong) additional logging is not visible as expected. It probably has to do with the fact that I only flatten "Do Something Without Logging", an not Log or Set Variable. But --flattenkeywords also takes care of this behaviour

robot:flatten usage:
![image](https://github.com/robotframework/robotframework/assets/59473010/d727148b-47bc-40d8-8d39-97e9dce97d2e)

CLI option:
![image](https://github.com/robotframework/robotframework/assets/59473010/70661f67-36b4-412c-a936-8de1a22f8fec)

I think the expected behaviour is that the robot:flatten and --flattenkeyword for this case should be equal.

If this is expected behaviour, the robot framework user guide might be wrong, as it states:
_Using this tag will work similarly as the command line option described in the previous chapter, e.g. all content except for log messages is removed from under the keyword having the tag. One important difference is that in this case, the removed content is not written to the output file at all, and thus cannot be accessed at later time._

**Comment by pekkaklarck** [comment] 2023-12-19 14:46
This seems to be a duplicate of #4921 that was fixed in RF 7.0 alpha 1.

**Closed by pekkaklarck** 2023-12-19 14:46 UTC
