### ISSUE TITLE
UnicodeDecodeError in case of importing error

### ISSUE THREAD

**Issue by NVoronchev** [robotframework/robotframework#2349] opened 2016-03-25 09:45 UTC
I have Robot Framework 3.0 downloaded by pip (version updatet on 2015-12-31). While importing a custom Robot library with an error in source code, I get the following exception:
```
[ ERROR ] Unexpected error: UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 1114: ordinal not in range(128)
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\robot\utils\application.py", line 80, in _execute
    rc = self.main(arguments, **options)
  File "C:\Python27\lib\site-packages\robot\run.py", line 434, in main
    result = suite.run(settings)
  File "C:\Python27\lib\site-packages\robot\running\model.py", line 247, in run
    self.visit(runner)
  File "C:\Python27\lib\site-packages\robot\model\testsuite.py", line 160, in visit
    visitor.visit_suite(self)
  File "C:\Python27\lib\site-packages\robot\model\visitor.py", line 83, in visit_suite
    if self.start_suite(suite) is not False:
  File "C:\Python27\lib\site-packages\robot\running\runner.py", line 72, in start_suite
    ns.handle_imports()
  File "C:\Python27\lib\site-packages\robot\running\namespace.py", line 54, in handle_imports
    self._handle_imports(self._imports)
  File "C:\Python27\lib\site-packages\robot\running\namespace.py", line 65, in _handle_imports
    self._import(item)
  File "C:\Python27\lib\site-packages\robot\running\namespace.py", line 73, in _import
    action(import_setting)
  File "C:\Python27\lib\site-packages\robot\running\namespace.py", line 127, in _import_library
    import_setting.alias, self.variables)
  File "C:\Python27\lib\site-packages\robot\running\importer.py", line 41, in import_library
    lib = TestLibrary(name, args, variables, create_handlers=False)
  File "C:\Python27\lib\site-packages\robot\running\testlibraries.py", line 49, in TestLibrary
    return_source=True)
  File "C:\Python27\lib\site-packages\robot\utils\importer.py", line 71, in import_class_or_module
    self._raise_import_failed(name, err)
  File "C:\Python27\lib\site-packages\robot\utils\importer.py", line 107, in _raise_import_failed
    raise DataError('\n'.join(msg))
```
The root of this exception is non-ASCII symbols in "bad" string of code . For example, it may be a Cyrillic comment (the following library is saved in `m_test.py` with UTF-8 encoding):
```
# -*- coding: utf-8 -*-
a = b  # +кириллический комментарий+
```
Changing the 102th string in `importer.py` to `msg = [msg, error.details.decode(errors='ignore')]`, one get a message like this one:
```
[ ERROR ] Error in file 'Z:\test.robot': Importing test library 'm_test' failed: NameError: name 'b' is not defined
Traceback (most recent call last):
  File "z:\m_test.py", line 2, in <module>
    a = b  # ++
```

**Comment by pekkaklarck** [comment] 2016-03-25 13:25
I'm fairly certain you have invalid encoding or encoding config somewhere. If not, please provide an executable example that we can use to reproduce the problem.

**Comment by pekkaklarck** [comment] 2016-06-01 09:05
Closing due to lack of information.

**Closed by pekkaklarck** 2016-06-01 09:05 UTC
