### ISSUE TITLE
Back navigation does not work properly in HTML outputs (log, report, Libdoc)

### ISSUE THREAD

**Issue by karniemi** [robotframework/robotframework#4754] opened 2023-05-04 05:03 UTC
We are just Upgrading from 3.x to 6.0.2.

Getting back to report.html from log.html requires 3 clicks on Back button. This is quite irritating.

Steps to reproduce:
1) from testreport.html, open a testcase. This takes to log.html, url ends like "log.html#s1-s2-s29-t6".
2) click Back. Still in log.html. url ends like "log.html#"
3) click Back. Still in log.html. url ends like "log.html#s1-s2-s29-t6"
4) click Back. Only now,, we are back in report.html

**Comment by karniemi** [comment] 2023-05-04 06:15
Further, we also noticed this problem in 4.x, which we decided to skip.

**Comment by pekkaklarck** [comment] 2023-05-04 17:01
I've noticed something like this as well. The must be somehow related to how navigating to internal targets works. I'm somewhat surprised it used to work better earlier.

A problem with this issue is that the log/report tech is badly outdated and we plan to replace it with something better soonish, hopefully already in RF 7.0. This means that spending time enhancing the current log/report will be kind of wasted. That's not an issue if the fix is simple, but another part of the problem is that current log/report code is also pretty annoying.

Getting this fixed in RF 6.1. would be great, I personally don't have time to investigate this at least in the near future. It would be awesome if someone else could look at it.

**Comment by karniemi** [comment] 2023-05-05 03:24
Thanks @pekkaklarck ! I had a peek on it.

It would seem to be caused by these lines:
https://github.com/robotframework/robotframework/blob/c926198fa8ab7733147e008c29c440dfa746cce0/src/robot/htmldata/rebot/report.html#L268-L269

In a saved log.html, I tested commenting out the line that sets the hash empty - and the problem was no more. So, at least in Firefox, setting  window.location.hash ends up in navigated history.

There seems to be some difference between browsers, though:
* https://stackoverflow.com/questions/58128939/changing-window-location-hash-creates-entry-in-history-but-doesnt-affect-chrome

**Comment by karniemi** [comment] 2023-05-05 06:53
I just noticed that about the same happens in report.html, with Firefox
1) open report.html, url ends like "robot/report/report.html"
2) click "All Tests", url ends like "robot/report/report.html#totals"
3) click Back. Still in report.html,  url ends like "robot/report/report.html#"
4) click Back. Still in report.html,  url ends like "robot/report/report.html"
5) click Back. Only now, we are back where we came from

**Comment by pekkaklarck** [comment] 2023-06-02 07:04
It's true that the issue is caused by cd470292fd51b805c6c0185c422d275ad554b14b that fixed #2881. The idea was that when we do `window.location.hash = ''` before setting `hash` to a new value, browsers always scroll to that hash. Unfortunately that seems to add new history entries making back navigation annoying.

Your monkey-patch avoids doing `window.location.hash = ''` and fixes back navigation but it also reintroduces #2881. I tested that locally and, for example, clicking a test in report didn't scroll to a correct place in the log file using Chrome.

After investigating this a bit more, I noticed that we can use [Element..scrollIntoView()](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) to scroll to the right place and the `window.location.hash = ''` hack isn't needed. That would have been a much better fix for #2881 in the first place. I'm not sure didn't we just notice that back then or was it considered not supported widely enough. Anyway, the [support looks great](https://caniuse.com/?search=scrollIntoView) nowadays, especially without any configuration, so it ought to be a totally safe option.

**Comment by pekkaklarck** [comment] 2023-06-02 07:09
I'll commit the fix and close this issue shortly. It would be awesome if you @karniemi could test the fix in your environment. You can monkey-patch your log/report even more, test the latest code, or wait for RF 6.1 rc 1 that's hopefully released soon.

**Closed** 2023-06-02 08:11 UTC
Labels: priority: medium, rc 1, effort: small
