### ISSUE TITLE
Honor `SOURCE_DATE_EPOCH` environment variable when generating library documentation

### ISSUE THREAD

**Issue by Apteryks** [robotframework/robotframework#4262] opened 2022-03-08 20:40 UTC
This leads to nondeterminism in the build artifacts (the documentation) of RobotFramework itself or its libraries.  The issue was discovered at the time RobotFramework was packaged for GNU Guix.  For more context and the associated [pull request](https://github.com/robotframework/robotframework/pull/3140).

**Comment by pekkaklarck** [comment] 2022-03-09 09:01
The PR referenced above was closed in favor of #4263. I hopefully have time to look at it later today. If it looks fine, we can still get this into RF 5.0.

**Comment by pekkaklarck** [comment] 2022-03-10 10:04
My understanding is that the idea of `SOURCE_DATE_EPOCH` is being able to generate reproducible builds. When packaging Robot Framework itself, we don't include date/time information anywhere, we only include the version number. As explained in BUILD.rst, our packages are created using setup.py:

```
python setup.py sdist --formats zip bdist_wheel
```

Version information is in `setup.py` itself and in `src/robot/version.py`, and they are both maintained using `invoke` as also explained in BUILD.rst. Version information has been set and committed before creating a tag, so you can recreate same package by checking out the same version control tag and using `setup.py` yourself.

Based on the discussion in #4263, the main motivation for `SOURCE_DATE_EPOCH` in our context is having consistent time information in generated library documentation. Libdoc outputs contain both the version information and generation date, so you cannot regenerate the exact same outputs that have been created earlier. I don't really understand why the generation time out HTML files really matters, but if it helps third-party packaging I'm fine making it configurable.

The initial implementation in #4263 had a problem that all calls to get the current timestamp required checking is the `SOURCE_DATE_EPOCH` environment variable available. We need start and end timestamp for each test, keyword, loop iteration, etc. during execution, so this code is _very_ performance critical. Checking environment variables is fast but not free, and doing that only to be able to regenerate exactly same Libdoc HTML outputs is not an important enough reason to slow down execution. The implementation needs to change and we already discussed about alternatives in the PR.

`SOURCE_DATE_EPOCH` affecting `robot.utils.get_timestamp` would also mean that if that environment variable is set, all start and end times in log and other outputs would be same. That would then mean that all elapsed times would be zero. We could argue that it allows having reproducible times, but I see absolutely no real use case for such configuration in this context.

Another problem with the approach in #4263 is that it doesn't affect the generation time at the end of the User Guide. That time is se by passing `--time` to `doctuils` and based on my testing `docutils` doesn't honor `SOURCE_DATE_EPOCH`. We could avoid the problem by adding the generation time to the User Guide footer ourselves and not using `--time` at all.

**Comment by pekkaklarck** [comment] 2022-03-10 10:15
Based on my understanding on why `SOURCE_EPOCH_DATE` is useful and based on findings explained in the above comment, I believe the best way forward would be:
1. Change Libdoc code so that it checks `SOURCE_EPOCH_DATE` and formats the generation time based on it when set. Libdoc doesn't need to use `get_timestamp` at all for this, it could very easily use `datetime.datetime` for that.
2. Change User Guide generation so that it also takes `SOURCE_EPOCH_DATE` into account.
3. Don't use `SOURCE_EPOCH_DATE` for anything during execution.

Does the above sound feasible @Apteryks? If yes, let's aim for that. Since there would be no code changes affecting execution, and changes to Libdoc ought to be trivial, we could do them even after RF 5.0 rc 1 that I hopefully get done today. Possibly the Libdoc change could even make it to the rc.

**Comment by Apteryks** [comment] 2022-03-10 14:24
> Does the above sound feasible @Apteryks?

Yes, it sounds reasonable!  I'll give it a spin.

**Comment by pekkaklarck** [comment] 2022-03-10 18:18
It turned out Libdoc XML spec files have yet another place where generation time is used and that would also need to look for `SOURCE_DATE_EPOCH`. It probably would be best to have some generic utility for getting the current time in some uniform format (or possibly as a `datetime` object that can then be formatted) so that it looks at `SOURCE_DATE_EPOCH`. That function most likely _should not_ be used when generating timestamps during execution due to the extra overhead needed for querying environment variables.

Due to there being several places to be enhanced, @Apteryks and I agreed on Slack to wait until RF 5.1 before doing that. We already have #4258 related to timestamp enhancements targeted for RF 5.1 and these two issues can be looked at together.

**Comment by Apteryks** [comment] 2022-03-10 22:01
The above branch is fixes all the timestamp sources in the doc (libdoc for HTML, JSON or XML output) and gets ride of it altogether for the user guide. It's bare bone, but can be refined after/at the time #4258 is worked on.

**Comment by Apteryks** [comment] 2022-03-11 02:57
@pekkaklarck Hi! I hope https://github.com/Apteryks/robotframework/commit/c748005bd13979ae0c3536c65f97950cb59cb6fa combines the total output of our discussions thus far and converges to something suitable.  Thanks!

**Comment by Apteryks** [comment] 2022-03-21 01:21
I just realized the PR had been closed by mistake (I had recreated the branch).  I've fixed that now, see above.  Thank you!

**Comment by pekkaklarck** [comment] 2022-05-27 19:39
PR #4286 changes generation time in Libdoc's XML spec file from `2022-05-27T19:08:42Z` to `2022-05-27T19:07:15+00:00`. They ought to mean the exact same thing, but because external tools may be dependent on the exact format this change is backwards incompatible and needs to be mentioned in the release notes.

**Comment by pekkaklarck** [comment] 2022-05-28 14:24
Generation time changes also in Libdoc JSON spec files. That changes from a naive timestamp like `2022-05-27 22:08:42` to `2022-05-27T19:07:15+00:00` i.e. to the same format that's used with XML specs. That change is definitely an enhancement but also a backwards incompatible.

**Closed** 2022-06-02 22:15 UTC
Labels: enhancement, priority: medium, backwards incompatible

**Comment by pekkaklarck** [comment] 2022-06-02 22:16
Fixed by PR #4286. Thanks for contribution @Apteryks!
