### ISSUE TITLE
Re-run test suite instead of tests

### ISSUE THREAD

**Issue by cdeokar** [robotframework/robotframework#2117] opened 2015-08-24 07:23 UTC
Is there any way which will facilitate to re-run failed test suites?

**Comment by pekkaklarck** [comment] 2015-08-24 08:41
No. Are you proposing to add something like that? Are you interested to implement it?

**Comment by satish88** [comment] 2015-08-31 17:38
I had the same requirement where test cases in a test suite were dependent on each other.
I achieved it with a hack where I processed the output.xml to mark all the test cases as failed, if even a single test case failed in a test suite. 
Anyway, I want to offer me to implement it in more cleaner way, if it is yet to be implemented

**Comment by pekkaklarck** [comment] 2015-09-04 08:17
Would something like `--rerunfailedsuites` be a good idea? If someone is interested to implement it, I'd be happy to merge a pull request and also help if needed. 

Implementation ought to be pretty easy otherwise, but handling non-critical failures may require a little extra work. Only suites with critical failures are considered failed by Robot, and I think this functionality should follow the same logic. The problem is that the result model parsed from the output.xml file won't have any information about criticality. This hopefully can be fixed pretty easily by configuring the result model with same criticality information (`--critical` and `--noncritical` options) as the suite that is about to be executed.

**Comment by pekkaklarck** [comment] 2015-10-09 11:45
Anyone interested about `--rerunfailedsuites` enough to provide a pull request? If not, I'll close this issue. If you are but are new to pull requests and contributing, you can start by reading these guidelines:
https://github.com/robotframework/robotframework/blob/master/CONTRIBUTING.rst

**Comment by jussimalinen** [comment] 2015-11-23 09:54
There seems to be no interest for this. Can be reopened if someone feels like doing this.

**Comment by antechrestos** [comment] 2016-12-05 20:15
I started implementing it. I made a *WIP* [merge requests](https://github.com/robotframework/robotframework/pull/2487)

**Comment by pekkaklarck** [comment] 2016-12-06 19:30
We now got PR #2487 with a very promising implementation. Reopening and assigning to RF 3.0.1 scope.

**Comment by pekkaklarck** [comment] 2016-12-29 19:10
Finally looking at PR #2487 by @antechrestos now and it looks pretty good. Started to think should we anyway run suites that have *any* failed tests without thinking criticality? I know I proposed taking criticality into account above, but now that I think about it running all suites with failed tests somehow sounds better. It would also simplify implementation a little.

**Comment by antechrestos** [comment] 2016-12-29 19:16
@pekkaklarck I will change my implementation by tomorrow. I agree with you, that might be confusing if non critical failed are not re-run...

**Comment by pekkaklarck** [comment] 2016-12-29 19:20
I can easily change the implementation myself if we agree that's the better implementation. I already got the PR in a local branch to go through the changes. Can do little cleanups at the same time if needed.

**Comment by pekkaklarck** [comment] 2016-12-29 19:21
@antechrestos, are you on Slack? Just asked an opinion about this there too. https://robotframework-slack.herokuapp.com/

**Comment by pekkaklarck** [comment] 2016-12-29 19:34
Well, I can leave it for you too if you have time for it tomorrow. I'm trying to get RF 3.0.1 out, preferably still this year, and thus a little in a hurry. I got other tasks to do too so if you can change this it'll be great! I'll mark some of the things I noticed that should/could be fixed as review comments.

**Comment by antechrestos** [comment] 2016-12-29 19:36
OK I treat it tomorrow morning French hour. Thanks for the comment, I'll take them into account.

**Closed** 2016-12-30 21:35 UTC
Labels: priority: medium

**Comment by pekkaklarck** [comment] 2016-12-30 21:37
Thanks a lot @antechrestos for a great PR!
