### ISSUE TITLE
Suite Setup details are collapsed in case of Failed Setup

### ISSUE THREAD

**Issue by Pawci3oo** [robotframework/robotframework#3555] opened 2020-04-26 20:12 UTC
In my framework, there are many keywords that are being executed in Suite Setup before the tests.
In case of failed Suite Setup, I have to manually open each keyword to see what happened.
Is there a possibility or option to expand details of Suite Setup after Report.html opening?

Example:
Currently, it looks something like this:
![image](https://user-images.githubusercontent.com/26310305/80318478-b4a53d80-880a-11ea-9ac6-753fec80fe73.png)

I want to be like Test Setup:

![image](https://user-images.githubusercontent.com/26310305/80318494-d272a280-880a-11ea-9f01-9485edd77c0b.png)

**Comment by pekkaklarck** [comment] 2020-04-29 19:53
How did you open the log file? Did you open it directly or did you first open report and then click a test there?

**Comment by Pawci3oo** [comment] 2020-04-29 19:58
I always open report.html file first and then specific test.

**Comment by pekkaklarck** [comment] 2020-04-30 07:37
OK, in that case the current functionality is by design. I guess it would be OK to change the functionality so that also possible failed suite setups are opened, but don't personally consider that too high priority. Are you interested to look at implementing this?

**Comment by Pawci3oo** [comment] 2020-04-30 12:39
Yes, sure but I'm not a python expert so if you don't mind I will ask you if I need any information.
Please provide location where mentioned implementation exists.

**Comment by pekkaklarck** [comment] 2020-04-30 13:47
This is actually implemented in log.html itself using Javascript. The template that's used when the file is created is linked below. The change should go to it or to some of the js-files it uses internally.

https://github.com/robotframework/robotframework/blob/master/src/robot/htmldata/rebot/log.html

**Comment by pekkaklarck** [comment] 2021-03-03 16:23
No updates in close to a year. Closing.

**Closed by pekkaklarck** 2021-03-03 16:23 UTC
