### ISSUE TITLE
Logging when timeouts are enabled may corrupt output

### ISSUE THREAD

**Issue by MonSap** [robotframework/robotframework#2839] opened 2018-05-14 13:08 UTC
Hi ,

I am getting below error randomly.Can someone pls help.

03:21:45   File "/usr/lib/python2.7/site-packages/pabot/result_merger.py", line 140, in merge
03:21:45     settings.non_critical_tags, tests_root_name)
03:21:45   File "/usr/lib/python2.7/site-packages/pabot/result_merger.py", line 127, in merge_groups
03:21:45     non_critical_tags).values():
03:21:45   File "/usr/lib/python2.7/site-packages/pabot/result_merger.py", line 118, in group_by_root
03:21:45     res = ExecutionResult(src)
03:21:45   File "/usr/lib/python2.7/site-packages/robot/result/resultbuilder.py", line 47, in ExecutionResult
03:21:45     return _single_result(sources[0], options)
03:21:45   File "/usr/lib/python2.7/site-packages/robot/result/resultbuilder.py", line 71, in _single_result
03:21:45     raise DataError("Reading XML source '%s' failed: %s" % (unic(ets), error))
03:21:45 robot.errors.DataError: Reading XML source '/var/lib/jenkins/workspace/Pabot/results/pabot_results/Test case 001xxx/original.xml' failed: Incompatible XML element 'errors'.

Command used is 
pabot --processes 8 -v res_LAB:${LAB} -v res_BROWSER_TYPE:gc - --outputdir ${results_folder} --output original.xml ${WORKSPACE}/test_cases",

**Comment by Noordsestern** [comment] 2018-05-17 07:50
I can confirm that. We experimented also with pabot a year ago. My guess is that something goes wrong when several threads write to the same pabot_result output file.

The errors are not exactly reproducable. We had like 200 Tests in parallel running over several hours. The error occured almost every time but at different testcases. Therefore you could say they happen "randomly".

**Comment by pekkaklarck** [comment] 2018-05-22 14:40
This kind of errors most often occur when results from different simultaneous test runs are accidentally written into same file. Alternatively tests could be run in threads (which is not generally supported) and output is not written in correct order. The problem could be in pabot, in your setup, or possibly in Robot itself. Unfortunately it's pretty much impossible even to guess where/why it occurs based on just this information. If you can provide a simple example demonstrating the problem, then it's possible to debug it.

**Comment by skhomuti** [comment] 2018-08-14 11:32
I confirm this problem, we very often catch it on one of the test stands. In other stands is much rarer. Why - I do not understand, the stands are exactly the same. At this moment, the problem is reproduced on this stand almost in every second launch, so it is very critical for us, but it is reproduced with such frequency only with a full run. I could not play on some test examples. What information can I provide to help solve this problem? How to debug this?

**Comment by pekkaklarck** [comment] 2018-08-14 12:49
You would need to provide a simple example that I can execute on my machine. It should not use external tools like Pabot.

**Comment by skhomuti** [comment] 2018-08-14 12:58
I'm not sure that this is the error, but in this example output.xml is defective:
test.robot
```
*** Settings ***
Library  ../lib.py    WITH NAME    Lib

*** Test Cases ***

Case1
    [Timeout]  10 sec
    Lib.Some Keyword
```
lib.py
```
from robot.api import logger

class lib(object):

    def some_keyword(self):
        str = ''
        i = 1
        while True:
            str = '{}{}'.format(str, i)
            logger.info(str)
            i += 1
```
`[ ERROR ] Reading XML source 'C:\Temp\untitled\output.xml' failed: Incompatible XML element 'msg'.`

I'll try to reproduce in other ways

**Comment by pekkaklarck** [comment] 2018-08-17 10:44
Hmm, I can see that the above example can corrupt the `output.xml` if the timeout occurs example when `logger.info` is executing. This is an inherit problem with timeouts, they can stop operations half way and leave the environment, tested system, or Robot Framework itself into an unstable state. They should only be used if absolutely necessary. That said, I can think could we somehow protect `logger` from timeouts. In addition to avoiding timeouts, an other workaround is logging using `print()` because such messages are only processed after they keyword has been executed and shouldn't be affected by timeouts.

**Comment by pekkaklarck** [comment] 2018-08-17 10:46
There are so often reports about corrupted `output.xml` files that getting some of the problems fixed by somehow protecting `logger` would be great. I'll add this tentatively to RF 3.1 scope to make it sure we remember to at least look at this.

**Comment by jgibbarduk** [comment] 2018-09-28 15:19
Hi - Is there any update on this? We are seeing this issue repeatedly. Is there any workaround that can be done while a fix is produced? Thanks.

**Closed** 2018-10-09 11:55 UTC
Labels: acknowledge, beta 1, bug, priority: critical

**Comment by fablefactor** [comment] 2024-04-16 08:55
Hi @pekkaklarck I Just  want to mention that we are seeing problems with this fix. When we add a timeout to a keyword the fix means that output.xml now gets cached. But when a timeout occurs, the cached output.xml is not flushed to disk, so we cannot see the log and analyze what went wrong without rerunning the simulation...
Please add a flushing mechanism to the caching of output.xml and call/trigger it when a timeout occurs. Should be simple? :-)
