### ISSUE TITLE
Appium crash since robotframework 3.2

### ISSUE THREAD

**Issue by ericmerisier** [robotframework/robotframework#3559] opened 2020-04-27 19:18 UTC
AppiumLibrary . Open Application ${appiumServer}, automationName=uiautomator2, platformName=Android, deviceName=Android, appPackage=${appPackage}, appActivity=${appActivity}, app=${app}

Keyword 'AppiumLibrary.Open Application' expected 2 to 3 non-named arguments, got 1.

**Comment by pekkaklarck** [comment] 2020-04-27 20:17
Which RF version you used earlier? Are you certain you use exact same setup otherwise?

**Comment by ericmerisier** [comment] 2020-04-27 21:00
I was using version 3.1.2
My test has not changed between yesterday and today.
Meanwhile, I had a batch script doing a "pip upgrade" that took version 3.2 of RBF. (diff of pip freeze)

**Comment by pekkaklarck** [comment] 2020-04-28 08:38
There was a similar sounding problem with FakerLibrary reported on our Slack but looking at AppiumLibrary code this doesn't seem to be caused by the same problem. I clearly need to debug this further.

I have zero experience with AppiumLibrary, so would be grateful if you could give simple instructions how to reproduce this. Is it enough to just install AppiumLibrary and use `Open Application`? Which library version did you use?

**Comment by pekkaklarck** [comment] 2020-04-28 09:36
It actually seems that the FakerLibrary issue I mentioned above (now also reported as #3560) and this issue have the same root cause.

**Comment by ericmerisier** [comment] 2020-04-28 10:15
![image](https://user-images.githubusercontent.com/57590568/80475563-55017c00-8949-11ea-8202-bbb6543c7344.png)

It is complicated to set up an appium environment (sdk_android, appium server, device or virtual device with android studio)
But without launching the test I already have syntax errors on the passage of the arguments on all the keywords appium.
if I put "self", I have no syntax error but the test also fails.

**Comment by pekkaklarck** [comment] 2020-04-28 10:19
I have a fix for the FakerLibrary issue ready and it ought to fix this issue as well.. Once I got it committed, it would be great if you could test it in your environment.

**Comment by pekkaklarck** [comment] 2020-04-28 10:51
This ought to be now fixed by b43f5823407030940823ae2a477ac6f5b98c3ed1. I would be grateful if you could test the fix in your own environment. You can do that by installing the latest code like this:

    pip install https://github.com/robotframework/robotframework/archive/master.zip

**Comment by ericmerisier** [comment] 2020-04-28 11:46
Great job, this version fix this issue :)

Successfully uninstalled robotframework-3.2
Successfully installed robotframework-3.2.1.dev1

**Comment by pekkaklarck** [comment] 2020-04-28 23:07
Great to hear and thanks for testing! I'll close this one as a duplicate of #3561 that explains the underlying issue in more details.

**Closed by pekkaklarck** 2020-04-28 23:07 UTC
