### ISSUE TITLE
Libdoc: Support setting dark or light mode explicitly

### ISSUE THREAD

**Issue by mardukbp** [robotframework/robotframework#4497] opened 2022-10-06 11:01 UTC
The HTML documentation generated by libdoc can be opened in an IDE, where many people use a dark theme. The contrast between the Robot Framework code on a dark background and the library documentation with a white background is unpleasant. 

This problem can be solved if libdoc has a stylesheet parameter to specify the CSS file that should be used to style the documentation. And maybe libdoc should include a light and a dark stylesheet.

**Comment by pekkaklarck** [comment] 2022-10-06 17:26
This is a good idea and injecting a custom style sheet wouldn't be too complicated. The problem is that we are planning to totally reimplement Libdoc's HTML output (#4304) and that would break all such external style sheets. A related issues that if we allow injecting styles, the whole HTML structure becomes part of the public API and we cannot change it without possibly breaking external styles. At this point it's probably best to wait until we get started with #4304 until we make a decision about that. I'll add a comment about this to that issue. Until this is resolved, you can pretty easily inject styles to the generated HTML file.

Support for dark and light modes is a different thing because it could be just enabled externally and how it actually works would be an implementation detail. More importantly, I think Libdoc already supports the dark mode but I don't know how it's actually activated nor that is there a way to do that programmatically. Ping @Snooz82!

**Comment by mardukbp** [comment] 2022-10-07 13:29
You are right. libdoc.css already supports dark mode, but only if configured in the OS. I think adding [a button to manually toggle the dark mode](https://stackoverflow.com/a/68824350/3534491) would be a good idea.

**Comment by pekkaklarck** [comment] 2022-10-07 21:59
Adding a button sounds good to me. Are you interested to provide a PR?

For IDE interaction there probably should be an API to switch between modes as well. Do @d-biehl or @fabioz have opinions about this?

If enhancements are added fast, they can still make it to RF 6.0. We need another release candidate and my current plan is to release it next Monday.

**Comment by Snooz82** [comment] 2022-10-07 22:09
It is not the os defining the color scheme.
It is the browser. But by default the browser takes it from os.

not sure if a switch makes sense. Your browser has a switch for that already.

**Comment by d-biehl** [comment] 2022-10-07 22:29
I like the idea. And an API would be even better.

@Snooz82, in Vscode and in most new apps meanwhile you can use the system settings or set your own mode. Then the system would be e.g. Dark and the app Light. In Vscode you can even define default themes for the respective system theme.

An advanced idea, In Vscode there are predefined CSS constants for the color scheme that is in use and you can use these in your own sheets. Maybe it would be possible to change the CSS stylesheet of the libdoc via API?

**Comment by pekkaklarck** [comment] 2022-10-08 12:06
As I commented above, we cannot really make CSS itself configurable until #4304 has been implemented. We'd most likely break all external styles at that point anyway. Even after that defining what parts of the HTML structure are considered public/stable can be tricky.

A toggle to switch between the already supported dark and light modes would be fine because such a toggle can be preserved in the rewrite. I don't see a problem with a visible toggle because I doubt it's common knowledge where in the browser to enable the dark mode and having a toggle would also make it explicit that a dark mode exists. The hover text could mention that the default is set by the browser and then user could figure out where to change that. I don't know how hard this would be to implement and since this is UI code also styles need to be though a bit. If someone is interested to implement such a toggle, it would be great to have a PR latest on Monday when I plan to release RF 6.0 rc 2.

Although a toggle for humans would be nice, I agree with @d-biehl that an API would be nicer as it would allow editor plugins to control the mode. An API would probably be easier to design than a visible toggle so getting this into RF 6.0 ought be doable. Are you  @d-biehl interested to provide a PR?

**Comment by d-biehl** [comment] 2022-10-09 06:29
Let me finish the other PR first. And then I'll take a look at it. But I don't think I'll make it until Monday. Tuesday or Wednesday more likely.

**Comment by Snooz82** [comment] 2022-10-10 13:22
I do not get it!

the page shows the content theme based on the setting of the browser.
Why forcing anything?

**Comment by pekkaklarck** [comment] 2022-10-10 13:39
The original description has this:
> The HTML documentation generated by libdoc can be opened in an IDE, where many people use a dark theme. The contrast between the Robot Framework code on a dark background and the library documentation with a white background is unpleasant.

Based on that my understanding is that the browser embedded to an IDE uses browser theme, not IDE theme, and it would be convenient to be override that.

**Comment by pekkaklarck** [comment] 2022-10-10 13:45
I got `--theme` option implemented. Below are changes to HTML and CSS files. Changes to Python files are pretty trivial.

If the changes look fine, and we agree this is a good idea, I can add some tests for the Python side and commit this. We can also agree to not do this now or decide this isn't a good idea in general and just close this issue. I guess @d-biehl and @fabioz as IDE developers have best opinion is this useful or not.

```diff
index 1c9aa8028..1eb8e41b2 100644
--- a/src/robot/htmldata/libdoc/libdoc.css
+++ b/src/robot/htmldata/libdoc/libdoc.css
@@ -10,19 +10,17 @@
     --link-color: #0000ee;
 }
 
-@media (prefers-color-scheme: dark) {
-    :root {
-        --background-color: #1c2227;
-        --text-color: #e2e1d7;
-        --border-color: #4e4e4e;
-        --light-background-color: #002b36;
-        --robot-highlight: yellow;
-        --highlighted-color: var(--background-color);
-        --highlighted-background-color: yellow;
-        --less-important-text-color: #5b6a6f;
-        --link-color: #52adff;
-        color-scheme: dark;
-    }
+[data-theme="dark"] {
+    --background-color: #1c2227;
+    --text-color: #e2e1d7;
+    --border-color: #4e4e4e;
+    --light-background-color: #002b36;
+    --robot-highlight: yellow;
+    --highlighted-color: var(--background-color);
+    --highlighted-background-color: yellow;
+    --less-important-text-color: #5b6a6f;
+    --link-color: #52adff;
+    color-scheme: dark;
 }
 
 body {
diff --git a/src/robot/htmldata/libdoc/libdoc.html b/src/robot/htmldata/libdoc/libdoc.html
index c805b12c4..2e48553f9 100644
--- a/src/robot/htmldata/libdoc/libdoc.html
+++ b/src/robot/htmldata/libdoc/libdoc.html
@@ -55,6 +55,7 @@
         parseTemplates();
         document.title = libdoc.name;
         storage.init('libdoc');
+        setTheme();
         renderTemplate('base', libdoc, $('body'));
         if (libdoc.inits.length) {
             libdoc.typedocs.map(function(type) {
@@ -88,6 +89,18 @@
         createModal();
     });
 
+    function setTheme() {
+        var theme = 'light';
+        if (libdoc['theme']) {
+            theme = libdoc['theme'];
+        } else if (window.matchMedia('(prefers-color-scheme: dark)').matches) {
+            theme = 'dark';
+        }
+        if (theme == 'dark') {
+            document.documentElement.setAttribute('data-theme', 'dark');
+        }
+    }
+
     function parseTemplates() {
         $('script[type="text/x-jquery-tmpl"]').map(function (idx, elem) {
             $.template(elem.id, elem.text);
```

**Comment by pekkaklarck** [comment] 2022-10-10 15:48
I enhanced the Javascript code for setting the theme a bit (see comment above), added tests and wrote documentation. Now the question is, is this a useful addition, does `--theme` work in the intended IDE usage, and are the HTML/CSS changes fine?

Do you @Snooz82 have objections adding this? If not, can you check do the above changes look good? Does this implementation work for you @d-biehl?

**Comment by d-biehl** [comment] 2022-10-11 10:51
Sorry, for the late response, the CSS code looks good to me. What I cannot imagine at the moment, how you implement the --theme, is it a new commandline parameter for libdoc and is it also available in direct call to LibraryDocumentation class?

**Comment by pekkaklarck** [comment] 2022-10-11 12:11
It's a command line option and various APIs also got `theme=None` argument. For example, this usage works:
```python
from robot.libdocpkg import LibraryDocumentation
libdoc = LibraryDocumentation('String')
libdoc.save('out.html', theme='dark')
```
If you have access to the browser JS environment, calling `setTheme('dark')` works as well. I'll commit changes so you can see and test yourself.

**Comment by pekkaklarck** [comment] 2022-10-11 12:15
This ought to be done now but I keep this open for a little time to see if there's some more feedback.

**Closed** 2022-10-11 17:37 UTC
Labels: priority: medium, rc 2
