### ISSUE TITLE
RobotFramework Unable to read or show the Documentation properly in log file when there is an empty line in between the lines of Keyword Documentation

### ISSUE THREAD

**Issue by abhisheksandilya30** [robotframework/robotframework#5163] opened 2024-07-09 12:18 UTC
RF- 7.0.1

RF is not showing the entire documentation whenever an empty line space come in between the lines in the keywords documentation. It shows the content of lines which are present before the empty line and completely misses out all the contents which comes after the empty lines.

When empty line is present in documentation
![image](https://github.com/robotframework/robotframework/assets/175118276/0c9ff015-cafa-4446-ac71-74ea5f8c675a)

When empty line is removed
![image](https://github.com/robotframework/robotframework/assets/175118276/355663b1-87fa-47c0-9296-5ca48bf8b0be)

Expected Outcome-

Robot Framework should be able to read or show the documentation properly even an empty line space is coming in between the keyword documentation.

PFA robot test files and there execution log files.
[RobotFrameword Test Files and Log Files.zip](https://github.com/user-attachments/files/16143081/RobotFrameword.Test.Files.and.Log.Files.zip)

**Comment by himanshudave** [comment] 2024-07-10 12:17
@abhisheksandilya30 following

**Comment by pekkaklarck** [comment] 2024-07-13 12:08
Showing only the first paragraph of keyword documentation in the log file is a [documented feature](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#user-keyword-name-and-documentation). The reason is that many keywords, especially library keywords, have very long documentation and including it every time the keyword is used would increase the output.xml and log.html size considerably.

The current behavior is not going to change, but we could consider making it configurable somehow. The problem is that I don't have any good ideas how configuration should work in practice. Adding a command line option that affects all keywords doesn't feel like a good idea.

**Comment by Meraxa** [comment] 2024-07-24 11:14
Hi @pekkaklarck, thank you for the answer. I actually didn't know that this is a feature!

I've struggled with the same behavior and think that this is a problem related to the RF Language Server (RF v7.0.1) and the way a keyword is previewed in VS Code.

Take the code snippet below:

```
Set Networks
    [Documentation]    Set network settings .
    ...    | =Arguments= | =Description= |
    ...    | ``url`` | Url used to access. |
    ...    | | The format of the URL is __https://<ip/dns_name>__ e.g. `https://192.168.128.5`. |
    ...    | ``layer2_start_ip_address`` | Layer 2 ip address to be set . |
    ...    | ``layer2_netmask`` | Layer 2 netmask to be set. |
    ...    | ``layer2_ipaddressRange`` | Layer 2 ip address range to be set. |
    ...    | =Raises= | = Description= |
    ...    | ``ValueError`` | If the response output is empty. |
    ...    | = Returns= | = Description= |
    ...    | ``response_output`` | Response data from Get Networks keyword. |
```

This code will lead to the following formatting in the log.html file:

![image](https://github.com/user-attachments/assets/09210ff3-5973-4228-ae82-dad206789044)

While this is totally fine and to be expected as you pointed out above, a problem arises in the code preview in VS Code.
Please pay attention to the Raises in the table. It should be displayed bold, just like the Arguments or the table in the log.html file.

![image](https://github.com/user-attachments/assets/e0c07ead-e80b-4e31-adbd-fecc3577fc99)



To solve this issue in VS Code, one can introduce newlines into the table, just like in the example below (I intentionally kept did not include a newline between the first documentation line and the start of the table to keep it in the log.html file):

```
Set Networks
    [Documentation]    Set network settings .
    ...    | =Arguments= | =Description= |
    ...    | ``url`` | Url used to access. |
    ...    | | The format of the URL is __https://<ip/dns_name>__ e.g. `https://192.168.128.5`. |
    ...    | ``layer2_start_ip_address`` | Layer 2 ip address to be set . |
    ...    | ``layer2_netmask`` | Layer 2 netmask to be set. |
    ...    | ``layer2_ipaddressRange`` | Layer 2 ip address range to be set. |
    ...    | =Raises= | = Description= |
    ...    | ``ValueError`` | If the response output is empty. |
    ...    | = Returns= | = Description= |
    ...    | ``response_output`` | Response data from Get Networks keyword. |
```

This will, rightfully so, remove the second half of the table from the log.html file:

![image](https://github.com/user-attachments/assets/69e03914-4add-42b3-90ba-54bf32db1b14)

However, in VS Code, the table now is perfectly formatted: 

![image](https://github.com/user-attachments/assets/d210139d-46a5-434e-a7ea-ad3b902223f8)


I guess what it comes down to is that the table formatting is not handled the same for the log file and the VS Code preview.

**Comment by pekkaklarck** [comment] 2024-08-30 06:31
The behavior in VSCode looks like bug to me. If you aren't already using the RobotCode plugin, I'd recommend testing does it behave that way too. If you already use it, you should submit an issue to its issue tracker.

**Comment by pekkaklarck** [comment] 2024-08-30 06:32
Does anyone have ideas what would be a good way to tell Robot that the whole documentation should be included in the log file?

**Comment by Meraxa** [comment] 2024-09-16 05:56
> If you aren't already using the RobotCode plugin, I'd recommend testing does it behave that way too.

Thank you for pointing this out.
I wasn't aware that the [Robot Framework Language Server seems to be deprecated](https://github.com/robocorp/robotframework-lsp/issues/1076).
Tested it on the RobotCode Plugin and it *behaves the same way*, not highlighting the Return in the keyword documentation if there are no blank lines in the keyword documentation.


> The behavior in VSCode looks like bug to me.

> If you already use it, you should submit an issue to its issue tracker.

Considering that both extensions, the RF Language Server and RobotCode, display the keyword documentation properly if there are blank lines in the keyword documentation, I actually think that adding a feature to include the whole keyword documentation to the log file would be the way to go.

**Comment by pekkaklarck** [comment] 2024-11-06 09:28
I close this issue because the current behavior is by design and at least the default behavior won't be changed.

As I've written earlier, I would be fine making it possible to configure the behavior somehow, but I don't think a command line option to change the behavior globally is a good idea. This needed to be configurable on keyword or on library/resource level somehow. If you have ideas how it could work, please submit a new issue. You can mention this issue there as a reference.

**Closed by pekkaklarck** 2024-11-06 09:28 UTC
