### ISSUE TITLE
BuiltIn.Log To Console doesn't append a line before printing message

### ISSUE THREAD

**Issue by eduvfalc** [robotframework/robotframework#4585] opened 2023-01-05 16:09 UTC
Hi,

I am aware that the Log To Console keyword appends a new line after the message is printed, but that means that every first logged message will end up being printed in the same line of whatever was printed before during the execution of the test suite (e.g. the test case name). I think that the new line should be added before, and not after.

**Comment by trogdor259** [comment] 2023-01-05 16:18
why not just concatenate a new line character to the beginning of your message?

**Comment by eduvfalc** [comment] 2023-01-05 16:31
That is exactly what I am doing, but I wondered why this is not already implemented in Log To Console. If that was the case we wouldn't need to add ${\n} in every log message to make it work as it is supposed to work (given that the new line is already part of the keyword itself in the BuiltIn library).

**Comment by pekkaklarck** [comment] 2023-01-15 17:29
The problem is that `Log To Console` writes to the same stream as Robot's normal console output. When starting a test, Robot only writes the test name but doesn't write a newline to be able to write the status at the end of the line when the test ends. If you use `Log To Console`, the message is written after the test name. I agree that it's somewhat annoying.

Adding a newline before the logged message would fix the annoyance, but we'd then get empty lines if `Log To Console` would be called multiple times. In my opinion that would be even more annoying than the current behavior. Keeping track has how many time we have logged to console within a test would probably be doable, but I don't consider it too high priority myself. If someone is interested to look at it, we can keep this issue open.

Probably a better solution would be re-implementing Robot's console logging so that it takes possible messages logged during tests into account better. That would probably require writing test name and status to different lines which would make the output more verbose. If the output would be easier to understand, that probably wouldn't be such a big problem. If someone is interested to look at this, please submit a separate issue.

**Comment by pekkaklarck** [comment] 2023-12-20 01:08
I don't think we can change the behavior with Log To Console. I close this issue and hope we at some point have better console output that takes messages logged to console into account better.

**Closed by pekkaklarck** 2023-12-20 01:08 UTC
