### ISSUE TITLE
Logging APIs do not work if Robot Framework is run on thread

### ISSUE THREAD

**Issue by kslz** [robotframework/robotframework#5255] opened 2024-11-07 02:31 UTC
When running a Robot Framework task directly, the logs are generated in the log.html file as expected. However, when the same task is registered as an APScheduler job and executed by the scheduled task, the logs do not appear in log.html.

Here is the code for the scheduled task:
```
from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.triggers.interval import IntervalTrigger
import robot
from datetime import datetime, timedelta

# Define the function to execute the Robot Framework task
def run_robot_task(robot_file_path):
    # Generate report directory
    report_dir = "./"

    # Run the Robot Framework task
    robot.run(robot_file_path, outputdir=report_dir)

# Create the APScheduler background scheduler
scheduler = BackgroundScheduler()

# Define the scheduling time, using IntervalTrigger to execute every 60 seconds
job_trigger = IntervalTrigger(seconds=60)

# Provide the actual Robot Framework file path
robot_file_path = "./3.robot"

# Register the job
scheduler.add_job(run_robot_task, job_trigger, args=[robot_file_path], id="robot_task",
                  name="Execute Robot Framework Task", next_run_time=datetime.now() + timedelta(seconds=5))

# Start the scheduler
scheduler.start()

# Keep the main thread running to ensure the task continues to schedule
try:
    while True:
        pass
except (KeyboardInterrupt, SystemExit):
    # Shutdown the scheduler
    scheduler.shutdown()
```

Here is the code for  3.robot

```
*** Settings ***
Library    Collections
Library    SeleniumLibrary
Library    DateTime
Library    OperatingSystem
Library    BuiltIn


*** Variables ***

${DETAILS_BUTTON_XPATH}    //*[@id="details-button"]
${PROCEED_LINK_XPATH}    //*[@id="proceed-link"]
${SRARCH_SHOW_HIDE}    //*[@id="search_show_hide"]

*** Test Cases ***
Open Browser With Custom Proxy
    ${version}=    Evaluate    robot.__version__
    Log    Robot Framework version: ${version}  console=True
    Log    Robot Framework version: ${version}    level=INFO
    Log    This is an info message    level=INFO
    Log    This is a debug message    level=DEBUG
    Log    This is a trace message    level=TRACE
```

**Comment by kslz** [comment] 2024-11-07 02:48
btw this is log.html, and the first step has log
![微信截图_20241107104655](https://github.com/user-attachments/assets/1eb33cac-8955-422e-a5f7-68d0cb85c691)

**Comment by kslz** [comment] 2024-11-08 05:56
If someone encounters a similar situation, you can change the executor type from threadpool to processpool, which should resolve the issue. However, the exact reason is still unclear.

**Comment by pekkaklarck** [comment] 2024-11-11 20:48
Based on the above commen,t I assume the problem is caused by Robot being run in a thread. Logging via the logging API is disabled in non-main threads to prevent keywords running on background threads to corrupt output.xml.

This is a somewhat annoying limitation im general, but I can see it becoming a bigger problem when Robot itself is run in a non-main thread. I guess we should not check does logging happen in the main thread but instead check does it happen in the thread where Robot itself is running. 

Fixing this shouldn't be too hard. I'll assign this tentatively to RF 7.2 scope.

**Closed** 2024-11-12 14:49 UTC
Labels: priority: high, beta 1, effort: small

**Comment by pekkaklarck** [comment] 2024-11-13 13:14
This was reported as #5138 in June. I was on paternity leave _and_ on holiday then, didn't have time to investigate it, and later forgot about it. Based on the comments there, the way this issue was fixed ought to work fine. That issue also makes it clear this has been a common issue and deserved high priority.
