### ISSUE TITLE
Enhance error when no test matches `--test`

### ISSUE THREAD

**Issue by JuyoungAn** [robotframework/robotframework#3034] opened 2018-12-31 01:58 UTC
RF Version 3.1 
RIDE Version 1.5.2.1 

[] in suite name or test name make a problem.  Error message is unexpected error: [ ERROR ] **Suite 'Test' contains no tests named 'Test.[tc1]' in suite 'Test'**. 

Ex) 
test.robot or test.txt

```robotframework
*** Test Cases ***
[tc1]
    log    abc
```

**Comment by pekkaklarck** [comment] 2018-12-31 13:44
Cannot reproduce. I created `test.robot` with the same content and can run `robot test.robot` just fine. Are you certain you told all the relevant information?

Also, good idea to format issue description (and comments). Click the ` Styling with Markdown is supported` link below to learn about formatting syntax. Notice also that you can edit text you've submitted earlier as well.

**Comment by JuyoungAn** [comment] 2019-01-01 23:54
Hi, pekka 

Can you select and run [tc1] on RIDE or with --suite and --test option on cmd? There is no problem without selected test case.

**Comment by aaltat** [comment] 2019-01-02 15:44
RIDE is a separate tool and problems with RIDE should be reported to https://github.com/robotframework/RIDE 

Because this doesn't look like problem with the Robot Framework I am closing this issue.

**Comment by pekkaklarck** [comment] 2019-01-02 17:01
Problem with `--test` and is caused by changes with pattern matching syntax:
https://github.com/robotframework/robotframework/blob/master/doc/releasenotes/rf-3.1.rst#changes-to-pattern-matching-syntax

**Comment by pekkaklarck** [comment] 2019-01-02 17:03
We could possibly do something to this. At least enhance the error message.

**Comment by pekkaklarck** [comment] 2019-01-15 21:17
It would be good to change the error message so that it says something like "no tests matching <pattern>" instead of the current "no test named <pattern>". Ought to be pretty easy to do, but will require running all tests to make sure all related tests are also updated.

**Closed** 2019-04-17 08:27 UTC
Labels: enhancement, good first issue, priority: low

**Comment by pekkaklarck** [comment] 2019-04-17 08:29
Also `--include` and `--exclude` had same issue. Now they and `--test` all have word "match" in the error message if no tests match the selection. The error in the original description would now be this:

> [ ERROR ]  Suite 'Test' contains no tests matching name 'Test.[tc1]' in suite 'Test'.
