### ISSUE TITLE
[ ERROR ] Reading XML source  output.xml' failed: ParseError: mismatched tag: line 27685, column 2

### ISSUE THREAD

**Issue by linzybettina** [robotframework/robotframework#3824] opened 2021-01-11 20:32 UTC
hi 
i am using robot to run the testcases. If I run the individual testcases i could get the report correctly**(python3 -m robot -t TC01 validate.robot**).but if i run the entire testsuite  i am facing ParseError.could some one help me how to solve this issue.?
i am using the robot version as( Robot Framework 3.2.2 (Python 3.6.9 on linux)
while i opened the output.xml file I could see the following content in the webbrowser.when i try to see the source of the content it shows like this:

XML Parsing Error: mismatched tag. Expected: </kw>.

Location: file:/output.xml
Line Number 27685, Column 3:
</test>
--^

xml content can be seen in attachment
[xmlparseissue.zip](https://github.com/robotframework/robotframework/files/5798306/xmlparseissue.zip)

**Comment by pekkaklarck** [comment] 2021-01-18 11:05
Something corrupts the output.xml but it's unfortunately impossible to tell why that happens. Most likely reasons are:
- Two processes writing to a same file. This could be caused by execution side configuration issue on your environment.
- One process uses threads that end up writing to output.xml in unsynchronized manner. Robot should be able to prevent this, but a library could still do something really strange to cause this.
- A bug in Robot.

The main problem investigating issues like this is being able to reproduce them. That basically requires you to create _simple_ example that demonstrates the problem that we can execute on our own machines. Creating such an example may not be easy but this resource gives some guidance: http://sscce.org/.

**Comment by pekkaklarck** [comment] 2021-02-20 13:06
Closing due to lack of information.

**Closed by pekkaklarck** 2021-02-20 13:06 UTC

**Comment by prateekc71191** [comment] 2023-10-09 19:49
I am seeing same XML parsing issue in robot 6.1.0 and 6.1.1 (and Python 3.10.10) aswell with one particular suite.
Not sure what is wrong! There is nothing unique about this suite ! 
same kind of TCs are run in different suite aswell (90% same input same output) 

its only generating proper report when all the cases are passing! If any one case is failing, I am getting the above parsing XML issue which is difficult to read and figure out

One thing which I have added in all these suites is a Python keyword which is using the python multiprocess but I don't think that would be impacting because other cases with same keyword are working fine!

**Comment by JishaQA** [comment] 2025-03-18 13:06
I am seeing XML failed: ParseError: mismatched tag: line 157, column 21 error after test execution for the robot framework output.xml file.I am executing an End To End test calling 4 tests and the output file generated is giving error.
I am on the latest versions
robotframework==7.2.2
robotframework-seleniumlibrary==6.7.1
selenium==4.29.1
