### ISSUE TITLE
mode Chrome to mobileEmulation:iPhone X. Keywords: Focus() does not work

### ISSUE THREAD

**Issue by tangxingjun** [robotframework/robotframework#2995] opened 2018-10-27 08:59 UTC
Browser:Chrome  and set it to mobileEmulation:iPhone X
I need to click on an element on the next screen，when i use the keywords:Focus(),found that it does not work well.then i try to use the JavaScript grammar：js="var q=document.documentElement.scrollTop=10000" ，also does not work。
But beyond that,I use the keywords：Execute Javascript   with any JavaScript Sentence does not work.
I guess there is someting wrong in fobot framework when mode the Chrome  mobileEmulation.
Can someone give me some advice?

**Comment by aaltat** [comment] 2018-10-30 19:16
The core Robot Framework does not keywords which would interact with system under test. The problem is related to the library you are using. Please see the support forums provided by the library you are using or ask question in the Robot Framework user group or in the slack. 

Because this is not Robot Framework core related issue, I am closing this issue.

**Closed by aaltat** 2018-10-30 19:16 UTC
