### ISSUE TITLE
With RF3.2 I get weird argument related error from FakerLibrary

### ISSUE THREAD

**Issue by nigotiator** [robotframework/robotframework#3560] opened 2020-04-28 09:13 UTC
Versions:
```
robotframework==3.2
robotframework-faker==5.0.0
```
Consider TC's
```
*** Settings ***
Library    FakerLibrary
*** Test Cases ***
Test1
    FakerLibrary.Ascii Email
Test2
    FakerLibrary.Email    domain=diibadaaba.vom
```
Result -->
```
Test1                                                                 | FAIL |
Keyword 'FakerLibrary.Email' missing value for argument 'self'.
------------------------------------------------------------------------------
Test2                                                                 | FAIL |
Keyword 'FakerLibrary.Ascii Email' expected 1 argument, got 0.
------------------------------------------------------------------------------
```
Both tests works on RF 3.1.2 and with the same version of FakerLib
Maybe related to #3559

**Comment by pekkaklarck** [comment] 2020-04-28 10:53
I submitted #3561 about the problem with wrapped methods which most likely is the root cause for this issue as well. The problem ought to be now fixed by b43f5823407030940823ae2a477ac6f5b98c3ed1. I would be grateful if you could test the fix in your own environment. You can do that by installing the latest code like this:

    pip install https://github.com/robotframework/robotframework/archive/master.zip

**Comment by nigotiator** [comment] 2020-04-29 06:11
Yep, seem to work with this version 👍
```
(rftest) ➜  rftest pip list | grep robotframework
robotframework       3.2.1.dev1
robotframework-faker 5.0.0
(rftest) ➜  rftest robot test.robot 
==============================================================================
Test                                                                          
==============================================================================
Test1                                                                 | PASS |
------------------------------------------------------------------------------
Test2                                                                 | PASS |
------------------------------------------------------------------------------
Test                                                                  | PASS |
2 critical tests, 2 passed, 0 failed
```

**Comment by pekkaklarck** [comment] 2020-04-29 06:50
Great to hear and thanks for testing! I'll close this one as a duplicate of #3561 that explains the underlying issue in more details.

**Closed by pekkaklarck** 2020-04-29 06:50 UTC
