### ISSUE TITLE
Keyword failure in teardown prevents next keyword from executing

### ISSUE THREAD

**Issue by lm-epam** [robotframework/robotframework#2661] opened 2017-08-23 08:32 UTC
Consider the following code

`
Suite Teardown  Run Keywords  this_keyword_fails  this_keyword_passes
`

On RF version 3.0 this code invokes the first keyword (it fails) then executes the second keyword.

On RF version 3.0.2 the second keyword is not executed at all, the failure from the first keyword prevents the invocation of the next one.

**Comment by pekkaklarck** [comment] 2017-08-23 17:35
How does the first kw fail?

**Comment by pekkaklarck** [comment] 2017-08-23 17:39
If the failure is considered a syntax error, then the change in behavior is caused by #2404. It's already caused problems described in #2648 and we may need to reconsider it.

**Comment by lm-epam** [comment] 2017-08-24 07:17
I've tested it with a duplicated keyword declaration (keyword declared in two different source *.robot files imported as resources)

**Comment by pekkaklarck** [comment] 2017-08-24 09:11
That is considered a syntax error. This issue is in practice a duplicate of #2648.

**Closed by pekkaklarck** 2017-08-24 09:11 UTC
