### ISSUE TITLE
Similarly-named Variables Colliding

### ISSUE THREAD

**Issue by GLMeece** [robotframework/robotframework#2270] opened 2015-12-17 00:50 UTC
# Summary
Similarly-named variables seem to be colliding due to some sort of name-mangling. Sorry - I've not perused all of the RF code to know where this is happening.

## My Case
I have two similar, but different, variables whose values can overwrite each other on runtime. Here are my variable examples:
* `${CO_APP_FIRST_NAME}`
* `${coapp_first_name}`

Notice that the first variable name has an underscore between _CO_ and _APP_, whereas the second has both of those character groupings together (_coapp_).

## Test Case

Run the following in RF and you should see what I am talking about:

```robotframework
*** Settings ***
Documentation   *Just for Testing*

*** Variables ***
${CO_APP_FIRST_NAME}        Foo

*** Test Cases ***
Test Stuff
    [Documentation]     1. Just for Testing things.
    Test Bed

*** Keywords ***
Test Bed
    Log to Console          \n\nValue of \${CO_APP_FIRST_NAME}: ${CO_APP_FIRST_NAME}
    Log to Console          Setting \${coapp_first_name} to Bar
    ${coapp_first_name}     Set Variable  Bar
    Log to Console          Value of \${coapp_first_name}: ${coapp_first_name}
    Log to Console          Value of \${CO_APP_FIRST_NAME}: ${CO_APP_FIRST_NAME} (should still be Foo)\n
```
Here's the console output:
```
C:\Users\gmeece\Documents\GitHub\qa-testing\New_Version>pybot test_bed.robot
==============================================================================
Test Bed :: *Just for Testing*
==============================================================================
Test Stuff :: 1. Just for Testing things.

Value of ${CO_APP_FIRST_NAME}: Foo
Setting ${coapp_first_name} to Bar
Value of ${coapp_first_name}: Bar
Value of ${CO_APP_FIRST_NAME}: Bar (should still be Foo)

Test Stuff :: 1. Just for Testing things.                             | PASS |
------------------------------------------------------------------------------
Test Bed :: *Just for Testing*                                        | PASS |
1 critical test, 1 passed, 0 failed
1 test total, 1 passed, 0 failed
==============================================================================
Output:  C:\Users\gmeece\Documents\GitHub\qa-testing\New_Version\output.xml
Log:     C:\Users\gmeece\Documents\GitHub\qa-testing\New_Version\log.html
Report:  C:\Users\gmeece\Documents\GitHub\qa-testing\New_Version\report.html
```
## Questions
* Am I doing something really stupid that I just can't see (this is a cut-down example, but it still demonstrates the issue)?
* Is this documented somewhere? I looked through [the section on variables](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#variables) again, but couldn't find anything addressing this topic. 
* Is this a known feature/limitation/bug?

**Comment by pekkaklarck** [comment] 2015-12-17 01:41
Variables being case, space and underscore insensitive is by design. The main motivation has been that in variable files you can create variables like

```python
my_variable = 'value'
```

and we wanted them to be available like `${MY VARIABLE}`. Rules could be made more strict, but all such changes are backwards incompatible and thus require deprecation period.

This stuff ought to be documented somewhere in the User Guide. If documentation is not adequate, at least that could be easily enhanced.

**Comment by GLMeece** [comment] 2015-12-17 02:45
@pekkaklarck -

Thanks for the reply. I had a suspicion it would boil down to something like this. 

Just so I'm clear on this, tell me if any or all of the following assumptions are true:
* Case doesn't matter (e.g., `${MYVAR}` and `${myvar}` are the same).
* Spaces and underscores are interchangeable (e.g., `${my_var}` and `${my var}` are the same).
* Not only are spaces and underscores interchangeable, but their order/occurrence with the name of a variable doesn't matter (e.g., `${m_y_v_ar}`, `${myvar}`, and `${m yv ar}` are all the same).

Are any of these assumptions incorrect? What other rules should users be aware of? 

I would be willing to add a section to the documentation if it would lighten the load on your part. I am **forever** grateful for this framework and all the time you've put into it. When I demo it to co-workers (including my boss), they are always impressed when they walk away. :astonished: :satisfied: :sunglasses:

**Comment by pekkaklarck** [comment] 2015-12-17 13:31
First of all, thanks for kind words! Always nice to hear compliments.

Your assumptions are pretty much correct. Technically spaces and underscores are simply ignored, but the end result is the same. I looked at the User Guide and noticed that this is briefly documented under Variable types section:
http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#variable-types

Enhancements to the documentation are welcome. In addition to making the aforementioned section more clear, they could include links from other other sections into it. It would be awesome if you could create a pull request. Enhancement just explained here as comments are fine too, but require more work from us. See [CONTRIBUTING.rst](https://github.com/robotframework/robotframework/blob/master/CONTRIBUTING.rst) for more details about pull requests, modifying User Guide, etc.

**Comment by GLMeece** [comment] 2015-12-17 16:18
@pekkaklarck - thanks for the reply. Yes, you are correct - I missed this entirely. :flushed: I will admit I often skim to get to the parts I think I need. Second paragraph, first sentence - you do indeed spell this out:

> Robot Framework variables, similarly as keywords, are _**case-insensitive, and also spaces and underscores are ignored**_. [_emphasis_ mine]

IMO, since you have already documented this - this would be more appropriate for someone's blog post or if someone ever wanted to tackle a Wiki on the Github repo.

**Comment by pekkaklarck** [comment] 2015-12-20 22:58
OK. Let's close this issue then.

**Closed by pekkaklarck** 2015-12-20 22:58 UTC
