### ISSUE TITLE
Enhance `Set Test Variable` docs to explain it cannot be used outside test

### ISSUE THREAD

**Issue by avancil** [robotframework/robotframework#3952] opened 2021-04-27 21:26 UTC
I have a keyword that will run in the suite setup as well as some test cases. One thing it needs to do is set a test variable (which is not used in the suite setup), but that's not valid in the suite setup, so I tried running it with `Run Keyword And Ignore Error`. But, the suite still fails.

I can work around this, but `Run Keyword And Ignore Error` should never fail.

Example:
```robotframework
*** Settings ***
Documentation   For testing purposes
Suite Setup     Before Suite


*** Test Cases ***
My Test Case
    [Documentation]     A test case
    My Keyword
    Log to Console      \nDo some more stuff with ${MY TEST VARIABLE}...


*** Keywords ***
Before Suite
    [Documentation]     Run the suite setup
    My Keyword
    Log to Console      \nDo some more setup stuff...

My Keyword
    [Documentation]                 This keyword might run in the suite setup, or in a test case.
    Run Keyword and Ignore Error    Set Test Variable   ${MY TEST VARIABLE}     Some Value
```

Output:
```text
==============================================================================
Robot Temp :: For testing purposes                                            
==============================================================================
My Test Case :: A test case                                           | FAIL |
Parent suite setup failed:
Cannot set test variable when no test is started.
------------------------------------------------------------------------------
Robot Temp :: For testing purposes                                    | FAIL |
Suite setup failed:
Cannot set test variable when no test is started.

1 test, 0 passed, 1 failed
==============================================================================
```

robotframework 4.0.1
Python 3.9.4
Ubuntu 20.04

**Comment by coder-cell** [comment] 2021-05-01 16:37
@avancil 
Hi, this is an fatal exception error, the above mentioned keyword works only when the keyword fails. (But the keyword `Set Test Variable` is a valid keyword)
As per the documentation, `Errors caused by invalid syntax, timeouts, or fatal exceptions are not caught by this keyword. Otherwise this keyword itself never fails.'

**Comment by avancil** [comment] 2021-05-03 16:16
@coder-cell I'm not sure how users are supposed to know which failures are "fatal exceptions" versus other keyword failures. The syntax and parameters are correct. And how does one catch fatal exceptions in Robot code?

At the least, the keyword documentation for `Set Test Variable` should call out that it is a Fatal exception to call it outside of a test case.

**Comment by chriscallan** [comment] 2021-05-06 12:43
I've checked through the docs and can see where an addition like: 
It is a fatal exception to call :name:`Set Test Variable`
outside the scope of a test (e.g. in a Suite Setup or Teardown).

would be a good addition to avoid this confusion going forward.  
I can put in a PR for this unless you'd like to make the addition.

**Comment by pekkaklarck** [comment] 2021-05-06 13:25
The line between "normal" and "fatal" errors isn't too clear and the line has been changing. Earlier any failure with variables, like using a non-existing variable, was considered fatal but that has been changed. In this case it's not really about variables, though, but instead it's more like a syntax error that `Set Test Variable` is used where it is not allowed. That said, I'm not really against changing this particular error to a "normal" error that can be caught. Don't think it's a good idea in RF 4.0.x bug fix releases, but could be considered in RF 4.1. Alternatively we could just change documentation which would obviously be safe also in a bug fix release.

How do others feel about this? "Vote" this comment with :+1: if you'd like this to be changed and with :-1: if not. If you have something to say, just add a comment! :smiley:

**Comment by chriscallan** [comment] 2021-05-07 11:57
I think that a doc update like the above is sufficient.  The original error is straightforward enough to point me in the right direction to fix the scoping issue.  The error message along with a doc update should take care of any confusion.

**Comment by chriscallan** [comment] 2021-05-28 13:10
Submitted PR https://github.com/robotframework/robotframework/pull/3979 for this a few days ago.  Just a doc update, so once it's merged this'll be taken care of.

**Comment by pekkaklarck** [comment] 2021-09-01 09:05
Let's go with a doc update. We already have PR #3979 covering that.

**Closed** 2021-09-01 09:05 UTC
Labels: priority: low, rc 1, acknowledge
