### ISSUE TITLE
Add support for testcase settings "[Comments]" or "[Notes]"

### ISSUE THREAD

**Issue by lynhbn** [robotframework/robotframework#3411] opened 2019-12-10 04:16 UTC
Currently we only have **[Documentation]** section in each testcase to store testcase/ keyword definitions or explanations 

I suppose it's better if providing one more option called _[Comments]_  or _[Notes]_ to store specific notes for each testcase. It looks better. Sometimes we need to store some additional information when working with different teams & groups.

For example:
**TC_12345 - Sample testcase**
    **[Tags]**       smoke_test         not_ready
    **[Notes]** This testcase is not ready due to ABC-XYZ...

**Comment by pekkaklarck** [comment] 2019-12-10 07:38
How would this new setting differ from the current documentation? If only by name, I don't see much benefits.

**Comment by lynhbn** [comment] 2019-12-10 07:49
> How would this new setting differ from the current documentation? If only by name, I don't see much benefits.

Literally it is the same.

But in my opinion, storing other stuff inside "[Documentation]" sometimes look ugly. They are just some notes, some comments... therefore, putting them into [Documentation] makes a little bit awkward for me. [Documentation] is for something "documental" & solemn

**Comment by pekkaklarck** [comment] 2019-12-10 08:25
The problem is that although "notes" would be great for you, someone else might want something different what works even better in their context. If we follow that path, we end up with several settings that work the same way and nobody knows which one to use. So no, we won't be adding a setting that works exactly like another but has a different name.

What we could consider is making it possible to configure setting names so that you could use notes instead of documentation and someone else could use something else. That would also enable localization that would be a lot more important feature in general. It would require its own issue, though.

We could also think about allowing totally free setting names so that values would just be shown in logs/reports and stored in the executed objects. This would be a generic feature and thus better than just adding a new setting with duplicate functionality, but it would also be a pretty big task to implement and I doubt it would be worth the effort.

Hopefully using `[Documentation]` for your notes doesn't make you too awkward. If it helps, you can prefix the text with something like `*NOTES:*`.

**Closed by pekkaklarck** 2019-12-10 08:25 UTC
