### ISSUE TITLE
Telnet connections might be left open

### ISSUE THREAD

**Issue by jonivanhamaki** [robotframework/robotframework#2351] opened 2016-04-12 12:42 UTC
If connection is closed using close_connection() it might still leave connections open.

Seems that close_connection() is missing shutdown() in Telnet.py.

I verified fix proposal by adding self.sock.shutdown(socket.SHUT_RDWR) to close_connection() and no open connections are left behind.

**Comment by pekkaklarck** [comment] 2016-04-13 09:13
Can you provide a pull request with a fix? Is it possible to create a test for this behavior?

**Comment by jonivanhamaki** [comment] 2016-04-13 09:39
https://github.com/jonivanhamaki/robotframework/compare/master...jonivanhamaki-patch-telnet-library?expand=1

**Comment by pekkaklarck** [comment] 2016-04-13 09:48
That's not a PR yet.

**Comment by pekkaklarck** [comment] 2016-04-13 09:48
Damn GitHub for having `Comment and close` and `Comment` buttons next to each others!!

**Comment by jonivanhamaki** [comment] 2016-04-13 09:52
How about this one:
https://github.com/jonivanhamaki/robotframework/pull/1

**Comment by pekkaklarck** [comment] 2016-04-13 10:13
It's a PR but for your own clone. A PR to this project would appear here too.

Have you studied GitHub docs about PRs? They are linked, for example, from our contribution guidelines: https://github.com/robotframework/robotframework/blob/master/CONTRIBUTING.rst

**Comment by jonivanhamaki** [comment] 2016-04-13 10:25
I didn't, sorry. I'm bit too busy at work :)

https://github.com/robotframework/robotframework/pull/2353

**Comment by pekkaklarck** [comment] 2016-04-13 21:34
Thanks for the PR. A test case demonstrating the problem and the fix would be great but I'm not sure how easy it would be to create. Without a test, we just need to be extra careful when accepting the PR. Based on the PR and related Python docs this seems to be what happens and why the fix apparently works:

1. `close_connection` currently just calls `telnetlib.Telnet.close`.

2.  `telnetlib.Telnet.close` calls `self.sock.close`.

3. `socket.close` has this note in [its docs](https://docs.python.org/2/library/socket.html#socket.socket.close):

  > **Note:** `close()` releases the resource associated with a connection but does not necessarily close the connection immediately. If you want to close the connection in a timely fashion, call `shutdown()` before `close()`.

4. The proposed fix here and in the PR is calling `sock.shutdown(socket.SHUT_RDWR)` before `close`.

5. `socket.SHUT_RDWR` [is documented](https://docs.python.org/2/library/socket.html#socket.socket.shutdown) to disallow both sending and receiving.

All that looks pretty good to me. Do you @jussimalinen have any comments?

**Comment by pekkaklarck** [comment] 2016-04-13 21:40
Based on the `socket.close` docs, connections won't be left open forever but they aren't totally closed immediately. Does anyone see any potential problems in changing that behavior?

**Comment by vkruoso** [comment] 2016-04-14 14:15
Based on your comment related to the docs it seems a good addition. We've used the Telnet Library intensively and never experienced this issue, but I see no potential problems as the user would actually want (expect) the connection to be closed immediately.

**Comment by pekkaklarck** [comment] 2016-04-15 07:52
@vkruoso, do you have a change to test the proposed fix in your system? If it causes no problems there, we ought to be 99.8% sure that the fix is safe. Based on your comments it is not worth the effort trying to create a test for this change.

**Comment by vkruoso** [comment] 2016-04-18 13:54
I've tested the fix and it worked fine. I agree with @pekkaklarck regarding creating tests for this change, so the PR looks good to me.

**Comment by pekkaklarck** [comment] 2016-04-20 12:32
Merged #2353. Thanks @jonivanhamaki for submitting the issue and the PR and @vkruoso for review and testing.

**Comment by juhoarvid** [comment] 2016-11-15 11:06
I definitely think this is good addition to close_connection() method but seems not be perfect to fullfill close_connection method definition http://robotframework.org/robotframework/latest/libraries/Telnet.html#Close%20Connection:
"""
It is not an error to close an already closed connection.
"""

Accidentally noticed this when trying to patch this change to automation environment which uses 2.9.2 robot version. One widely used keyword duople closes connection, so I immediately face problem:
"""
 	AttributeError: 'int' object has no attribute 'shutdown'
"""
Solution maybe could be type check for self.sock before try 'shutdown'.

**Comment by pekkaklarck** [comment] 2016-11-20 23:51
Good catch @juhoarvid! The strange AttributeError is caused by `telnetlib.Telnet.close()` setting `self.sock = 0`. I find it really strange to set an attribute to an integer like that, but luckily we can just add `if self.sock` above the added `self.sock.shutdown(...)` line. Would someone like to create PR?

It would also be good to check is there already an acceptance test for closing connection multiple times. If not, one should be added.

**Closed** 2016-12-28 18:47 UTC
Labels: bug, prio-medium
