### ISSUE TITLE
Failed keywords inside skipped tests are not expanded

### ISSUE THREAD

**Issue by karniemi** [robotframework/robotframework#4756] opened 2023-05-04 08:58 UTC
We are just upgrading from 3.x to 6.0.2. We are moving our test framework to use the "skipped"-concept instead of the deprecated "critical/non-critical"-concept. We noticed that in log.html, the failed KWs are not automatically expanded for a test skipped using skipOnFailure.

Reproducing:
- click a  failed skipped test in report.html.
- Failed nested KWs are not automatically expanded in log.html

For a failed non-skipped test, the failed KWs are automatically recursively expanded. The same happens for failed non-critical test in 3.x. We would expect and like the same behaviour for the failed skipped tests. Especially for nested KWs, it's irritating to manually expand the failed nested KWs to get to the lowest level failed KW.

**Comment by pekkaklarck** [comment] 2023-05-04 16:31
The problem is that failed keywords are never expanded. That was changed in f22b78e118f7280535e7f7a41b0343b202bf4e07 to avoid expanding keywords that weren't run at all (#4214). Failed keywords were also explicitly ignored. I believe the reason was that they typically are expanded anyway, but that doesn't happen if the test is skipped. It's easy to fix this by changing the current condition from `kw.passed or kw.skipped` to `not kw.non_run`.

**Comment by pekkaklarck** [comment] 2023-05-04 16:36
Another question is, should failed keywords inside skipped tests be automatically expanded when a skipped test is opened. Currently expanding is only done when the whole log file is opened, not when individual tests, suites or keywords are opened. I believe changing that now isn't worth the effort for two reasons:
- It's not clear would always expanding failed keywords always be a good idea. It could mean unnecessarily expanding lot of failed keywords in some cases.
- The current log/report tech is outdated and we plan to replace it in the future. All changes to the current log would need to be redone in the future.

**Comment by karniemi** [comment] 2023-05-10 09:08
@pekkaklarck  thanks. Sorry, but I did not quite follow. You seemed to change the title so that it does not match my description any more. I find that a bit mis-leading. I read the commit, but I'm not able to conclude if it fixes the problem in the description.

From your first comment, I get that it's an easy fix. From your second comment, I sense hesitation and a turn around.

Fixing the issue ( in the description), as you first planned would make the "skipOnFailure" work the same way as "non-critical" worked in RF3.x. I thought "--skipOnFailure" was supposed to be a direct replacement for "--noncritical". At least that's what the use-cases for it seem like, and also the docs suggest they used to be aliases to each other at some point: "To ease migrating from criticality to skipping, the old --noncritical option works as a direct alias for the new --skiponfailure."

Not intending to argue, though. We might be able to live with, though it makes our daily live now a bit harder.

**Comment by pekkaklarck** [comment] 2023-05-10 10:16
I changed the title because this issue wasn't directly related to `--skiponfailure`, it occurred with _all_ failed keywords. That didn't typically matter, because failed tests and failed keywords inside them are automatically expanded. If a test is skipped, it or its failed keywords aren't expanded, though, and the issue occurred.

I fixed expanding failed keywords and the issue you encounterd ought to be resolved. You can easily test that by installing RF 6.1 beta 1. If there are still issues, report them here so that we can sort them out before the final release.

My latter comment was related to possibly expanding failed keywords if you open a akipped test in a log file. As I mentioned above, skipped tests aren't automatically expanded and failed keywords inside them stay closed also when you open such a test. Automatically expanding keywords at that point could be a good idea, but it's not directly related to this issue.

**Comment by karniemi** [comment] 2023-05-10 11:15
Just to make sure: in the description I'm talking about "failed skipped test" i.e. like in "big red apple", an object which has both of those qualities. Your latest comment still seems to contradict this.

**Comment by karniemi** [comment] 2023-05-10 11:19
I already tried monkey-patching expand_keywords.robot over 6.0.2, because i did not know there was a beta release for this. A skipped failed test still did not expand.

**Comment by karniemi** [comment] 2023-05-10 13:26
It seems that the issue is in rebot/log.js. With "noncritical"-concept, these lines allowed both critical&non-critical to be expanded:
https://github.com/robotframework/robotframework/blob/9325f44c60634d1bab77ddc8226c46147d7296f1/src/robot/htmldata/rebot/log.js#L45
https://github.com/robotframework/robotframework/blob/9325f44c60634d1bab77ddc8226c46147d7296f1/src/robot/htmldata/rebot/log.js#L82
...and now there's a new status "SKIP", so those conditions no more match, and therefore expansion does not happen for a failed skipped test.

I monkey-patched our RF6.0.2 docker image like this to get forward:
```
RUN sed -i 's/if (suite.status == "FAIL")/if ( suite.status == "FAIL" || suite.status == "SKIP" )/' \
        /usr/local/lib/python3.8/site-packages/robot/htmldata/rebot/log.js
RUN sed -i 's/if (element.status == "FAIL")/if ( element.status == "FAIL" || element.status == "SKIP" )/' \
        /usr/local/lib/python3.8/site-packages/robot/htmldata/rebot/log.js
```

**Comment by pekkaklarck** [comment] 2023-05-10 19:52
Hmm, it seems I didn't read the description carefully enough in the beginning. For some reason I was thinking you used `--expandkeywords`, but now that I read the description again I didn't see it mentioned. There was a bug with `--expandkeywords` that I fixed, but clearly your issue was that failed keywords inside skipped tests aren't expanded automatically. That's exactly what I mentioned in [one of the comments above](https://github.com/robotframework/robotframework/issues/4756#issuecomment-1535056123). Since exactly that seems to be causing issues, I'll reopen this issue.

**Comment by pekkaklarck** [comment] 2023-05-10 20:14
The problem with automatically expanding skipped tests is that it isn't always desirable. I understand you want to have them open if they are skipped using `--skiponfailure`, but Robot doesn't differentiate how tests have been skipped. I see two solutions:

1. Try to come up with some algorithm for expanding skipped tests that suites all needs. We could, for example, always expand failed keywords inside a skipped test and keep the test closed if there are no such failures. This would need to be done fully on the Javascript side and I'm not sure how easy it is. As I already mentioned, we plan to rewrite log/report in the nearish future and I wouldn't like to spend too much time enhancing them.
2. Add a new functionality to expand tests based on tags and then expand also failed keywords on them. This could be a useful feature in general, but we could automatically use if you use ´--skiponfailure`. This would be partly implemented on Python side, but it would also need Javascript changes.

I believe trying out the option 1 first is the best idea. I'll take a look at it.

**Comment by pekkaklarck** [comment] 2023-05-10 21:24
I experimented with the above option 1 and got pretty good results in my opinion. This is what I changed:
- When expanding failed elements, expand failed child elements not only if the element status is FAIL but also if the element is a test and the status is SKIP. This automatically expands failed keywords when navigating to a skipped test from report or when you otherwise have a URL with a test id at the end. It won't expand keywords with skip status, though.
- When opening a test manually in log, expand failed keywords is test status is SKIP. This keeps skipped test closed by default and avoids unnecessarily opening them, but failed keywords are nevertheless expanded if you open the test yourself.

Could you @karniemi test does the above work ok in your use case? The diff below shows all changes and I can commit them if they look good.

```diff
diff --git a/src/robot/htmldata/rebot/log.js b/src/robot/htmldata/rebot/log.js
index f44067e96..f5d1bd303 100644
--- a/src/robot/htmldata/rebot/log.js
+++ b/src/robot/htmldata/rebot/log.js
@@ -6,6 +6,9 @@ function toggleSuite(suiteId) {
 
 function toggleTest(testId) {
     toggleElement(testId, ['keyword']);
+    var test = window.testdata.findLoaded(testId);
+    if (test.status == "SKIP")
+        expandFailed(test);
 }
 
 function toggleKeyword(kwId) {
@@ -79,7 +82,7 @@ function loadAndExpandElementIds(ids) {
 }
 
 function expandFailed(element) {
-    if (element.status == "FAIL") {
+    if (element.status == "FAIL" || (element.type == "test" && element.status == "SKIP")) {
         window.elementsToExpand = [element];
         window.expandDecider = function (e) {
             return e.status == "FAIL";
```

One thing we could still consider is opening skipped tests if they contain failed keywords, but I got a feeling that it would require too big changes to be worth it.

**Comment by karniemi** [comment] 2023-05-11 05:09
Thanks, I'll have a look.

As far as I understand, the real use case from user perspective could be:
* a user opens a specific test: if the test had failed, the user most probably opened the test to investigate the failure -so it's convenient that the failed KWs are automatically recursively expanded. The same holds if the test had failed but was marked as skipped.

**Comment by karniemi** [comment] 2023-05-11 05:24
First, about your change in toggleElement(): if I get it right, that would auto-expand failed KWs if the user opens a suite and then toggles i.e. opens (and also if closes?) a test in log.html. That does not work in RF3.0.4, not for critical and not for non-critical either. So with toggleElement(), we would going an extra mile. But of course, it would be logical considering the assumed use case(in my previous comment). But your change would limit this new behaviour to SKIP-status only, and would not auto-expand FAIL-status: is that intentional?

**Comment by karniemi** [comment] 2023-05-11 08:41
Next, I reviewed your code change for expandFailed(), and compared it against the functionality in my monkey-patches ( https://github.com/robotframework/robotframework/issues/4756#issuecomment-1542210575 ).
* in RF3.0.4, there is a similar auto-expansion also in suite-level. If the user opens a suite that had failed, all the failed tests and KWs are automatically recursively expanded. I also confirmed this by trying it in a RF3.0.4 produced log.html. In RF6.0.2 this works the same way - but only for FAIL-status, not for SKIP-status. I understand that I did not describe this originally - it's something that I just realized. My monkey-patches fix this also in suite-level ( accidentally, I did not understand the true meaning of my change in expandSuite(), when I implemented it :unamused:  ).

**Comment by karniemi** [comment] 2023-05-11 11:33
I tried your patch - and I mean, I really did for a long time - but it's frustratingly random. Sometimes the KWs are expanded, sometimes the KW cannot be expanded even manually and there's an error on Console, sometimes the KWs are expanded also when I open a Suite. And it seems completely random - though it can't be, there's something causing it.

I'm suspecting my test method is not correct. I saved a log.html from out CI rounds, and edited your changes in it -then opened the local file in browser. I'm not sure if that should work OK ... because it seems that the document header is there twice and also the "Total Statistics" and "Test Statistics" are there twice ...and also "Test Execution Log".

It's probably not causes by those changes you indicated, but this makes it pretty much impossible to test them.

**Comment by pekkaklarck** [comment] 2023-05-11 21:42
The current logic for expanding is as follows:
1. If you open the log file directly, failed tests are expanded.
2. If you open a single test in the log file, typically via the report, only that test is opened.
3. In the above case, if the test has failed, its failed keywords are expanded.
4. If you manually open a test, its failed keywords aren't expanded (unless they already were expanded earlier). 

After my above change the rules are these.
1. Same as earlier.
2. Same as earlier.
3. If you open a single test, failed keywords are expanded also if a test was skipped.
4. If you manually open a test, its failed keywords are expanded if the test was skipped.

Based on you comments we could still change the behavior so that if you manually open a test, its failed keywords are expanded both if the test has been skipped or failed. If you have opened the whole log file, failed tests are already expanded, but if you opened a single test, opening another failed test would then expand it.

**Comment by pekkaklarck** [comment] 2023-05-11 21:47
To take my earlier changes into use, you basically needed to install new enough Robot version (preferably RF 6.1 beta 1) and then apply the patch over the installed version. That's a big complicated, so I will commit those changes (along with a change to expand failed keywords also if a test has failed). After that you can install the latest code from the version control like this:

     pip install https://github.com/robotframework/robotframework/archive/master.zip

**Comment by karniemi** [comment] 2023-05-12 08:31
Thanks @pekkaklarck , sounds like the plan.

I understand that you are not quite happy maintaining the current log/report tech, but I think we revealed here some relevant user scenarios as well. BTW, the title does not quite match after we got to the same page with the actual issue - I'm not sure if it matters ( for traceability/release notes/etc).

**Comment by pekkaklarck** [comment] 2023-05-12 10:24
The fix has now been committed. Can you @karniemi install the latest version as instructed above and test does it work well enough? I also updated the title to be more generic.

**Comment by karniemi** [comment] 2023-05-15 05:13
@pekkaklarck : I just tested the changed rules #3 and #4 using master.zip - and it works nicely! Thank you!

**Comment by pekkaklarck** [comment] 2023-05-17 18:12
Thanks for testing! Great to hear the functionality now works fine. I hope transition from criticality to skip-on-failure hasn't been too painful in general.

**Closed by pekkaklarck** 2023-05-17 18:12 UTC
Labels: priority: medium, rc 1, effort: small
