### ISSUE TITLE
Use lighter and more neutral colors for report and log html page

### ISSUE THREAD

**Issue by Mogztter** [robotframework/robotframework#1943] opened 2015-03-07 23:49 UTC
Current colors are very bright/flashy, I think it would be better to user lighter and more neutral colors. To be consistent we can use Twitter Bootstrap's color scheme: http://getbootstrap.com/css/#less-variables

An other approach would be to use (sparingly) the [robotframework.org](http://robotframework.org/) color scheme to emphasize important information.

**Goal**
 * Reduce the number of colors used
  * Replace yellow as hover color with grayscale color
  * Replace grey-blue table header with grayscale color
  * Replace purple and (default) blue for links with a more balanced blue
 * Use [labels](http://getbootstrap.com/components/#labels) for status (error, warn, fail...)
 * Use monospaced font for test executions output (more readable in most case)
 * Replace black border with grayscale color (black is too intense and make other colors look pale)

**Comment by jussimalinen** [comment] 2015-04-09 07:54
We are starting to create alpha1 release now. I will move this to alpha2. That should give us still plenty of time to test the changes before final release.

**Comment by pekkaklarck** [comment] 2015-06-22 10:12
@Mogztter, are you still interested in this? As we commented in PR #1940, we really liked the new styles in general but there were some issues that needed to be fixed. If you aren't interested or don't have time, we can take a look at this ourselves. We'd like to get the new styles into 2.9 beta 1 to give users more time to comment them before the final release. We try to get that beta released already early next week.

**Comment by Mogztter** [comment] 2015-06-22 12:43
Sorry I didn't have much spare time lately. I don't think I will have time
to fix this issues this week but feel free to adapt my work.

Guillaume
Le 22 juin 2015 12:12 PM, "Pekka Klärck" <notifications@github.com> a
écrit :

**Comment by jussimalinen** [comment] 2015-06-24 18:21
So the colors we used now are still a bit more flashy than the suggested ones, but we also wanted them to be easy to differentiate for a colorblind person, and to still look good on an older monitor. These seem to work and they are still quite a bit less flashy than the originals.

Comments are welcome!

**Comment by pekkaklarck** [comment] 2015-06-24 18:45
@jussimalinen and I went through the changes proposed in PR #1940. We did same/similar changes on a separate branch, fixed some problems, and committed changes separately. As Jussi already commented above, we didn't use exactly same colors as suggested and there were also some other differences. The commits above contain more details.

In the end we are very happy with the results. Big thanks for providing the original PR @Mogztter! I hope you don't mind me adding you to AUTHORS.txt.

**Closed by pekkaklarck** 2015-06-24 18:45 UTC
Labels: beta 1, enhancement, prio-high

**Comment by Mogztter** [comment] 2015-06-26 07:18
Thanks for the follow up.

> I hope you don't mind me adding you to AUTHORS.txt.

Not at all!

**Comment by pekkaklarck** [comment] 2015-06-26 07:31
Have you @Mogztter looked how logs and reports look now? We are interested in feedback about the new styles in general, but it would be especially nice to get comments from the originator of this issue.

**Comment by Mogztter** [comment] 2015-06-29 16:05
Not yet, I need to setup a new local environment to view the changes, I will let you know :smile:

**Comment by archerydwd** [comment] 2015-10-20 10:45
As a colour blind person, I think the new colours are not good, its very hard for me to differentiate between the colours. Maybe text saying PASS / FAIL instead of TEST would be better. btw I am only slightly colour bind in the red/green spectrum, so this may be worse for people that are more colour blind on this spectrum.

**Comment by pekkaklarck** [comment] 2015-10-20 11:52
Interesting. Do you mean the proposed colord or the ones that are nowadays in use? We actually had a color blind person to test the colors and also used a tool to visualize how people with different color blindness see them. I guess the problem is that there are so many different color blindness variations. If you have problems with the current colors, please submit a new issue about that. Even better if you have a proposal for new colors or other enhancements.

**Comment by markwinspear** [comment] 2015-10-22 14:15
I ran a 'failed' report through an accessibility checker (against WCAG v2 AA) and nothing was returned against the following criterion... "1.4.3 Contrast (Minimum): The visual presentation of text and images of text has a contrast ratio of at least 4.5:1, except for the following: (Level AA)" which is the one which springs to mind.

You're right though, there are different types of colour-blindness (I have red-green colour blindness myself, but can see the reports fine).  If you are looking at changes, consider this tool... http://gmazzocato.altervista.org/colorwheel/wheel.php (from http://www.w3.org/WAI/ER/tools/)
