### ISSUE TITLE
Robot Framework == 7.0 Creates Issues with Pabot

### ISSUE THREAD

**Issue by SireenAtGithub** [robotframework/robotframework#5011] opened 2024-01-12 08:51 UTC
I am not into much of a development of the framework, but this morning I have encountered a serious trouble with latest version of robot accompanied with pabot.

For a below command, it ends up creating a thread single testcase for the given number of processes.

pabot --testlevelsplit --processes 6 testSuite.robot

Suppose above Test Suite has 8 test cases inside. with the pabot execution, it creates 6 instances of a 1st test cases. and I will endup executing each testcase 6 times in the execution.

**Comment by pekkaklarck** [comment] 2024-01-12 09:37
That sounds strange and also more like a bug in Pabot. Have you reported the issue to its tracker? Someone needed to debug the issue to see where the problem is. If there's a regression in Robot, it needs to be fixed. If there's a change to some private API used by Pabot, the fix should be done in Pabot instead.

**Comment by SireenAtGithub** [comment] 2024-01-12 10:53
> That sounds strange and also more like a bug in Pabot. Have you reported the issue to its tracker? Someone needed to debug the issue to see where the problem is. If there's a regression in Robot, it needs to be fixed. If there's a change to some private API used by Pabot, the fix should be done in Pabot instead.

I saw the latest release from pabot; It was updated on Last October, and I saw latest update in robot framework just a day ago. So it was my due diligence to update the folks in this community. Anyhow I will creating a copy of the issue in pabot as well.

**Comment by pekkaklarck** [comment] 2024-01-31 11:30
It seems incompatibilities in Pabot have been fixed and the Pabot issue referenced above closed. I'll close this issue.

**Closed by pekkaklarck** 2024-01-31 11:30 UTC
