### ISSUE TITLE
Unable to use keywords with embedded arguments in Teardown statements

### ISSUE THREAD

**Issue by luisjaviersanz** [robotframework/robotframework#2378] opened 2016-05-26 11:18 UTC
Using the latest version of Robot Framework, it seems that it is not possible to use keywords with embedded arguments in Teardown statements, for example:

```
*** Variables ***
${EMBEDDED}    one

*** Test Cases ***
Test name
    Some stuff
    [Teardown]   Keyword with ${EMBEDDED} argument
```

While executing the test, the runner throws this output:

```
Also, teardown failed:
No keyword with name 'Keyword with one argument' found.
```

But it works when including the keyword in the test case like:
```
Test name
    Some stuff
    Keyword with ${EMBEDDED} argument
```

Maybe, this issue is also reproducible when using this kind of keywords in setup statements.

Thanks in advance!

**Comment by pekkaklarck** [comment] 2016-05-31 10:10
This limitation is caused by the fact that setups and teardowns can be specified as variables:
http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#test-setup-and-teardown

In practice Robot replaces variables in setup/teardown before searching does a keyword with that name exist. Due to backwards compatibility reasons this behavior cannot be changed overnight. We could consider changing the logic so that variable is resolved before finding a keyword only if the keyword is defined fully as a variable (e.g. `${SETUP}`) but now when a variable is part of the name (e.g `Do some ${SETUP} stuff`). Even that change would be backwards incompatible, but I would guess having a variable only as part of the name is *very* rare. Because we want to be extra careful with backwards compatibility, such a change is only possible in a major version like RF 3.1.

Are you @luisjaviersanz interested to look at implementing this? The new functionality should obviously also be documented in the User Guide.

**Comment by pekkaklarck** [comment] 2016-07-04 11:49
Works as designed. Changing the design is too much work and at least somewhat backwards incompatible. Closing.

**Closed by pekkaklarck** 2016-07-04 11:49 UTC
