### ISSUE TITLE
Robot Keyword Arguments naming conflict between argument name and global variable

### ISSUE THREAD

**Issue by tjshewmake** [robotframework/robotframework#1957] opened 2015-04-02 21:32 UTC
I am using Robot Framework 2.8.7 with Python 2.7.3.

I am running into an issue when trying to define kwargs for Robot keywords where the default value (which is currently pointing to a global variable) is being overwritten by a local-scoped variable with the same name.  Here's the code...

```
*** Variables ***
${POSTAL_CODE}      90401


*** Keywords ***
Log a variable
    [Arguments]     ${postal_code}=${POSTAL_CODE}
    Log     ${postal_code}
    Another keyword to log a variable    # postal_code is not being explicitly passed in
 
Another keyword to log a variable
    [Arguments]     ${postal_code}=${POSTAL_CODE}
    Log     ${postal_code}


*** Test Cases ***
I want to validate that local variables are different
    Log a variable                       # This logs 90401 twice, as expected
    Log a variable  postal_code=90230    # This logs 90230 the first time (as expected),
                                         #   but also the second time (not expected).
```

`Another keyword to log a variable` as it is being used in `Log a variable` should be logging the default global value of POSTAL_CODE, but the locally-scoped postal_code is being logged instead.

My current work-around for this issue is to have different names for the arguments as we do for their global variable equivalents, but naming things is hard, and it would be ideal to use the same name for both global variables and local arguments without worrying about adverse side-effects.

**Comment by pekkaklarck** [comment] 2015-04-02 22:50
This looks like a duplicate of #532.

**Closed** 2015-04-08 07:50 UTC
Labels: duplicate
