### ISSUE TITLE
RF 4.0.2 fails keyword is keyword typehint has TypedDict

### ISSUE THREAD

**Issue by aaltat** [robotframework/robotframework#3969] opened 2021-05-12 18:14 UTC
RF 4.0.2 fails keyword is library keyword type hint has TypedDict. When I have this test:
```
*** Settings ***
Library    MyLib.py

*** Test Cases ***
Test
    ${dict} =    Create Dictionary    key=value    other=1
    Log    ${dict}
    Keyword    ${dict}
```
And when library is like this:
```
from typing import TypedDict, Union


class Arg(TypedDict):
    key: str
    other: str


def keyword(arg: Union[Arg] = None):
    print(arg)
```
When test is run, then keyword fails with: `TypeError: TypedDict does not support instance and class checks`. The stack trace points to:
```
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/typing.py", line 1728, in _check_fails
    raise TypeError('TypedDict does not support instance and class checks')
```
Can be reproduced with Python 3.7 - 3.9 and only with RF 4.0.2. The above test works with RF 4.0.1, so it feels like it is regression in RF 4.0.2.

**Comment by pekkaklarck** [comment] 2021-05-13 21:34
The problem described is serious but it seems problems with TypedDicts are even worse. I tested this with the following library

```python
import sys
from typing import TypedDict, Union
X = TypedDict('X', x=int)
def normal(a: X):
    print(a, type(a), file=sys.__stdout__)
def union(a: Union[X, int]):
    print(a, type(a), file=sys.__stdout__)

**Comment by pekkaklarck** [comment] 2021-05-13 21:43
The problem with `Union` and `TypedDict` is a regression caused by #3897. `TypedDict` nowadays not working at all is an other regression caused by #3931 that fixed a problem caused by #3897 with subscribed generics.

In addition to making sure `TypedDict` works with and without `Union`, need to make sure `Union` containing types that raise an exception if used with `isinstance` or `issubclass` is handled properly as well.

**Comment by pekkaklarck** [comment] 2021-05-13 23:05
Problems with TypedDicts ought to now be fixed. Before closing this issue, I still want to make sure no other type that fails when used with `isinstance` or `issubclass` can cause this kind of problems.

**Closed** 2021-05-16 20:49 UTC
Labels: bug, priority: critical

**Comment by pekkaklarck** [comment] 2021-05-16 20:51
Above commit fixed the underlying problem with TypedDicts in more generic manner. RF 4.0.3 beta 1 will be created on Monday. Hopefully you @aaltat can test the fix once its out.

**Comment by aaltat** [comment] 2021-05-17 17:44
Tested from current master branch and worked well. No failures.

**Comment by pekkaklarck** [comment] 2021-05-19 11:21
Thanks for testing @aaltat! I'll create RF 4.0.3 beta today so that others can test this as well. The final could then be released on Monday.
