### ISSUE TITLE
Appending to test message using HTML doesn't work if old message is not HTML

### ISSUE THREAD

**Issue by StephanMath** [robotframework/robotframework#2732] opened 2017-12-07 17:00 UTC
I would like insert a line between test messages :
`Set Test Message | *HTML* Insert line here<hr> | append=True`
But when i use optional argument 'append=True', message appear in text format. 

(Test with robotframework 3.0.2)

**Comment by laurentbristiel** [comment] 2017-12-08 12:45
I did some testing around this and the problem is a little bit more complex.
What I see is that "Set Test Message" with HTML formatting AND append=yes does not work when appending on a "test message" that is not HTML formatted.

1) this would work:
````
	Set Test Message  *HTML* custom message<hr>after the line<BR>
	Set Test Message  *HTML* and another custom message  append=True
````

2) but this would indeed not work properly
````
	Set Test Message  custom message
	Set Test Message  *HTML* and another custom message in <HR> with a line  append=True
````
=> In that case you would get : `custom message *HTML* and another custom message in <HR> with a line`

3) note that appending Test Message with HTML formatting in Test Teardown with an error message coming from Robot (in case of failure) would not work neither because Robot Message is not HTML formatted.

@StephanMath do you agree with this analysis?

All that being said, I don't know how Robot should managed cases where HTML should be append to non-HTML... Looks quite difficult. Maybe we should just document that *HTML* with append works only when appending to HTML?

**Comment by pekkaklarck** [comment] 2017-12-08 13:00
Seems to be a variation of #2360. Shouldn't be overly complicated to fix.

**Comment by StephanMath** [comment] 2017-12-08 14:09
@laurentbristiel I confirm your analysis. 
So I understand I can use "Set Test Message" keyword in HTML format with argument "append=True" only if all test messages in one testcase use HTML formatting.
Thank you for your explanations.

**Comment by StephanMath** [comment] 2017-12-08 14:11
@pekkaklarck Thank you for your change with a title more explicit :)

**Comment by pekkaklarck** [comment] 2017-12-08 14:24
No need to close this. I consider the current functionality a bug that ought to be fixed.

**Closed** 2018-03-27 18:01 UTC
Labels: priority: medium
