### ISSUE TITLE
Log Variables fails if a variable file contains import statement: "from typing import ..."

### ISSUE THREAD

**Issue by mikeleppane** [robotframework/robotframework#3545] opened 2020-04-16 12:28 UTC
Hi!

I have a python file which acts as a variable file and it is imported to robot side via Variables declaration. This file contains type hints. Now if I try execute Robot Log Variables-kw it fails for raising TypeError. It tries to log "@{Dict}"? In this case the variable file contains following statement:
```python
from typing import Dict
```
The same thing happens if there is e.g. a Tuple or Set instead of Dict. 

Traceback:
```python
TypeError: Parameters to generic types must be types. Got 0.
Traceback (most recent call last):
  File "/usr/lib/python3.6/typing.py", line 682, in inner
    return func(*args, **kwds)
  File "/usr/lib/python3.6/typing.py", line 1107, in __getitem__
    params = tuple(_type_check(p, msg) for p in params)
  File "/usr/lib/python3.6/typing.py", line 1107, in <genexpr>
    params = tuple(_type_check(p, msg) for p in params)
  File "/usr/lib/python3.6/typing.py", line 374, in _type_check
    raise TypeError(msg + " Got %.100r." % (arg,))
```
Log Variables-kw works if I change the import statement to "import typing" and use it including the namespace: "typing.Dict[...]"

I'm using Robot framework version 3.1.2

-Mikko

**Comment by pekkaklarck** [comment] 2020-04-16 13:14
The reason this happens is that:

- Also that `Dict` is exposed as a variable. See the User Guide for possibilities how to avoid that.
- `typing.Dict` is considered iterable by our code but trying to iterate over it fails with the TypeError you got.
- `Log Variables` tries to iterate over values that are considered iterable to log items individually.

Incidentally this exact same problem, that time with `faker.Faker` instead of `typing.Dict`, was reported few days ago as #3540. The problem was fixed by adding error handling to `Log Variables` and the plan is to change our iterable detection in the future. See the [StackOverflow answer](https://stackoverflow.com/a/61139278/38083) I wrote after investigating #3540 for more details about the latter.

The problem is thus now fixed and the fix will be included in RF 3.2 final that is likely to be released on Monday. I was hoping to get it out already tomorrow, but there's still so much documentation work to be done that it's unlikely to be ready by then. Consider testing RF 3.2 rc 1 (which doesn't have the `Log Variables` fix) to see can you migrate to it once the final release is out.

**Closed by pekkaklarck** 2020-04-16 13:14 UTC
