### ISSUE TITLE
Keyword fails on type conversion with complex types

### ISSUE THREAD

**Issue by orjgre** [robotframework/robotframework#3954] opened 2021-04-29 13:00 UTC
Keywords with subscripted generics type hints fails with the following error
```
TypeError: Subscripted generics cannot be used with class and instance checks
```
This seems to be related to the [breaking changes in version 4.0.1](https://github.com/robotframework/robotframework/blob/master/doc/releasenotes/rf-4.0.1.rst#avoid-argument-conversion-if-given-argument-has-one-of-the-accepted-types)

Example:
Library file defining the keyword
```
from typing import Union, Dict, List
_type1 = Dict[str, Union[str, Number]]
def failing_function(arg: Union[_type1, List[_type1]] = None):
    doSomething()
```
Robot file defining the test case:
```
Test case
    &{test_dict} =     Create Dictionary    a=1   b=2 c=test
    Failing function    a=&{test_dict}
```

The whole traceback is not visible in the log:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/typing.py", line 769, in __instancecheck__
    return self.__subclasscheck__(type(obj))
  File "/usr/lib/python3.8/typing.py", line 777, in __subclasscheck__
    raise TypeError("Subscripted generics cannot be used with"
```
Version info:
```
python3 -m robot --version
Robot Framework 4.0.1 (Python 3.8.5 on linux)
```

**Comment by pekkaklarck** [comment] 2021-04-29 13:19
This is already reported as #3931 and will be fixed in RF 4.0.2. Annoying regression caused by the fix for #3897.

**Closed by pekkaklarck** 2021-04-29 13:19 UTC

**Comment by orjgre** [comment] 2021-04-29 13:34
Sorry. I didn't find that issue.

**Comment by pekkaklarck** [comment] 2021-04-29 13:46
No worries. :smile:
