### ISSUE TITLE
Method Names With Same Beginning Failing

### ISSUE THREAD

**Issue by mattc41190** [robotframework/robotframework#2127] opened 2015-09-02 15:40 UTC
## Set Up 

Robot Framework version: 2.9
Python interpreter type: Python -  2.7.10
Operating System: Lenovo T530 Windows 8.1

## Step To Reproduce:

Create Two Keywords With Identical Beginning and different endings
Example:

Keyword 1: Call ExampleAPI As User: ${username} Password: ${password}

Keyword 2: Call ExampleAPI As User: ${username} Password: ${password} With Filter ${filter} Set To: ${value}

## Result

When you attempt to run either keyword you receive the following error:

```[ ERROR ] Creating user keyword 'Call ExampleAPI As User: ${username} Password: ${password} With Filter ${filter} Set To: ${value}' failed: Keyword with same name defined multiple times.```

**Comment by pekkaklarck** [comment] 2015-09-02 20:25
This looks very much like a duplicate of #2098 that was fixed in 2.9.1. Could you upgrade and see does that fix you problem?

**Comment by pekkaklarck** [comment] 2015-09-08 08:29
I assume this was a dupe of #2098. Please comment here or submit a new issue if the problem persists in 2.9.1.

**Closed by pekkaklarck** 2015-09-08 08:29 UTC
