### ISSUE TITLE
Dictinaries are not accepted as-is in argument conversion with unions containing TypedDicts

### ISSUE THREAD

**Issue by David-Tennant-Enreach** [robotframework/robotframework#5114] opened 2024-04-16 12:52 UTC
When executing my library, arguments get cast to the first matching type instead of the actual type of the input. I believe this is to do with how Robot handles annotations. Rather than investigating too much into this, I have created an example to show the unexpected behaviour.

Please let me know if this is intentional.

Issues:
- arguments that do not match the type become `str`, see the `float` variable below
- arguments that match the first type are cast to that type, you can see a `dict` being cast to `str`. Order A fails, Order B works as expected

# Output from terminal

When executing the robot file:

```
robot TestSuite.robot
==============================================================================
TestSuite
==============================================================================
Foo                                                                   .......expected | None | <class 'NoneType'>
order_a | None | <class 'NoneType'>
order_b | None | <class 'NoneType'>
expected | {'prop': 'bar'} | <class 'robot.utils.dotdict.DotDict'>
order_a | {'prop': 'bar'} | <class 'str'> ### This should not be str
order_b | {'prop': 'bar'} | <class 'robot.utils.dotdict.DotDict'>
expected | foo | <class 'str'>
order_a | foo | <class 'str'>
order_b | foo | <class 'str'>
expected | 4 | <class 'int'>
order_a | 4 | <class 'int'>
order_b | 4 | <class 'int'>
expected | 2.0 | <class 'float'>
order_a | 2.0 | <class 'str'> ### This should be float
order_b | 2.0 | <class 'str'>  ### This should be float
expected | {'prop': 'bar'} | <class 'dict'>
order_a | {'prop': 'bar'} | <class 'str'> ### This should not be str
order_b | {'prop': 'bar'} | <class 'dict'>
Foo                                                                   | PASS |
------------------------------------------------------------------------------
TestSuite                                                             | PASS |
1 test, 1 passed, 0 failed
==============================================================================
```

When exectuing the python file

```
python3 test.py

def types_order_a(self, var: str | MyDictType | None | int):
def types_order_b(self, var: None | MyDictType | str | int):
order_a | None | <class 'NoneType'>
order_b | None | <class 'NoneType'>
expected | None | <class 'NoneType'>
order_a | {'prop': 'bar'} | <class 'dict'>
order_b | {'prop': 'bar'} | <class 'dict'>
expected | {'prop': 'bar'} | <class 'dict'>
order_a | foo | <class 'str'>
order_b | foo | <class 'str'>
expected | foo | <class 'str'>
order_a | 4 | <class 'int'>
order_b | 4 | <class 'int'>
expected | 4 | <class 'int'>
order_a | 2.0 | <class 'float'>
order_b | 2.0 | <class 'float'>
expected | 2.0 | <class 'float'>
```

# Files

## Library: CustomLibrary.py

```py

from typing import TypedDict
from robot.api.logger import console


class MyDictType(TypedDict):
    prop: str


class CustomLibrary:
    def print_signatures(self):
        console("def types_order_a(self, var: str | MyDictType | None | int):")
        console("def types_order_b(self, var: None | MyDictType | str | int):")

    def types_order_a(self, var: str | MyDictType | None | int):
        console(f"order_a | {var} | {type(var)}")

    def types_order_b(self, var: MyDictType | str | None | int):
        console(f"order_b | {var} | {type(var)}")

    def no_types(self, var):
        console(f"expected | {var} | {type(var)}")



```

## Robot: TestSuite.robot

```robot

*** Settings ***
Library     ./CustomLibrary.py


*** Test Cases ***
Foo
    ${var1}=    Evaluate    None
    # Gets cast to a string for order A but not order B
    ${var2}=    Create Dictionary    prop=bar
    ${var3}=    Set Variable    foo
    ${var4}=    Set Variable    ${4}
    # Gets cast to a string because there is no float type in the function
    ${var5}=    Set Variable    ${2.0}
    # Dictionary that matches MyDictType
    ${var6}=    Evaluate    {"prop":"bar"}

    ${list}=    Create List    ${var1}    ${var2}    ${var3}    ${var4}    ${var5}    ${var6}
    FOR    ${item}    IN    @{list}
        CustomLibrary.No Types    ${item}
        CustomLibrary.Types Order A    ${item}
        CustomLibrary.Types Order B    ${item}
    END


```

## Python Runner: test.py

```py

from CustomLibrary import CustomLibrary

lib = CustomLibrary()

var1 = None
var2 = {"prop": "bar"}
var3 = "foo"
var4 = 4
var5 = 2.0


lib.print_signatures()

inputs = [var1, var2, var3, var4, var5]

for input in inputs:
    lib.types_order_a(input)
    lib.types_order_b(input)
    lib.no_types(input)


```

**Comment by pekkaklarck** [comment] 2024-04-16 17:48
I'm on mobile and cannot run the example now, but some clarifying questions below:
-Which Robot version do you use?
- Which conversations don't look good for you?
- Could you test changing `MyDictType` to `dict` in type hints?

**Comment by David-Tennant-Enreach** [comment] 2024-04-17 13:56
Thanks for the reply!

> Which Robot version do you use?

`pip show robotframework`

```
Name: robotframework
Version: 7.0
Summary: Generic automation framework for acceptance testing and robotic process automation (RPA)
Home-page: https://robotframework.org
Author: Pekka Klärck
Author-email: peke@eliga.fi
License: Apache License 2.0
Location: /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages
Requires:
Required-by: robotframework-seleniumlibrary, robotframework-tidy
```


> Which conversations don't look good for you?

I extracted the parts that do not look good. Where it's casting a `dict` to a `str` because the signature is ` def types_order_a(self, var: str | MyDictType | None | int):`, hence order_a being `str` and not the Robot dict or native dict

I would expect it to not match on str but match on MyDictType. It does match for `order_b` which puts `MyDictType` first

```
expected | {'prop': 'bar'} | <class 'robot.utils.dotdict.DotDict'>
order_a | {'prop': 'bar'} | <class 'str'> ### This should not be str
order_b | {'prop': 'bar'} | <class 'robot.utils.dotdict.DotDict'>

expected | 2.0 | <class 'float'>
order_a | 2.0 | <class 'str'> ### This should be float
order_b | 2.0 | <class 'str'>  ### This should be float

expected | {'prop': 'bar'} | <class 'dict'>
order_a | {'prop': 'bar'} | <class 'str'> ### This should not be str
order_b | {'prop': 'bar'} | <class 'dict'>
```

> Could you test changing MyDictType to dict in type hints?

i did so and it works as expected

```
expected | {'prop': 'bar'} | <class 'robot.utils.dotdict.DotDict'>
order_a | {'prop': 'bar'} | <class 'robot.utils.dotdict.DotDict'>
order_b | {'prop': 'bar'} | <class 'robot.utils.dotdict.DotDict'>

expected | {'prop': 'bar'} | <class 'dict'>
order_a | {'prop': 'bar'} | <class 'dict'>
order_b | {'prop': 'bar'} | <class 'dict'>
```

**Comment by pekkaklarck** [comment] 2024-04-21 23:09
If an argument has multiple accepted types, argument conversion goes like this on high level:
1. Check does the given argument match any of the accepted types.
2. If it does, use the argument as-is.
3. If it doesn't, try converting the argument to specified types from left to right.
4. If conversion to any type succeeds, return the converted value.
5. If no conversion succeeds, fail.

The above rules explain why your float is converted to a string:
1. Your keyword doesn't accept floats
2. Float cannot be used as-is.
3. Conversion to specified types is accepted.
4. Conversion to `str` succeeds and the converted value is returned.

The problems with TypedDicts are caused by a bug, though. When checking does the given argument match any of the accepted types, TypedDicts currently never match. Because no other type match either, conversion is attempted from left to right and `str` conversion is the first to succeed. As you have already noticed, if you have `str` after a TypedDict, TypedDict conversion is attempted first and it succeeds.

I'll update the issue title accordingly. Fixing this doesn't seem to be too complicated, so I'll assign this to already long overdue 7.0.1 scope.

**Comment by David-Tennant-Enreach** [comment] 2024-04-22 09:48
Thanks for the response and the information. Hope the bug fix goes well

**Closed** 2024-04-22 10:31 UTC
Labels: bug, priority: medium, effort: small
