### ISSUE TITLE
"FAIL: Invalid variable name" when using "Get Variable Value" with variable inside variable

### ISSUE THREAD

**Issue by grossvati** [robotframework/robotframework#3552] opened 2020-04-20 20:42 UTC
When I use the "Get Variable Value" function with a "variable inside a variable", I get an error message that the "variable inside the variable" is invalid.

Test Example:
I have three test environments for my web application. With a variable ${stage} I can easily select the desired stage via the commandline. If the variable is not assigned via the commandline, "stage 2" should be used in the standard.

```
*** Variables ***
${URL}     ${EMPTY}
${URL for stage 0}    https://localhost:8080/
${URL for stage 1}    https://123.server.de/
${URL for stage 2}    https://987.server.de/
${stage}    2

*** Keywords ***
Find URL
     ${URL} =    Get Variable Value    ${URL for stage ${stage}}
     Set Global Variable    ${URL}
```

FAIL : Invalid variable name '${URL for stage ${stage}}'.

**Comment by Snooz82** [comment] 2020-04-20 21:25
@pekkaklarck 

This one causes it.
`Refactor variable search and validation.` from 04.03.2020

https://github.com/robotframework/robotframework/commit/52a0923d422275a7a2f2db05bda59103d1bbd03d

**Comment by pekkaklarck** [comment] 2020-04-20 22:02
I can reproduce the problem and @Snooz82 seems to be right about the commit that broke this. The logic related to resolving variable name when used with `Get Variable Value` is somewhat complicated and we clearly didn't have any tests for this particular case. Good news is that I ought to be able to get it fixed.

Although this hopefully will be fixed still before RF 3.2, there are two good workarounds how to avoid the issue:

1. Instead of `${URL for stage ${stage}}` use either `\${URL for stage ${stage}}` or `$URL for stage ${stage}` format with `Get Variable Value`. Why this helps is explained in the documentation of [Set Suite Variable](http://robotframework.org/robotframework/latest/libraries/BuiltIn.html#Set%20Suite%20Variable) and is part of the reason why resolving these variable names is somewhat complicated.

2. Don't use `Get Variable Value` at all. You may need it in some other cases, but in this particular case you can simply use:

        Set Global Variable    ${URL}    ${URL for stage ${stage}}

**Closed** 2020-04-20 22:43 UTC

**Comment by pekkaklarck** [comment] 2020-04-20 22:44
Got this fixed pretty easily. I was already thinking should I create RF 3.2 rc 2 due to earlier smallish changes, but after this regression fix there's no question about it anymore.

**Comment by grossvati** [comment] 2020-04-21 07:33
Great job and thanks for the quick help and tip in the end.
I changed my keyword. Now it works as a one-liner without "Get Variable Value".
How long does "Set Global Variable" have the argument "* values"?
I have been using Robot Framework for a year and I remember that I had to use "Get Variable Value" in an earlier version of the Robot Framework for this case. Strange but never mind :-)

**Comment by pekkaklarck** [comment] 2020-04-21 07:38
Good that the tip helped but hopefully you can also validate the fix for your problem once rc2 is out.

`Set Global Variable` has accepted the variable value for ages, most likely from time when the keyword was implemented.

**Comment by grossvati** [comment] 2020-04-21 07:43
With pleasure. The old code still exists as a "comment".

**Comment by pekkaklarck** [comment] 2020-04-21 14:36
Release candidate 2 is now out. Based on the discussion on Slack also others had encountered this issue.

**Comment by grossvati** [comment] 2020-04-23 13:49
I tested my test cases with rc2. The new release works correctly.
