### ISSUE TITLE
Listeners slow down execution, especially in RF 2.9 when keyword return values are big

### ISSUE THREAD

**Issue by Brunlof** [robotframework/robotframework#2234] opened 2015-11-25 07:58 UTC
Hi,

I raised a question on the robotframework-users forum and was recommended to create an issue here instead: https://groups.google.com/forum/#!topic/robotframework-users/l3S0S7aJLAg

Anyway:
I recently upgraded from Robot Framework 2.8.7 to version 2.9.2. After doing so I saw my test suite execution time increased from the normal 20 min to 30 min. After looking in to it a bit closer I think it boils down to that working with large dictionaries has become a lot slower.

I created a simple test to illustrate the issue, all I'm doing is assigning the value of myDict[data] to a variable. (I run python 2.7.6 on windows 7)

In Robot Framework 2.8.7 this takes approximately 70 ms.
In Robot Framework 2.9.2 this takes more than 1.2 s.

I also tried to use "Get From Dictionary" from the "Collections" library instead but I get almost the same results, its even a bit worse. ~70 ms VS 1.4 s.

[testDict.py.txt](https://github.com/robotframework/robotframework/files/43583/testDict.py.txt)
[test.txt](https://github.com/robotframework/robotframework/files/43581/test.txt)

**Comment by pekkaklarck** [comment] 2015-11-25 08:44
This could be due to us introducing a new `DotDict` object that is used instead of normal dicts with the new dictionary variables and also in some other cases. Normal dictionaries in variable files shouldn't be converted to `DotDict` objects automatically, though, so it shouldn't affect the example you attached. I also tested your example both on Windows and Linux and got no meaningful time differences between 2.8.7, 2.9.2 and the latest code in the repository. Are you sure this is exactly the scenario that is so much slower with 2.9.2 in your system?

**Comment by Brunlof** [comment] 2015-11-25 12:40
Hi Pekka,

Thanks for a quick reply.

I run exactly the same test case as I attached and it is much slower on 2.9.2 on my system.
Included picture (Could not upload a .zip) of log output from both 2.8.7 and 2.9.2. 

![testlog2 8 7](https://cloud.githubusercontent.com/assets/15976512/11397432/b657add2-9379-11e5-98bc-bd06a7100636.png)
![testlog2 9 2](https://cloud.githubusercontent.com/assets/15976512/11397433/b65a20a8-9379-11e5-940b-71eb799a0bba.png)

**Comment by Brunlof** [comment] 2015-11-27 08:27
I could add that I do not usually have dictionaries in variable files in my test suite, it was just the simplest example I found that could reproduce the problem.

Here is an example that is closer to reality:
[CodeExample.txt](https://github.com/robotframework/robotframework/files/45509/CodeExample.txt)
![example2 8 7](https://cloud.githubusercontent.com/assets/15976512/11436814/71c2317c-94e8-11e5-8eaf-f9b42b15eeb6.png)
![example2 9 2](https://cloud.githubusercontent.com/assets/15976512/11436815/7506a890-94e8-11e5-9085-9d094af89bbc.png)

In the test case I use a PicoScope to collect voltage measurement data.
2.8.7 Total execution time: 7.3s
2.9.2 Total execution time: 15.2

The differences in time are seen when the dictionary is processed.

**Comment by Brunlof** [comment] 2015-11-27 09:03
Not sure if this is any help but I just realized that I get the same performance issue if I use a large list instead of a large dictionary.

**Comment by pekkaklarck** [comment] 2015-11-27 09:20
How much RAM you have? Could it be that memory consumption has got bigger and that results swapping and thus slower execution?

**Comment by Brunlof** [comment] 2015-11-27 09:33
I have 8 GB of RAM free so I do not think that should be the problem.

**Comment by Brunlof** [comment] 2015-11-27 09:54
I might be on to something. 
I cannot reproduce the issue on my local machine by just running it from command line. I get the problem when I execute the test case from RIDE.

However, on our build machine we see the problem even though RIDE is not used. Let me see if I can find out what differs.

**Comment by pekkaklarck** [comment] 2015-11-27 10:37
8GB is definitely enough, I have less on my virtual machine. I just try to understand why I didn't have performance regression with your earlier example. Related to that, it is definitely a good idea to try this without RIDE.

If you you more examples I could try on my environment please attach them here. I have actually been doing a little performance optimization recently also otherwise, and would be interested to profile different data sets.

**Comment by Brunlof** [comment] 2015-11-27 11:11
I think I have found it.

We have a listener (--listener=TCReporter) that reports data to TeamCity and it looks like that one is slowing things down considerably when running 2.9.2.
[TCReporter.py.txt](https://github.com/robotframework/robotframework/files/45655/TCReporter.py.txt)

Do you have any idea why this has become slower?

**Comment by pekkaklarck** [comment] 2015-11-27 12:39
Interesting. Apparently some change to the listener API has made it slower. Could you try creating a listener that demonstrates this behavior so that we could test it?

**Comment by Brunlof** [comment] 2015-11-27 13:24
You should be able to run the one I attached. I just produces printouts that TeamCity can read, there are no dependencies.

**Comment by pekkaklarck** [comment] 2015-11-29 22:29
Ok, didn't notice the attachement earlier. I'll test it tomorrow. Assuming I can reproduce the issue, it shouldn't be hard to find out what change has caused it between 2.8.7 and 2.9.

If you are interested, you could also clone the repository and bisect changes between releases yourself. It would also be interested to know how the latest RF code works in your real environment.

**Comment by pekkaklarck** [comment] 2015-11-30 09:20
OK, found the root cause. I also learned that listeners slow down execution with earlier versions too, but there the problem is much smaller. I don't have time to explain it right now, but this is definitely something we want to fix urgently. I'll probably open a new issue about this and explain it more thoroughly, but before that I'll just assign this one to 3.0 alpha 2 scope.

**Comment by pekkaklarck** [comment] 2015-11-30 12:59
Opened #2241 about the underlying issue. As explained there, the slow down in 2.9 was due to Robot pretty-printing its own trace level log messages about keyword return values. The real bug is that those messages are always evaluated when using listeners.

Thanks for reporting the issue @Brunlof and investigating it further when the original example didn't cause issues in my system. I close this issue now as a duplicate of #2241. I will fix the problem today or tomorrow, and it will be part of RF 3.0 alpha 2 that we plan to release latest next week.

**Closed by pekkaklarck** 2015-11-30 12:59 UTC
Labels: duplicate, priority: high

**Comment by Brunlof** [comment] 2015-11-30 13:18
I'm glad I could be of assistance. I'm really impressed with the amount of support I got on this, keep up the good work!
