### ISSUE TITLE
KWD "Lists Should Be Equal" | TypeError: '<' not supported between instances of 'dict' and 'dict'

### ISSUE THREAD

**Issue by ZephyrusMB** [robotframework/robotframework#4938] opened 2023-11-10 09:41 UTC
Hi,

I'm receiving following error for KWD  "Lists Should Be Equal" when comparing 2 lists of dictionaries.

`TypeError: '<' not supported between instances of 'dict' and 'dict'`

As in documentation is not described that the KWD does not support comparing lists of dictionaries I assumed that I could use it.

The use case is a control list, extracted from a json and a "found" list, extracted from UI via BrowserLibrary.
Here the example of code to reproduce the error. 
**JSONLibrary is required to reproduce the issue** `pip install robotframework-jsonlibrary`

```
*** Settings ***
Library    JSONLibrary
Library    Collections

*** Variables ***
@{capitoliTrovati}    ${cap1}  ${cap1}
&{cap1}                Accertamenti=0,00 €    Capitoli=004297    Casella Spuntata=${True}    Economie=0,00 €    Impegni=20,00 €    Liquidazioni=0,00 €
&{cap2}                Accertamenti=0,00 €    Capitoli=010794    Casella Spuntata=${False}    Economie=0,00 €    Impegni=0,00 €    Liquidazioni=0,00 €

*** Test Cases ***
Verifica liste
    Set Log Level    TRACE
    ${capitoliAttesi}    Load Json From File    3.1.3_capitoli.json
    ...    encoding=utf-8
    Lists Should Be Equal    ${capitoliAttesi}    ${capitoliTrovati}
    ...    msg=Capitoli non combacianti!    ignore_order=${True}
```

Attached the control json
[3.1.3_capitoli.json](https://github.com/robotframework/robotframework/files/13317829/3.1.3_capitoli.json)

**Comment by kkotenko** [comment] 2023-11-27 16:30
The error seems to occur because the argument ignore_order is True, so Robot Framework attempts to sort the lists ${capitoliAttesi} and ${capitoliTrovati}. For this, I assume it needs to compare the list elements, i.e. the dictionaries.

**Comment by pekkaklarck** [comment] 2023-11-27 21:23
Yeah, the problem is that when you use `ignore_order=True`, list items in the list must be sortable. Dictionaries aren't:
```python
>>> sorted([{'a': 1}, {}])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: '<' not supported between instances of 'dict' and 'dict'
```
Same error occurs if the list has, for example, integers and strings:
```python
>>> sorted([1, '2'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: '<' not supported between instances of 'str' and 'int'
```

Fixing this would require coming up with an algorithm for sorting unsortable items. Handling the latter case would be relatively simple, because we could separate items having different types to different groups and items in those groups, but types not sortable with themselves like dicsts would require separate handling. I'm personally not too interested to try solve this, but if someone else has interest I'd be happy to review PRs.

**Comment by pekkaklarck** [comment] 2023-12-15 11:16
The doesn't seem to be interest towards fixing this. Closing.

**Closed by pekkaklarck** 2023-12-15 11:16 UTC
