### ISSUE TITLE
`Import Resource` should be executed in dry-run

### ISSUE THREAD

**Issue by RobertUlbrich** [robotframework/robotframework#3418] opened 2019-12-18 18:38 UTC
When I do a dryrun on Test Cases that utilize a dynamic import (Import Resource), it fails saying that the keywords are missing, but during a real run, they are imported and available as expected.

**Comment by pekkaklarck** [comment] 2019-12-18 20:01
The problem is that library keywords like "Import Resource" aren't executed at all. There are certain exceptions to this, like "Run Keyword If", and possibly "Import Resource" and other import keywords could be handled the same way. Unfortunately variables cannot be evaluated in the dry-run mode (we got an issue about that as well), and I would except most import keyword usages to use them. It this thus a bit questionable would that change alone make a real difference.

What's your use case for using "Import Resource"?

**Comment by RobertUlbrich** [comment] 2019-12-18 21:30
I am essentially trying to implement polymorphism. So that from my Test Case, I can call a Keyword, but depending on the environment, the Keyword implementation may come from one of a few different Resource files. The way this is done is that during Suite Setup, the execution environment is checked and the proper Resources are Imported.

As far as implementing the dry run for robot, it would be quite a challenge because, in this case, there are duplicated Keywords. I just thought I would see where this idea lands :)

**Comment by pekkaklarck** [comment] 2019-12-19 05:54
Have you tried implementing this by using normal resource import having a variable like:

    Resource            ${ENVIRONMENT}.resource

In this context variables may be resolved even in dry-run.

**Comment by RobertUlbrich** [comment] 2019-12-19 14:41
Interesting..I did not realize that was an option. I can definitely use that to simplify some of my test cases. But, there are still variables, in my situation, which are only determined during run-time. I do not see how I can do the normal resource import for this case. Any other thoughts/ideas?

**Comment by laurierloi** [comment] 2021-09-17 18:45
I encountered a similar issue using `Import Library`.

### My use case
I use the `Import Library myvar=${baz} FOO` to generate multiple instance of library FOO with value `myvar` set to variable `baz`. As a configuration. Because `baz` variable is present in the call, dry-run fails because it is unable to resolve the `Import Library` keyword.

Error message is: `Resolving variable '${baz}' failed: Variable '${baz}' not found.` It causes the successive call of `FOO`'s method to also fail, leading to multiple failures in the dryrun.

### Saving our CI
We use dryrun in our CI to validate syntax. Ignoring segments where we do dynamic `Import Library` would be fine. Ideally we would have a way to avoid failures when they are encountered. We though about overloading `Import Library` to have a version where the variable is not used when in dry-run, but it feels like it is a very hacky solution.

Is there a way to ignore the dynamics import, such as `Import Resource` or `Import Library` during dry-run? Even if it ignores the complete test case or resources associated

**Comment by borutzki** [comment] 2023-06-21 11:10
In my case, I had to use only one keyword from imported resource, so I just moved `Import Resource` keyword to another container-keyword with `robot:no-dry-run` tag in it. Worked correctly but I wouldn't like to use it in a broader context.

**Comment by pekkaklarck** [comment] 2024-07-13 13:30
There's PR #5131 that ought to fix this, but it lacks tests. It can still be merged before RF 7.1 if tests are added.

**Comment by pekkaklarck** [comment] 2024-08-27 14:05
Implemented in PR #5131 by @wendi616. Thanks for the contribution!

**Closed by pekkaklarck** 2024-08-27 14:05 UTC
Labels: enhancement, priority: medium, acknowledge, effort: small

**Comment by pekkaklarck** [comment] 2024-08-27 14:15
Due to the limitation that variables aren't available in dry-run, all `Import Resource` usages aren't going to work. An exception is using the `${CURDIR}` variable, because it is handled differently than other variables.
