### ISSUE TITLE
`IF` condition is ignored if test teardown was fail intentionally by `Fail` keyword

### ISSUE THREAD

**Issue by MininAS** [robotframework/robotframework#4064] opened 2021-08-20 11:56 UTC
Why is a test status keeped like PASS if really the test status is PASS but we intentionally fail it by Fail keyword in teardown?

robotframework = 4.0.1
os = win 10
python = 3.7.9

```
*** Settings ***
Documentation      ...

*** Variables ***

*** Test cases ***
Some Test Case
    Should Be True    ${TRUE}
    [Teardown]    Test Teardown

*** Keywords ***
Test Teardown
    Log    ${TEST_STATUS}
    Fail
    Log    ${TEST_STATUS}
    IF    '${TEST_STATUS}' == 'FAIL' or '${TEST_STATUS}' == 'SKIP'
        Some needed operations
    END
```

![image](https://user-images.githubusercontent.com/48047242/130424539-cf886e63-cfd2-4452-8c2d-08bcf5bda5e2.png)

**Comment by MininAS** [comment] 2021-08-20 11:57
![image](https://user-images.githubusercontent.com/48047242/130229719-b922be9f-cc1b-4baf-a306-014e440a39e4.png)

**Comment by MrBIN89** [comment] 2021-08-23 09:18
Looks like the root cause is the ${TEST_STATUS} isn't updated in case the `Fail` was called in test teardown.
Though it looks pretty ok for me, actually test is pass, but the teardown is a fail really.

**Comment by MininAS** [comment] 2021-08-23 10:55
Yep, looks like so, so I have edited report. 
Also, the gray state of `IF` is misleading - as if it was not executed at all. Shouldn't it be red if the condition is not true?

**Comment by pekkaklarck** [comment] 2021-08-23 11:06
Yeah, the problem is that `${TEST STATUS}` isn't updated if teardown fails. We have #2078 about that but no concrete plans when/if it will be fixed.

Un-executed IF/ELSE branches are gray by design. They aren't executed so they cannot really get PASS, FAIL or SKIP status.

**Closed by pekkaklarck** 2021-08-23 11:06 UTC

**Comment by MininAS** [comment] 2021-08-23 11:37
Big thanks!!! I understood about variables.
And don't understand why IF is not executed only if condition is false?
![image](https://user-images.githubusercontent.com/48047242/130440926-fcbf76ee-3176-4677-8a20-03e9dbe84cd2.png)

**Comment by MininAS** [comment] 2021-08-23 12:56
How `IF` can not be exexuted if it is executed and does some work like `Run Keyword If`?

![image](https://user-images.githubusercontent.com/48047242/130450547-f7f7cd3f-8e4d-43a3-9014-bfc7ee0de521.png)

**Comment by MininAS** [comment] 2021-08-23 14:14
IMHO
![image](https://user-images.githubusercontent.com/48047242/130462540-5ee314b8-23fa-41b6-84f5-a07a3874aef3.png)

**Comment by pekkaklarck** [comment] 2021-08-24 19:20
With IF branches possible statuses and associated colors are:

- NOT RUN (gray), when condition isn't true.
- PASS (green), when condition is true and the executed branch passes.
- FAIL (red), when condition is true and the executed branch fails or when evaluating the condition fails with an exception.
- SKIP (yellow), when condition is true and there's a skip in the executed branch.

As you can see, there's a clear difference between NOT RUN and PASS statuses. This won't change.

Run Keyword If is a keyword. It can also have same statuses and colors but semantics are slightly different:

- NOT RUN (gray), when the keyword isn't executed at all e.g. due to an earlier failure.
- PASS (green), when the keyword is run and passes. This includes both the situation where the condition isn't true and the underlying keyword isn't run at all and the situation where the condition is true and the underlying keyword succeeds.
- FAIL (red), when the keyword is run and fails. This includes both the situation where the condition is true and the underlying keyword fails and the situation where evaluating the condition fails with an exception.
- SKIP (yellow), when the keyword is run, the condition is true, and the executed keyword causes a skip.

**Comment by pekkaklarck** [comment] 2021-08-24 19:25
You'd probably get a better idea why colors with IF are what they are with an example with multiple branches where there's no failure. In such a case having only the executed branch in green when others are gray makes it easier to see what branch actually was run while still having all possible branches visible in the log file. Try, for example, running this example:

```robotframework
*** Test Cases ***
Example
    IF    1 < 0
        Log    Not executed
    ELSE IF    1 == 0
        Log    Executed
    ELSE IF    1 > 0
        Log    Executed
    ELSE
        Log    Not executed
    END
```

**Comment by MininAS** [comment] 2021-08-25 06:17
Big thanks for more explanation. I just more was wanted to get why status semantics are different between `IF` and `Run Keyword If`. We started to use `IF` instead the keyword recently and need to get used to that.
The example with multiple branches was more than descriptive.
