### ISSUE TITLE
Library using `@classmethod` and `@property` together crashes execution and fails with Libdoc

### ISSUE THREAD

**Issue by magrosso** [robotframework/robotframework#4802] opened 2023-06-21 09:29 UTC
Defining a tuple class variable causes this error by libdoc:

Building library 'lib\Example.py' failed: TypeError: 1 is not a callable object.

For example, something like this will fail:

class Example:
    TUPLE_CONST = (1, 2, 3, 4, 6, 8, 9, 10, 12, 14, 15, 16)

Seems like libdoc tries to interpret this tuple as a keyword. A workaround is to add a class @library decorator with auto_keywords=False. This may however cause other issues, e.g.: you have to mark all keywords explicitly with @keyword decorator.

**Comment by pekkaklarck** [comment] 2023-06-21 12:24
I tested the above example with Libdoc and had no problems. Are you sure the example is correct? How did you use Libdoc?

**Comment by magrosso** [comment] 2023-06-21 12:39
With a Python script going through all py files in folder and calling libdoc() for each one:
libdoc(library_or_resource=file_path, outfile=output_file)

Here's the more accurate example w/o methods:
class LineAccumulation:

    STANDARD_LINE_ACCU_LIST = (1, 2, 3, 4, 6, 8, 9, 10, 12, 14, 15, 16)

Building library 'lib\LineAccumulation.py' failed: TypeError: 1 is not a callable object

**Comment by pekkaklarck** [comment] 2023-06-21 13:59
Ok, that example reproduces the issue. It's the `@classmethod` + `@property` combination that causes issues, using either of them alone is fine. Using a library like this would Robot crashes the whole execution which makes this more severe. Need to be fixed in RF 6.1.1. This isn't a regression, the same issue occurs also with older versions, and I don't consider this severe enough to warrant an immediate bug fix release.

**Comment by magrosso** [comment] 2023-06-22 11:10
Good news:
The problem occurs only when decorators appear in certain order. The following order works fine in libdoc, I assume, it also works as robot keywords. It's till a bug, but the workaround is easy.

    @property
    @classmethod

**Comment by magrosso** [comment] 2023-06-22 11:47
Another problem. Libdoc does not fail but obviously ignores @property methods, i.e. they don't appear in the html output!

**Comment by magrosso** [comment] 2023-06-22 15:39
Sorry Pekka for the confusion I'm causing, but it seems to be a rabbithole. I just learned that classmethods cannot be combined with @property anymore starting in Python 3.11. It was introduced in 3.9 but is now deprecated again. However, it only works in the order @classmethod before @property, which is the order that crashes libdoc and robot.

I will remove @property from my @classmethods.

For details, see here:
https://docs.python.org/3.11/library/functions.html#classmethod
https://stackoverflow.com/questions/128573/using-property-on-classmethods/64738850#64738850

**Comment by pekkaklarck** [comment] 2023-07-14 10:25
Thanks for investigation! Also python/cpython#89519 is related.

Because `classmethod/property` usage is deprecated, it certainly makes sense for you to avoid it and that fact also makes this issue less severe. The whole execution crashing is nevertheless so bad that this issue certainly needs to be fixed.

Incidentally we also recently needed a property that works with classes and implemented our own [classproperty](https://github.com/robotframework/robotframework/blob/master/src/robot/utils/misc.py#L145). Need to test are libraries using such decorators also affected.

**Comment by pekkaklarck** [comment] 2023-07-23 21:25
This problem isn't limited only to `property`, same problem happens also if `classmethod` is used with other descriptors. Badly behaving descriptors can cause issues also otherwise. Our own `classmethodproperty` doesn't cause issues, though.

**Closed** 2023-07-23 23:14 UTC
Labels: bug, priority: high
