### ISSUE TITLE
end_test listener does not have keyword status

### ISSUE THREAD

**Issue by Deepika-mathur** [robotframework/robotframework#3236] opened 2019-07-10 14:31 UTC
We are using the robot listener end_test with params data and result.. However none of these objects have the status of all keywords that were executed as a part of this test.

**Comment by pekkaklarck** [comment] 2019-08-14 13:03
This is actually by design. The result object that's collected during execution doesn't contain keyword information to avoid using too much memory. Things that could be done:

1. See is this adequately explained in the current docs.
2. Test how much memory would actually be used if we'd keep all information. Machines have a lot of memory these days and it could be that we didn't need to worry about it.
3. Add `start/end_keyword` methods to listener v3 to allow getting kw information directly. I though we have an issue about this but couldn't find it. Issue #1208 introduced v3 listeners and [this comment](https://github.com/robotframework/robotframework/issues/1208#issuecomment-164910769) explains why `start/end_keyword` weren't added back then.

The problem with both 2 and 3 is that they require a lot of changes.

**Comment by bergstenarn** [comment] 2019-08-30 12:02
Hi @pekkaklarck 
I've been interested in list item 3 above (support for `start/end_keyword` in listener version 3) for quite some time now. Any idea if/when that's gonna happen? Is there a dedicated ticket for that which I can track?

**Comment by pekkaklarck** [comment] 2019-08-30 14:57
I couldn't find an issue about missing `start/end_keyword` when I searched a little time ago. You can submit one if you don't find anything either.

I don't know that problem will be fixed. It requires quite big changes to execution logic and we aren't planning to touch it in RF 3.2 In RF 3.3 `IF/ELSE` will require changes there and I plan to keep this in mind to see could this resolved at the same time. No promises, though.

**Comment by pekkaklarck** [comment] 2019-08-30 16:02
As always, development help or sponsoring either directly or via [Robot Framework Foundation](https://robotframework.org/foundation/) can speed up development.

**Comment by bergstenarn** [comment] 2019-09-04 18:57
Thanks for the reply @pekkaklarck. I have submitted issue [3296](https://github.com/robotframework/robotframework/issues/3296).
FYI I've asked my company to look at the possibility to become a Robot Framework Foundation member. Not sure where we are in that process. Let's hope for the best.

**Comment by tysonite** [comment] 2019-11-24 13:56
> 2. Test how much memory would actually be used if we'd keep all information. Machines have a lot of memory these days and it could be that we didn't need to worry about it.

This actually may vary. At one of my projects, we are using Robot Framework on Orange Pi/Raspberry Pi, and they have limited RAM (start from 512Mb).

**Comment by pekkaklarck** [comment] 2019-11-25 21:55
I think this issue can be closed now hat we have #3296 about adding dedicated `start/end_keyword` methods.

**Closed by pekkaklarck** 2019-11-25 21:55 UTC

**Comment by pekkaklarck** [comment] 2019-11-25 21:56
Also, good point @tysonite that not all environments have that much memory. Possible changes to storing keyword information in memory shouldn't be done without carefully measuring effects.
