### ISSUE TITLE
Using HTML in failure messages is not possible in setups/teardowns or with continuable failures

### ISSUE THREAD

**Issue by GLMeece** [robotframework/robotframework#2360] opened 2016-04-28 03:40 UTC
**Note**: This is related to issue [2358](https://github.com/robotframework/robotframework/issues/2358).

## Summary

Triggering the `Fail` keyword during Test Teardown causes the `*HTML*` markup to fail - it is rendered literally.

## Steps to Reproduce

1. Create a short test suite (example is below) which includes a keyword that sets the test case to _Fail_ status, along with HTML-formatted text.
2. Set the **Test Teardown** value to call this keyword.
3. Create a test case that does something simple, but which will not set the case state to Fail.
4. Create the keyword that sets the execution value to Fail and include an HTML message.

### Example Test Suite

```robotframework
*** Settings ***

Test Teardown       Fail State with Test Message

*** Test Cases ***
Test Fail at Teardown
    [Documentation]    The test case below should resolve to true/pass
    Should Be Equal As Strings    Foo    Foo

*** Keywords ***
Fail State with Test Message
    [Documentation]    The HTML below should be rendered as one would expect,
    ...                however, this bug causes the text to be rendered
    ...                literally in the Message column.
    ...                If it were called as the last step in the test case itself, it would be
    ...                rendered correctly!
    Fail    msg=*HTML* <b>This should be bold!</b> and <i>This should be italic!</i>
```

Questions?

**Comment by pekkaklarck** [comment] 2016-04-28 04:21
This problem is caused by the added `Teardown failed` prefix changing the message so that it doesn't anymore start with the `*HTML*` marker. It occurs also in setup and with continuable failures if there is more than one failure. It also occurs with all keywords, not only `FAIL`.

It ought to be easy to If setup or teardown fails alone. If both test and its teardown fails or if there are multiple failures otherwise, fix requires eacaping non-HTML messages.

**Comment by GLMeece** [comment] 2016-04-28 21:14
FWIW, the Jenkins Robot Framework plugin somehow renders this correctly if you zoom in on a test case which has resulted in an error:
![jenkins_plugin_html](https://cloud.githubusercontent.com/assets/7154245/14901619/ffad3e82-0d5b-11e6-8d5d-c9db39d3d5cd.png)

**Comment by pekkaklarck** [comment] 2016-07-05 12:36
My guess is that either the Jenkins plugin just always formats text as HTML or uses some kind of algorithm to guess does the text contain HTML or not. In both cases there can be problems if the message contains normal text with HTML or HTML-like syntax that is then rendered incorrectly.

Good news is that I ought to have this fixed on Robot side now.

**Closed** 2016-07-05 12:38 UTC
Labels: bug, prio-medium
