### ISSUE TITLE
`Copy Directory` does not work with Jython on Windows

### ISSUE THREAD

**Issue by clarmso** [robotframework/robotframework#2321] opened 2016-02-23 15:38 UTC
Robot Framework version: 2.9.2
Python Interpreter: Jython 2.7.0 on java1.8.0_65
Operating System: Windows 8.1

The "Operating System.Copy Directory" operation works for robot run by Python 2.7.x but does not work for jybot run by Jython.  Here's the error message:

[(u'C:\Users\Clare\Documents\tmp\hello', u'C:\Users\Clare\Documents\tmp\foo\hello', "[Errno 1] Operation not permitted: u'C:\\Users\\Clare\\Documents\\tmp\\foo\\hello'")]

Here's the steps to reproduce:

[RobotFrameworkIssueCopyDirectory.txt](https://github.com/robotframework/robotframework/files/142867/RobotFrameworkIssueCopyDirectory.txt)

**Comment by HelioGuilherme66** [comment] 2016-02-23 22:55
Your test runs fine in my Linux system:
```jybot --version
Robot Framework 2.9.2 (Jython 2.7.0 on java1.8.0_71)
```
It looks like a Windows security specific problem. Maybe if you experiment opening the command windows as an Administrator user, or using Power Shell instead. Other possibility is to use a "neutral" directory path like C:\Temp (not in the user's home).

**Comment by clarmso** [comment] 2016-02-23 23:08
@HelioGuilherme66 Thanks for taking a look.  If the test works for you, then it's definitely a Windows-specific issue.  I am logged in as an admin user, but do not run PowerShell as administrator.  I ran the test again just now and got the same error.
![screenshot-2016-02-23-1808](https://cloud.githubusercontent.com/assets/1740517/13269893/73ea0a3c-da58-11e5-8f51-1ebdaf372641.png)

Any Windows users out there?

**Comment by pekkaklarck** [comment] 2016-02-24 09:34
I was able to reproduce this problem on Windows. It turned out to be a bug in Jython:
http://bugs.jython.org/issue2474

The problem on Jython occurs when copying directory metadata, copying the directory content seems to work fine. We could thus workaround this problem on Robot Framework side by ignoring possible errors when using Jython on Windows. That has a problem that also real problems may be silenced, but this keyword not working at all is not good either. What do others think?

It was surprised our acceptance tests for `Copy Directory` haven't caught this earlier, but then noticed that `Copy Directory` doesn't have any tests! I guess the reason is that initially `Move Directory` used `Copy Directory` internally and the former is thoroughly tested. Later implementation changed (move using copy internally is not actually a good idea) and no new tests were added. Regardless the reason, tests definitely need to be added to `Copy Directory`.

**Comment by pekkaklarck** [comment] 2016-02-24 09:36
@clarmso: Notice that you don't need those `Wait ...` keywords when using OperatingSystem keywords to create, move or copy files and directories. Explicit waiting is only needed if some external system is creating/removing files and you want to wait that.

**Comment by clarmso** [comment] 2016-02-24 15:05
Thanks @pekkaklarck for confirming the bug quickly and clarifying the use of the `Wait...` keywords.

Using `Run Keyword and Ignore error` for `Copy Directory` in the Robot Framework level would not be ideal since some real problems could not be caught.  As a (temporary) workaround, I `Create Directory` and `Copy Files` into the newly created directory.

**Comment by pekkaklarck** [comment] 2016-02-24 15:31
I didn't mean using `Run Keyword And Ignore Error` but enhancing  `Copy Directory`:

```python
    try:
        shutil.copytree(source, destination)
    except OSError:
        if not (WINDOWS and JYTHON):
            raise
```

Ignoring all errors is risky, but I guess that's better than the current total breakage. If the underlying bug is fixed on Jython 2.7.1, we could limit ignoring errors only to Jython 2.7.0.

**Comment by clarmso** [comment] 2016-02-24 20:50
Sounds good.  In addition to checking the OS and Jython, it would be good to catch "[Errno 1]" as well.

**Comment by pekkaklarck** [comment] 2016-02-24 22:23
Good point. The Jython bug I submitted was assigned to Jython 2.7.1. Assuming it gets fixed, something like this ought to be good:

```python
try:
        shutil.copytree(source, destination)
    except OSError as err:
        # https://github.com/robotframework/robotframework/issues/2321
        if not (err.errno == 1 and WINDOWS and JYTHON and sys.version_info < (2, 7, 1)):
            raise
```

**Comment by clarmso** [comment] 2016-02-24 22:48
I suggest the following as a (temporary) workaround for the Jython bug in the Robot Framework level.  What do you think, @pekkaklarck ?

`Run Keyword and Expect error  *[Errno 1]*Operation not permitted:*  Copy Directory      ${dir1}   ${dir2}`

Of course, this workaround will break when the Jython bug is fixed.

**Comment by pekkaklarck** [comment] 2016-02-24 22:59
I'd probably use `Run Keyword And Ignore Error`. If you want to be really fancy, you can check the error it returns *if* it fails.

**Closed** 2016-07-04 22:33 UTC
Labels: priority: medium
