### ISSUE TITLE
Crash when in Dialogs window is closed

### ISSUE THREAD

**Issue by xRowe** [robotframework/robotframework#4993] opened 2023-12-26 15:04 UTC
Dear Developer

I am setting up a auto/semi-auto test using the RobotFramework, installed by pip along with RIDE

```
robot --version
Robot Framework 6.1.1 (Python 3.11.5 on win32)
```

But now I am stuck at below warning when I selected "FAIL" in Dialogs.Execute Manual Step.
`Tcl_AsyncDelete: async handler deleted by the wrong thread`

100% Reproduce in specific step.
"initTransport" will setup the connection and create/start multi-threads to send/receive cyclic messages. 
When the press any button to close Dialog windows, it will raise the Tcl_AsyncDelete Error
```
Test_Dialogs
    initTransport
    Dialogs.Execute Manual Step    Check The LIGHT is ON    LIGHT OFF
```

But 0% reproduce in below steps
```
Test_Dialogs
    Dialogs.Execute Manual Step    Check The LIGHT is ON    LIGHT OFF
```
or
```
Test_Dialogs
    ${answer}    Dialogs.get value from user    Are you OK?
```

**Comment by pekkaklarck** [comment] 2024-01-02 23:31
I have no idea why this happens, but the problem seems to be somehow related to what your `initTransport` keyword does. Somehow it causes problems with Tcl that Dialogs uses via Python's tikinter module. I would be surprised if the problem would be in the Dialogs library itself, but also that is certainly possible.

We cannot investigate this ourselves because we cannot reproduce the problem. Your options include investigating this yourself or providing a _simple_ example we could run ourselves that demonstrates the issue.

**Comment by lfighter** [comment] 2024-01-08 12:40
I think I have a reproducible example of the problem (At least I think it is the same problem).

tcl_bug.robot:
```
*** Settings ***
Library     ./ManualGarbageCollection.py
Library     Dialogs


*** Test Cases ***
test with gb collection in thread
    Execute Manual Step    test
    Run In Thread
```

ManualGarbageCollection.py:
```python
import gc
from threading import Thread


class ManualGarbageCollection:
    def run_in_main_thread(self):
        gc.collect()

    def run_in_thread(self):
        thread = Thread(target=gc.collect)
        thread.start()
        thread.join()

```

I currently think that after a window is closed the resources are not immediately cleaned up. If then the garbage collection is run from a different thread and the resource is cleaned up this exception occurs. My currently workarounds are not using threads at all or modifing the code of the dialog window in robot framework to trigger pythons garbage collection manually after closing the window. I don't like both solutions too much.

**Comment by devincrossman** [comment] 2024-01-24 20:35
I had this issue when using the Dialogs library in robotframework 6.1.1 with the vscode robot framework language server v1.11.0. Here is a short example:

```
*** Settings ***
Documentation    Example of dialog error
Library    Dialogs

*** Test Cases ***
Test Dialog
    [Documentation]    Test the dialog to show the Tcl error
    Execute Manual Step    Continue?
    Should Be Equal    Apple    Apple
```
    
If I put a breakpoint on the Should Be Equal line then after the Execute Manual Step dialog appears and I click on pass or fail, I will get the error

> Tcl_AsyncDelete: async handler deleted by the wrong thread

and then the execution stops and I don't hit my breakpoint.

I guess the RFLS runs the robot script in a separate thread which causes issues with tkinter which needs to be running in the main thread.

The solution by @lfighter to explicitly call the garbage collector works. I'm not sure why it would not be a good solution?

In the dialogs_py.py in the TkDialog _close method

```
def _close(self, event=None):
        # self.destroy() is not enough on Linux
        self.root.destroy()
        gc.collect()

```
After adding gc.collect() explicitly it no longer gives the Tcl error and I can hit my breakpoint

**Comment by pekkaklarck** [comment] 2024-01-28 11:21
Do I get it right that adding `gc.collect()` to `_close` fixes/workarounds the issue? If yes, and the change doesn't have adverse effects, could someone create a PR with the fix that could be merged before RF 7.0.1? There should be a comment about the `gc.collect` line explaining why it's needed, possibly with a reference to this issue.

**Comment by pekkaklarck** [comment] 2024-02-04 14:53
PR #5046 looks good but I don't have time to test it now. I'll add this issue to RF 7.0.1 scope so that we don't forget about it.

**Comment by pekkaklarck** [comment] 2024-03-17 15:40
Fixed by PR #5046. Thanks for contribution @lfighter!

**Closed** 2024-03-17 15:40 UTC
Labels: bug, priority: medium, acknowledge

**Comment by pekkaklarck** [comment] 2024-03-17 15:43
This fix will be included in the forthcoming RF 7.0.1. I hope users who have encountered crashes with Dialogs can test that release and submit new issues if problems persist.

**Comment by pekkaklarck** [comment] 2024-06-04 16:01
RF 7.0.1 rc 1 with this fix [has just been released](https://github.com/robotframework/robotframework/blob/master/doc/releasenotes/rf-7.0.1rc1.rst). It would be great if you could test does the fix work properly before the final release that's targeted for Monday June 10.

**Comment by lfighter** [comment] 2024-06-07 17:55
Even though you may mean the issue reporter I did test RF 7.0.1 rc 2 on two windows and one linux machine. I had no issues. It would still be great to have a third party confirm this as well.
