### ISSUE TITLE
Need way for library to know it's name

### ISSUE THREAD

**Issue by boakley** [robotframework/robotframework#2169] opened 2015-10-01 15:41 UTC
I'm writing a keyword library that needs to know it's name, so that it can insert itself into the library search order. This works fine if I import it like this:

    | Library | MyLibrary

In that case the code can use it's own class name. However, if I've set up my path so that I import this relative to some other package, or with "WITH NAME", the name of the class is not the name that robot uses internally.

My use case is this: my company has two products, and each product may define the same keyword. I am importing them like this:

    | Library | ProductA.Keywords
    | Library | ProductB.Keywords

In both cases, the class name is `Keywords`, but robot knows them as `ProductA.Keywords` and `ProductB.Keywords`, and those are the names I must use when adding the library to the search order. There's a similar problem if I use "WITH NAME", in that my class has no idea what name the test is giving to the instance of the library.

I need a way to reconcile this. How can an instance of my keyword library know what name robot uses to refer to it? Is there already an API call I can use? Something like  `robot.get_instance_name(self)`?

**Comment by pekkaklarck** [comment] 2015-10-02 11:46
Nothing like this is available in the public APIs. I don't like the idea to add a method just to map an instance to a name, but having a method that returns Robot's internal `TestLibrary` instance based either name or instance would be fine. Then you could access name, arguments, etc. as attributes of the returned instance. Implementing such a method would be easy, but unfortunately the `TestLibrary` itself is a mess, and I wouldn't like to make it part of the public API. I would really like to get `TestLibrary` cleaned up in RF 3.0 and then adding a method to get an access to them would be OK.

If your actual need is to set library search order, a simpler solution would be allowing that to be done using an instance. Robot could then internally map the instance to a name and set search order accordingly. Please submit a separate enhancement request if you think that would be a good idea. If you can create a pull request fast, we can still include it into RF 2.9.2 that we plan to release early next week.

**Comment by jussimalinen** [comment] 2015-10-06 09:40
We need already a way to a dictionary of all libraries in current namespace. (#2170) This can be used to map the instances back to aliases.

**Comment by pekkaklarck** [comment] 2015-10-06 09:59
I guess we can consider this a duplicate of #2170.

**Closed by pekkaklarck** 2015-10-06 09:59 UTC
