### ISSUE TITLE
Keyword type passed to listeners is wrong then keyword is for loop

### ISSUE THREAD

**Issue by adam-wypych** [robotframework/robotframework#2227] opened 2015-11-22 16:54 UTC
As we observed during RED debugger implementation everytime RF during test execution meets keyword, which are ```:FOR``` loop, the ```type``` attribute in ```start_keyword``` attributes dictionary/map is set to ```Test For``` and the same is done when loop keyword is end. For corresponding items inside loop the ```type``` is set to ```Test Foritem```. We are strongly base on this contract for present user, which line is currently executed by RF. This works completly correct, when the loop is made from Library keywords or simple user keywords (here I mean without loop inside). 
When we made test case like below (`LoopInLoop.robot`), where ```Nested Loop Keyword``` contains inside also internal ```:FOR``` loop we get wrong about `type` of `Nested Loop Keyword` in case of `end_keyword` function from listener API - the `type` is `Keyword` instead of `Test Foritem`. The same problem shows also for next loop item `	\	Log		'End for: ' ${x}`, but for both `start_keyword` and `end_keyword`. 

Listener output for `LoopInLoop.robot` execution (see lines: 16-18 and 32-34)

```
1 {start_keyword, name=BuiltIn.Log, type=Keyword}
2 {end_keyword, name=BuiltIn.Log, type=Keyword}
3 {start_keyword, name=${x} IN RANGE [ 0 | 2 ], type=Test For}
4 {start_keyword, name=${x} = 0, type=Test Foritem}
5 {start_keyword, name=BuiltIn.Log, type=Test Foritem}
6 {end_keyword, name=BuiltIn.Log, type=Test Foritem}
7 {start_keyword, name=Nested Loop Keyword, type=Test Foritem}
8 {start_keyword, name=BuiltIn.Log, type=Test Foritem}
9 {end_keyword, name=BuiltIn.Log, type=Test Foritem}
10 {start_keyword, name=${y} IN RANGE [ 0 | 1 ], type=Test For}
11 {start_keyword, name=${y} = 0, type=Test Foritem}
12 {start_keyword, name=BuiltIn.Log, type=Test Foritem}
13 {end_keyword, name=BuiltIn.Log, type=Test Foritem}
14 {end_keyword, name=${y} = 0, type=Test Foritem}
15 {end_keyword, name=${y} IN RANGE [ 0 | 1 ], type=Test For}
16 {end_keyword, name=Nested Loop Keyword, type=Keyword}
17 {start_keyword, name=BuiltIn.Log, type=Keyword}
18 {end_keyword, name=BuiltIn.Log, type=Keyword}
19 {end_keyword, name=${x} = 0, type=Test Foritem}
20 {start_keyword, name=${x} = 1, type=Test Foritem}
21 {start_keyword, name=BuiltIn.Log, type=Test Foritem}
22 {end_keyword, name=BuiltIn.Log, type=Test Foritem}
23 {start_keyword, name=Nested Loop Keyword, type=Test Foritem}
24 {start_keyword, name=BuiltIn.Log, type=Test Foritem}
25 {end_keyword, name=BuiltIn.Log, type=Test Foritem}
26 {start_keyword, name=${y} IN RANGE [ 0 | 1 ], type=Test For}
27 {start_keyword, name=${y} = 0, type=Test Foritem}
28 {start_keyword, name=BuiltIn.Log, type=Test Foritem}
29 {end_keyword, name=BuiltIn.Log, type=Test Foritem}
30 {end_keyword, name=${y} = 0, type=Test Foritem}
31 {end_keyword, name=${y} IN RANGE [ 0 | 1 ], type=Test For}
32 {end_keyword, name=Nested Loop Keyword, type=Keyword}
33 {start_keyword, name=BuiltIn.Log, type=Keyword}
34 {end_keyword, name=BuiltIn.Log, type=Keyword}
35 {end_keyword, name=${x} = 1, type=Test Foritem}
36 {end_keyword, name=${x} IN RANGE [ 0 | 2 ], type=Test For}
37 {start_keyword, name=BuiltIn.Log, type=Keyword}
38 {end_keyword, name=BuiltIn.Log, type=Keyword}
```
 
**DATA TO REPRODUCE**
```LoopInLoop.robot``` file content:
```robot
*** Test Cases ***
ForTest
	Log		start
	:FOR	${x}	IN RANGE	0	2
	\	Log		'Start for: ' ${x}
	\	Nested Loop Keyword		${x}
	\	Log		'End for: ' ${x}
	Log		end
	
*** Keywords ***
Nested Loop Keyword
	[Arguments]		${got}
	Log		${got}
	:FOR	${y}	IN RANGE	0	1
	\	Log		${y}
```

```MyListener.py``` file content used to collect data as RF execution listener via option `--listener`:
```python
import os.path
import tempfile


class MyListener(object):
    ROBOT_LISTENER_API_VERSION = 2

    def __init__(self, filename='listen.txt'):
        self.output_path = os.path.join(tempfile.gettempdir(), filename)
        print 'Communication stored in: ' + str(self.output_path)
        self.outfile = open(self.output_path, 'w')
        self.line_number = 0

    def start_keyword(self, name, attributes):
        self.line_number += 1
        self.outfile.write(str(self.line_number) + ' {start_keyword, name=' + str(name) + ', type=' + str(attributes['type']) + '}')
        self.outfile.write('\n')


    def end_keyword(self, name, attributes):
        self.line_number += 1
        self.outfile.write(str(self.line_number) + ' {end_keyword, name=' + str(name) + ', type=' + str(attributes['type']) + '}')
        self.outfile.write('\n')

    def close(self):
        self.outfile.close()
```

The problem also show up on the newest RF 3.0a1 version.

**Comment by pekkaklarck** [comment] 2015-11-23 09:05
Interesting bug, thanks for the report. The problem actually is that the code setting keyword types in listeners doesn't take for loops into account at all. It tries to return `Keyword` or `Suite/Test Setup/Teardown` to make it possible to know is a normal keyword or setup/teardown executed. As you can see from the code, it totally ignores the possibility that type can also be `for` or `foritem`:
https://github.com/robotframework/robotframework/blob/master/src/robot/output/listeners.py#L129

This is easy to fix but we need to first decide how to fix it. Should we set type to `For` or `For Loop` when a for loop starts? Should we use the same when different iterations start or should we then use something like `For Item` or `For Loop Iteration`?

**Comment by adam-wypych** [comment] 2015-11-23 09:23
In my opinion only the first `:FOR` should get type `for` and anything inside this loop include other `:FOR` should get type as `foritem`. In our case and I think in most cases listener is not able to judgment what new iterations will brings and the fact that to get `:FOR` in `:FOR` we need to bring this nested loop to other keyword is enough to get where we are now.

**Comment by jussimalinen** [comment] 2015-11-23 09:37
Internally foritem is a bad name for one iteration of the loop. (You will see this in the log file).

So considering this input:
```robotframework
*** Test Cases ***
Example
    :FOR   ${i}   IN   first   second
    \      Log    ${i}
    \      No Operation  
```
We would suggest renaming the foritem to for loop and the listener would then get the following events:
```
for
  for loop (first) 
    keyword (log)
    keyword (no operation)
  for loop (second)
    keyword (log)
    keyword (no operation)
```

How does this seem to you?

**Comment by adam-wypych** [comment] 2015-11-23 09:58
Can you describe Your proposal (events, which will we get) base on below test case:

```robot
*** Test Cases ***
ForTest
    Log     start
    :FOR    ${x}    IN RANGE    0   2
    \   Log     'Start for: ' ${x}
    \   Nested Loop Keyword     ${x}
    \   Log     'End for: ' ${x}
    Log     end

*** Keywords ***
Nested Loop Keyword
    [Arguments]     ${got}
    Log     ${got}
    :FOR    ${y}    IN RANGE    0   1
    \   Log     ${y}
```

Thanks in advance for your prompt responses.

**Comment by jussimalinen** [comment] 2015-11-23 12:51
We talked with @pekkaklarck that the per loop item could be called "for loop" and each iteration "for iteration".

So like this:

- kw log (start)
- for loop ( in range 0, 2)
   - for iteration (0)
     - kw log
     - kw nested loop keyword
        - kw log
        - for loop ( in range 0, 1)
           - for iteration (0)
               - kw log
     - kw log (end for 0)
   - for iteration (1)
     - kw log
     - kw nested loop keyword
        - kw log
        - for loop (in range 0, 1)
           - for iteration (0)
               - kw log
     - kw log (end for 1)
- kw log (end)

**Comment by adam-wypych** [comment] 2015-11-23 13:28
The most important for us is to get the same `type` attribute in the `end_keyword` as we will get in  `start_keyword` listener API function - without this information we will be blind. The second information is to clear indicate that RF execute currently repeat/iterate action - here `:for` loop. For me seems that we can meet this goal with this new two types, but it will be nice to do not mix old `Test foritem` with new types for loop iteration proposed by You.

**Comment by pekkaklarck** [comment] 2015-11-23 14:55
OK, will go with the design illustrated by @jussimalinen above. I guess type names `For Loop` and `For Iteration` are good enough. Old `Test foritem` etc. were just bugs, they won't appear as types once we get this fixed.

**Comment by adam-wypych** [comment] 2015-11-23 15:03
OK thanks for both of You.

**Comment by pekkaklarck** [comment] 2015-11-23 15:36
Actually, would it be enough if the type would just be `Keyword`? After studying this a bit more (including issue #859 that introduced the `type` attribute), I noticed that type is `Suite/Test Setup/Teardown` not only with the top level keyword uses as setup/teardown has but also with all keywords it uses. It would be more consistent to use same type everywhere.

**Comment by adam-wypych** [comment] 2015-11-23 15:58
Yes type `keyword` is enough for keywords inside other keywords, if main keyword will give much information where is executed - means `Suite/Test Setup/Teardown/Test` or `:FOR` loop.

**Comment by pekkaklarck** [comment] 2015-11-24 22:50
I didn't explain myself too clearly earlier. The problem is that currently, as designed in #859, `type` is used to make it easy to check is a keyword executed in setup/teardown or in test body. That's why the type is setup/teardown with all keywords that are executed as setup/teardown. For example, if we have listener

```python
from __future__ import print_function
import sys

ROBOT_LISTENER_API_VERSION = 2

def start_keyword(name, attrs):
    print('%s:\t%s [%s]' % (attrs['type'], name, ', '.join(attrs['args'])),
          file=sys.stderr)
```

and use it with test

```robotframework
*** Test Cases ***
Example
    [Setup]    Keyword    setup
    Keyword    body
    [Teardown]    Keyword    teardown

*** Keywords ***
Keyword
    [Arguments]    @{args}
    No Operation
```

the output we get to the stderr is

```
Test Setup:       Keyword [setup]
Test Setup:       BuiltIn.No Operation []
Keyword:          Keyword [body]
Keyword:          BuiltIn.No Operation []
Test Teardown:    Keyword [teardown]
Test Teardown:    BuiltIn.No Operation []
```

It would be highly confusing if we would now change for loops to have a different type regardless where they are executed. On the other hand, only having a separate type when they are used in test body would mean you cannot just use the type to monitor is the executed keyword a for loop or not.

I see we have two possibilities:

1. Just set the type of for loops to be `Keyword`. That would match the original planned behavior in #859, but obviously you couldn't differentiate for loops from other keywords based on the type.

2. Always use the actual keyword type. This would mean:
    - Use `For Loop` and `For Iteration` types with for loops regardless where they are used.
    - Use `Setup/Teardown` types **only** with the top level setup/teardown keyword. This would change the current behavior. For example, the output above would be change so that the type of `BuiltIn.No Operation` would always be `Keyword`. The change would cause backwards compatibility issues for anyone using types as designed in #859. I guess we could do that in a major version, but it would definitely need a separate issue and a note in release notes.

Do you @adam-wypych consider either of the above better/worse than the above or have some other ideas how we possibly could fix the current situation? Personally I would generally prefer the option 2. because it makes the type information generally more useful, but it would also require much more work and I'm always worried about backwards compatibility. If option 1. would be enough for you, it would probably be a better solution now.

**Comment by adam-wypych** [comment] 2015-11-25 14:50
@pekkaklarck As I understand issue #859 is equal to have only `Setup/Keyword/Teardown` types for keywords. Please correct me if I am wrong. 
Generally removing types indicating steps from `:FOR` loop will required to check if line is `:FOR` loop on listener side and adopt a little bit parser logic.

**Comment by pekkaklarck** [comment] 2015-11-30 23:04
You are right that both solutions I explained above would be to some extend backwards incompatible.

- If we go with the option 1, there is no type information about for loops anymore. The current information is buggy, though.

- With the option 2 we would break cases where people expect the type always to be setup/teardown when inside a setup/teardown. Information about for loops would be available, but it would be different that it used to be.

The latter option is more backwards incompatible than the former, but since this is going to be a major version it's not really an issue. It would actually simplify listener code if we could just return whatever type the keyword actually has and didn't need to track are we in setup/teardown or now. Documenting the change would require some work but not too much.

I'm personally fine either way. Which would you @adam-wypych prefer?

**Comment by adam-wypych** [comment] 2015-12-01 07:21
@pekkaklarck I read Your message and I fully agree with You that that the only `Setup/Teardown` type information is need both for `suite` and `test` plus that keyword `start` or `end` was is meet by corresponding listener API functions. From our side perspective we can just ignore `Test For` and `Test Foritem` and switch to get information if line is loop in `keyword` and `test case` execution table.

**Comment by pekkaklarck** [comment] 2015-12-01 09:33
Did I get it right that option 1 is OK for you? In other words, it would be fine if we use the current setup/teardown types like earlier and for loops get `keyword` type? Notice that the current `Test For`, `Test Foritem` are bugs in the type handling code. I definitely don't wan't to report for loops differently are they inside a test or a keyword.

We were planning to create 3.0 alpha 2 when we are ready with the new listener API, but there has already been so many changes that perhaps we should decope it now and try to get a2 out this week. You can obviously clone the repository and test the latest code whenever you want.

**Comment by adam-wypych** [comment] 2015-12-01 09:55
'In other words, it would be fine if we use the current setup/teardown types like earlier and for loops get `keyword` type?' Yes I think it will be the best option.

**Comment by pekkaklarck** [comment] 2015-12-01 12:06
Would the other option, i.e. always returning whatever the keyword type is, be OK for you? I'm currently refactoring listener implementation to fix a high priority performance problem (see #2241 for details), and with the new design it would be a lot easier to just return the keyword type directly. Instead of spending time for that, I would rather change the current behavior.

**Comment by adam-wypych** [comment] 2015-12-01 13:07
@pekkaklarck Do you mean that `keyword` type will be always set anywhere - even inside `Suite Setup\Suite Teardown`?

**Comment by pekkaklarck** [comment] 2015-12-01 14:26
I'm not sure did I understand the previous comment correctly. Keyword type is always set, the question what values the type should have. Currently the type is `setup/teardown` for all keywords that are executed as part of setup/teardown. You can see that from my [earlier example](https://github.com/robotframework/robotframework/issues/2227#issuecomment-159431128).

If we change the type to be always the actual keyword type (possibility 2 in the aforementioned comment), then the output of the example in the comment would be like this:

```
Test Setup:       Keyword [setup]
Keyword:          BuiltIn.No Operation []
Keyword:          Keyword [body]
Keyword:          BuiltIn.No Operation []
Test Teardown:    Keyword [teardown]
Keyword:          BuiltIn.No Operation []
```

This approach would have the following benefits:
- It would make it possible to report for loop types separately from keywords.
- It would allow separating keyword teardowns from test/suite teardowns. I just tested that currently keyword teardowns are reported to wrong!
- It would simplify implementation

The fact that currently also keyword teardowns are reported wrong was the last straw, and I plan to change the reported keyword types to be whatever type the keyword actually has. Let me know ASAP if that would be totally unacceptable for you and I can still reconsider it.

**Comment by adam-wypych** [comment] 2015-12-01 14:32
Ok as I understand the implementation will have 3 types only `setup\keyword\teardown` if yes then is acceptable.

**Comment by pekkaklarck** [comment] 2015-12-01 14:44
My plan was to have types `keyword`, `setup`, `teardown`, `for loop` and `for iteration` (exact spelling/casing not yet decided). I wouldn't mind using `keyword` also with for loops, but somehow using the actual type sounds better to me.

**Comment by adam-wypych** [comment] 2015-12-01 16:30
@pekkaklarck for me its totaly ok with those 3 types  (`keyword`, `setup`, `teardown`) minimum and maximum 5

**Comment by pekkaklarck** [comment] 2015-12-06 22:04
Submitted #2248 about changes that we are going to do keyword type reporting. Problems initially reported here will be fixed as part of it, so I'll close this issue as its duplicate.

**Closed by pekkaklarck** 2015-12-06 22:04 UTC
Labels: alpha 2, bug, prio-medium

**Comment by pekkaklarck** [comment] 2015-12-11 07:42
Have you @adam-wypych had a change to test alpha 2 and how types work there? We can still do modifications before the final version if needed.

**Comment by adam-wypych** [comment] 2015-12-11 09:46
@mateosy could you comment since is your nice feature ;) ?

**Comment by Mateosy** [comment] 2015-12-30 11:17
Hi, It works fine for me.

**Comment by adam-wypych** [comment] 2018-11-09 05:54
@sathishj-gh1 you need to simple 
a) implement your stack for getting notify about keywords executed so far
b) in listener API http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#id780 you have end_keyword message - then you need to check the type '_type: String Keyword for normal keywords, Setup or Teardown for the top level keyword used as setup/teardown, For for for loops, and For Item for individual for loop iterations. NOTE: Keyword type reporting was changed in RF 3.0. See issue #2248 for details._'

The _b_ option is so far the best one ;)
