### ISSUE TITLE
'OR' operator not working in Selecting test cases by tag

### ISSUE THREAD

**Issue by shuaiyes** [robotframework/robotframework#2290] opened 2016-01-08 08:53 UTC
I have 3 types of tags in my test suite. They are 'common', 'mrf' and 'TriggerAIF'.

I use command '--include mrfORcommon' to select cases by tags, but got error with no case found.
(I tried '--include commonORmrf', didn't work, either. But with --exclude opreator, function is OK)

Now, I use '--include common --include mrf' instead to implement.

I'm confused that why not to use like 'a&&(b||c)' way to configure tag. It's more clearly.

**Comment by pekkaklarck** [comment] 2016-01-08 08:57
Which RF version? The support of `OR` is somewhat new feature.

**Comment by pekkaklarck** [comment] 2016-01-11 09:47
I tested that `--include` works with `OR` since RF 2.8.4. Assuming you are using a newer version, I'm fairly certain you either have a typo in your tags or use `--exclude` or some other filtering option at the same time. Could you verify that and test again?

**Comment by shuaiyes** [comment] 2016-01-12 03:42
# pybot --version
Robot Framework 2.9.2 (Python 2.7.3 on linux2)

I think the version is supported this.

**Comment by pekkaklarck** [comment] 2016-01-12 06:16
I cannot reproduce the problem with that version. Please test this again. If it still fails, please provide a concrete example I can run on my own machine.

**Comment by pekkaklarck** [comment] 2016-02-24 13:22
Couldn't reproduce the problem. No new information in 1.5 months. Closing.

**Closed by pekkaklarck** 2016-02-24 13:22 UTC
