### ISSUE TITLE
Error when install Selenium 2 (WebDriver) Library

### ISSUE THREAD

**Issue by fergadipa** [robotframework/robotframework#2677] opened 2017-09-13 04:30 UTC
Hi, 
I'm newbie for RobotFramework and Python.
I am using Windows 10.
I  already installed Robot Framework 3.0.2 (Python 3.6.2 on win32).
It display 

> C:\Users\Daniel>robot --version
> c:\users\daniel\appdata\local\programs\python\python36-32\lib\runpy.py:125: RuntimeWarning: 'robot.run' found in sys.modules after import of package 'robot', but prior to execution of 'robot.run'; this may result in unpredictable behaviour
>   warn(RuntimeWarning(msg))
> Robot Framework 3.0.2 (Python 3.6.2 on win32)

When I'm trying install Selenium 2 WebDriver I found an error on console 

> C:\Users\Daniel>pip install robotframework-selenium2library
> Collecting robotframework-selenium2library
>   Using cached robotframework-selenium2library-1.8.0.tar.gz
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "C:\Users\Daniel\AppData\Local\Temp\pip-build-dbtfn33a\robotframework-selenium2library\setup.py", line 7, in <module>
>         from ez_setup import use_setuptools
>       File "C:\Users\Daniel\AppData\Local\Temp\pip-build-dbtfn33a\robotframework-selenium2library\src\ez_setup.py", line 106
>         except pkg_resources.VersionConflict, e:
>                                             ^
>     SyntaxError: invalid syntax
> 
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in C:\Users\Daniel\AppData\Local\Temp\pip-build-dbtfn33a\robotframework-selenium2library\

Is there any step that I missed?
Thank you.

**Comment by HelioGuilherme66** [comment] 2017-09-13 10:05
Yes, there are two mistakes.
First, this is a Issue tracker for bugs or improvements for the Robot Framework, and you had problem with [Selenium2Library](https://github.com/robotframework/SeleniumLibrary).
Second, you missed the instructions on README.rst at [here](https://github.com/robotframework/SeleniumLibrary/blob/master/README.rst). The version you installed is not compatible with Python 3.

Please close this issue, and use other communication channels for questions.

**Comment by pekkaklarck** [comment] 2017-09-13 22:23
The first reported issue is duplicate of #2552. @HelioGuilherme66 is right about the others.

**Closed by pekkaklarck** 2017-09-13 22:23 UTC
