### ISSUE TITLE
Robot output can crash when piping output

### ISSUE THREAD

**Issue by mkorpela** [robotframework/robotframework#3264] opened 2019-08-12 09:20 UTC
robot . | echo

[ ERROR ] Unexpected error: BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/robot/utils/application.py", line 83, in _execute
    rc = self.main(arguments, **options)
  File "/usr/local/lib/python3.7/site-packages/robot/run.py", line 439, in main
    result = suite.run(settings)
  File "/usr/local/lib/python3.7/site-packages/robot/running/model.py", line 222, in run
    self.visit(runner)
  File "/usr/local/lib/python3.7/site-packages/robot/model/testsuite.py", line 168, in visit
    visitor.visit_suite(self)
  File "/usr/local/lib/python3.7/site-packages/robot/model/visitor.py", line 84, in visit_suite
    if self.start_suite(suite) is not False:
  File "/usr/local/lib/python3.7/site-packages/robot/running/runner.py", line 83, in start_suite
    test_count=suite.test_count))
  File "/usr/local/lib/python3.7/site-packages/robot/output/output.py", line 51, in start_suite
    LOGGER.start_suite(suite)
  File "/usr/local/lib/python3.7/site-packages/robot/output/logger.py", line 201, in start_suite
    logger.start_suite(suite)
  File "/usr/local/lib/python3.7/site-packages/robot/output/console/verbose.py", line 36, in start_suite
    self._writer.suite_separator()
  File "/usr/local/lib/python3.7/site-packages/robot/output/console/verbose.py", line 106, in suite_separator
    self._fill('=')
  File "/usr/local/lib/python3.7/site-packages/robot/output/console/verbose.py", line 112, in _fill
    self._stdout.write('%s\n' % (char * self._width))
  File "/usr/local/lib/python3.7/site-packages/robot/output/console/highlighting.py", line 53, in write
    self.flush()
  File "/usr/local/lib/python3.7/site-packages/robot/output/console/highlighting.py", line 66, in flush
    self.stream.flush()
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe

**Comment by pekkaklarck** [comment] 2019-08-14 08:14
It seems to depend on which command the output is piped to. For example, `| less` and `| tail` seem to work fine but `| echo` and `| head` cause problems.

**Comment by pekkaklarck** [comment] 2019-08-14 08:27
OK, I think I know what's going on.

- The reason `| echo` fails is that `echo` *does not* read stdin but only prints its arguments and then exists and that breaks the pipe. Related to that, `command | echo` basically never makes sense. Use `command | cat` instead.
- The reason `| head` fails is that it (by design) exists and closes the pipe immediately when it's got enough info. Unlike `command | echo`, `command | head` is actually useful.

**Comment by pekkaklarck** [comment] 2019-08-14 08:51
Python's docs actually explain the problem and also explain why disabling `SIGPIPE` signals is not a good solution: https://docs.python.org/3/library/signal.html#note-on-sigpipe

Now the real question is, how should we handle this? Options include:

1. Do nothing. Let the program crash. Close this issue.

2. Handle exception and exit gracefully. That's what the example in the docs referenced above do. In addition to that we should add some error reporting that execution was stopped due to a closed pipe. This fix should probably go to `robot.utils.Application`.

3. Ignore broken pipe and run test until the end. AFAIK pipes are typically line buffered so it ought to be enough to add `try/except` around `self.stream.flush()` in `HighlightingStream`. I already tested that it works at least with `| head`. It can be a bit strange that the output is cut but execution continues, but then again you are explicitly using `head` and stopping execution doesn't feel that good either.

What do you think @mkorpela?

**Comment by mkorpela** [comment] 2019-08-15 16:13
I tested piping with head command to answer a question on RF slack about removing 3 last rows of output (that contain the locations of output, report and log files). I was thinking something like ```robot ... | head -n -3``` (this does not work on OSX (as it is BSD derivative) but works on GNU derivative linuxes).
In this case the correct option would be number 3.
Just continue execution although output will not go anywhere.

**Comment by pekkaklarck** [comment] 2019-08-15 17:20
Option 3 feels best to me as well.

**Closed** 2019-08-15 20:36 UTC
Labels: priority: medium, alpha 1
