### ISSUE TITLE
'-s' option is processed before prerunmodifier is called

### ISSUE THREAD

**Issue by kumaraish** [robotframework/robotframework#4790] opened 2023-06-09 06:53 UTC
As per Robot Framework User Guide Version 6.0.2, Section 3.5.8 Programmatic modification of test data:

> Pre-run modifiers are executed before other configuration affecting the executed test suite and test cases. Most importantly, options related to [selecting test cases](https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#selecting-test-cases) are processed after modifiers, making it possible to use options like --include also with possible dynamically added tests.

But I see a deviation from the above statement. It looks like that robotframework processes `-s` option **before** _prerunmodifier_, as opposed to the sequence mentioned in the guide.

This is a simple Modifier, just prints the visited suites:

```python
from robot.api import SuiteVisitor
from robot.api import logger

class Issue(SuiteVisitor):

    def start_suite(self, suite):
        logger.warn("Suite={}".format(suite.name))
```

And this is the test suite structure:

```
prerunmodifierissue
|-- Issue.py
`-- TC
    |-- A
    |   `-- A1
    |       `-- asuite.robot
    `-- B
        `-- B1
            `-- bsuite.robot
```

When tests are executed with just one test case selected via `-t` option, the prerunmodifier is called for both suites - A1 and B1

```
$ robot --prerunmodifier Issue.py -t TC.B.B1.bsuite.Test_B TC
Suite=TC
Suite=A
Suite=A1
Suite=Asuite
Suite=B
Suite=B1
Suite=Bsuite
```

However, when executing tests with just one suite selected via `-s` option, prerunmodifier is called only for that suite. 

Which means _robot does preprocesses `-s` option before calling modifier_; contrary to what the user guide suggests.

```
$ robot --prerunmodifier Issue.py -s TC.B.B1.Bsuite TC
Suite=TC
Suite=B
Suite=B1
Suite=Bsuite
```

Is this the expected behviour?

**Comment by pekkaklarck** [comment] 2023-06-09 22:42
This seems to be caused by `--suite` (i.e. `-s`) affecting which files are parsed. Non-matching files are not parsed at all, so those suites cannot be seen by model my modifiers either. Incidentally this has just been changed (#4688) and behavior with RF 6.1 ought to be different. Could you test that? RF 6.1 rc 1 is out and the final release ia planned for next Monday.

**Comment by kumaraish** [comment] 2023-06-10 12:13
Thanks @pekkaklarck , I tested this with 6.1 rc 1, working as expected. Both the suites are seen by modifier. You can close this one.

**Comment by pekkaklarck** [comment] 2023-06-10 21:04
Thanks for testing! It also sounds like changing the behavior was a good idea. I guess can consider this issue a duplicate of #4688.

**Closed by pekkaklarck** 2023-06-10 21:04 UTC
