### ISSUE TITLE
RF-2.9.1 detects type of variable as dict but fails when applying Collections API - Set to Dictionary/Convert to Dictionary

### ISSUE THREAD

**Issue by sudarsesh** [robotframework/robotframework#2884] opened 2018-06-29 06:07 UTC
**Environment: Robot Framework 2.9.1 (Python 2.7.6 on linux2)**

I am passing a dictionary to an argument embedded into the keyword. RF is recognizing it as a dictionary as you can see from the log but, I am getting the error "Unicode object has no attribute update" while using the Collections.Set to Dictionary API. I even tried the Collections.Convert to Dictionary on that dictionary variable but got the error "*ValueError: dictionary update sequence element #0 has length 1; 2 is required*". I am not sure as to why RF which is correctly giving the type of the variable as dict but throwing errors when used with the Collection library APIs.

**Code snippet used**

```robotframework

Create traffic stream ${stream} on traffic generator vlan ${port}
    ${trmac} =  dutIntObj.getInterfaceMAC   device=${tr2}    interfaceType=${ifType}   interface=${port}
    ${temp_type}=  Evaluate   type(${stream})
    Log    stream type is ${temp_type}
    Set to Dictionary    ${stream}    mac_dst  ${trmac}
```

**Log: While using the Set to Dictionary**

![dict-error-rf2 9 1](https://user-images.githubusercontent.com/12856088/42075122-08ad1538-7b8d-11e8-8fec-c45a80fa930f.JPG)

**Log: While using the Convert to Dictionary**

![dict-error2-rf2 9 1](https://user-images.githubusercontent.com/12856088/42075853-7afadae6-7b90-11e8-8c28-cd3d9ff4ec8e.JPG)

**Comment by sudarsesh** [comment] 2018-06-29 06:16
@pekkaklarck Please help with this issue

**Comment by pekkaklarck** [comment] 2018-07-03 14:04
The problem is that if you have a keyword like

```robotframework
*** Keywords ***
Example ${embedded} arguments
    Log    ${embedded}
```

and use it in your test like `Example {'a': 1, 'b': 2} arguments`, `${embedded}` will get literal string `{'a': 1, 'b': 2}` as a value. It cannot know you wanted to to have a dictionary with that content instead, but you ought to be able to use `Evaluate` keyword to convert it into a dictionary. Notice also that if you'd have argument `${dict}` that contains an actual dictionary as its value, using `Example ${dict} arguments` would work just fine.

I don't think automatically converting that `{'a': 1, 'b': 2}` into a dictionary in the above example would be a good idea. We do, however, have issue #2699 about doing that if the keyword would have been defined as 

```robotframework
*** Keywords ***
Example &{embedded} arguments
    Log    ${embedded}
```

**Comment by pekkaklarck** [comment] 2018-07-03 14:05
Closing this as a duplicate of the aforementioned #2699.

**Closed by pekkaklarck** 2018-07-03 14:05 UTC
