### ISSUE TITLE
Invalid string representation for bytes outside ASCII range

### ISSUE THREAD

**Issue by WisniewskiP** [robotframework/robotframework#5052] opened 2024-02-14 10:35 UTC
Currently output from `Should be Equal` as well as `Should Contain` for bytes is not useful.

Consider following tests:
```robot
*** Test Cases ***
Test Should be Equal
    ${binary1Var} =    Convert To Bytes    \x00\x01\x02\xA0\xB0
    ${binary2Var} =    Convert To Bytes    abc

    Should Be Equal    ${binary1Var}    ${binary2Var}

Test Should Contain
    ${binary1Var} =    Convert To Bytes    \x00\x01\x02\xA0\xB0
    ${item} =    Convert To Bytes    \xC0

    Should Contain    ${binary1Var}    ${item}
```
output is:
```
==============================================================================
Test Should be Equal                                                  | FAIL |
☺☻\xa0\xb0 != abc
------------------------------------------------------------------------------
Test Should Contain                                                   | FAIL |
'☺☻\xa0\xb0' does not contain '\xc0'
------------------------------------------------------------------------------
Test                                                                  | FAIL |
2 tests, 0 passed, 2 failed
==============================================================================
```

it would be better to have `b'\x00\x01\x02\xa0\xb0'` instead of `☺☻\xa0\xb0`

inside log some values are invisible:
![grafik](https://github.com/robotframework/robotframework/assets/1016654/5fc6098e-7842-43c9-a1fb-9b77671fcfbb)

**Comment by pekkaklarck** [comment] 2024-03-26 13:32
I agree the current representation of bytes in error messages isn't great. It's leftover from Python 2 times when the `str` type was actually bytes and people used it for representing both binary data and text. It would be easy to use Python's normal `b'...'` format, but I'm slightly worried the quotes may cause some confusion. I'm not sure is there any better syntax, though, and the Python syntax is at least familiar for many Python users.

Changing this requires changing the ´safe_str` function we use for converting objects to strings so that possible exceptions are handled gracefully. It's used pretty widely, possibly too widely, and touching it may thus have unexpected effects. Better to thus do this in a major release even though I don't see real backwards incompatibility risks.

**Comment by pekkaklarck** [comment] 2024-11-07 22:33
Issue #5259 and the discussion we had about it on Slack made me look at this issue again. It made me realize the current behavior is quite a bit worse than discussed above. I'll explain why below.

Why the string representation looks so strange is that our [string conversion code](https://github.com/robotframework/robotframework/blob/e9e75b7ce5f94da3530e14470d0cb4aa0358f510/src/robot/utils/unic.py#L32) is strange. It basically maps all bytes in the ASCII range (0-127) to Unicode code points with the same value and escapes other bytes (128-255). For example, bytes `b'\x00\xFF'` is converted to a string `'\x00\\FF'`. This makes absolutely no sense, because now there's no easy way to convert this string back to bytes. We should handle all bytes the same way. I'll write a separate comment about alternatives.

Why this is so severe is that the problem isn't limited to error messages as initially reported. For example, a keyword getting `Hello, ${x}!` as an argument where `${x}` contains bytes `b'\x00\xFF'` will get a string `Hello, \x00\\FF!`.

**Comment by pekkaklarck** [comment] 2024-11-07 22:50
It's clear that converting `b'\x00\xFF'` to `'\x00\\FF'` isn't a good idea. Here are some alternatives:

1. Just convert bytes to strings with `str()`. This isn't great because the string representation of bytes in Python contains `b''`  and the earlier `Hello, ${x}!` example would thus be converted to `Hello, b'\x00\xFF'!`.

2. Map all bytes to matching Unicode code points. Bytes are handled consistently and the resulting string can be converted back to bytes by `Convert To Bytes` and with all keywords that have `bytes` as a type hint. Our example would be converted to `Hello, \x00\xFF!`. A problem is that lot of the bytes don't have visible representation and with others the string representation can be strange. For example, our example would actually look like `Hello, ÿ!` in the log file.

3. Escape all bytes. The result would depend on the escaping mechanism, but with the style we currently use our example would become `Hello, \\x00\\xFF!` which in the log file would look like `Hello, \x00\xFF!`. This would have a benefit that all bytes are seen, but it wouldn't be easy to convert it back to bytes. In addition to that, also bytes having a readable string representation like `R` would be converted to `\\x52`.

I pretty strongly believe that the option 2. above is the best. It's only downside is that seeing byte values or even seeing some bytes is hard, but it is possible to use `repr(x)` in Python or `Log    ${x}    formatter=repr` in Robot to see the details. We can also consider adding new keywords for pretty printing bytes if needed.

A nice benefit of the option 2. is that it allows using something like `Header: ${header}\n\n${body}` where `${header}` and `${body}` contain bytes. This value itself would be a string, but if it's passed to a keyword accepting, for example, `message: bytes`, it is converted to bytes automatically without problems.

**Comment by pekkaklarck** [comment] 2024-11-07 23:52
I moved this to RF 7.2 scope even though the change isn't backwards compatible. The reason I believe it won't cause problems, and also the reason I believe this should be fixed ASAP, is that the current string representation is invalid.

**Closed** 2024-11-08 21:20 UTC
Labels: bug, priority: high, backwards incompatible, effort: medium
