### ISSUE TITLE
Robotframework freezing on windows10

### ISSUE THREAD

**Issue by Riwan12** [robotframework/robotframework#2753] opened 2018-01-25 08:57 UTC
Hi,
my robotframework is always freezing, but i dont know the reason causing that issue.
It always happens when i try to open keywords or when i am going to right click(with mouse) on that keywords.

additional information (versions used):
python 2.7.14 
wxPython 2.8 
ride 1.5.2.1

KR

**Comment by HelioGuilherme66** [comment] 2018-01-25 11:02
This does not look like a Robot Framework issue, but a RIDE problem.
Robot Framework is a command line tool, which RIDE has the facility to run it.

If you agree what I said, then, please close this issue.

**Comment by pekkaklarck** [comment] 2018-01-25 14:47
Yeah, we'd need to know a bit more about the failure. If problem occurs while running tests, it could be a bug in Robot, but typically such problems are caused by bugs in libraries. If the problem is that RIDE or some other editor hangs, then it's definitely not a bug in Robot itself.

**Comment by pekkaklarck** [comment] 2018-03-26 20:34
Closing due to lack of information.

**Closed by pekkaklarck** 2018-03-26 20:34 UTC

**Comment by Ionsilver** [comment] 2018-05-17 07:16
This is a problem with RIDE on Windows 10 that I have noticed on several computers. I don't know what causes it or how to fix it.

**Comment by lehaihaitaly** [comment] 2019-01-11 15:56
Hi
