### ISSUE TITLE
Regression if keyword uses `BuiltIn.run_keyword` internally to execute user keyword with timeouts and TRACE log level

### ISSUE THREAD

**Issue by aleskarovadi** [robotframework/robotframework#3062] opened 2019-01-21 13:10 UTC
Hello!

After updating the verision of Robot Framework, some tests started failing with this error message:
```
Variable '${x}' not found.
```
This happens, when I try to run keyword with arguments (which is in a resource file) using `BuiltIn().run_keyword` in Python code.
Here is an example code that reproduced this situation:

1. Resource file `my_resource.robot`
```robot
*** Settings ***
Documentation    My resource file

*** Keywords ***
Keyword With Arguments
    [Arguments]    ${x}    ${y}    ${z}=${None}
    Log many    ${x}    ${y}    ${z}
```

2. Library `mylib.py`
```python
from robot.libraries.BuiltIn import BuiltIn


def run_keyword_from_resource_file():
    BuiltIn().run_keyword("my_resource.Keyword With Arguments", 'This is x', 911)

```

3. Suite file `example.robot`
```robot
*** Settings ***
Library         mylib.py
Resource        my_resource.robot
Test Timeout    10 seconds

*** Test Cases ***
Variable Not Found Bug
    Run Keyword From Resource File
```
**My environment:** Robot Framework 3.1.1 (Python 3.6.2 on win32), but this error is also reprodused with Robot Framework 3.1

It might be similar with issue #3025, because if I remove `Test Timeout`, the test will pass successfully.

**Comment by pekkaklarck** [comment] 2019-01-22 13:46
I cannot reproduce the problem. Are you sure this fails with the exact same examples in your environment?

**Comment by aleskarovadi** [comment] 2019-01-22 14:04
I have checked it one more time. Here is my console output:
```shell
(rf_3.1) C:\Users\user\PycharmProjects\rf_bug>pip freeze
robotframework==3.1.1

(rf_3.1) C:\Users\user\PycharmProjects\rf_bug>robot --version
Robot Framework 3.1.1 (Python 3.6.2 on win32)

(rf_3.1) C:\Users\user\PycharmProjects\rf_bug>ls -la
total 27
drwxr-xr-x 1 user 197121   0 Jan 22 17:58 .
drwxr-xr-x 1 user 197121   0 Jan 22 17:54 ..
-rw-r--r-- 1 user 197121 181 Jan 21 18:01 example.robot
-rw-r--r-- 1 user 197121 177 Jan 21 17:11 my_resource.robot
-rw-r--r-- 1 user 197121 166 Jan 21 16:53 mylib.py

(rf_3.1) C:\Users\user\PycharmProjects\rf_bug>cat my_resource.robot
*** Settings ***
Documentation    My resource file

*** Keywords ***
Keyword With Arguments
    [Arguments]    ${x}    ${y}    ${z}=${None}
    Log many    ${x}    ${y}    ${z}

(rf_3.1) C:\Users\user\PycharmProjects\rf_bug>cat mylib.py
from robot.libraries.BuiltIn import BuiltIn


def run_keyword_from_resource_file():
    BuiltIn().run_keyword("my_resource.Keyword With Arguments", 'This is x', 911)

(rf_3.1) C:\Users\user\PycharmProjects\rf_bug>cat example.robot
*** Settings ***
Library         mylib.py
Resource        my_resource.robot
Test Timeout    10 seconds

*** Test Cases ***
Variable Not Found Bug
    Run Keyword From Resource File

(rf_3.1) C:\Users\user\PycharmProjects\rf_bug>robot --loglevel TRACE example.robot
==============================================================================
Example
==============================================================================
Variable Not Found Bug                                                | FAIL |
Variable '${x}' not found.
------------------------------------------------------------------------------
Example                                                               | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
Output:  C:\Users\user\PycharmProjects\rf_bug\output.xml
Log:     C:\Users\user\PycharmProjects\rf_bug\log.html
Report:  C:\Users\user\PycharmProjects\rf_bug\report.html
```

**Comment by aleskarovadi** [comment] 2019-01-22 14:13
Just tried to run the same test without any additional command line arguments (eg. `--loglevel`). In this case the test passes.
```shell
(rf_3.1) C:\Users\user\PycharmProjects\rf_bug>robot example.robot
==============================================================================
Example
==============================================================================
Variable Not Found Bug                                                | PASS |
------------------------------------------------------------------------------
Example                                                               | PASS |
1 critical test, 1 passed, 0 failed
1 test total, 1 passed, 0 failed
==============================================================================
Output:  C:\Users\user\PycharmProjects\rf_bug\output.xml
Log:     C:\Users\user\PycharmProjects\rf_bug\log.html
Report:  C:\Users\user\PycharmProjects\rf_bug\report.html
```

**Comment by pekkaklarck** [comment] 2019-01-23 11:08
OK, I can reproduce the problem with TRACE level as well. Clearly a bug somewhere and I'll add this to RF 3.1.2 scope. I don't consider this too high priority, though, because it only seems to occur in pretty rare circumstances. There's also a very easy workaround by running tests using DEBUG level.

Notice also that we don't in general recommend running tests on the TRACE level except when investigating problems. In that level all argument values are logged, and that can increase output.xml and log.html sizes basically without bounds.

**Comment by pekkaklarck** [comment] 2019-01-23 12:21
This issue is very similar to #3025. In both cases the underlying issue is that custom library keywords use `BuiltIn.run_keyword` to execute other keywords. Robot's own keywords that execute other keywords internally are registered as so called "run keywords" to handle them specially. This special handling includes:

- Not applying timeouts when these keywords are run. Timeouts are used only when the lowest level keywords are run.

- Optionally not processing arguments (e.g. resolving variables) passed to these keywords. This avoids problems when same arguments are processed again when the lower level keywords are called.

External keywords executing other keywords via `BuiltIn.run_keyword` should actually be registered as "run keywords" as well. Unfortunately the current API for that is a mess and this recommendation isn't documented adequately in the User Guide or elsewhere. The current registration API is [register_run_keyword](https://github.com/robotframework/robotframework/blob/master/src/robot/libraries/BuiltIn.py#L3447) method directly in the BuiltIn module and it is only documented there. As you can see from the docs, the API is deprecated and the idea was to improve it in RF 3.1 (#2190). Unfortunately it was descoped from that release because it wasn't considered important enough. This issue and #3025 demonstrate that a clean and adequately documented registration API is definitely needed add I'll add that issue to RF 3.2 scope.

Although the current registration API is bad, it can still be used to avoid problems described here and in #3025 and to get other possible benefits. In this particular case the original example could be changed to this:

```python
from robot.libraries.BuiltIn import BuiltIn, register_run_keyword

def run_keyword_from_resource_file():
    BuiltIn().run_keyword("my_resource.Keyword With Arguments", 'This is x', 911)

register_run_keyword(__name__, run_keyword_from_resource_file, 
                     deprecation_warning=False)

**Comment by zastress** [comment] 2019-01-23 16:15
Found the same problem but only on Windows OS, with a FOR loop.
In my test, there is the correct syntax "FOR" but in the log.html file, apart from the "variable not found" error I can see this: `Reserved . For ${directory}, IN, @{boxdir}` so the syntax is automatically converted from "FOR" to "For"

**Closed** 2019-03-28 11:51 UTC
Labels: bug, priority: medium
