### ISSUE TITLE
Log: Linking to warnings and `--expandkeywords` broken with IF/ELSE structures

### ISSUE THREAD

**Issue by DirkRichter** [robotframework/robotframework#4195] opened 2022-01-20 12:14 UTC
Running 
> robot --expandkeywords name:*.Comment ExpandBug.robot

on this ExpandBug.robot:
```
*** Test Cases ***
ExpandBug
	IF  ${True}
		Log  true-ranch
	ELSE IF  ${False}
		Log  dead code
	END
	Comment  Hello
```
results in *wrong* expanded keyword *Log dead code* instead of expected keyword *Comment*:
![grafik](https://user-images.githubusercontent.com/20930315/150336178-84188fce-68f7-447f-af17-7641851b5cd9.png)

**Reason:** Rebot correctly identifies the IF and ELSE IF lines as single keyword and thus gives the expand-directive path for the log.html as s1-t1-k2 in order to expand the 2nd keyword. Unfortunately in log space, the ELSE IF branch is now a single keyword-node, thus s1-t1-k3 would be correct.

**Comment by DirkRichter** [comment] 2022-01-21 08:41
The problem is not related to --expandkeywords, because the problem exists in general *linking* mechanism, too (e.g. for warnings). E.g. see this example:
```
*** Test Cases ***
ExpandBug
	IF  ${True}
		Log  true-ranch
	ELSE IF  ${False}
		Log  dead code
	END
	Log  Hello  level=WARN
```
Running this via 
> robot expandBug.robot

results in 
![grafik](https://user-images.githubusercontent.com/20930315/150494169-e67a7f02-6a51-4c55-be80-6433d19023c3.png)

I will investigate robot code and maybe can create a pull request to fix this. 

Related code seems to be this:
https://github.com/robotframework/robotframework/blob/ad4d3a9484a4a523b88357d0e88270897b9f650b/src/robot/model/body.py#L45

**Comment by pekkaklarck** [comment] 2022-01-23 23:06
The problem is doe to the internal model and structure in the log file being different with IF/ELSE structures as well as with new TRY/EXCEPT structures. With both of them the model has a root object that contains all IF/ELSE or TRY/EXCEPT branches, but in the log we only show those individual branches. Due to this difference the id generated for each object in the model is not in sync with id generated in log.

Most likely this is best fixed by changing the id generation code in the model. Hopefully that can be done without making the code too much slower than nowadays. Are you @DirkRichter working with the fix?

**Comment by DirkRichter** [comment] 2022-01-25 07:43
We have done just some tests with the fix to ensure correct working. No performance tests was done, jet. I'll setup a testhost and do some more tests in order to find out the runtime increase...

**Comment by DirkRichter** [comment] 2022-01-25 13:13
I've done hundrets of tests using our test suites. No impact on performance!

**Comment by pekkaklarck** [comment] 2022-01-26 02:13
Good to hear the fix has no performance impact. Is  it the same as in the commit linked above? I have similar fix done locally as well, and was thinking should I add some tests and commit it or should I wait for you to create a PR.

**Comment by DirkRichter** [comment] 2022-01-26 10:26
Yes, i tested the same as in the commit linked above.

**Comment by pekkaklarck** [comment] 2022-01-27 00:23
I noticed that there was another related problem with IF and TRY branches. They have their own `id` implementations that don't take other possible IF or TRY structures into account, not even with the proposed fix, and are actually buggy also otherwise. I have these problems fixed now, along with the original reported problem, and will commit and push changes shortly. I hope you @DirkRichter weren't working with a PR and also hope you can test changes once RF 5.0 alpha 1 out hopefully soon.

**Closed** 2022-01-27 02:19 UTC
Labels: bug, priority: high

**Comment by DirkRichter** [comment] 2022-01-27 07:13
thanks, no problem. I do not need a new release for testing and reviewed your commit. We also need to exclude skipped keywords from body...

**Comment by pekkaklarck** [comment] 2022-01-27 09:49
We'll create an alpha soon anyway, hopefully today, and it would be great if you could test the fix and at the same time the alpha in general.

With skipped keywords, do you mean keywords that aren't run due to an earlier failure or otherwise but are nowadays nevertheless shown in log? If yes, I agree expanding them doesn't make much sense. Please submit a separate issue about that. Still time to get if changed before RF 5 final.
