### ISSUE TITLE
Maximum recursion depth problem

### ISSUE THREAD

**Issue by tarand** [robotframework/robotframework#2123] opened 2015-08-31 12:33 UTC
After having switched to robot 2.8.6, one of our testsuites sporadically reports a "maximum recursion depth exceeded" error. The test case files are basically the same as before.

Any ideas what could be the reason? Note: I looked up the issue repository for this problem, I found such a behavior could occur if recursive variable definitions are there. I briefly looked in the test case files, I couldn't find such a definition.

12:48:34.771 	TRACE 	Arguments: [ u'Execute Success' | u'DeleteRequest_LUR_11.xml' ] 	
12:48:34.781 	FAIL 	maximum recursion depth exceeded (Java StackOverflowError) 	
12:48:34.782 	DEBUG 	Traceback (most recent call last):
  File "/opt/tex/lib/robotframework/robotframework-2.8.6/robot/libraries/BuiltIn.py", line 1370, in run_keyword_and_ignore_error
    return 'PASS', self.run_keyword(name, *args)
  File "/opt/tex/lib/robotframework/robotframework-2.8.6/robot/libraries/BuiltIn.py", line 1370, in run_keyword_and_ignore_error
    return 'PASS', self.run_keyword(name, *args)
  File "/opt/tex/lib/robotframework/robotframework-2.8.6/robot/libraries/BuiltIn.py", line 1198, in run_keyword
    return kw.run(self._context)
  File "/opt/tex/lib/robotframework/robotframework-2.8.6/robot/running/keywords.py", line 103, in run
    handler = self._start(context)
  File "/opt/tex/lib/robotframework/robotframework-2.8.6/robot/running/keywords.py", line 117, in _start
    handler = context.get_handler(self.handler_name)
  File "/opt/tex/lib/robotframework/robotframework-2.8.6/robot/running/context.py", line 173, in get_handler
    return self.namespace.get_handler(name)
  File "/opt/tex/lib/robotframework/robotframework-2.8.6/robot/running/namespace.py", line 210, in get_handler
    handler = self._kw_store.get_handler(name)
  File "/opt/tex/lib/robotframework/robotframework-2.8.6/robot/running/namespace.py", line 210, in get_handler
    handler = self._kw_store.get_handler(name)
  File "/opt/tex/lib/robotframework/robotframework-2.8.6/robot/running/namespace.py", line 236, in get_handler
    handler = self._get_handler(name)
  File "/opt/tex/lib/robotframework/robotframework-2.8.6/robot/running/namespace.py", line 259, in _get_handler
    handler = self._get_implicit_handler(name)
  File "/opt/tex/lib/robotframework/robotframework-2.8.6/robot/running/namespace.py", line 298, in _get_implicit_handler
    handler = method(name)
  File "/opt/tex/lib/robotframework/robotframework-2.8.6/robot/running/namespace.py", line 304, in _get_handler_from_test_case_file_user_keywords
    if self.user_keywords.has_handler(name):
  File "/opt/tex/lib/robotframework/robotframework-2.8.6/robot/running/userkeyword.py", line 68, in has_handler
    if BaseLibrary.has_handler(self, name):
  File "/opt/tex/lib/robotframework/robotframework-2.8.6/robot/running/baselibrary.py", line 27, in has_handler
    return name in self.handlers
  File "/opt/tex/lib/robotframework/robotframework-2.8.6/robot/utils/normalizing.py", line 131, in has_key
    return self.data.has_key(self._normalize(key))
  File "/opt/tex/lib/robotframework/robotframework-2.8.6/robot/utils/normalizing.py", line 82, in <lambda>
    self._normalize = lambda s: normalize(s, ignore, caseless, spaceless)

**Comment by pekkaklarck** [comment] 2015-08-31 13:09
This could be a weird bug somewhere or it could be that your Java stack is just too small. We may have, for example, refactored code so that there are few more recursion levels and that is enough to sporadically cause failures. You can read more about increasing Java stack size and how too small stack size can cause sporadic failures from here:
http://stackoverflow.com/questions/3700459/how-to-increase-the-java-stack-size

It would be great if you could try RF 2.9.1 too. There have been more changes to Robot's internals and situation could have got better or worse. We are not going to create any more RF 2.8.x releases, and thus aren't particularly interested to debug this kind of problems in old releases.

**Comment by pekkaklarck** [comment] 2015-09-08 08:33
Have you had time to investigate this? I cannot do much because there were no instructions how to reproduce this, I haven't encountered this error or heard about others seeing it, and the traceback doesn't tell anything that would help me investigate this.

**Comment by tarand** [comment] 2015-09-10 06:49
Hi Peke,

I added –Xss2mb to the startup command.

With that we did not see that problem again.

Thanks for your suggestion!

Ciao,
                Thomas

**Comment by pekkaklarck** [comment] 2015-09-10 07:18
Thanks for the info! It really seems that the problem is with stack size. Do you possibly have recursive user keywords or just a deep hierarchy of keywords?

Would it be possible for you to test also RF 2.9.1 w/ and w/o `–Xss2mb`? It would be very interesting to know has the situation got better or worse. Based on that we could then decided should we try doing something to this in RF 3.0.

**Comment by pekkaklarck** [comment] 2015-10-09 11:36
Any new info about this?

**Comment by tarand** [comment] 2015-10-14 08:06
This problem did not occur after having increased the stack memory!

**Comment by pekkaklarck** [comment] 2015-10-14 19:39
Good to hear. I guess we can close this issue then.

**Closed by pekkaklarck** 2015-10-14 19:39 UTC
