### ISSUE TITLE
Secure coding warning prints to console when running Dialogs keywords in macOS Sonoma

### ISSUE THREAD

**Issue by KleerCoder** [robotframework/robotframework#4918] opened 2023-10-31 01:54 UTC
After upgrading to macOS Sonoma, the following message prints to the console when I run a test with Pause Execution (or other keywords from the Dialogs library):

`WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.`

The same test runs without this message appearing if I remove the Pause Execution keyword.

**Comment by pekkaklarck** [comment] 2023-10-31 10:16
My guess is that this is somehow related to tkInter that Dialogs uses, but I don't have macOS to test this. Can you possibly investigate this further?

**Comment by pekkaklarck** [comment] 2023-10-31 10:32
Little searching validated my guess. 
https://github.com/python/cpython/issues/110950

Except that technically the issue is in Tk and not in tkinter:
https://core.tcl-lang.org/tk/tktview/10b38a7a7c13235296cb0fbc6205f591d5ed15a4

We cannot do anything ourselves to fix or workaround this so I'll close this issue. Good news is that this seems to be just a warning and that the issue ought to be already fixed and will be included in the next Tk/tkinter release.

**Closed by pekkaklarck** 2023-10-31 10:32 UTC
