### ISSUE TITLE
Append test messages to "FAIL" message

### ISSUE THREAD

**Issue by philip-karlsson** [robotframework/robotframework#2795] opened 2018-03-28 06:08 UTC
Hello, 

In robotframework version 2 I made sort of an "hack" in order to be able to append text from keyword failues to the parent test case failure by doing something similar to:

`message = BuiltIn()._namespace.test.message`

Then appending text to that variable.

When updating to robotframework 3 this doesnt seem to do the trick anymore as the _namespace.test.message has been moved elsewhere. I could find to where with the debugger but I would prefer if there was a way of doing this throgh the "official API"? Can this be implemented?

**Comment by pekkaklarck** [comment] 2018-03-28 06:13
Could you clarify the usage and what you try to accomplish?

**Comment by philip-karlsson** [comment] 2018-03-28 06:22
For example: 

testCase
   kw1
   kw2
   kw3
   kw4
   kw5
   kw6
   kw7
   kw8

If kw 8 fails and all other kws are succesful, the output that rf prints to the console is lost for all the other kws.

I am sorry if it is unclear, the "hack" was done a few years ago and became an issue when I started porting the codebase to rf3 now.

**Comment by pekkaklarck** [comment] 2018-03-28 07:06
Sorry, still don't understand. How can test's message even affect to stuff earlier kws have printed to the console?

**Comment by philip-karlsson** [comment] 2018-03-28 07:17
I can attach some screenshots, the stuff is not printed until the end of the test case actually, that’s why.

**Comment by pekkaklarck** [comment] 2018-03-28 07:28
A simple example would probably be better than a screenshot. Also, explaining the underlying use case would be helpful.

**Comment by philip-karlsson** [comment] 2018-04-04 06:28
Consider the following example:
dummyCase
    [Documentation]             DummyCase
    ${dummy} =                  Set Variable            1
    Should Be True               ${dummy} == 1
    ${dummy} =                  Set Variable            1
    Should Be True               ${dummy} == 1
    ${dummy} =                  Set Variable            2
    Should Be True               ${dummy} == 1

Which gives:
dummyCase :: DummyCase                                                | FAIL |
'2 == 1' should be true.

Previoulsy with the hack we were able to get the result of the succesful keywords printed to the console before the fail. This swift feedback was useful since I had to deal with large autogenerated .robot scripts and needed to see what the succesful values were.

**Comment by pekkaklarck** [comment] 2018-04-24 17:50
I still don't understand this. If you just want to print to console, you can do that from any keyword regardless are there failures or not. Also, what do you mean with "result of the successful keywords"? By default no such information is written to the console.

**Comment by juacompe** [comment] 2018-06-13 05:33
Below is an output of normal fail cases.

```
==============================================================================
Test Mnp Package
==============================================================================
Because not upload ID card photo.                              | FAIL |
The text of element 'css:.field-error > span' should have been 'กรุณาอัพโหลดเอกสารระบุตัวตน ตามขั้นตอนข้างต้น โดยภาพจะต้องเป็นไฟล์ .JPE, .JPEG, .PNG และมีขนาดไฟล์ไม่เกิน 10 MB' but it was 'กรุณากรอกข้อมูล'.
------------------------------------------------------------------------------
Because Port-in number on porting process.                     | FAIL |
The text of element 'css:div.messages .message-error div' should have been 'ดีแทคได้รับคำขอย้ายค่ายสำหรับหมายเลขนี้เรียบร้อยแล้ว และขณะนี้อยู่ในระหว่างการตรวจสอบคำขอย้ายค่าย' but it was 'กำลังตรวจสอบเอกสาร'.
------------------------------------------------------------------------------
Test Mnp Package                                               | FAIL |
2 critical tests, 0 passed, 2 failed
2 tests total, 0 passed, 2 failed
==============================================================================
```

@philip-karlsson can you provide an output of the fail tests with append-text hack? I'm assuming you want something like below?

```
==============================================================================
Test Mnp Package
==============================================================================
Because not upload ID card photo.                              | FAIL |
    √ Open Landing Page
    √ Select MNP Package          MNP Voucher 1500 (2860)
    √ Click Add To Cart Button
    √ Input Personal Detail       ${firstName}    ${lastName}    ${emailAddress}     ${contactNumber}     ${idCard}
    √ Continue MNP Step
    X Element Text Should Be      css:.field-error > span     กรุณาอัพโหลดเอกสารระบุตัวตน ตามขั้นตอนข้างต้น โดยภาพจะต้องเป็นไฟล์ .JPE, .JPEG, .PNG และมีขนาดไฟล์ไม่เกิน 10 MB

The text of element 'css:.field-error > span' should have been 'กรุณาอัพโหลดเอกสารระบุตัวตน ตามขั้นตอนข้างต้น โดยภาพจะต้องเป็นไฟล์ .JPE, .JPEG, .PNG และมีขนาดไฟล์ไม่เกิน 10 MB' but it was 'กรุณากรอกข้อมูล'.
------------------------------------------------------------------------------
Because Port-in number on porting process.                     | FAIL |
    √ Open Landing Page
    √ Select MNP Package          MNP Voucher 1500 (2860)
    √ Click Add To Cart Button
    √ Input Personal Detail       ${firstName}    ${lastName}    ${emailAddress}     ${contactNumber}     ${idCard}
    √ Input ID Card Image
    √ Continue MNP Step
    √ Input Shipping Address      ที่อยู่จัดส่ง  ${addressLine1} ${MNPNumber}     ${subDistrictBill}     ${district}     ${province}     ${postcode}
    √ Continue MNP Step
    √ Confirm Page
    √ Input Portin Number         0893030178
    √ Click Confirm Button
    X Element Text Should Be      css:div.messages .message-error div     ดีแทคได้รับคำขอย้ายค่ายสำหรับหมายเลขนี้เรียบร้อยแล้ว และขณะนี้อยู่ในระหว่างการตรวจสอบคำขอย้ายค่าย

The text of element 'css:div.messages .message-error div' should have been 'ดีแทคได้รับคำขอย้ายค่ายสำหรับหมายเลขนี้เรียบร้อยแล้ว และขณะนี้อยู่ในระหว่างการตรวจสอบคำขอย้ายค่าย' but it was 'กำลังตรวจสอบเอกสาร'.
------------------------------------------------------------------------------
Test Mnp Package                                               | FAIL |
2 critical tests, 0 passed, 2 failed
2 tests total, 0 passed, 2 failed
==============================================================================
```

**Comment by philip-karlsson** [comment] 2018-06-14 06:04
@juacompe This is EXACTLY what I am looking for. Have you made your own hack?

**Comment by juacompe** [comment] 2018-06-15 10:13
@philip-karlsson , not yet. I'm thinking of adding another console type (i.e. `console=enterprise`) to change the display to this. What do you think @pekkaklarck ?

I'm coaching teams in enterprises and usually they have another operation team whose work station is ssh on remote servers. In this situation, a dev team who write and own robot tests and use 
 the default `console=verbose`. And the operation team who did not write the test want to be able to see which keyword was failing to communicate better with the dev team; therefore, the operation team would use `console=enterprise`.

Any comments or suggestions would be highly appreciated.

**Comment by chibihokage** [comment] 2018-06-20 09:52
I created a pull request here <https://github.com/robotframework/robotframework/pull/2875>

**Comment by bkhouri** [comment] 2018-06-20 10:48
why not simply look at the log.html file to see what keywords passed and
which failed?

**Comment by juacompe** [comment] 2018-06-21 01:47
Simply looking at the log.html works perfectly when I’m writing the test on my own machine. It is harder for the operation engineers who look at the test results on Jenkin which has no screen. The tests were run through xvfb-run.

**Comment by pekkaklarck** [comment] 2018-06-21 10:49
@philip-karlsson, do I get it right that you'd want the top-level keywords to be shown on the console? That's at least what the example by @juacompe looks like. I agree that more verbose output would sometimes be useful, and we already have #1393 about that and it's even targeted for RF 3.1. If I've understood your needs correctly, then we can just close this issue as a duplicate of #1393.

There's also PR #2525 that aims to fix #1393 and now also #2875 related to this issue. I need to look at these PRs in more detail, but I want to get RF 3.1 alpha 2 out first. One thing I can comment already now is that I don't like `--console enterprise` too much. What I propose instead is renaming the current default behavior to `--console standard` (or `default` or something similar) and then using `verbose` with the more verbose console output. In addition to supporting '--console verbose`, we should also support `--verbose`. Anyway, coming up with a good output on console is the actual hard part here.

**Comment by philip-karlsson** [comment] 2018-06-27 05:47
@pekkaklarck Yes that is what I am after. I too agree that "enterprise" is not the best naming for the parameter. Console --verbose is an alternative. The way we did it before RF 3;

`BuiltIn().set_test_message("Signal:` " + signal + " is verified to " + value + "\n", `True)` for every successful run.

Then when failing;
`message` = BuiltIn()._namespace.test.message
BuiltIn().fail(message + "Signal: " + signal + " = " + str(sigValue) + ", expected " + `str(value))`

That way we could get our information also for failing keywords to the console as well. Thank for the attention.

**Comment by pekkaklarck** [comment] 2018-06-27 07:46
OK, in that case I'll close this as a duplicate as #1393. Let's continue discussion how the more verbose console output should actually look there.

**Closed by pekkaklarck** 2018-06-27 07:46 UTC
