### ISSUE TITLE
`@{list}` used as embedded argument not anymore expanded if keyword accepts varargs

### ISSUE THREAD

**Issue by jatalahd** [robotframework/robotframework#4364] opened 2022-06-10 08:02 UTC
Until Robot 4.1.2 we have used the following style in library keywords:

    class testlibrary:

        @keyword("Testing embedded ${arguments}")     
        def test_embedded_arguments(self, *arguments: str):
            print (arguments)

        def test_unembedded_arguments(self, *arguments: str):
            print (arguments)

and calling them from robot file

    *** Settings ***
    Library    testlibrary

    *** Variables ***
    @{ARGUMENTS}    arg1  arg2  arg3

    *** Test Cases ***
    Test Embedded Arguments
        Testing embedded @{ARGUMENTS}

    Test Unembedded Arguments
        Test Unembedded Arguments    @{ARGUMENTS}

Output:

    ('arg1', 'arg2', 'arg3')

    ('arg1', 'arg2', 'arg3')

Starting from Robot FW version 5.0, the argument expansion does not work the same way between these two:

Output:

    ("['arg1', 'arg2', 'arg3']",)

    ('arg1', 'arg2', 'arg3')

I feel that this is regression from fixing issue: #4207

Do you see this as a defect or do we need to do the required modifications to our test libraries?

**Comment by pekkaklarck** [comment] 2022-06-14 14:18
I can see that the behavior has changed. Such changes aren't great without a notice in general and in this case it seems the old behavior was better. You are right that the change is most likely due to #4207. That fix itself made sense especially when it made the behavior consistent with library and user keywords. The situation in this issue is slightly different, though, as the keyword accepts varargs. I need to study could we keep the old behavior in that case while avoiding problems that were fixed in #4207. We don't have plans for more RF 5.0.x bug fix releases but hopefully this can be changed in RF 5.1.

Notice that the behavior changes if you change `*arguments: str` to `*arguments: tuple[str]` or just `*arguments`. It won't restore the old behavior but at least the argument isn't converted to a string anymore.

**Comment by pekkaklarck** [comment] 2022-08-13 19:35
Type conversion didn't have anything to do with this issue. The problem is that nowadays `@{list}` used as an embedded argument is always same as `${list}` but earlier `@{list}` was expanded if the keyword accepts varargs. This is pretty easy to fix.

**Closed** 2022-08-13 20:25 UTC
Labels: bug, priority: medium

**Comment by pekkaklarck** [comment] 2023-10-27 11:22
We are planning add support for library keywords with both embedded and normal arguments (#4710). It has two implications related to this issue and the example in the description.

First of all, the plan is to support the mixed argument usage so that we allow keywords like
```python
@keyword('Number of ${animals} should be') 
def example(animals, count):
    ...
```
where the number of accepted arguments of the keyword function is bigger than the number of embedded arguments. The ideas is that you then need to pass them as normal arguments:

**Comment by pekkaklarck** [comment] 2023-10-27 11:35
As explained above, the example in the description won't work anymore if #4710 is implemented. I recommend changing it to this:
```python
class testlibrary:

    @keyword("Testing embedded ${arguments}")     
    def test_embedded_arguments(self, arguments: list[str]):
        print(arguments)
```
That ought to support usages like
```
Testing embedded ${ARGUMENTS}
```
where `${ARGUMENTS}` is a list of strings and automatic conversion ought to also handle this:
```
Testing embedded ['arg1', 'arg2', 'arg3']
```
The above ought to work starting from RF 6.0 when using Python 3.9. If `arguments: list[str]` is replaced with `arguments: list`, also older Robot and Python versions should work too.

**Comment by Vahv1** [comment] 2024-01-18 09:23
So does this mean that there's no way to unpack a list to multiple arguments when giving it from Robot? How would you suggest handling a keyword that can take a single argument or a list of arguments and iterate over them? We have hundreds of methods like:
```
@keyword("Stuff is done in ${things}")
def do_stuff(self, *things: CustomObject):
    for t in things:
        t.do_the_stuff()
```
*things may be a list of CustomObjects or a single CustomObject. Type checking and converting to a list in every method is not nice. Maybe custom converter is the cleanest way? However we don't want to convert a single CustomObject to a list for every method.

**Comment by pekkaklarck** [comment] 2024-01-18 13:51
You could simply use `do_stuff(self, things)` or, if you want to preserve type hints,  `do_stuff(self, things: CustomObject | list[CustomObject])`. In both cases you'd then need to check inside the keyword that did you get a single `CustomObject` or a list of them. If you always want to get a list, then using a custom converter is a good idea. You could have `do_stuff(self, things: CustomObjects)` and then register a converter for `CustomObjects` that always returns a list.

If you don't need to use embedded arguments, then using simply `stuff_is_done_in(self, *things)` without a custom ought to work.
