### ISSUE TITLE
Creating keyword with name matching earlier embedded arguments keyword fails

### ISSUE THREAD

**Issue by adam-wypych** [robotframework/robotframework#2098] opened 2015-08-12 07:17 UTC
I am testing my own Java parser for RED and I found that test case file `test_keyword.robot` executed in RF cause error: `Creating user keyword 'KeywordX' failed: Keyword with same name defined multiple times.` It is confuse, because keyword is defined once:

```
*** Test Cases ***
T1
    Log     dummy

*** Keywords ***
${V}
        Log     x

KeywordX
        Log     keyword executed
```

Additionaly, as I see RIDE shows `${V}` as keyword correctly. In case as I understand name of keyword like variable is not allowed, I think better will be to give more descriptive message, if possible.

**Comment by pekkaklarck** [comment] 2015-08-12 09:46
If a keyword name has a variable, it is considered to contain [embedded arguments](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#embedding-arguments-into-keyword-name). If the name only contains a variable, it will match any used keyword.

The reason for the weird error is that when creating `KeywordX`, Robot checks does the same file already have a keyword with same name. This check is buggy in RF 2.9. Instead of checking is there a keyword with exactly same name, Robot checks are they any keywords matching the name. The earlier created keyword `${V}` matches anything and thus you get the error. I think you wouldn't get an error if keywords were defined in different order.

The same root cause caused also issue #2095. That issue is already fixed and thus also this problem doesn't occur anymore. These problems manifest themselves so differently that I don't think resolving this as the duplicate of #2095 is a good idea. I also want to add some tests for exactly this case before closing this issue.

**Closed** 2015-08-24 12:38 UTC
Labels: priority: high

**Comment by mattc41190** [comment] 2015-09-08 19:51
@pekkaklarck very sorry for delayed response. I upgraded to 2.9.1 and I am getting a different, but similar error message. 

A notable difference in upgrading to 2.9.1 is that the first run works (previously did not) and when it begins to run the second I get an error that the tests have the same name. I will attempt to whip up a demo in a single robot or txt file and attach it.

**Comment by pekkaklarck** [comment] 2015-09-08 20:12
Please submit a new issue if you have encountered a bug in 2.9.1. Notice that warning if a suite has multiple tests with same name is a feature. It's also an old feature so the behavior ought to be same also with earlier versions.

**Comment by mattc41190** [comment] 2015-09-08 21:50
It isn't a warning. It won't run the tests.
If it is intended functionality that the tests below:

Search google for ${number} and ${symbol}

Search google for ${word}

should result in a warning message and an failure of the tests is there a way to disable this feature?

**Comment by pekkaklarck** [comment] 2015-09-08 22:03
Cannot comment much without context. As I already wrote, please submit a new issue if you think you have encountered a bug.
