### ISSUE TITLE
Embedding arguments keyword does not work with "Wait Until Keyword Succeeds"

### ISSUE THREAD

**Issue by Mason-Lin** [robotframework/robotframework#3111] opened 2019-03-05 05:54 UTC
Embedding arguments keyword does not work with "Wait Until Keyword Succeeds"
I tried to send a list/dictionary/object by embedding keyword.
It doesn't work when the keyword is right after Wait Until Keyword Succeeds

It shows error message like this:
Resolving variable '${object.member}' failed: AttributeError: 'str' object has no attribute 'member'

Seems like the embedded arguments is convert into str.

**Comment by pekkaklarck** [comment] 2019-03-05 10:04
This is a duplicate of #1595. Unfortunately not very easy to fix.

**Closed by pekkaklarck** 2019-03-05 10:04 UTC
