### ISSUE TITLE
Parsed Error Mismatched line 2483 column 2  - Seeing with Python 3.10.10 and Robot 6.1.1

### ISSUE THREAD

**Issue by prateekc71191** [robotframework/robotframework#4892] opened 2023-10-09 19:52 UTC
I am seeing same XML parsing issue in robot 6.1.0 and 6.1.1 (and Python 3.10.10) aswell only with one particular suite.
Not sure what is wrong! There is nothing unique about this suite !
same kind of TCs are run in different suite aswell (90% same )

its only generating proper report when all the cases are passing in the suite! If any one case fails, I am getting the above parsing XML issue which is difficult to read and figure out rca!

One thing which I have added in all these suites recently is a Python keyword which is using the python multiprocess (starting 3 threads) but I don't think that would be impacting because other cases with same keyword are working fine!

**Comment by pekkaklarck** [comment] 2023-10-13 23:56
What are those keywords using multi processing doing? If they interact with Robot while running on background that's likely to cause issues. If they themselves run separate Robot processes, problems will occur if they end up writing to the same output.xml file.

**Comment by prateekc71191** [comment] 2023-10-14 05:00
Example:
Task 1:
Some builtin keyword
FOR LOOP
....Some task
END

Task 2:
Custom Keyword



Python Custom keyword def:
""It opens 3 Multiprocess, perform few network devices operation in parallel, Write output to 3 diff files and finally open these 3 diff files and print the file content"



Now in Output.xml
I am observing three entries on (s1-task2) 
1st two entries of task2 have repeated keywords of last iteration of Task1 "FOR LOOP"
and 3rd entry is proper...

**Comment by pekkaklarck** [comment] 2023-10-25 22:52
I suspect the problem is related to how your library uses thread, but it's impossible to know for sure or to be able to help any more with this information alone. If you believe the problem is in Robot, please create a simple example that demonstrates the issue that we can run.

**Comment by pekkaklarck** [comment] 2023-12-15 11:17
No new info. Closing.

**Closed by pekkaklarck** 2023-12-15 11:17 UTC
