### ISSUE TITLE
Ensure Test/Suite Teardowns are executed when Robot is Ctrl-C'd

### ISSUE THREAD

**Issue by bdfariello** [robotframework/robotframework#2451] opened 2016-09-28 21:17 UTC
I've noticed recently that when you're executing tests, if you Ctrl-C (or for Jenkins, if the job is Aborted) that Test and Suite Teardown steps are not executed.

For cleanup purposes, it would be optimal to try to catch and execute these steps. Treat Ctrl-C as a "Fatal Error", if possible, and then proceed with the necessary teardown steps.

If it's not technically possible I understand (as is certainly the case if someone does a kill -9), but thought it was worth filing the Enhancement Request all the same.

**Comment by Tattoo** [comment] 2016-09-29 08:20
Stopping test execution gracefully, ie. running teardowns, is already supported feature: http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#pressing-ctrl-c

Could you provide a case, where this does not work as intended?

Due note that with Jenkins, if I remember correctly, situation is different as Jenkins kills the Robot-process without giving it any chance to clean itself up. Again, if I remember correctly, there was no way to circumvent this issue.

**Comment by pekkaklarck** [comment] 2016-09-29 09:21
@Tattoo is right, Robot already handles Ctrl-C (as well as SIGINT and SIGTERM signals) as suggested in this issue. He's also right that unfortunately that doesn't work correctly with Jenkins. The reason is that Jenkins sends multiple SIGINT/SIGTERM signals and Robot considers that to mean that execution should be stopped immediately. There's no simple workaround or fix for this issue, but these are all possible:

1. Enhance Jenkins so that what signals it sends when aborting a job can be configured. This could possibly be a change to Jenkins core or a feature provided by a plugin.

2. Enhance Robot's Jenkins plugin to either provide the above or add separate test termination system to it.

3. Enhance Robot to handle signal sequence sent by Jenkins automatically. This would require investigating what Jenkins actually does when stopping execution and adapting Robot's termination system to it. Should also investigate is Jenkins possibly changing how it terminates jobs or is the current mechanism a documented functionality that won't be changed. Changes should not cause backwards compatibility problems.

4. Do the above but make it configurable with a command line option. This only makes sense if required changes would be backwards incompatible.

Are you @bdfariello interested to study is any of the above possibilities doable? First two ones are obviously out of the scope of the Robot Framework core project.

**Comment by pekkaklarck** [comment] 2016-10-07 08:53
Any comments about this @bdfariello?

**Comment by bdfariello** [comment] 2016-10-07 12:44
I didn't know Jenkins was sending multiple sigints. It seems like #1 would
be the best option, since it would handle any Jenkins abort (e.g. user
canceling the job). So the best course of action would probably be to close
this, and I would open an issue for Jenkins instead.

Thanks for looking into it!

**Closed** 2016-10-07 12:44 UTC

**Comment by pekkaklarck** [comment] 2016-10-07 19:16
I agree solution 1) would be a good enhancement in Jenkins, but I'm not sure how likely it is to get it added into the core or how easily a plugin could be creates. For Robot users any extra configuration would be a little annoying, mainly because you needed to know about that to be able to use it.

Feature provided by Robot plugin or Robot by default would obviously be more convenient. I can help if someone is interested to look at Robot's Ctrl-C/signal handling to make it compatible with Jenkins.

**Comment by dgube** [comment] 2017-08-11 05:32
A bit late, but maybe others will face the issue described here. Below some details about Jenkins behavior and one possible workaround that will avoid Jenkins' multiple int/term signals to reach Robot. 

The feature responsible for killing process tree once a job is cancelled/exits is described here: [https://wiki.jenkins.io/display/JENKINS/ProcessTreeKiller](https://wiki.jenkins.io/display/JENKINS/ProcessTreeKiller). 

However this behaves incorrectly and sends multiple sigterms/sigints in some cases.

Debugged Jenkins core code and method responsible for this is

`    public void killAll(Process proc, Map<String, String> modelEnvVars) throws InterruptedException {
        LOGGER.fine("killAll: process="+proc+" and envs="+modelEnvVars);
        OSProcess p = get(proc);
        if(p!=null) p.killRecursively();
        if(modelEnvVars!=null)
            killAll(modelEnvVars);
    }`

Jenkins source code can be found here:
[https://github.com/jenkinsci/jenkins/blame/master/core/src/main/java/hudson/util/ProcessTree.java](https://github.com/jenkinsci/jenkins/blame/master/core/src/main/java/hudson/util/ProcessTree.java)

Basically the method kills processes based on both parent - direct child relation and also by comparing build environment with process environment. And does this recursively (for direct descendants). Shell scripts and Python processes that are started by the job are matched (recursively) first by child - parent relationship and then also by env (still recursively) - hence multiple term/int signals. If there are nested chains like Jenkins jobs executes shell script - parent.py popen -> child.py popen -> grandchild.py then the grandchild python process will receive 4 int/term signals.

In Robot case we would want to avoid env based matching.  One workaround to do this is to temper child processes that we want to avoid matching based on this criteria.

Below an example on how to do this in a shell script that is called by the jenkins job (not directly in the shell executor from the jenkins job - parent.py can be seen as the script that start Robot execution):

`#!/usr/bin/env bash

BUILD_ID=doNotKillMe
HUDSON_COOKIE=doNotKillMe
HUDSON_SERVER_COOKIE=doNotKillMe
JENKINS_COOKIE=doNotKillMe
JENKINS_SERVER_COOKIE=doNotKillMe

python parent.py`

 
More details about this below:

[https://wiki.jenkins.io/display/JENKINS/Spawning+processes+from+build](https://wiki.jenkins.io/display/JENKINS/Spawning+processes+from+build)
[https://stackoverflow.com/questions/25639678/how-to-fork-a-background-process-in-jenkins-setting-build-id-and-using-nohup-se](https://stackoverflow.com/questions/25639678/how-to-fork-a-background-process-in-jenkins-setting-build-id-and-using-nohup-se)
