### ISSUE TITLE
Some unit and acceptance tests fail on Python 3.6

### ISSUE THREAD

**Issue by alexandrul** [robotframework/robotframework#2502] opened 2016-12-27 16:50 UTC
* test_import_non_existing (test_importer_util.TestImportClassOrModule)
* test_import_non_existing_module (test_testlibrary.TestImports)
* test_item_from_non_existing_module (test_importer_util.TestImportClassOrModule)
* test_structure (test_importer_util.TestErrorDetails)

https://docs.python.org/3.6/library/exceptions.html#ModuleNotFoundError

> exception ModuleNotFoundError
>
> A subclass of ImportError which is raised by import when a module could not be located. It is also raised when None is found in sys.modules.
>
> New in version 3.6.

**Comment by pekkaklarck** [comment] 2016-12-27 21:02
Interesting. Is there easy fix? Definitely need to test the forthcoming RF 3.0.1 with Python 3.6.

**Comment by alexandrul** [comment] 2016-12-28 09:11
First I have to find an existing test that checks the actual type of the exception, instead of checking the string content.

**Comment by pekkaklarck** [comment] 2016-12-28 14:43
I reproduced the problem too. We have tests that validate error message we got when importing fails and the error message contains the exception name. It won't be a big task to update the four failing unit tests, but I'm fairly certain that there are much more failing acceptance tests.

**Comment by pekkaklarck** [comment] 2016-12-28 18:44
Running acceptance tests on Python 3.6 revealed an encoding problem (see #2505). After fixing that locally 15 tests still fails. Most of them seem to be related to same `ImportError` -> `ModuleNotFoundError` change as the unit test failures. Need to go through them one-by-one and see is there something else too.

**Comment by pekkaklarck** [comment] 2016-12-28 20:51
Also edf890bf3a2d5cc6bd061384af0066b8d04c809b was related to this issue.

**Comment by pekkaklarck** [comment] 2016-12-28 22:08
All tests seem to pass now. Only been testing on Windows so far because I didn't want to spent time with Linux installation (I really miss [deadsnakes](https://launchpad.net/~fkrull/+archive/ubuntu/deadsnakes)), but need to test elsewhere too before 3.0.1 release.

**Comment by pekkaklarck** [comment] 2016-12-29 16:02
I expect all tests to pass and close this issue. Verifying the final status is part of testing the release in different environments.

**Closed by pekkaklarck** 2016-12-29 16:02 UTC
Labels: priority: low
