### ISSUE TITLE
Robot framework document very very stupid

### ISSUE THREAD

**Issue by ntduykkkkkkkk** [robotframework/robotframework#4518] opened 2022-10-28 07:42 UTC
How can I use robot.api package. There's no any example. What is "result" parameter in the function "visit_result". What's the purpose of the docs?. For funny or what else?

![image](https://user-images.githubusercontent.com/52169471/198532038-c3aa04a4-9665-42ae-b520-9a78e7c39985.png)

**Comment by Snooz82** [comment] 2022-10-28 10:33
Hello @ntduykkkkkkkk ,

My name is René and i am the chairman of Robot Framework Foundation.

We do have a very high interest in a nice and polite community. Respect is important.
For me and also for others, your opened ticket is pretty respect less and sarcastic.

Therefore i am closing it!

We do agree, that the api documentation could be improved. The problem is that Robot Framework is totally open source and gathering enough money to finance these improvements is a challenge.

You can improve this situation by joining the foundation and start supporting that framework that you are able to use fully free. 

I would recommend that you ask your question about the api in https://forum.robotframework.org or in our Slack channel. But this time please in a polite and respectful way.

Kind regards
René Rohner
*Chairman of the board of Robot Framework Foundation*

**Closed by Snooz82** 2022-10-28 10:33 UTC

**Comment by manykarim** [comment] 2022-10-28 12:49
Wow, what a rude way of asking a question.

Somebody who would have read the documentation carefully (in the posted screenshot) could have found the example:
![image](https://user-images.githubusercontent.com/61293164/198590130-b692b819-d9c4-44bd-8bec-945c15b0a210.png)

https://robot-framework.readthedocs.io/en/master/autodoc/robot.result.html#example
https://robot-framework.readthedocs.io/en/master/autodoc/robot.model.html#visitor-algorithm
