### ISSUE TITLE
LIBDOC: Improvement to support the return type of a keyword through libdoc

### ISSUE THREAD

**Issue by Harishgoud123** [robotframework/robotframework#3836] opened 2021-01-25 07:05 UTC
Hi Robot framework group,

We are trying to make some enhancements for the remote library that we have implemented and would like to know the return type for each keyword that's implemented in library and currently the xml that get's generated with this libdoc is only returning the following details:

1. Keyword Name
2. Arguments list
3. Documentation

Can we please consider and improvement to add support for return type as well for all the libraries that gets generated the xml using libdoc command?

Thanks,
Harish

**Comment by MaciejWiczk** [comment] 2021-01-25 18:54
@Harishgoud123 could You take a look at this [issue](https://github.com/robotframework/robotframework/issues/3017) if i's not the same?

**Comment by pekkaklarck** [comment] 2021-02-05 08:43
Yeah, this is a duplicate of #3017.

**Closed by pekkaklarck** 2021-02-05 08:43 UTC

**Comment by Harishgoud123** [comment] 2021-02-05 09:09
Thanks for the update, Yeah this one and #3017 are same.
