### ISSUE TITLE
Process: Started processes can hang due to how stdin is configured

### ISSUE THREAD

**Issue by Harm10** [robotframework/robotframework#4065] opened 2021-08-20 16:10 UTC
To get more control on my ps1 scripts I have used WIN-PS2EXE to create executables from them.
This works fine in command console and in Windows 10 in general.
But as soon as I try to run them through Run process I get a time out. If I run the raw ps1 script in Run process everything runs fine and I get the expected result. This happens both in RIDE and in batch interface.
If I run the generated executable through Run and return RC and output (or similar Run approaches) the executable works fine.
I tried several different parameters of WIN-PS2EXE to no avail.
If needed I can supply a doNothing and a helloWorld example executable.
What can I do to resolve this problem?

Python 3.7.9
RF 4.1

Edit: I looked at the process table to find that the requested executable is started by RF and also is terminated on my own request by setting argument on_timeout=terminate (I use a time out period of 30 seconds which should be ample enough for the normal running time)

**Comment by pekkaklarck** [comment] 2021-08-24 16:22
Sounds strange that `Run Process` fails but `Run` from OperatingSystem works. I think the latter runs the command in a shell so that could be the difference. Could you run the former with `shell=True` to see does it matter?

**Comment by Harm10** [comment] 2021-08-25 10:41
I ran with shell=True and the result is the same: timeout. But there is a minor difference: the stderr now contains ^C but that is probably due to on_timeout=terminate? Before shell=True the stderr was empty even when on_timeout was set.

I also tested with some other exec (not generated by WIN-PS2EXE) and this runs fine with Run Process. So apparently WIN-PS2EXE creates peculiar executables?

**Comment by Harm10** [comment] 2021-08-28 23:22
Is there any additional information I can gather so this problem can be debugged?

**Comment by pekkaklarck** [comment] 2021-09-01 08:46
It's very hard to tell where the problem could be without being able to reproduce it myself. If you can provide me instructions how to create a simple problem causing this issue I can try that. Alternatively you could take a look at how the Run Process keyword is implemented and test do you get same problem if you run same code with pure Python without RF. Then you could try modifying the code to see can you somehow fix the problem.

**Comment by Harm10** [comment] 2021-09-02 18:19
You need to install PS2EXE on Windows. You can read the instructions here [https://www.powershellgallery.com/packages/ps2exe/1.0.5](url). If you have that activated you can use the GUI WIN-PS2EXE which is available on GitHub [https://github.com/MScholtes/Win-PS2EXE](url)
Then you can compile any powershell script.
I also experience this problem with a DoNothing script:
`param()
    try {
        $ErrorActionPreference = "Stop"    # Stop on first error
        exit 0
    }
    # general catch
    catch {
        Write-Host "General catch - error occurred:"
        Write-Host Current error: $_
        Write-Host Stacktrace: $_.ScriptStackTrace
        Write-Host Error type: $Error[0].Exception.GetType().FullName
        # get process info to deduce whether this is started as powershell or something else (like an .exe)
        $Pr = Get-Process -ID $PID
        if ($Pr.name -eq 'powershell') {
            $scriptname = $PSCommandPath
        } else {
            $scriptname = $Pr.Path
        }
        $host.ui.WriteErrorLine("Error occurred in $scriptname script!")
        exit 999
    }
    finally {
        #Write-Host This is always executed!
        $error.Clear() ; #"Errors are cleared!"
    }`

Is this clear enough?

**Comment by Harm10** [comment] 2021-09-17 22:45
Was my description clear enough?

**Comment by Harm10** [comment] 2021-09-23 22:27
Could I get some response please?

**Comment by pekkaklarck** [comment] 2021-09-30 20:46
Description looks ok although I have no idea what is a DoNothingScript. The problem is that I have zero PowerShell experience and thus there's lot to learn and I have very limited time.

URLs in the description seem to also be broken but I probably can fix them myself.

**Comment by Harm10** [comment] 2021-09-30 21:03
URLs work fine for me. The DoNothingScript is just a powershell script that does nothing; you start it and it returns. You need to compile it with PS2EXE to get an executable. When you start this exec this return does not happen and a time-out occurs.
In what file of Run Process can I put some debug statements to see what is happening? I really want this to be solved. If you could give me some guidance?

**Comment by pekkaklarck** [comment] 2021-09-30 21:44
URLs work now because I fixed then. Also reformatted the script. More importantly, I was able to create an executable with PS2EXE and was also able to reproduce the problem.

Strangely I was able to run the exe on Python interpreter using the subprocess module that the library uses internally. After debugging this further, I noticed we always set `stdin=PIPE` when starting the process and doing that with plain subprocess caused the same problem as well. Removing this configuration from the Process library also fixed the problem in this case.

I don't remember why we do such configuration, but I believe its there for a reason and cannot just blindly remove it. Need to study subprocess docs first to see what they say about that. Other things to do include studying library history to see if there's an explanation for this config and running our pretty thorough acceptance tests so that the config is removed. Too late now for all that but I'll look at it tomorrow. Hopefully would get this fixed one way or the other for RF 4.1.2.

**Comment by Harm10** [comment] 2021-09-30 22:36
Thanks for your time and I am glad you could reproduce the problem! I will await the new release.

**Comment by pekkaklarck** [comment] 2021-10-01 09:01
I tested that we cannot remove the `stdin=PIPE` configuration that causes the problem with ps2exe programs simply because it breaks our own acceptance tests. Probably I could change them, but I'm pretty certain others depend on this behavior and changing it would be a backwards incompatible change. It absolutely couldn't be done in a patch release like 4.1.2, but I'm not sure would it be a good idea in a major release either.

We can, however, make this configurable. We can add new `stdin` configuration option to `Run Process` and `Start Process` and allow users to use `stdin=NONE` in their data to change the internal [Popen](https://docs.python.org/3/library/subprocess.html#subprocess.Popen) configuration to `stdin=None`. I already prototyped that it's pretty easy to do and also fixes the issue.

If we make it possible to configure `stdin`, we could also enhance it so that you can actually write something to the standard input stream of the started process. Both `stdin=input.txt` and `stdin=Some text` would be convenient. This kind of enhancements don't really belong to a patch release, but since I'm already started to look at stdin behavior, I may implement that as well.

**Comment by Harm10** [comment] 2021-10-01 14:51
That sounds like a win-win situation! If I need to do some preliminary testing please say so.

**Comment by pekkaklarck** [comment] 2021-10-01 20:46
As the notifications above show, I submitted #4102 about the enhancement to support configuring stdin. That's targeted for RF 4.1.2 and ought to make it possible to handle this particular situation. I'll keep this issue separately in RF 4.1.2 as well. I also submitted #4103 about changing the default stdin behavior. That's something we can do earliest in RF 5.0.

**Closed** 2021-10-01 21:46 UTC
Labels: priority: medium, rc 1

**Comment by pekkaklarck** [comment] 2021-10-01 21:58
It would be great if you @Harm10 could test the fix. It's too late now for me to create RF 4.1.2 rc 1 today (well, it's not even "today" as we are past midnight here) but I try to create it on Saturday. If you want to test fixes already before that, you can install the latest code directly from GitHub. Installation instructions you can find via our GitHub main page instruct you how.

**Comment by Harm10** [comment] 2022-03-20 11:44
I was going through my old reports to find that I never replied to your request. Shame on me! I will test and report back.

**Comment by Harm10** [comment] 2022-03-20 12:00
@pekkaklarck : I installed RF 4.1.3 to find that the run process still times out. Am I testing with the right version?

**Comment by pekkaklarck** [comment] 2022-03-20 18:53
Did you configure stdin?

**Comment by Harm10** [comment] 2022-03-21 00:12
Thanks for replying!

No I did not............. :-(  
Now I just did and the time-out is gone! So that seems to be working fine.

For my understanding: what should I specify for stdin? I am used to stdout and stderr. Currently I am using STDIN=NONE (like documented on the Process page).
Should my arguments go in there? They seem to be still picked up as specified before.

**Comment by pekkaklarck** [comment] 2022-03-21 10:31
Use `stdin=None`.

**Comment by Harm10** [comment] 2022-03-21 16:04
OK. I am already using that.

**Comment by pekkaklarck** [comment] 2022-11-10 19:51
I have no Azure experience so cannot really help. Unless you can create a simple example I can run locally, in afraid you need to debug the issue yourself.

**Comment by Harm10** [comment] 2022-11-10 21:01
Thanks for replying. I narrowed it down to the following structure which also fails when running from the command line on my own machine (so not only in Azure):
I start a bat file that in turn starts a robot TC. That TC starts another bat file that starts another robot TC and that one times out on a powershell exec (I have no idea how to get debug info in these circumstances). The first TC executes several instances of the same powershell exec and I have the feeling that the second TC hangs on the first execution of the same powershell exec. As that exec has a name it seems to me that I could see that somewhere? The compiled script in this case starts with checking whether that same exec is still active in the task list. If so then it throws an error.
When I start the TC in RIDE the second bat also gets started and the powershell exec sequence is exactly the same but I do not get any timeout. So my feeling is that it has something to with the bat starting another bat file. As the fix you created had something to do with the way STDIN was handled could bat starting bat have any effect on that?

The exec in this case interacts with an USER envvar of Windows. I should also add that running the same structure with the source of this powershell has no problems whatsoever.

**Comment by Harm10** [comment] 2022-12-04 20:12
@pekkaklarck I was trying to create an example for you to test with to find that there are also problems when starting robot from a bat file that in turn starts it's own bat file. That structure also times out on the second one.

I have 2 TC's (I have difficulty to paste them including new lines):
`TEST_RF_batmain
    [Documentation]    Trying to debug RF timeout when doing bat to bat file - Main file
    ${alias}    set variable    TEST_RF_batmain
    ${battoexec}    set variable    Hello_world
    ${battoexec}    set variable    TEST_RF_batsecond
    Comment    ${battoexec}    set variable    TEST_run_powershell
    set global variable    ${powershell_loc}    ${EXECDIR}\\..\\Powershell
    set global variable    ${bat_loc}    ${EXECDIR}\\..\\BAT_devonly
    set global variable    ${workdir}    ${EXECDIR}\\..\\Work
    ${timeout}    set variable    10s
    ${ontimeout}    set variable    terminate
    ${arg1}    set variable
    ${datetime}    Get Current Date    result_format=%Y%m%d%H%M%S%f
    ${stdout}    set variable    ${work_dir}\\${alias}_${battoexec}_${datetime}_stdout.txt
    ${stderr}    set variable    ${work_dir}\\${alias}_${battoexec}_${datetime}_stderr.txt
    log to console    \nMain: starting bat ${battoexec}
    ${process}    start process    ${bat_loc}\\${battoexec}.bat    ${arg1}    output_encoding=SYSTEM    alias=${alias}    stdout=${stdout}    stderr=${stderr}    stdin=None
    ${res}    wait for process    ${process}    timeout=${timeout}    on_timeout=continue
    ${running}    is process running    ${process}
    run keyword if    '${running}' == '${True}' and '${ontimeout}' == 'terminate'    terminate process    ${process}    kill=false
    run keyword if    '${running}' == '${True}'    fail    Main ${battoexec} timed out!
    log to console    RC: ${res.rc}
    log to console    Stdout: ${res.stdout}
    log to console    Stderr: ${res.stderr}
    log to console    Stdoutpath: ${res.stdout_path}
    log to console    Stderrpath: ${res.stderr_path}`

`TEST_RF_batsecond
    [Documentation]    Trying to debug RF timeout when doing bat to bat file - Second file
    ${alias}    set variable    TEST_RF_batsecond
    ${battoexec}    set variable    Hello_world
    Comment    ${battoexec}    set variable    TEST_run_powershell
    set global variable    ${powershell_loc}    ${EXECDIR}\\..\\Powershell
    set global variable    ${bat_loc}    ${EXECDIR}\\..\\BAT_devonly
    set global variable    ${workdir}    ${EXECDIR}\\..\\Work
    ${timeout}    set variable    10s
    ${ontimeout}    set variable    terminate
    ${arg1}    set variable
    ${datetime}    Get Current Date    result_format=%Y%m%d%H%M%S%f
    ${stdout}    set variable    ${work_dir}\\${alias}_${battoexec}_${datetime}_stdout.txt
    ${stderr}    set variable    ${work_dir}\\${alias}_${battoexec}_${datetime}_stderr.txt
    log to console    \nSecond: starting bat ${battoexec}
    ${process}    start process    ${bat_loc}\\${battoexec}.bat    ${arg1}    output_encoding=SYSTEM    alias=${alias}    stdout=${stdout}    stderr=${stderr}    stdin=None
    ${res}    wait for process    ${process}    timeout=${timeout}    on_timeout=continue
    ${running}    is process running    ${process}
    run keyword if    '${running}' == '${True}' and '${ontimeout}' == 'terminate'    terminate process    ${process}    kill=false
    run keyword if    '${running}' == '${True}'    fail    Second ${battoexec} timed out!
    log to console    RC: ${res.rc}
    log to console    Stdout: ${res.stdout}
    log to console    Stderr: ${res.stderr}
    log to console    Stdoutpath: ${res.stdout_path}
    log to console    Stderrpath: ${res.stderr_path}`

And 2 bat files:
`@echo off
REM start batch file for DevTest TC TEST_RF_batmain
SETLOCAL enabledelayedexpansion

set TC=TEST_RF_batmain
set TCloc="D:\RobotFramework\cps project\TestRobots\DevTest"

robot --timestampoutputs --log %TC%_log.html --report %TC%_report.html --output %TC%_output.xml --outputdir ..\Work --test %TC% %TCloc%.robot
REM echo errorlevel %ERRORLEVEL%
IF %ERRORLEVEL% NEQ 0 ( 
   echo Something went wrong! %ERRORLEVEL%
)
pause
exit /B %ERRORLEVEL%`

`@echo off
REM start batch file for DevTest TC TEST_RF_batsecond
SETLOCAL enabledelayedexpansion

set TC=TEST_RF_batsecond
set TCloc="D:\RobotFramework\cps project\TestRobots\DevTest"

robot --timestampoutputs --log %TC%_log.html --report %TC%_report.html --output %TC%_output.xml --outputdir ..\Work --test %TC% %TCloc%.robot
REM echo errorlevel %ERRORLEVEL%
IF %ERRORLEVEL% NEQ 0 ( 
   echo Something went wrong! %ERRORLEVEL%
)
pause
exit /B %ERRORLEVEL%`

If I run the second one directly from a command window then it runs fine.
If I run the first one directly from a command window then the second one times out.

The bat that gets executed in the second one is very simple:
`echo Hello world!`

So no powershell whatsoever. I think this behavior will also influence a more complicated way of starting a bat file that in turn starts another.

Do you have enough information to investigate?

**Comment by pekkaklarck** [comment] 2022-12-04 22:49
This looks too complicated for me to test. Please try creating something I can just download and run or at least reformat the example. I recommend reading http://sscce.org/ and learning basics of [Markdown](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax).

**Comment by Harm10** [comment] 2022-12-04 23:58
How can I attach files to a post? 
And this is really simple to run if I change the location of the files and put them in one folder. But you need that have Windows I guess? Do you have that?

**Comment by Harm10** [comment] 2022-12-07 21:20
I managed to put it all into 1 folder. But I found in both bat files a pause statement at the end. The first one does not bother RF apparently but the second one does. If I remove that the test runs fine. I will now put a PS call in it and report back.

In the meantime I would like to know how I can supply you with files?

**Comment by Harm10** [comment] 2022-12-10 13:54
I can report that I solved the problem!

A very weird construction in the behavior of STDIN=NONE

I have this structure:
Start TC1 from the command line
---- this TC1 starts several processes of compiled powershell programs with parm STDIN=NONE
---- then it starts TC2 as a bat file **_without_** STDIN=NONE
---------- this TC2 also wants to start several processes of compiled powershell programs with parm STDIN=NONE
---------- one the first one it "hangs" and gets timed out

If I run this same structure from RIDE the problem is not there even when I add one more layer (e.g. TC3).
If I run this same structure from command line a do not use the compiled versions but call the ps1 sources directly this problem also is not there.

If I change the structure to
Start TC1 from the command line
---- this TC1 starts several processes of compiled powershell programs with parm STDIN=NONE
---- then it starts TC2 as a bat file **_with_** STDIN=NONE
---------- TC2 works flawlessly

I feel this has something to do with inheritance of the STDIN=NONE option? My knowledge is too limited on that subject but maybe @pekkaklarck has a view on that?

**Comment by pekkaklarck** [comment] 2022-12-11 18:21
I don't know what you mean with "inheritance of the STDION=NONE option".

Your problems may be related to using batch files. They are _really_ bad for anything more complicated. For example, if a batch file calls another batch file like

```
echo before
another.bat
echo after
```
the parent batch file is killed when the child batch file ends and code afterwards isn't run. You can avoid that by using `call` like
```
echo before
call another.bat
echo after
```
but I'm sure there are other brain dead features there as well.

**Comment by Harm10** [comment] 2022-12-11 23:55
Apparently my explanation was not clear enough. After starting a robot file from the command line that starts a process for a bat file without using stdin=None then specifying stdin=None on a subsequent compiled powershell in that second started bat file is useless as it hangs. If you start the same robot file from Ride this does not happen. If I use that structure and start the powershell processes as a script then the problem also does not occur.
(Each bat file starts its own robot test case)

My feeling is the command line started robot works differently with stdin so you need to explicitly state it on the next bat process to get it "down" to the next process. Otherwise I cannot explain the difference between command line start and RIDE start.

I know bat files could have strange behavior but I need a process that starts a test case which decides to start 1-n other test cases. So I use multi layered bat files to do that.

Anyway I am glad I have found it and it works flawlessly now.
