### ISSUE TITLE
Ussing RemoteApplications library, can't start two applications

### ISSUE THREAD

**Issue by filipecduarte** [robotframework/robotframework#2284] opened 2015-12-28 14:30 UTC
Version: robotframework-3.0b1

I use remote applications to start and tests the java applications.
I kwon this library is deprecated but i can use the remote swing library, i need to import custom librarys. Rigth now, remote swing library not support this imports.

The issue is, i can start one appliction and work fine, in the secund application i have this error:

[ ERROR ] Error in test library 'RemoteApplications': Creating keyword 'Start Application' failed: Keyword with same name defined multiple times.
dez 28, 2015 2:23:04 PM org.robotframework.remoteapplications.org.springframework.beans.factory.xml.XmlBeanDefinitionReader loadBeanDefinitions

INFO: Loading XML bean definitions from class path resource [org/robotframework/remoteapplications/client/clientContext.xml]

Login LCT                                                                                                                           | FAIL |
Keyword with same name defined multiple times.

Regards
Filipe Duarte

**Comment by jussimalinen** [comment] 2015-12-28 15:05
Damn... We really should improve the remoteswinglibrary to make it possible to add your own libraries there.

Fixing RemoteApplications is very unappealing option...

**Comment by pekkaklarck** [comment] 2015-12-28 15:50
It sounds like this problem is caused by the fix for #2097. We definitely don't want to revert that fix but I agree with @jussimalinen that touching RemoteApplications is not appealing either.

RemoteSwingLibrary was designed on purpose to support only SwingLibrary, not general Java libraries. The motivation was to simplify the already complicated problem domain. It was discussed that it could be enhanced to support custom versions of SwingLibrary too, but I don't remember was that ever implemented. There were also some talks about building a framework to allow creating custom remote libraries using the same infrastructure as RemoteSwingLibrary, but that was not done.

Is the library you @filipecduarte are using a custom version of SwingLibrary or a totally custom Java library? Are you interested to look at extending RemoteSwingLibrary to support custom libraries somehow yourself? Alternatively you could look at fixing the problem in RemoteApplications. Creating a new release to fix this issue is an option even if the library itself is deprecated.

As I already wrote, I don't thing the fix for issue #2097 should be reverted. In other words, we probably should close this issue in this tracker as WontFix.

**Comment by filipecduarte** [comment] 2015-12-28 16:18
Hi

Thanks the responses.

I have one extencion for the swing library. My application have custom components and the application developes add more keywords to access to this components. I have a java library who import the swing library.

Your propouse is compile the remote swing library with my library? 
If this is easy i can try. 
I don't have some much knowledge in java.

regards
Filipe Duarte

**Comment by pekkaklarck** [comment] 2015-12-30 18:54
OK. If you have a custom SwingLibrary version, then the good solution for you would be enhancing RemoteSwingLibrary so that it can also support such custom versions. You should submit an issue to its tracker about it. We cannot make any promises when such a feature would be implemented unless you have time and knowledge to create a pull request yourself.

The other solution is fixing this particular problem in RemoteApplications. Although that library is deprecated, fixing a problem that apparently makes in unusable with RF 2.9.1 and newer could still be considered. Also this would likely require a pull request from you, though.

An obvious and easy solution is using RF 2.9 or older where this problem doesn't occur. That is not a good solution in the long run, but ought to be an OK workaround until SwingLibrary is enhanced or RemoteApplications is fixed.

Because we are not going to revert the change that is causing problems for RemoteApplications in Robot side, I will close this issue.

**Closed by pekkaklarck** 2015-12-30 18:54 UTC
