### ISSUE TITLE
Unexecuted IF statements takes a lof of time 

### ISSUE THREAD

**Issue by Eya-Mh** [robotframework/robotframework#4539] opened 2022-11-18 13:20 UTC
**We figured out that unexecuted IF statements takes a long time (  more than 100ms ) and it's affecting our expected results,
as if they were executed.**

**So we have noticed, that when defining the arguments inside the [Documentation] section with the same syntax ( the scalar variable syntax ) as in the declaration of the [Arguments] section, is the main cause of this consumed time.**

**It also effects the executed keywords as when we removed the args from the documentation or we write them in a different way, the time of execution has been decreased significantly in all cases.**

**here i attached two example ( before and after removing the args from the doc ) of how the existence of the args in the [Documentation] section influence the time.**

![result_with_args](https://user-images.githubusercontent.com/118344172/202713001-e75de8de-ffb5-45aa-8608-fd565b369b83.png)
![result_without_args](https://user-images.githubusercontent.com/118344172/202713008-129f2ad2-9075-4dc7-be8f-203fd5ffbb3b.png)
![userKeyword1_with_args](https://user-images.githubusercontent.com/118344172/202713009-5819d740-e137-4ded-aa38-7666cec24bfe.png)
![userKeyword1_without_args](https://user-images.githubusercontent.com/118344172/202713011-7b9b997a-1dcc-46c0-b3ea-ad992338f85d.png)
![issue](https://user-images.githubusercontent.com/118344172/202716697-032066db-5b76-42e2-b6f9-60244c16d0bb.png)

**Comment by pekkaklarck** [comment] 2022-11-18 14:05
Resolving variables in documentation as well as writing documentation to output.xml certainly takes some time, but this looks surprisingly slow. I can take a look where the time is spent but don't have time for that now.

Good news is that you have a simple way to reformat documentation so that this problem most likely goes away. Your documentation now creates a single paragraph that is then written to the log file as a whole. Only the first paragraph is used at the execution time, though, and formatting the doc like below ought to help considerably.

```robotframework
Example
    [Documentation]    Short introduction documentation. Shouldn't probably refer to variables.
   ...
   ...    More details. This is only used by Libdoc so can be long.
   ...    Variables are fine.
```

For more details see the User Guide sections linked below. I need to check is the fact that only the first paragraph is used at execution time explained there well enough. If we cannot enhance performance of writing documentation, need to add a note to the docs about how this can affect performance as well.

http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#library-documentation-tool-libdoc
http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#documentation-formatting

**Comment by Eya-Mh** [comment] 2022-11-18 15:29
In fact, it is not only the first line of the documentation that will affect the execution time if it contains variables, it is the whole section of the documentation, variables take a lot of time in any case regardless of the length of the description, also i can not explain the time spent in a keyword why it's more than the time spent by all it's subkeywords, this time represents a major problem in our project.

**Comment by pekkaklarck** [comment] 2022-11-20 16:27
I tried to reproduce this with the example below, but execution time was max 1ms. Could you create an example that demonstrates the issue in your environment, but isn't overly complicated, that I could test?

```robotframework
*** Variables ***
${X}    x
${Y}    y
${Z}    z

*** Test Cases ***
X
    IF    False
        Keyword 1
        Keyword 2
    ELSE
        Keyword 1
        Keyword 2
    END

*** Keywords ***
Keyword 1
    [Documentation]    Variables exist.
    ...    ${X}
    ...    ${Y}
    ...    ${Z}
    No Operation

Keyword 2
    [Documentation]    Variables don't exist.
    ...    ${a}
    ...    ${b}
    ...    ${c}
    No Operation
```

**Comment by Eya-Mh** [comment] 2022-11-21 13:28
**In my case, Utilities.robot contains many .resource files in the *** Settings *** section ( one of them contains my used keywords ) ... so I tried to create my keywords in the same file where my test case is created, and everything is OK, there is no time consuming, but in my case, as I import the keywords from this Utlities.robot and it contains all the other imports ( .resource files ), the time problem appears and for now to avoid it, I must not use my arguments with the scalar variable syntax in the [Documentation] section of the keyword, Despite this, it seems that there are still many keywords affected by this problem**
**So maybe you can try to do something like this to see if you will encounter the same problem.**

**The .robot file**
```
*** Settings ***
Resource    ../../Keywords/ProjectKeywords/Utilities.robot
*** Test Cases ***
Test 1
    [Tags]    robot:recursive-continue-on-failure
    Should be Equal   1   2
    User Keyword 2
    User Keyword 3    Locked
    Log   log from test case
```
**the .resource file**

```
*** Keywords ***
User Keyword 2
    IF    1 > 3
        User Keyword 1    AE_CAN_FD::0x65::ST_OP_SSP    ${2} 
    ELSE IF    5 > 3
        User Keyword 1    AE_CAN_FD::0x65::ST_OP_SSP    ${2} 
    ELSE IF    0 > 3
        User Keyword 1    AE_CAN_FD::0x65::ST_OP_SSP    ${2}
    ELSE IF    2 > 3
        User Keyword 1    AE_CAN_FD::0x65::ST_OP_SSP    ${2}
    ELSE 
        Log    Hello All
    END
    

User Keyword 1 
    [Documentation]     set signal to specific value ${value}
    ...                 ${update_and_send}: This flag optionnel, by default will be set to True
    ...                 in case of setting multiple signals in the same PDU we need just set this bool to false 
    ...                 just to make sure that the signal value was updated, then in the end we send the whole payload by setting the bool to true
    ...                 Example:     Monitor Signal    Monitor Signal     AE_CAN_FD::0x3C::ST_CON_VEH    ${3}    ${2000}
    [Arguments]    ${path}    ${value}    ${update_and_send}=True
    ${val}=    Convert To Integer    ${value}

    
User Keyword 3
   [Documentation]    Set CLW DRD to specific value ${ClwSet} 
   ...     &{ClwSet}    Released=0    Unlocked=1    Locked=2    Funktionsschnittstelle_ist_nicht_verfuegbar=5    Funktion_meldet_FehlerFunktion_meldet_Fehler=6    Signal_unbefuellt=7       
   ...    Exemple: Set CLW DRD    Locked 
   [Arguments]    ${ClwSet}
   
    IF    '${ClwSet}'=='Released'
        User Keyword 1    CAN_IPB_4::0x137::StatusPushButtonCenterLockDriverDoor    ${0}       
    ELSE IF    '${ClwSet}'=='Unlocked'
        User Keyword 1    CAN_IPB_4::0x137::StatusPushButtonCenterLockDriverDoor    ${1}   
    ELSE IF    '${ClwSet}'=='Locked'
        User Keyword 1    CAN_IPB_4::0x137::StatusPushButtonCenterLockDriverDoor    ${2}
    ELSE IF    '${ClwSet}'=='Funktionsschnittstelle_ist_nicht_verfuegbar'
        User Keyword 1    CAN_IPB_4::0x137::StatusPushButtonCenterLockDriverDoor    ${5}     
    ELSE IF    '${ClwSet}'=='Funktion_meldet_FehlerFunktion_meldet_Fehler'
        User Keyword 1    CAN_IPB_4::0x137::StatusPushButtonCenterLockDriverDoor    ${6}
    ELSE IF    '${ClwSet}'=='Signal_unbefuellt'
        User Keyword 1    CAN_IPB_4::0x137::StatusPushButtonCenterLockDriverDoor    ${7}   
    ELSE
        Fail    the given attribute is not correct  
    END
    
```

**Comment by pekkaklarck** [comment] 2023-02-28 21:30
Now new info since November. Closing.

**Closed** 2023-12-20 01:16 UTC
