### ISSUE TITLE
Lower-level keyword name conflicts

### ISSUE THREAD

**Issue by KseniaStar** [robotframework/robotframework#2417] opened 2016-07-18 18:38 UTC
Hello,

I have used Robot Framework to create over 30 resource files, each of which has its own lower-lever resource file linked to it.
I needed to use keywords from the higher-level resource files in one bundle, so I created a wrapper resource file (importing the 30 higher level resource files into it). I then created a test suite and imported this one resource into it.
My goal has been to use (in tests) the higher-level keywords only (lower-level just helped me on the implementation side). So, because lower-level keywords are being used by their immediate parent only, I did allow their names to be unique only within that resource file (i.e. in the whole bundle of 30 resource files + their children, the children keywords won't have unique names).

In my test cases: I am using unique paths for my higher level keywords. I am getting conflicts for the **lower-level keywords**. For example:

>  Multiple keywords with name 'keyword_name' found. Give the full name of the keyword you want to use:
>     low_level_resource_file1.keyword_name1
>     low_level_resource_file1.keyword_name1
>     low_level_resource_file2.keyword_name1

How can these conflicts be occurring? I am specifying a unique path for the higher-level keyword, from there the lower-level one should be unique.

I am also getting duplicates reported, although no duplicates exist.

How can I resolve this?

**Comment by KseniaStar** [comment] 2016-07-18 19:44
Should mention also the version is RIDE 1.5.2.1

**Comment by pekkaklarck** [comment] 2017-01-30 09:36
First of all, sorry for ignoring this issue for so long. It was buried under a pile of other issues during summer time when I didn't have much time to follow this tracker.

The problem you have faced is very annoying and also known, see #1041. I hope we could fix it one way or other at some point, but cannot unfortunately give any promises when. I close this issue a duplicate of #1041.

**Closed by pekkaklarck** 2017-01-30 09:36 UTC

**Comment by pekkaklarck** [comment] 2017-01-30 09:40
This problem could also be resolved by keyword visibility modifiers proposed by #430. That would probably be a simpler than changing import logic as required by #1041 and wouldn't cause backwards compatibility problems either.
