### ISSUE TITLE
Robotframework become blank page on browser after long time waiting reply from server

### ISSUE THREAD

**Issue by sidarakeo** [robotframework/robotframework#2882] opened 2018-06-28 02:33 UTC
I have a test case that's need to upload file excel that's need to wait until sucess and it's took around 10-15mn to wait when click submit . But i got erorr while i'm waiting around 6-7 minutes the screen browser is become blank like my screenshot below .    image link : https://i.stack.imgur.com/3mvfP.png

Here is a code :
```
TC_WEB_00005-AbnormalCase-Upload-Payroll-Not-Enought
        [Documentation]  Upload payroll for fail test
        Set Selenium Speed      0.3s
        Load Configuration Data     ${config_path}
        LoadCom_ID
        Login TMC Web   ${browser}      ${url}      ${user}     ${pwd}
        click element       //*[@id="menu_file"]/div/div/ul/li[15]/a
        click element       //*[@id="menu_file"]/div/div/ul/li[15]/ul/li[12]/a
        choose file         id=excel         ${CURDIR}/tmp_payroll_upoad.xlsx
        choose file         id=doc         ${CURDIR}/res/mypdf.pdf
        ${time}=    get time
        ${time}=   Get Substring    ${time}    -8   -6
        log to console  ${time}
        input text      id=effective-hours      ${time}
        input text       id=remark           Test fromQA
        click element      //div[@class='col-md-2']/input[@class='btn']
        element should be visible       //div[@class='alert alert-danger']          1800s
        [Teardown]    close browser
```
and the final i get erorr message below :

> TimeoutException: Message: timeout (Session info: chrome=66.0.3359.181) (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5ab),platform=Windows NT 10.0.14393 x86_64)
Any help please ?
**PS: For manual test is fine, but it's become blank like this while in automated test only .**

**Comment by HelioGuilherme66** [comment] 2018-06-28 12:47
Well, this is not a Robot Framework issue. So you should close this issue.
(there are things you could do to try to identify the cause, like:
- Upgrade Chrome, although is supported by your chromedriver it may do some difference
- Try with Firefox
- Try with Ie
- Write a similar test in Java or Python, just to use the Selenium library.
)

**Comment by sidarakeo** [comment] 2018-06-28 13:16
@HelioGuilherme66 Ok , I get it  ,Thanks you

**Closed** 2018-06-28 13:17 UTC
