### ISSUE TITLE
Create Dictionary - dynamic variable

### ISSUE THREAD

**Issue by extmme** [robotframework/robotframework#4649] opened 2023-02-07 09:07 UTC
Hi, 

Can you help me or create a new function in Create Dictionary ( actually function for variables)

I want to create a dictionary in my keyword and argument would be a name for new Dictionary - but not it is not possible by way mentioned below
KW
[Arguments]  ${name_of_dictionary}
&{${name_of_dictionary}}  Create Dictionary 

I get respons : No keyword with name '${${name_of_dictionary}}' found.

But it does not work and actually would be very useful :-) Is there a way how to make dynamic variable for creating dictionary? Or can you create this function in future? :-)

Thanks

**Comment by pekkaklarck** [comment] 2023-02-08 00:01
This seems to be a duplicate of #4545. Until it's fixed, you can use `Set Local Variable` keyword that accepts the variable name itself as a variable.

**Closed by pekkaklarck** 2023-02-08 00:01 UTC
