### ISSUE TITLE
[ ERROR ] Error in file Setting 'Test Teardown' used multiple times.

### ISSUE THREAD

**Issue by tinytongolai** [robotframework/robotframework#2446] opened 2016-09-21 15:09 UTC
Robot Framework 3.0 (Python 2.7.12 on win32)

**\* Settings ***
Test Teardown       CleanUp
Force Tags  SanityCheck
Resource        ./Settings/f1.robot
Resource        ./Settings/f2.robot

**\* Test Cases ***
Valid Login Low Level
    Given Login Page Is Displayed
    When Login Using A Valid Username And Password    ${user}    ${password}
    Then Home Page Is Displayed And Logout Link Enabled
    [Teardown]  Logout

While i am parsing the file robot , i having this ERROR : [ ERROR ] Error in file Setting 'Test Teardown' used multiple times.
Is it really an error, from the Parser ? do i have an errror from my robot file ?

**Comment by pekkaklarck** [comment] 2016-09-21 18:11
There doesn't seem to be anything wrong with this example. Is this the exact same file that causes the error?

**Comment by tinytongolai** [comment] 2016-09-22 07:49
yes, it's is the exact same file that causes the error ? Besides this error, i have an another one almost closed to : [ ERROR ] Error in file Setting 'Force Tags' used multiple times.

I guess due to this error, the Fixture Test/Suite Teardown/Setup are not initiate properly

**Comment by pekkaklarck** [comment] 2016-09-22 09:26
I don't get that error when I test the provided example. Referenced resource files obviously don't exist, but resource files cannot contain Test Teardown settings at all.

Could you please provide an example I can run on my own system that demonstrates this problem? The example shouldn't contain references to resource files, libraries, or keywords only available on your environment.

**Comment by tinytongolai** [comment] 2016-09-22 10:30
Thanks for your time to investigate : "but resource files cannot contain Test Teardown settings at all."
However, the Parser Robot, doesn't initiate the Fixture Test/Suite Setup/Teardon...

is there a patch for Robot Framework 3.0 (Python 2.7.12 on win32) ?

**Comment by pekkaklarck** [comment] 2016-09-22 17:59
If you have `Test Teardown` in a resource file, you should get `Non-existing setting 'Test Teardown'.` error. Please double check the data you use. If you then are certain you get a wrong error somewhere, please provide an example demonstrating the problem that others can execute too.

**Comment by pekkaklarck** [comment] 2016-10-05 14:54
Any new information about this?

**Comment by tinytongolai** [comment] 2016-10-06 08:14
Thanks for your concern... i am still investigating why i have this Error message. I let you know why ... if i found out

**Comment by pekkaklarck** [comment] 2017-01-30 11:09
No new info since October, closing. Please comment here or open a new issue if you have more information and are sure this is caused by a bug in Robot.

**Closed by pekkaklarck** 2017-01-30 11:09 UTC

**Comment by DishaMunshi** [comment] 2018-03-07 11:13
Hi all,

I am getting this issue ' Setting '[Return]' used multiple times.' when I run my cases which call resources having keywords with multiple return statements. below is example of the keyword in that resource file

Check xyz when customer has mobile limit value
  ${line}=  Get Text  xpath=(//div[2]/div[1]/table/tbody/tr[7]/td[2])[1]
  @{list}=  Split String  ${line}
  Set Test Variable  ${abc}  @{list}[1]
  [Return]  ${abc}
  ${kdef}=  Remove String  @{list}[1]  ,
  [Return]  ${kdef}
  Set Suite Variable  ${kdef}
  Should be equal  ${kdef}  55.00
  Sleep  1
  ${line}=  Get Text  xpath=(//div[2]/div[1]/table/tbody/tr[7]/td[2])[1]
  @{list}=  Split String  ${line}
  Set Test Variable  ${xyz}  @{list}[2]
  [Return]  ${xyz}
  Set Suite Variable  ${xyz}
  Should be equal  ${xyz}  contract
  Close Browser

**Comment by pekkaklarck** [comment] 2018-03-08 10:48
You can only use `[Return]` once. If you have multiple points where'd you like to return, use `Return From Keyword` or `Return From Keyword If` keywords.
