### ISSUE TITLE
If anything writes to the the console if screws up the alignment of the test status

### ISSUE THREAD

**Issue by KotlinIsland** [robotframework/robotframework#3989] opened 2021-05-28 01:21 UTC
```robot
*** Test Cases ***
Test1
    [Documentation]    some doc
    log  hi
```
```
==============================================================================
Suite                                                                         
==============================================================================
Test1 :: some doc                                                     | PASS |
------------------------------------------------------------------------------
Suite                                                                 | PASS |
1 test, 1 passed, 0 failed
==============================================================================
```
```robot
*** Test Cases ***
Test1
    [Documentation]    some doc
    log  hi  console=True
```
```
==============================================================================
Suite                                                                         
==============================================================================
Test1 :: some doc                                                     hi
| PASS |
------------------------------------------------------------------------------
Suite                                                                 | PASS |
1 test, 1 passed, 0 failed
==============================================================================
```

**Comment by pekkaklarck** [comment] 2021-06-19 20:45
I don't think there's anything we really can to to fix this. The problem is that we have a single stdout stream and write to it from multiple sources that cannot easily cooperate. It would probably be easiest to just create a separate GUI runner that could show execution in one window/pane and logged messages in another. That should be implemented as a separate project outside the core, though. Or do you have ideas how this could be handled?

**Comment by Zeckie** [comment] 2021-06-20 04:33
The issue as I see it as that robot currently assumes that nothing will log to the console (despite providing multiple ways to do so) while a test is running, and that it is ok to leave cursor part way through a line and assume it will not move.

I can think of 4 different ways this could be solved (I prefer option 3)

## Option 1 - Keep track of whether anything logs to console during the test run

The first time (in a test) anything logs to console, print a newline char before the output, so the new message goes on a new line. 

When the test finishes, check whether anything has logged to the console. It anything has written to the console, output the whole line again, so the console output looks like this:

```
==============================================================================
Suite                                                                         
==============================================================================
Test1 :: some doc                                                     
hi
Test1 :: some doc                                                     | PASS |
------------------------------------------------------------------------------
Suite                                                                 | PASS |
1 test, 1 passed, 0 failed
==============================================================================
```

## Option 2 - Only output full lines
Don't log the test line until the test finishes, and then log the whole line (incl newline) in one go. The cursor is always left at the start of a new line.

```
==============================================================================
Suite                                                                         
==============================================================================
hi
Test1 :: some doc                                                     | PASS |
------------------------------------------------------------------------------
Suite                                                                 | PASS |
1 test, 1 passed, 0 failed
==============================================================================
```

## Option 3 - Have the existing robot output be a listener that can be turned off
Have the output (option 1 or 2) being done by a listener that is enabled by default, but turned off using the [`--console` switch](https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#console-output-type). Users could then develop their own [listener](https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#listener-interface) based on that one if they want it to behave differently.

## Option 4 - No change
Don't change anything - users who want this behaviour can implement using `--console none`](https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#console-output-type), and their own [listener](https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#listener-interface) that uses [`logger.console`](https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#programmatic-logging-apis)

**Comment by pekkaklarck** [comment] 2021-06-20 10:33
You are right about the root cause @Zeckie. Comments about the options you propose:

1. In the common case where there's no output to the console other than what Robot itself writes the output would be

        ==============================================================================
        Suite                                                                         
        ==============================================================================
        Test1 :: some doc                                                     
        Test1 :: some doc                                                     | PASS |
        ------------------------------------------------------------------------------
        Suite                                                                 | PASS |
        1 test, 1 passed, 0 failed
        ==============================================================================

    which I don't like too much. Once we write the newline after writing `Test 1 :: some doc`, we cannot anymore (AFAIK) delete it and write more stuff to that line. Another problem is that we needed some way to detect does someone write to `sys.__stdout__` and that's not too easy. It's not a good practice in general to replace it with a custom object, and if we did that we needed to be super careful.

2. Nothing, not even the name of the test, would be printed to the console when a test starts. I don't think that's a good idea in this verbose output.

3. Does this mean converting the current console output code to use the public listener API instead of some private APIs it uses currently? And then users could inherit the code (or just copy and modify) in their listeners? That sounds like a good idea and would probably simplify the code also otherwise.

4. Yeah, custom listeners are already an option now.

Yet another option is rewriting the current verbose output totally so that it takes possible external outputs better into account. Due to the limitations we have with just having `sys.__stdout__` and console this may not be easy. Anyway, possible new output doesn't need to look anything like the current output does.

**Comment by pekkaklarck** [comment] 2023-12-19 22:20
I don't think we can do anything to fix this with the current console output. It needs to be re-designed and re-implemented at some point, hopefully sooner than later, and I'm sure console logging by tests will be taken into account better than nowadays. Anyway, I close this issue.

**Closed by pekkaklarck** 2023-12-19 22:20 UTC
