### ISSUE TITLE
FatalError raised in Evaluate doesn't stop the excution

### ISSUE THREAD

**Issue by tminakov** [robotframework/robotframework#4023] opened 2021-06-25 14:45 UTC
If code executed inside `Evaluate` raises `robot.api.FatalError`, this does not stop the execution of all follow up cases _(contrary to raising it in a normal, keyword context)_.

Sample python code, test.py:

```
from robot.api import FatalError


def test_fatal():
    if True:
        raise FatalError('raised in function')
    return 5
```

When used in `Evaluate`, the follow up case "Testcase2" is executed:

```
A testcase
    ${blah}=     Evaluate    test.test_fatal()

Testcase2
    Log To Console      aaaa
```

When the usage is through the normal flow - a keyword call like `${blah}=    Test Fatal` for example, the following cases are not executed _(with the expected message "Test execution stopped due to a fatal error.")_

The behavior is also visible with inline python evaluation, e.g. this call stops only the variable declaration, not the whole execution:

```
*** Variables ***
${my var}    ${{ test.test_fatal() }}
```

**Comment by pekkaklarck** [comment] 2021-06-28 10:13
This is due to expression evaluation catching all exceptions and only handling `SystemExit` and `KeyboardInterrupt` specially so that they aren't caught. These caught exceptions are then reported as normal exceptions and later the code handling exceptions by executed keywords sees them, not original `FatalError`. This could probably be changed relatively easily with the `Evaluate` keyword so that it would pass special exceptions through, but I'm afraid handling this in the Variables section would be a lot harder.

I personally see it rather strange to raise this kind of special exceptions from expression evaluation and don't see this limitation worth fixing. We have a well defined API that already supports stopping execution altogether and other special exceptions. That said, I don't mind it working either so if someone else is interested to study how easily it could be fixed I can leave this issue open and wait for a pull request.

**Comment by tminakov** [comment] 2021-07-07 20:56
> We have a well defined API that already supports stopping execution altogether and other special exceptions.

Can you please point me to something in that direction, I thought `robot.api.FatalError` is the (only) way to go? 

To give some context, my use case is for the variables case - when they are storing secrets, instead of putting them directly in the code or through env variables, I'm setting them through a provider. And if it cannot retrieve the value (for - reasons), I'd prefer to halt the execution rather than continuing with an undefined Robot Framework variable.

**Comment by pekkaklarck** [comment] 2021-07-07 21:20
The API is raising a fatal exception by a keyword. Raising such an error elsewhere is not supported. I'm not against such support being added, but I believe adding it everywhere consistently is pretty hard. I personally consider this so low priority that I don't have interest to look at it more closely, but if someone else is interested to study I'm happy to review PRs and help also otherwise.

**Comment by pekkaklarck** [comment] 2022-01-13 13:30
FatalError can be used for stopping execution using your own keyword. It's just not handled specially elsewhere. If FatalError has worked earlier with Evaluate, then the change can be considered a regression and I can fix it.

**Comment by pekkaklarck** [comment] 2023-12-20 01:56
No updates about the behavior being different earlier. Closing.

**Closed by pekkaklarck** 2023-12-20 01:56 UTC
