### ISSUE TITLE
`Run Keyword And Ignore Error` and others don't handle "passing" exceptions correctly

### ISSUE THREAD

**Issue by fblampe** [robotframework/robotframework#2799] opened 2018-03-29 15:10 UTC
The keyword "Run Keyword And Ignore Error" returns 'FAIL' as the status of the executed keyword if that keyword internally executes "Pass Execution", even if the keyword passes.

This is contrary to the documentation of the BuiltIn library:

> This keyword returns two values, so that the first is either string PASS or FAIL, depending on the status of the executed keyword.

Reading this, I would expect that if the keyword given to "Run Keyword And Ignore Error" passes, then 'PASS' will be returned as the first return value.

However, for example, the following test case will log "${status} is FAIL":

```
*** Test Cases ***
| Test Bug With Ignore Error And Pass Execution
|    | ${status} | ${retVal}= | Run Keyword And Ignore Error | Pass Execution | status should be 'PASS' |
|    | Log To Console | \${status} is ${status} |
```

The output.xml file contains the following lines:
```
<kw library="BuiltIn" name="Run Keyword And Ignore Error">
<doc>Runs the given keyword with the given arguments and ignores possible error.</doc>
<arguments>
<arg>Pass Execution</arg>
<arg>test passed, status should be 'PASS'</arg>
</arguments>
<assign>
<var>${status}</var>
<var>${returnVal}</var>
</assign>
<kw library="BuiltIn" name="Pass Execution">
<doc>Skips rest of the current test, setup, or teardown with PASS status.</doc>
<arguments>
<arg>test passed, status should be 'PASS'</arg>
</arguments>
<msg level="INFO" timestamp="20180329 16:55:48.734">Execution passed with message:
test passed, status should be 'PASS'</msg>
<status endtime="20180329 16:55:48.736" starttime="20180329 16:55:48.730" status="PASS"></status>
</kw>
<msg level="INFO" timestamp="20180329 16:55:48.737">${status} = FAIL</msg>
<msg level="INFO" timestamp="20180329 16:55:48.738">${returnVal} = test passed, status should be 'PASS'</msg>
<status endtime="20180329 16:55:48.739" starttime="20180329 16:55:48.725" status="PASS"></status>
</kw>
```

The log.html file also shows that the inner keyword passed (green label), but the resulting status is for some reason 'FAIL': https://imgur.com/a/6c6bv.

Found in Robot Framework versions 3.0.2, 3.0.0, 2.8.5
Interpreter: Jython (Java 1.8.0_161)
OS: Ubuntu 16.04

**Comment by pekkaklarck** [comment] 2018-03-29 15:30
Good catch. The reason this happens is that this keyword catches `ExecutionFailed` which happens to be the base class for `ExecutionPassed` that `Pass Execution` uses. It's easy to handle `ExecutionPassed` separately, but need to decide how to do it. We have two options:

1. Return `PASS` and the return value associated with the `ExecutionPassed` from this keyword. Execution would continue after the keyword.

2. Re-raise `ExecutionPassed` so that the execution really stops. No further keywords would be run.

The latter is closer to the spirit of the `Pass Execution` keyword but also more backwards incompatible. I'm thinking we should still do that but wait until RF 3.1.

**Comment by pekkaklarck** [comment] 2018-03-29 15:31
Various other keywords are affected by the same bug. One good solution would be changing code so that `ExecutionPassed` isn't anymore based on `ExecutionFailed`.

**Comment by michalanglart** [comment] 2018-04-17 12:36
Hi,

in [RED](https://github.com/nokia/RED) we're hit by this issue in following way:

We have a small feature called 'Conditional Breakpoint' - user can put a breakpoint in source file and assign it with some condition like:

```
Should Be Equal  ${x}  ${y}
```

The execution would pause if the condition `PASS`-es. Internally when RED considers if it should pause on this breakpoint we pass the condition and use `Run Keyword And Return Status` to evaluate (which internally calls `Run Keyword And Ignore Error`). 

Up till RF 3.0.2 we had 3 outcomes of condition evaluation:
- Keyword passes so the execution pauses
- Keyword fails so execution continues
- There is some kind of error like e.g. non existing keyword used in condition; in such cases we were pausing execution and displaying the error to user so that he or she would be aware of the problem and to give a chance to fix it

After updating to 3.0.3 we no longer have an exception from `Run Keyword And Return Status` so in such cases it behaves like a failed keyword thus the execution continues.

It seems that we could fix it by somehow using `Run Keyword` and properly handling different type of exceptions which comes from this call but it may be sensitive due to possible changes in errors/exceptions inheritance structure.

Is there other reliable way of executing keywords which would return one of 3 possibilities: `PASS`, `FAIL`, or exception with message?

**Comment by pekkaklarck** [comment] 2018-10-26 06:51
As I commented earlier, not only `Run Keyword And Ignore Error` but also many other similar keyword like `Run Keyword And Expect Error` and `Wait Until Keyword Succeeds` have the same issue as well. The root cause is that our internally used `ExecutionPassed` exception is based on `ExecutionFailed` and these keywords have have code like

```python
try:
    # something
except ExecutionFailed as err:
    # handler failure
```

which end up handling also `ExecutionPassed` as if it was a failure. Could handle this by changing the code to

```python
try:
    # something
except ExecutionPassed:
    raise
except ExecutionFailed as err:
    # handler failure
```

but that needed to be added to each keyword. Much better to change our internal exceptions so that `ExectionPassed` isn't anymore based on `ExecutionFailed`. That makes sense logically and also makes it possible to remove one `ExecutionPassed: raise` added when #2594 was fixed yesterday.

Changing the internal exception hierarchy shouldn't cause problems with external code, but various keywords now letting "passing exceptions" go through is potentially backwards incompatible. I doubt that causes problems in real usage, but better to mention this in the RF 3.1 release notes anyway.

**Closed** 2018-10-26 06:54 UTC
Labels: backwards incompatible, beta 1, bug, priority: low
