### ISSUE TITLE
Multiple keywords matching: 'User Login Successfully' in 'PageCommonActions'.

### ISSUE THREAD

**Issue by walaa-akram** [robotframework/robotframework#5117] opened 2024-04-21 15:19 UTC
I'm implementing automation solution for  a website using page object model.
So I have the robot file named with "PageCommonActions" which contains all common keywords I built to be used in pages.
each robot file that represent a page in my website contains importing to the "PageCommonActions" using resource keyword.
In tests folder I can import more than one page robot files to implement scenario steps through pages.
if in test scenario I used a keyword written in "PageCommonActions" file then I get error:
Multiple keywords matching: 'User Login Successfully' in 'PageCommonActions'.
which is the same file but it is seen in the test more than once as each imported page imports already this file so the pycharm see the keyword multiple times.
Is there a solution for this issue?

**Comment by pekkaklarck** [comment] 2024-04-22 11:11
Does the error occur when you run tests or is it only shown in the IDE?

**Comment by pekkaklarck** [comment] 2024-04-23 21:53
Ok. In that case the issue isn't in Robot Framework itself and I'll close this issue here. I don't know is there a bug in the editor or editor plugin you use or is this due to misconfiguration. If you suspect the former, please find the issue tracker of the tool you use and submit the issue there. If you believe it's a configuration issue, or you aren't sure, asking help on our Slack or Forum is probably the best idea. This issue tracker is only for bug reports and enhancement requests related to Robot Framework core.

**Closed by pekkaklarck** 2024-04-23 21:53 UTC
