### ISSUE TITLE
rebot - Reading XML source 'xxx/output.xml' failed: Incompatible XML element 'arg'.

### ISSUE THREAD

**Issue by Pratapreddy1188** [robotframework/robotframework#4325] opened 2022-04-27 05:57 UTC
[output.txt](https://github.com/robotframework/robotframework/files/8569224/output.txt)
I am using latest Robot Framework version 5.0 for automated tests.

I use rebot tool to aggregate my test result ran in multiple stages. 

I see below error 
**Reading XML source 'xxx/output.xml' failed: Incompatible XML element 'arg'.**

It is working fine locally on my VM.

this error is only coming on my bamboo build server.

**Comment by pekkaklarck** [comment] 2022-05-05 17:41
With this information it's rather hard to tell where the problem is. One possibility is that your Rebot version on the build server is old and not compatible with output.xml files produced with new Robot versions. Please check the installed versions first. If versions match, the problem is somewhere else. In that case you'd need to provide more information about the situation. Best would be a simple example demonstrating the problem.

**Comment by ranjith-bhoopalan** [comment] 2022-05-06 06:47
Yes,  your comment is right. It was rebot version issue. I got it resolved by making sure the same version is used for running tests and aggregating test results.

**Comment by Pratapreddy1188** [comment] 2022-05-06 08:33
Yes, your comment is right. It was rebot version issue. I got it resolved by making sure the same version is used for running tests and aggregating test results

**Closed** 2022-05-06 08:33 UTC
