### ISSUE TITLE
Wrong HTML keyword link, when executing with --loglevel TRACE

### ISSUE THREAD

**Issue by dbdlahd1027** [robotframework/robotframework#4056] opened 2021-08-09 01:01 UTC
[INFO]
Robot Framework version: 4.1

[Symptom]
Keyword link index is supposed to start with -k1, but starts from -k2 while executing with --loglevel TRACE.
Please refer to the figure attached.
<img width="541" alt="KW_link_start_index_wrong_with_TRACE" src="https://user-images.githubusercontent.com/43832506/128651275-572012e0-3c42-45af-8c72-c30dc390aa7b.png">

**Comment by pekkaklarck** [comment] 2021-08-12 09:32
I can reproduce this, but because this id is only for internal usage and regenerated for each run, I don't think the actual value really matters. If there are concrete problems due to that, like #4057 indicates, then it's a different situation.

**Comment by pekkaklarck** [comment] 2021-08-13 11:46
The problem was that generating keyword id didn't take into account possible messages the parent keyword had. That didn't seem to generate other problems than the one reported in #4057. Having multiple issues about the same underlying problem doesn't make much sense so I close this issue as its duplicate.

**Closed by pekkaklarck** 2021-08-13 11:46 UTC
