### ISSUE TITLE
AutoItLibrary not compatible with RF 2.9.1

### ISSUE THREAD

**Issue by c-voigt** [robotframework/robotframework#2147] opened 2015-09-15 11:48 UTC
It can't run the built in tests of AutoItLibrary 1.1 when using robotframework 2.9.1. Installation was done following this description:
https://blog.codecentric.de/en/2014/02/robot-framework-testing-windows-applications/

The test produces the following output...

```
d:\software\AutoItLibrary-1.1\tests>runtests
==============================================================================
AutoItLibrary Windows Calculator :: Post installation self-test for AutoItL...
==============================================================================
[ ERROR ] Error in test library 'AutoItLibrary': Creating keyword 'Run' failed: Keyword with same name defined multiple times.
[ ERROR ] Error in test library 'AutoItLibrary': Creating keyword 'Win Wait' failed: Keyword with same name defined multiple times.
[ ERROR ] Error in test library 'AutoItLibrary': Creating keyword 'Win Wait Active' failed: Keyword with same name defined multiple times.
[ ERROR ] Error in test library 'AutoItLibrary': Creating keyword 'Win Wait Close' failed: Keyword with same name defined multiple times.
AutoItLibrary Windows Calculator.Calculator Test Cases :: Tests the AutoItL...
==============================================================================
Integer Addition :: Get "The Answer" by addition.                     | FAIL |
Parent suite setup failed:
Keyword with same name defined multiple times.
------------------------------------------------------------------------------
Integer Subtraction :: Get "The Answer" by subtraction.               | FAIL |
Parent suite setup failed:
Keyword with same name defined multiple times.
------------------------------------------------------------------------------
Integer Multiplication :: Get "The Answer" by multiplication.         | FAIL |
Parent suite setup failed:
Keyword with same name defined multiple times.
------------------------------------------------------------------------------
Integer Division :: Get "The Answer" by division.                     | FAIL |
Parent suite setup failed:
Keyword with same name defined multiple times.
------------------------------------------------------------------------------
Hex Addition :: Test Hex addition.                                    | FAIL |
Parent suite setup failed:
Keyword with same name defined multiple times.
------------------------------------------------------------------------------
Hex Subtraction :: Test Hex subtraction.                              | FAIL |
Parent suite setup failed:
Keyword with same name defined multiple times.
------------------------------------------------------------------------------
Test Screen Capture On FAIL :: Test that a screenshot is taken and... | FAIL |
Parent suite setup failed:
Keyword with same name defined multiple times.
------------------------------------------------------------------------------
AutoItLibrary Windows Calculator.Calculator Test Cases :: Tests th... | FAIL |
Suite setup failed:
Keyword with same name defined multiple times.

Also suite teardown failed:
Variable '${MENUMAP}' not found. Did you mean:
    ${MENUMAP_61}
    ${MENUMAP_60}
    ${MENUMAP_51}

6 critical tests, 0 passed, 6 failed
7 tests total, 0 passed, 7 failed
==============================================================================
AutoItLibrary Windows Calculator :: Post installation self-test fo... | FAIL |
6 critical tests, 0 passed, 6 failed
7 tests total, 0 passed, 7 failed
==============================================================================
Output:  d:\software\AutoItLibrary-1.1\tests\results\output.xml
Log:     d:\software\AutoItLibrary-1.1\tests\results\log.html
Report:  d:\software\AutoItLibrary-1.1\tests\results\report.html
```

**Comment by pekkaklarck** [comment] 2015-09-15 12:36
This is most likely caused by #2097. Have you @CMTaylor encountered this?

Apparently AutoItLibrary has multiple methods that would create the same keyword. Earlier that worked without warnings, but it actually dependent on luck which method was actually used. This is something that should be fixed in AutoItLibrary, but we probably need to consider reverting #2097 or at least only emitting a warning, not failing, in this case.

**Comment by pekkaklarck** [comment] 2015-09-17 14:41
I was able to reproduce the problem and investigate why it occurs. As I already suspected, the problem is due to library containing same keyword multiple times nowadays being an error (#2097).

AutoItLibrary is a hybrid library that tells what keywords it has by using `get_keyword_names` method. It is implemented so that it returns all names of the methods exposed by AutoIt tool as well as all names of the methods implemented by the library itself. Methods `Run`, `WinWait`, `WinWaitActive` and `WinWaitClose` are defined in both in AutoIt and in the library and thus the list returned by `get_keyword_names` contains duplicates.

The best way to fix this would be updating AutoItLibrary so that it would remove duplicates. I asked about that from @CMTaylor via email, but unfortunately he doesn't have time to work on AutoItLibrary and there apparently is nobody else to maintain it either. It would be great if the library would get a new maintainer that would also move it out from the dying Google Code, but that's not the topic of this issue.

We can also fix this on Robot side by reverting changes in #2097. I don't think that would be a good long term solution because the fix itself was valid. Even if we would revert it in 2.9.2, I would like to add it back in 3.0. If AutoItLibrary isn't maintained, we'll have the same problem then too.

A better way to avoid this problem on Robot side would be making it OK for a library to have two keywords with *exactly* the same name. That simply isn't possible with the static library API (if you have `def kw():` twice, the latter overrides the other already on Python level) and with the hybrid and dynamic APIs the dispatching logic couldn't anyway tell the difference between exact same names. This fix is also trivial.

**Comment by CMTaylor** [comment] 2015-09-17 15:08
Thanks for this investigation into AutoItLibrary, Peke!  It’s a bug. My intention was that the AutoItLibrary methods override any similarly named methods from the wrapped DLL library. I’ll be meeting with my team in Mexico next week and some of them may still use AutoItLibrary.  I’ll see if we can do anything about continued maintenance of it.

Thanks again,
Martin

**Comment by pekkaklarck** [comment] 2015-09-17 15:48
Thanks @CMTaylor for your comment!

Methods defined in AutoItLibrary do override methods defined in AutoIt tool. It's just that the list returned by `get_keyword_names` contains `Run` and some other keywords multiple times. That didn't matter with earlier RF versions because it didn't notice duplicates and the latest created keyword always just overwrote earlier. That didn't matter because all of these versions would end up calling the same method in AutoItLibrary.

This is only a problem in RF 2.9.1 which notices library contains duplicates and considers that an error. I already have a fix implemented that ignores *exact* duplicates because they would anyway always end up being exact same keyword. That fixes the problem with AutoItLibrary and also makes changes caused by #2097 a little less backwards incompatible.

Great news that you try to get a new maintainer for the library. If you cannot find anyone from TI, please ask would anyone on robotframework-users be interested. It's totally understandable that you cannot maintain it forever.

**Closed** 2015-09-17 15:54 UTC
Labels: priority: critical
