### ISSUE TITLE
Run Keyword in library is displayed in the report above other messages

### ISSUE THREAD

**Issue by skhomuti** [robotframework/robotframework#2842] opened 2018-05-21 12:12 UTC
Hello! See example bellow.
![screenshot_7](https://user-images.githubusercontent.com/31664571/40306790-71b3f73c-5d19-11e8-91ff-11657e8251cb.png)

```
from robot.libraries.BuiltIn import BuiltIn


class Library(object):
    def do_something(self):
        BuiltIn().log('One')
        BuiltIn().log('Two')
        BuiltIn().run_keyword('Log', 'Three')
        BuiltIn().log('Four')
```
Here you can see that the third message is displayed higher than the rest. Because of this feature it is unclear at what point in time the call to Run Keyword
Is it possible to fix this? I want the messages to be in order no matter how they were received

**Comment by pekkaklarck** [comment] 2018-05-22 14:17
This is a known issue already reported as #2086. Unfortunately the issue is rather hard to fix and it's unlikely it will be resolved in the near future.

I don't understand why you'd want to use `BuiltIn().run_keyword` or even `BuiltIn().log` for logging. See the Creating test libraries section in the User Guide for much better logging solutions.

**Closed by pekkaklarck** 2018-05-22 14:17 UTC

**Comment by pekkaklarck** [comment] 2018-05-25 08:59
Well, you shouldn't need to use WUKS in a library keyword either because you can easily implement your own error handling and timeouts. Anyway, the underlying issue is valid and that's why we have #2086.
