### ISSUE TITLE
`Format String`: Allow using template strings containing `=` without escaping

### ISSUE THREAD

**Issue by rrajpuro** [robotframework/robotframework#4821] opened 2023-07-15 07:32 UTC
The Format String keyword from BuiltIn String Library needs escaping of equals sign (=). Is this behaviour expected?

_Robot Framework REPL_
```
>>> Format String    [text()="{}"]    TESTING
ERROR Keyword 'String.Format String' got positional argument after named arguments.
>>>
>>> Format String    [text()\="{}"]    TESTING
[text()="TESTING"]
```
_Python REPL_
```
>>> '[text()="{}"]'.format('TESTING')
'[text()="TESTING"]'
>>>
```

**Comment by Snooz82** [comment] 2023-07-16 20:48
The situation here is, that Robot Framework in general interprets any key=value pattern as a named argument, when there are **kwargs present. This is the case with `Format String` 

Example code to reproduce and maybe also an idea for a fix in the future? @pekkaklarck 
[>> Executable Example <<](https://robotframework.org/embed/?codeProject=N4IgdghgtgpiBcIDCBXAzgFwPZQAQGMsATOAGhBLXwCcBLABw1qzARBHIDNaAbGNBAG1Q3PgDlocRBn4YAdNSwAjLBg4hCYGVrYAqfbgDKMDEzABzNLn26AOmAAytJdQjUAnri+4nSufXd7ILAbXAAVWVwkCDR+a317CMxcAHdaDAALXDdLe29cAGkYdxSsaiJcAHV0rIBBakt8+iw0dOZIHgB9ADcIHhQYfNUMmGpO5tamFj78qDKYcZa26Z5vAGtigEYAXl7+mE38jfcAJl2+gZPgpIxUmtx6RSU+KDQ87yKSsorqzNx6xreR7KF7bGAARxQM1oYAeLWyDVSI1h+jWKRyVke-BgWiGmVGi0m7Rm3jm1AWE2WHXWW3O+0ONNOdMu10iaT+AAV4QB5MA8TwAt6wj7FUrlKr3LloXn8-4NKxAp6gtAZLAoHgVMVrbKYlosWXeYYEylTamk+aEqkk3DHHZ7AYMrzHM72mAnEAAX1IIl4MAksDYvn87nUmm0akQnEUeCeqjkEHotFwtCgzWotx4WHM5lGwRInBtou+nXZGU6GIAFBNSNZeq55TXUUXyhiAJTwd5eTPZ0ZyTRoLB8CucWwgCbwXDACYe0etzu4bs56h9lgDocjkC6OsYifAbfymcgOfCrtZpcrsBrmDD0dNr4t+W745iogYw-H-L2fOF+9EEs1Ql9Xcct5SrFoawAekbfdLEbXRn2+NsOxPBcz17ftB2vDdx0nadZ3nRd0NXTCb03GC0F3cj3wItDlww9db3g5tX0fScEIfSxqNYD0AF1yBIOhuhgIgOUUAArGB8AjTg+lichYwwAA1UZWhYNgADY5E2T0gA)


```python
from robot.api import logger

def keyword_with_args(pos, *varargs, **keywordargs):
    logger.console(f"pos: {pos}")
    logger.console(f"*varargs: {varargs}")
    logger.console(f"**keywordargs: {keywordargs}")
    
def keyword_with_posonly_args(pos, /, *varargs, **keywordargs):
    logger.console(f"pos: {pos}")
    logger.console(f"*varargs: {varargs}")
    logger.console(f"**keywordargs: {keywordargs}")
```


```robotframework
*** Settings ***
Library    Lib.py


*** Test Cases ***
Test with args
    Keyword With Args    positional_value    other_positional    more_positional   key1=value1    key2=value2

Test with problems
    Keyword With Args    problem=equal in pos arg when **kwargs present    other_positional    more_positional   key1=value1    key2=value2

Test with Pos Only Args
    Keyword With PosOnly Args    problem=should work as posonly    other_positional    more_positional   key1=value1    key2=value2
```
   
positional only Arguments could be used to automatically match the first given argument as is and not trying to pass it to **keywordargs, because of that =.

This is not how positional only arguments do work right now, but i think it could be a good usecase for them.

Given the two python keywords on top, the following Robot code shows the current use case for positional_only arguments.
```robotframework
Test posonly vs normal positional
    Keyword With PosOnly Args    posonly_value    pos=kwargs_value
    Keyword With Args    pos_value    pos=kwargs_value
```
While the forst keyword works, because the first arg can not be accessed named, in the second keyword call, the argument `pos`, which is positional_or_named, is set twice.
So the python use case for pos_only arguments is, that you can hand over keys/argument_names to a **kwargs, that are already existing in the argument interface.


So the change could be that pos_only args in robot are just taken by their position and not by their name.

This could also solve an issue, that once existed in Browser lib:
```python
def type_text(self, selector, text):
    ...
```

```robotframework
Test
    Type Text    text=Username    admin
```
where `text=Usermane` is a valid playwright selector, it conflicts with the `text` argument

with the new proposed interpretation of pos_only, it would be 
```python
def type_text(self, selector, /, text):
    ...
```
and `text=Username` would just be given to `selector`

**Comment by pekkaklarck** [comment] 2023-07-23 21:42
@Snooz82 is right that this occurs because the keyword accepts `**named` and thus Robot considers all arguments using `=` to be named arguments.

The proposal by @Snooz82 to ignore `=` in positional-only arguments is a good one. If we added that support, then signature of this keyword could be changed to `template, /, *positional, **named` and the issue would be resolved. Could you submit a separate issue about that enhancement? We could then keep this issue open as a reminder to update `Format String`.

**Comment by pekkaklarck** [comment] 2023-12-19 23:53
It seems we forgot about the idea to use positional-only arguments for this usage. I believe it would be pretty useful and we could try doing that in RF 7.1. I assign this issue to its scope and we then need to submit a separate about the actual positional-only enhancement.

**Closed** 2024-06-23 13:54 UTC
Labels: priority: medium, rc 1
