### ISSUE TITLE
Tags(tag_list) != Tags(tag_list)

### ISSUE THREAD

**Issue by stdedos** [robotframework/robotframework#3242] opened 2019-07-18 08:12 UTC
I tried to unit-test a listener manipulating tags here: https://github.com/pytest-dev/pytest/issues/5618#issuecomment-512241787 It seems that compares `robot.model.Tags` is kinda tricky. Is this wanted?

**Comment by pekkaklarck** [comment] 2019-07-22 22:07
I can reproduce this:

```python
>>> from robot.model import Tags
>>> Tags(['x']) == Tags(['x'])
False
```

This definitely isn't correct, but it luckily ought to be pretty easy to add `__eq__` (and `__ne__`) to `Tags`. PR would be appreciated, but because I consider this a bug, I can fix it myself as well after my holidays and once the newparser branch is merged to master.

**Comment by stdedos** [comment] 2019-07-23 08:58
My only objection is that, I don't feel confident enough doing so.

Regarless, here(^^) is a PR to consider.

**Comment by pekkaklarck** [comment] 2019-08-14 09:33
One thing to take into account is that tags in Robot are case-, space- and underscore-insensitive. In other words, `Tags(['X X']) == Tags(['x_x'])` should be true. Also the order of tags shouldn't matter so `Tags(['a', 'b']) == Tags(['b', 'a'])` should be true as well.

An other thing to consider is that should `Tags` get more list methods. I added missing list methods to `ItemList` few days ago (#3261) and I guess same could be done to `Tags` as well. In this case the easiest solution would be using [collections.abc.MutableSequence](https://docs.python.org/3/library/collections.abc.html). I'm not sure is that worth the effort, though.

**Comment by stdedos** [comment] 2019-09-16 08:03
> One thing to take into account is that tags in Robot are case-, space- and underscore-insensitive. In other words, `Tags(['X X']) == Tags(['x_x'])` should be true. Also the order of tags shouldn't matter so `Tags(['a', 'b']) == Tags(['b', 'a'])` should be true as well.

Would it then be acceptable, only for comparison purposes, to normalize everything? (`this.lower().replace('_', ' ') == otherthis.lower().replace('_', ' ')` and `sorted(this) == sorted(other)`)

Or should that be done during init (as it could lower operations per call)?

> An other thing to consider is that should `Tags` get more list methods. I added missing list methods to `ItemList` few days ago (#3261) and I guess same could be done to `Tags` as well. In this case the easiest solution would be using [collections.abc.MutableSequence](https://docs.python.org/3/library/collections.abc.html). I'm not sure is that worth the effort, though.

It seems you have alpha-merged something. Should I retry the patchset? Should I try to implement the normalization above? Do nothing and close?

**Comment by pekkaklarck** [comment] 2019-09-16 08:35
Normalization should be done when comparing. We want to preserver the original format so it cannot be done at `__init__`. I normalization when needed really affects performance, especially when normally there aren't that many tags and comparisons ought to be pretty rare in general.

**Closed** 2019-10-18 09:52 UTC
Labels: bug, good first issue, priority: low
