### ISSUE TITLE
Test libraries  listener _output_file won't get notified 

### ISSUE THREAD

**Issue by lonestep** [robotframework/robotframework#2244] opened 2015-12-01 08:54 UTC
Following the document  <Test libraries as listeners>:
http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#test-libraries-as-listeners

I implemented a simple library with listener '_output_file' and it JUST DON'T WORK:

class SomeLibrary(object):
    ROBOT_LIBRARY_SCOPE = "GLOBAL"
    ROBOT_LIBRARY_VERSION = get_version()
    ROBOT_LISTENER_API_VERSION  = 2

    def __init__(self):
        self.ROBOT_LIBRARY_LISTENER = self

    '''
    Keywords
    '''

    def UserKeyword1(self):
        pass

    def UserKeyword2(self):
        pass

    def UserKeyword3(self):
        pass

    '''
        Listeners
    '''
    def _start_test(self, name, attr):
        print 'test:%s' %(name)

    def _output_file(self,path):
        print(path)

WHILE the '_start_test' keyword works FINE.

Here's my environment:

robotframework: 2.9.2
python:2.7.8
windows:win32

**Comment by pekkaklarck** [comment] 2015-12-01 09:07
IIRC this was by design. Library listeners go out of the scope when the library itself goes out of the scope. This means listener methods not related to execution aren't supported. I doubt that would be easy to change or would it even be a good idea. Need to check is this documented adequately, though.

**Comment by lonestep** [comment] 2015-12-01 09:16
Thanks  pekkaklarck, It would be great if we can update the document to clarify this.

In this case the only way monitoring output_file is  to add '--listener' argument to the pybot command, not Test Library.

**Comment by pekkaklarck** [comment] 2015-12-03 21:49
The docs you referenced seem to already document what methods are called. Here's a direct link:
http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#called-listener-methods

Do you have ideas how to enhance the docs?

**Comment by pekkaklarck** [comment] 2015-12-16 06:57
This is already documented and there hasn't been new activity lately. Closing.

**Closed by pekkaklarck** 2015-12-16 06:57 UTC
