### ISSUE TITLE
"Copy Directory" fails under jybot.

### ISSUE THREAD

**Issue by brianruss** [robotframework/robotframework#1912] opened 2015-02-06 12:22 UTC
Hi.
This is a follow-on from google code issue 1519 (https://code.google.com/p/robotframework/issues/detail?id=1519)  (sorry, I appended there before realising that the project is now active in github)

I am using robot framework 2.8.4 on Windows 7 64-bit
The simple test script is:
```
	Remove Directory  /test/dest-folder  recurse
	Copy Directory  /test/src-folder  /test/dest-folder
```
There is one very small file in /test/src-folder

When the test is executed using pybot, it works every time.
When the test is executed using jybot, the directory copies correctly, but the keyword still provides an error.

The log has the entries:
```
11:10:04.069 	FAIL 	[u'\\test\\src-folder', u'\\test\\dest-folder', "[Errno 5] Input/output error: u'\\\\test\\\\dest-folder'"]
11:10:04.069 	DEBUG 	Traceback (most recent call last): File "C:\tools\jython2.5.3\Lib\site-packages\robotframework-2.8.4-py2.5.egg\robot\libraries\OperatingSystem.py", line 881, in copy_directory source, destination = self._copy_dir(source, destination) File "C:\tools\jython2.5.3\Lib\site-packages\robotframework-2.8.4-py2.5.egg\robot\libraries\OperatingSystem.py", line 897, in _copy_dir shutil.copytree(source, dest) File "C:\tools\jython2.5.3\Lib\shutil.py", line 144, in copytree raise Error, errors
```
Please let me know if I can provide more information.

Thanks,
Brian.

**Comment by pekkaklarck** [comment] 2015-02-09 11:08
Looks weird. Some things you could test:

- Does the keyword work if you include the drive letter in the path like `c:/test/`.
- Does `shutil.copytree` work with your paths on Jython.
- Does the keyword work with Jython 2.7 pre-releases. Beta 4 with some fixes to directory path handling on Windows ought to be released any-day-now.

**Comment by brianruss** [comment] 2015-02-09 13:39
Hi.

Using the drive letter:
```
	Remove Directory  c:/test/dest-folder  recurse
    Copy Directory  c:/test/src-folder  c:/test/dest-folder
```
Still gives an error:

```
u'c:\\test\\src-folder', u'c:\\test\\dest-folder', "[Errno 5] Input/output error: u'c:\\\\test\\\\dest-folder'"
```

Using the shutil.copytree On Jython 2.5.3

```
>>> shutil.copytree("/test/src-folder", "/test/dest-folder")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\tools\jython2.5.3\Lib\shutil.py", line 144, in copytree
    raise Error, errors
shutil.Error: ['/test/src-folder', '/test/dest-folder', "[Errno 5] Input/output error: '/test/dest-folder'"]
>>>
```

But on Jython 2.7b3 - No error.

```
>>> shutil.copytree("/test/src-folder", "/test/dest-folder")
>>>
```

I tried Jython 2.5.4rc1 too, but it still fails.

So I guess that means waiting for a release of 2.7? Do you know what the roadmap for Jython releases are?

Many thanks for your help.

Brian.

**Comment by pekkaklarck** [comment] 2015-02-09 23:06
Great to hear that it works on Jython 2.7 but I'm still surprised it fails with 2.5. We ought to have tests for these keywords and we do run them on Windows. Is your path on a network drive or is there something else that's special?

There is no official roadmap towards Jython 2.7 and because there aren't that many active developers the process is pretty slow. Jython 2.7 beta 4 ought to be ready soon, though, and it should also be pretty mature. I sure hope so because the current plan is for RF 2.9 to drop Python/Jython 2.5 support. We won't do that until that b4 is out and we've tested that is solid, though.

 I'll close this issue because the root cause for the problem is in Jython

**Closed by pekkaklarck** 2015-02-09 23:06 UTC
