### ISSUE TITLE
Suggestion for hiding helper keywords in resources

### ISSUE THREAD

**Issue by sebastianciupinski** [robotframework/robotframework#3176] opened 2019-05-08 10:59 UTC
For now, in libraries, methods which begin from underscore are considered as helpers and are not exposed as keywords. The same approach should be followed for resources, where keywords definitions with underscore shall be accessible only in resource internally and should not be exposed as user keywords (e.g. in IDE, html documentation, libspecs)

**Comment by pekkaklarck** [comment] 2019-05-08 20:11
This is a duplicate of #430. I agree something like this would be awesome but I also know I won't personally have time for this in the near future.

**Closed by pekkaklarck** 2019-05-08 20:11 UTC
