### ISSUE TITLE
TRACE Logging is done in wrong order

### ISSUE THREAD

**Issue by tarand** [robotframework/robotframework#2072] opened 2015-07-27 08:59 UTC
Please look at the following log. As you can see at the very end (where all the trace logging is done), the logs are printed in the wrong order. This makes reading very hard.

KEYWORD: SeleniumTestSupportLib.Expect Text In Table credentialList:dataTable, HTTP Access
Documentation: 	

As there is no "Table Should Not Contain"
Start / End / Elapsed: 	20150727 10:49:10.091 / 20150727 10:49:10.234 / 00:00:00.143
00:00:00.006 KEYWORD: ${xpath} = BuiltIn.Set Variable //table[@id='${tableId}']
00:00:00.035 KEYWORD: selLib.Get Webelements ${xpath}
00:00:00.074 KEYWORD: SeleniumTestSupportLib.Run And Retry Selenium Keyword And Log Only Last Failure selLib.Table Should Contain, loglevel=INFO, ${xpath}, ${text}
Documentation: 	

THIS IS AN INTERNAL KEYWORD OF THIS LIBRARY; DO NOT USE DIRECTLY!
Start / End / Elapsed: 	20150727 10:49:10.157 / 20150727 10:49:10.231 / 00:00:00.074
00:00:00.044 KEYWORD: ${status}, ${retval} = BuiltIn.Run Keyword And Ignore Error Wait Until Keyword Succeeds, ${defaultWaitTimout}, ${defaultWaitRetry}, ${keyword}, loglevel=NONE, @{keywordArgs}
Documentation: 	

Runs the given keyword with the given arguments and ignores possible error.
Start / End / Elapsed: 	20150727 10:49:10.176 / 20150727 10:49:10.220 / 00:00:00.044
00:00:00.027 KEYWORD: BuiltIn.Wait Until Keyword Succeeds ${defaultWaitTimout}, ${defaultWaitRetry}, ${keyword}, loglevel=NONE, @{keywordArgs}
Documentation: 	

Waits until the specified keyword succeeds or the given timeout expires.
Start / End / Elapsed: 	20150727 10:49:10.182 / 20150727 10:49:10.209 / 00:00:00.027
00:00:00.002 KEYWORD: selLib.Table Should Contain loglevel=NONE, @{keywordArgs}
Documentation: 	

Verifies that `expected` can be found somewhere in the table.
Start / End / Elapsed: 	20150727 10:49:10.186 / 20150727 10:49:10.188 / 00:00:00.002
10:49:10.187 	FAIL 	Keyword 'Selenium2Library.Table Should Contain' got positional argument after named arguments. 	
10:49:10.184 	TRACE 	Arguments: [ u'20' | u'1' | u'selLib.Table Should Contain' | u'loglevel=NONE' | u'@{keywordArgs}' ] 	
10:49:10.180 	TRACE 	Arguments: [ u'Wait Until Keyword Succeeds' | u'${defaultWaitTimout}' | u'${defaultWaitRetry}' | u'${keyword}' | u'loglevel=NONE' | u'@{keywordArgs}' ] 	
10:49:10.174 	TRACE 	Arguments: [ ${keyword}=u'selLib.Table Should Contain' | ${logLevelOfLastCall}=u'loglevel=INFO' | @{keywordArgs}=[u"//table[@id='credentialList:dataTable']", u'HTTP Access'] ] 	
10:49:10.105 	TRACE 	Arguments: [ ${tableId}=u'credentialList:dataTable' | ${text}=u'HTTP Access' ]

**Comment by pekkaklarck** [comment] 2015-08-05 09:20
The log you included is not very readable. Could you clarify what is the problem? Also, is this an issue in Robot Framework itself or in Selenium2Library?

**Comment by tarand** [comment] 2015-08-20 06:59
Hi Peke,

sorry that my answer took so long...

It is a robot framework problem. I’m attaching a log (hope you can read it) where Selenium is not used at all.

Ciao,
                Thomas



---------------------------------------------------------------------------------------
Thomas Arand
Tel.  +49 (89) 5159 36328 / +49 (160) 90888023
thomas.arand@nokia.com<mailto:thomas.arand@nsn.com>

Nokia Solutions and Networks Deutschland GmbH

**Comment by pekkaklarck** [comment] 2015-08-20 10:46
No, I don't see any log anywhere. Notice that you are replying to a comment from GitHub issue tracker and you cannot even attach anything to these issues.

**Comment by pekkaklarck** [comment] 2015-08-20 10:49
Is this possibly the same problem as #2086?

**Comment by tarand** [comment] 2015-08-20 11:10
How can I pass the logs to you?

---------------------------------------------------------------------------------------
Thomas Arand
Tel.  +49 (89) 5159 36328 / +49 (160) 90888023
thomas.arand@nokia.com<mailto:thomas.arand@nsn.com>

Nokia Solutions and Networks Deutschland GmbH

**Comment by tarand** [comment] 2015-08-21 11:30
I guess so!

Thomas

---------------------------------------------------------------------------------------
Thomas Arand
Tel.  +49 (89) 5159 36328 / +49 (160) 90888023
thomas.arand@nokia.com<mailto:thomas.arand@nsn.com>

Nokia Solutions and Networks Deutschland GmbH

**Comment by pekkaklarck** [comment] 2015-08-21 12:44
OK, closing as a dupe of #2086. I've already added it into RF 3.0 scope, but it may turn out to be too big a task.

**Closed by pekkaklarck** 2015-08-21 12:44 UTC
