### ISSUE TITLE
Regression with Python 3.5+ when keyword is decorated and decorator uses `functools.wraps`

### ISSUE THREAD

**Issue by rainmanwy** [robotframework/robotframework#3024] opened 2018-12-11 08:07 UTC
After upgrade RF to 3.1, i got many "Add keyword" error report,
like 

>  Adding keyword 'keyword1' to library 'MyClass' failed: Type information given to non-existing argument 

I found it is related with my own decoractor. And it could be re-produced with below code:
```
import functools


def trace(func=None):
    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        return func(*args, **kwargs)
    return wrapper

class MyClass():

    @trace
    def my_test(self, p1: str):
        print(p1)
```

And test case:
```
*** Settings ***
Library   MyClass

*** Test Cases ***
Test 1
    My Test     1
```

if i remove the type-hint in python code, no error report!

Could you @pekkaklarck help to check this problem?

**Comment by rainmanwy** [comment] 2018-12-12 06:41
Whether could use "__wrapped__" attribute to check "keyword" is wrapped, and RF could skip “type validate” in "TypeValidator"  
robot.running.arguments.typevalidator.TypeValidator#validate_type_dict

**Comment by pekkaklarck** [comment] 2018-12-13 10:36
The problem is caused by type information validation that tries to avoid issue with the `@keyword` decorator like

```python
@keyword(types={'ooop': int})
def keyword(arg):
    pass
```

When implementing this validation, it didn't occur to me that decorators can mask arguments so that type information got via annotations can be "wrong" as well. This is easy to fix by either removing the validation altogether or at least when types are got from annotations.

Looking for [__wrapped__](https://docs.python.org/3/library/functools.html#functools.update_wrapper) to see the original function and to be able to get real argument information is a great idea as well. That wouldn't fix this particular problem fully, though, because not all decorators set `__wrapped__` and even `functools.wraps` doesn't do that in Python 2. It would, however, solve lot of problems with decorators that actually set it (incl. `functools.wraps` in Python 3) and would be a great enhancement. Can you @rainmanwy submit a separate issue about that?

**Comment by rainmanwy** [comment] 2018-12-14 01:39
@pekkaklarck , thank you very much!
I have created issue #3027 for that.

**Comment by pekkaklarck** [comment] 2018-12-28 11:35
This issue only occurs in these circumstances:

1. Using decorator that uses `functools.wraps` that adds `__annotations__` to the wrapper function (or by adding that attribute manually).

2. Using Python 3.5+ where we by default use `typing.get_type_hints` to get type information. It returns information as-is, while `inspect` module that we use with Python < 3.5 (or if `typing.get_type_hints` fails) automatically removes mismatching annotations.

Anyway, I got a fix ready to be committed. The plan is to create RF 3.1.1 rc 1 with this and some other fixes on Monday.

**Closed** 2018-12-28 11:37 UTC
Labels: priority: high
