### ISSUE TITLE
Dialogs: Return-Key should perform a click on left button (OK)

### ISSUE THREAD

**Issue by MisterChild** [robotframework/robotframework#2239] opened 2015-11-26 14:08 UTC
Hi,

as Escape key selects "Cancel" button in user interaction windows, it would be nice if Return key selects "OK".

Works for me by adding line:

        self.bind("<Return>", self._left_button_clicked)

to _initialize_dialog(self)   in file dialogs_py.py

Maybe this is useful for others and could be implemented?

Thank you.

**Comment by jussimalinen** [comment] 2015-11-27 10:07
Could you tell a bit more on what platform does this happen? I tried on Python 2.7 on OSX and Windows 7 and on both platform on all Dialogs (`Execute Manual Step`, `Get Selection From User`, `Get Value From User`) enter key does nothing. If I press tab then the focus moves to first button (ok, pass) and then enter does push that button.

**Comment by MisterChild** [comment] 2015-11-27 12:37
System is Xubuntu. Python 2.7.6.
Is Escape key working for cancelling an user interaction? 

Complete function from dialogs_py.py:

    def _initialize_dialog(self):
        self.title('Robot Framework')
        self.grab_set()
        self.protocol("WM_DELETE_WINDOW", self._right_button_clicked)
        self.bind("<Escape>", self._right_button_clicked)
        self.bind("<Return>", self._left_button_clicked)
        self.minsize(250, 80)
        self.geometry("+%d+%d" % self._get_center_location())
        self._bring_to_front()

Sorry, I didn't test this on other systems.

**Comment by jussimalinen** [comment] 2015-11-27 12:48
Weird. @pekkaklarck just tired on Mint, Python 2.7 and Enter does nothing there either. Escape does work as cancel everywhere.

Anyway, I guess having enter bind on "OK" by default could be handy. We can do this later when we have time, or if you are interested in getting this into a new release as soon as possible, you could create a pull request with an acceptance test. (There is an acceptance test for the escape cancelling.)

**Comment by pekkaklarck** [comment] 2015-12-16 07:29
I played with this and was able to reproduce the issue and tested that that binding return to `_left_button_clicked` changed the behavior. I don't think making the change is actually a good idea, though. With the changed behavior it was possible to do this:

1. Open PASS/FAIL dialog.
2. Set focus to FAIL by using tab.
3. Hit enter to press the button.
=> PASS pressed because enter is hard-coded to always press it.

I know I could press space instead, but that is definitely not obvious for a normal user.

While investigating this, I noticed that the current esc behavior isn't that good either. With the PASS/FAIL dialog it is considered same as pressing FAIL although it should just close the dialog. I submitted #2267 about that.

I close this issue because I think binding enter to the left button isn't a good idea. If we want to add shortcuts for pressing buttons, we could, for example, bind O to OK, C to Cancel, P to PASS and F to FAIL. That requires a separate issue, though, preferably backed by a pull request.

**Closed by pekkaklarck** 2015-12-16 07:29 UTC

**Comment by pekkaklarck** [comment] 2015-12-16 09:01
Apparently with Jython pressing enter always presses the left button. I couldn't find a way to avoid that easily and don't want to spend more time fore it. I still think that is bad idea and don't want other implementations to behave same way.
