### ISSUE TITLE
version7.1.1，Create Session    test    ${BASE_URL}    proxies={proxy}，the argument ‘proxies’ do not work

### ISSUE THREAD

**Issue by littleshao** [robotframework/robotframework#5253] opened 2024-11-04 02:03 UTC
version7.1.1，Create Session    test    ${BASE_URL}    proxies={proxy}，the argument ‘proxies’ do not work，
but  set up the proxy in the system,  this ‘Create Session ’ is work.

**Comment by pekkaklarck** [comment] 2024-11-05 15:29
Robot Framework itself doesn't have a `Create Session` keyword so if the problem is in the keyword itself, you have submitted this issue to a wrong issue tracker. If the keyword fails with Robot Framework 7.1.1 but works with earlier versions, then the problem could be in Robot. In that case please give some more information about the library you use, how it fails, what version it works with, and so on. Creating a simple example we could use ourselves to reproduce the issue would be helpful as well.

**Comment by littleshao** [comment] 2024-11-06 03:04
wo ，sorry，Create Session is the keyword of robotframework-requests

**Comment by pekkaklarck** [comment] 2024-11-06 09:04
That alone doesn't help much. Please read my previous message and provide also other requested information. Most importantly, we need to know does this keyword work when using older Robot versions.

**Comment by littleshao** [comment] 2024-11-06 09:20
the version like this image，Create Session is the keyword of robotframework-requests。my usage is  ：Create Session  base_session ${url}  proxies={proxy}   ------ it  does not  work，but set up the proxy in the system, this ‘Create Session base_session ${url} ’ is work
![微信图片_20241106171540](https://github.com/user-attachments/assets/099cdea7-4444-470e-b935-ce85a55e0525)
![微信图片_20241106171553](https://github.com/user-attachments/assets/2c5942da-04b4-47c2-8fc2-2a8eebbb80db)

**Comment by pekkaklarck** [comment] 2024-11-13 13:18
I cannot help you with Create Session and this is a wrong issue tracker for ReqeustLibrary related issues in general. If the keyword would work fine when using older Robot Framework versions but wouldn't work anymore in RF 7.1.1, then there could have been a regression in Robot itself that should be fixed. It seems to me you have some other problem and thus I close this issue.

If you are just looking for help, please use our Slack or Forum. Both are linked from https://robotframework.org.

**Closed by pekkaklarck** 2024-11-13 13:18 UTC
