### ISSUE TITLE
Call of a function of parent class doesn't work when the class object is passed as an embedded argument.

### ISSUE THREAD

**Issue by JohnCharitoudis** [robotframework/robotframework#2578] opened 2017-04-12 11:25 UTC
I've noticed that built-in "Call Method" doesn't work when the class instance is passed as an embedded argument. Let's assume the following Python library:

```
def newchildClass():
    return childClass()
    
class parentClass(object):
    
    def __init__(self):
        pass
    
    def myFunction(self):
        print "Success"

class childClass(parentClass):
    
    def __init__(self):
        super(childClass, self).__init__()
```

and the following Test:
```

*** Settings ***
Library          myPythonModule.py

*** Keywords ***

Create Child Class
	${object} =    newchildClass
	[Return]    ${object}
	
Call Function
    [Arguments]    ${class}
    Call Method    ${class}    myFunction
    
Call Function from ${class}
    Call Method    ${class}    myFunction
    
*** Test Cases ***

My Test
    ${instance} =  Create Child Class
    Run Keyword And Continue On Failure  Call Function  ${instance}         # will succeed
    Run Keyword And Continue On Failure  Call Function from ${instance}  # will fail
```

The use of the KW '_Call Function from ${class}_' that takes the class object as an embedded fails with:

```
==============================================================================
myRobotTestCase                                                               
==============================================================================
My Test                                                               | FAIL |
Object '<myPythonModule.childClass object at 0x136ba50>' does not have method 'myFunction'.
------------------------------------------------------------------------------
myRobotTestCase                                                       | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
```
*Tested in Robot Framework 3.0 (Python 2.7.5 on linux2)*

Is this valid? Shouldn't '_Call Function from ${class}_' work just like the '_Call Function_' KW?

I'm attaching (*remove the .txt extension) output files from the respective reproduction of this issue.

[log.html.txt](https://github.com/robotframework/robotframework/files/916312/log.html.txt)

**Comment by pekkaklarck** [comment] 2017-04-12 11:30
This seems to be a duplicate of #1595. Unfortunately complicated to fix.

**Closed by pekkaklarck** 2017-04-12 11:30 UTC

**Comment by JohnCharitoudis** [comment] 2017-04-12 12:13
Thanks for the prompt response!
