### ISSUE TITLE
Listeners are not unregistered when using `TestSuite.run` API

### ISSUE THREAD

**Issue by WojtekKowaluk** [robotframework/robotframework#1992] opened 2015-05-13 10:25 UTC
let _a_ and _b_ be instances of TestSuite.
If i run `a.run(listeners='listener.py')` and then after i run `b.run()` then listener will still be used during execution of TestSuite _b_.

**Comment by WojtekKowaluk** [comment] 2015-05-13 10:38
Seems this fixes the problem:
https://github.com/robotframework/robotframework/pull/1993

**Comment by pekkaklarck** [comment] 2015-05-13 16:47
Have you tested does this happen also with `robot.run` API or only with `TestSuite.run`?

**Comment by WojtekKowaluk** [comment] 2015-05-13 18:13
I will check that.

**Comment by WojtekKowaluk** [comment] 2015-05-13 18:48
I have tried and this does not happen with `robot.run`.

**Comment by pekkaklarck** [comment] 2015-05-13 18:59
Interesting. Have you analyzed why not?

**Comment by WojtekKowaluk** [comment] 2015-05-14 21:36
So far i was not able to figure that out.

**Comment by WojtekKowaluk** [comment] 2015-05-21 19:20
I found the reason.
When I call `robot.run`, `execute' method use `_logging` contextmanager. This manager calls `close` method on listener object. This method clears `self._loggers` in logger object. When using `TestSuite.run` non of that is called.
Anyway I think I am on the track with my fix to unregister listeners in `close` method for output object. Let me know what do you think.

**Comment by pekkaklarck** [comment] 2015-05-21 19:27
Great that you found the root cause! Your fix sounds good too. It would great if you could create a PR with unit tests and your fix. I can then review it and look at the related code too.

**Comment by WojtekKowaluk** [comment] 2015-05-21 19:46
It is already done: https://github.com/robotframework/robotframework/pull/1993
Or do you mean we need something more?

**Comment by pekkaklarck** [comment] 2015-05-21 19:49
Sorry, forgot about that. Hopefully I have time to look at it and some other PRs tomorrow.

**Comment by pekkaklarck** [comment] 2015-06-02 11:34
PR #1993 was merged in 0886b61. This issue can be considered done. Thanks @WojtekKowaluk!!

**Closed by pekkaklarck** 2015-06-02 11:34 UTC
Labels: priority: medium, alpha 2

**Comment by pekkaklarck** [comment] 2015-06-02 22:03
Unfortunately the fix in PR #1993 broke listener interface slightly. Now that listeners are closed already after execution has ended, they do not get notification when log and report are created. There are tests that catch this error but unfortunately our CI has been down lately and the PR wasn't automatically tested.

Good news is that I have a new fix that looks promising. The idea is to use `LOGGER` as a context manager so that it can be nested, and automatically call `LOGGER.close()` when the context manager on top exits.

**Comment by WojtekKowaluk** [comment] 2015-06-02 22:13
I'm sorry to hear that. :(

**Comment by pekkaklarck** [comment] 2015-06-02 22:15
No worries. This definitely wasn't easy to spot from the code. Obviously it would have been a good idea for you to run all tests on your machine too, but the real problem was that CI was down. Anyway, all tests are now passing on my machine.

**Comment by pekkaklarck** [comment] 2015-06-02 22:18
Fixed by a4c4ae1.
