### ISSUE TITLE
Pymyql Error 

### ISSUE THREAD

**Issue by alisterdarrel** [robotframework/robotframework#2550] opened 2017-02-23 01:34 UTC
[ ERROR ] Error in test library 'pymysql': Creating keyword 'Connect' failed: Keyword with same name defined multiple times.

Some error is there in pymyql, i am using robot framework 3

**Comment by wodeta33** [comment] 2017-03-10 10:11
Yes, i also have this problem.

**Comment by pekkaklarck** [comment] 2017-03-13 11:11
It would be good to provide a little more information when submitting a bug report. First of all, what is `pymysql`? Secondly, does this happen also with older Robot Framework versions?

Based on the error message, this could be caused by #2097. If that's the case, then this `pymysql` itself needs to be updated. If it's a Robot Framework library, that ought to be easy. If it's just a Python module that you try to use as a library, then you need to create a library that uses the module.

**Comment by wodeta33** [comment] 2017-03-14 02:13
It doesn't happen in robot framework 2.8

**Comment by pekkaklarck** [comment] 2018-04-23 21:58
No new information provided so here's my guess what's happening:

- pymysql is a this pure Python MySQL client: https://github.com/PyMySQL/PyMySQL
- Some users have been using it directly as a library
- It has multiple methods that end up creating same keyword which causes errors after #2097

If my guesses are correct, the fix for this problem is creating a dedicate Robot library that exposes functionality provided by pymysql instead of using it directly as library. If pymysql happens to be a library in this context, then it just needs to be updated. Anyway, the problem seems to be in pymysql.

**Closed by pekkaklarck** 2018-04-23 21:58 UTC
