### ISSUE TITLE
SSH connection on remote machine using robot framework: Channel Exception;(4,Resource Shortage")

### ISSUE THREAD

**Issue by purple3188** [robotframework/robotframework#2565] opened 2017-03-27 19:30 UTC
I am trying to establish an SSH connection to a remote machine using robot framework and execute some commands. But I get an error saying ChannelException:(4,'Resource shortage').

```
Script: test.robot
*** Settings ***
Library    SSHLibrary
Suite Setup    open_connection_and_login
Suite Teardown    Close All Connections

*** Variables ***
${HOST}    login
${USERNAME}    root
${PASSWORD}    password

*** Test Cases ***
available_disk_on_remote
    ${output}=    Execute Command  df -h
    Log To Console    "${output}"

*** Keywords ***
open_connection_and_login
    Open Connection    ${HOST}
    Login  ${USERNAME}    ${PASSWORD}   4
```

Output:
[root@machine1 Robot]# robot test.robot

Test
======================================================================
available_disk_on_remote                                             | FAIL |
ChannelException: (4, 'Resource shortage')
--------------------------------------------------------------------------
Test                                                                 | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
=========================================================================
Output:  /root/Robot/output.xml
Log:     /root/Robot/log.html
Report:  /root/Robot/report.html

Python 2.7.5 and Robot Framework 3.0.2 (FYI, new to Robot Framework)

**Comment by chriscallan** [comment] 2017-03-27 20:30
have you tried providing the named argument name along with the '4'?  e.g.: 
Login   ${USERNAME}   ${PASSWORD}   delay=4

**Comment by chriscallan** [comment] 2017-03-27 20:43
Unable to repro in my system with a copy-n-pasted version of the above.  Had to fix the spacing and syntax for my version of RF (3.0.1), maybe the devil is in the details?

*** Settings ***
Library     SSHLibrary
Suite Setup     open_connection_and_login
Suite Teardown  Close All Connections

*** Variables ***
${HOST} =    myHostName
${USERNAME} =   root
${PASSWORD} =   rootish

*** Test Cases ***
available_disk_on_remote
    ${output}=  Execute Command     df -h
    Log     ${output}

*** Keywords ***
open_connection_and_login
    Open Connection     ${HOST}
    Login   ${USERNAME}     ${PASSWORD}     delay=4

What version of RF are you running?

**Comment by purple3188** [comment] 2017-03-27 23:38
@chriscallan - I am running 
```

[root@nfv-git paramiko]# pip freeze | grep robot
robotframework==3.0.2
robotframework-sshlibrary==2.1.3
[root@nfv-git paramiko]# pip freeze | grep paramiko
paramiko==2.1.2
[root@nfv-git paramiko]# pip freeze | grep cryptography
cryptography==1.8.1
```


**Debug Log**

```

<var>${output}</var>
</assign>
<msg timestamp="20170327 19:37:27.150" level="INFO">Executing command 'date'.</msg>
<msg timestamp="20170327 19:37:27.151" level="DEBUG">[chan 1] Max packet in: 32768 bytes</msg>
<msg timestamp="20170327 19:37:27.653" level="FAIL">ChannelException: (4, 'Resource shortage')</msg>
<msg timestamp="20170327 19:37:27.653" level="DEBUG">Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/SSHLibrary/library.py", line 881, in execute_command
    stdout, stderr, rc = self.current.execute_command(command)
  File "/usr/lib/python2.7/site-packages/SSHLibrary/abstractclient.py", line 225, in execute_command
    self.start_command(command)
  File "/usr/lib/python2.7/site-packages/SSHLibrary/abstractclient.py", line 243, in start_command
    self._started_commands.append(self._start_command(command))
  File "/usr/lib/python2.7/site-packages/SSHLibrary/pythonclient.py", line 86, in _start_command
    new_shell = transport.open_session()
  File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 707, in open_session
    timeout=timeout)
  File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 839, in open_channel
    raise e</msg>
<status status="FAIL" endtime="20170327 19:37:27.653" starttime="20170327 19:37:27.150"></status>
</kw>
<status status="FAIL" endtime="20170327 19:37:27.654" critical="yes" starttime="20170327 19:37:27.149">ChannelException: (4, 'Resource shortage')</status>
</test>
<kw type="teardown" name="Close All Connections" library="SSHLibrary">
<doc>Closes all open connections.</doc>

```

**# The device I am running actually is more like a cisco device. This device runs with custom framework for SSH.**

**Comment by chriscallan** [comment] 2017-03-28 12:47
This link points to some oddities in the way Cisco devices can work with ssh connections, http://git.net/ml/python-paramiko/2010-06/msg00012.html, not necessarily the issue here but does punctuate that Cisco's custom implementation has its own quirks that need to be worked around.
Is it possible to make a connection using just Python/Paramiko, so that the RF portion of things can be eliminated from the equation?

**Comment by purple3188** [comment] 2017-03-30 15:17
```
import paramiko
ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh.connect('myHostName',username='root',password='rootish',look_for_keys=False, timeout=60)
stdin, stdout, stderr = ssh.exec_command("show version")
```

**Failure**
```
>>> stdin, stdout, stderr = ssh.exec_command("show version")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/paramiko/client.py", line 436, in exec_command
    chan = self._transport.open_session(timeout=timeout)
  File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 707, in open_session
    timeout=timeout)
  File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 791, in open_channel
    raise SSHException('SSH session not active')
paramiko.ssh_exception.SSHException: SSH session not active
```

**Comment by chriscallan** [comment] 2017-03-30 15:49
Alright, so it looks like the issue is with the underlying libraries and their connection to this Cisco device with a custom SSH implementation rather than something to do with RF.  I tried your code against my base Ubuntu and had no issue.
My best guess at the issue here would be that the Cisco device has implemented their SSH in a way that it is incompatible with the paramiko library in some way.  I did see a couple of comments during my searches that said that setting up a channel object after establishing the connection was necessary in order to keep the ssh connection open.  E.g.: 
...
ssh.connect(...)
channel = ssh.invoke_shell()
...

Not sure if that will help in this instance, but it's worth a shot.

**Comment by purple3188** [comment] 2017-03-30 17:46
_**Script with Changes**_

```
import paramiko
ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh.connect('myHostName',username='root',password='rootish',look_for_keys=False, timeout=60)
**channel = ssh.invoke_shell()**
stdin, stdout, stderr = ssh.exec_command("show version")
```
**_Execution_**
```
[root@pytest ~]# python
Python 2.7.5 (default, Sep  5 2016, 02:30:38)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-9)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import paramiko
>>> ssh = paramiko.SSHClient()
>>> ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
>>> ssh.connect('myHostName',username='root',password='rootish',look_for_keys=False, timeout=60)
>>> channel = ssh.invoke_shell()
>>> stdin, stdout, stderr = ssh.exec_command("show version")
No handlers could be found for logger "paramiko.transport"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/paramiko/client.py", line 436, in exec_command
    chan = self._transport.open_session(timeout=timeout)
  File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 707, in open_session
    timeout=timeout)
  File "/usr/lib/python2.7/site-packages/paramiko/transport.py", line 839, in open_channel
    raise e
**paramiko.ssh_exception.ChannelException: (4, 'Resource shortage')**
```

**Comment by pekkaklarck** [comment] 2017-03-31 12:01
This is not related to Robot Framework core. Closing.

**Closed by pekkaklarck** 2017-03-31 12:01 UTC
