### ISSUE TITLE
robot --dryrun does not detect bad separation between arguments

### ISSUE THREAD

**Issue by Gadzy** [robotframework/robotframework#4448] opened 2022-08-31 08:23 UTC
The following error is detected by VS Code Intellisense but not when running `robot --dryrun`.

![image](https://user-images.githubusercontent.com/6734772/187629302-ae319b9d-d998-4d24-9a30-94382dc4f6ce.png)

VS Code expects 4 spaces after keyword `Click Element` whereas only 1 follows keyword.

Is this expected behavior ?

We're looking for a way to enforce this check this within our CI. [`robocop`](https://github.com/MarketSquare/robotframework-robocop) [can't detect this indentation](https://github.com/MarketSquare/robotframework-robocop/issues/688) error either. Any ideas ?

**Comment by Lucas-C** [comment] 2022-08-31 09:34
As a side note, `robot --dry-run` does not detect errors like "Multiple keywords with name XXX found" either:
https://github.com/MarketSquare/robotframework-robocop/issues/687

**Comment by pekkaklarck** [comment] 2022-08-31 13:07
Dry-run doesn't care about indentation or other formatting as long as the data is syntactically valid. The reported problem isn't really about indentation, as the title says, but instead there isn't a proper separator between a keyword and its argument. That's certainly something that dry-run ought to detect and report something like "No keyword with name ... found.". Are you certain that running the data with `--dryrun` succeeds? If yes, please create a simple example demonstrating that.

Dry-run should also detect the problem if there are multiple keywords. If such an error isn't detected, please create an example I can try locally for that as well.

**Comment by pekkaklarck** [comment] 2022-09-16 08:34
No updates in over two weeks. Closing

**Closed by pekkaklarck** 2022-09-16 08:34 UTC

**Comment by Lucas-C** [comment] 2022-09-20 18:45
> Dry-run should also detect the problem if there are multiple keywords. If such an error isn't detected, please create an example I can try locally for that as well.

I confirm that I could not reproduce the issue: in each example I tried to create `--dryrun` detected the issue
