### ISSUE TITLE
Officially remove support for using using colon (`:`) in Settings section

### ISSUE THREAD

**Issue by mathze** [robotframework/robotframework#3991] opened 2021-05-29 08:13 UTC
As of the [documentation](https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#id449)
> All setting names can optionally include a colon at the end, for example _Documentation:_.
Having a robot suite file as
``` Robot
*** Settings ***
Documentation:    Here we have documentation for this suite.
...               Documentation is often quite long.
...
...               It can also contain multiple paragraphs.
Resource:         ${execDir}/CommonResource.resource
Force Tags:       MyTag
Library:          myLibarary
```
and executing
``` shell
python -m robot .\Test.robot
```
rais the following errors:
```
[ ERROR ] Error in file '<...>\Test.robot' on line 2: Non-existing setting 'Documentation:'. Did you mean:
    Documentation
[ ERROR ] Error in file '<...>\Test.robot' on line 6: Non-existing setting 'Resource:'. Did you mean:
    Resource
[ ERROR ] Error in file '<...>\Test.robot' on line 7: Non-existing setting 'Force Tags:'. Did you mean:
    Force Tags
[ ERROR ] Error in file '<...>\Test.robot' on line 8: Non-existing setting 'Library:'. Did you mean:
    Library
```
This also affects `testdoc` command so that, for example, the suites documentation is not included in html.

Version-Infos:
Robotframework: 4.0.1 and 4.0.3
OS: Windows 10 Version 20H2 (Build 19042.1023)
Python: 3.9.4

**Comment by pekkaklarck** [comment] 2021-05-30 19:13
I can reproduce the bug and it seems it was introduced already in RF 3.2 that was released in April 2020. Most likely it was caused by the parser rewrite what also affected all settings. Surprising we didn't have any tests that would have caught it. Even more surprising that nobody has noticed or at least reported it earlier.

Because there's a simple workaround to use settings without colons, and because nobody has reported this in over a year, I don't consider this severe enough to warrant another RF 4.0.x bug fix release. This could easily be fixed in RF 4.1, but I'm not certain is that a good idea. Based on nobody reporting this earlier, this functionality doesn't seem to be too widely used and we could consider it removed and just update documentation instead. Did you @mathze encounter this problem when upgrading RF or did you just spot the documentation explaining this functionality and decided to test it?

**Comment by mathze** [comment] 2021-05-30 19:28
@pekkaklarck I agree to the 'unused' part 😄 
How I detected it was, by writing a Parser for a IDE plugin. So more by accident 😋 I my self also don't used the colon.

**Comment by pekkaklarck** [comment] 2021-05-30 19:33
Sounds like we can considering this feature gone. I'll update the title and leave this open for a while to see does anyone complain. If not, we'll just update the docs in RF 4.1.

**Closed** 2021-06-07 10:15 UTC
Labels: enhancement, priority: low
