### ISSUE TITLE
Support tokenizing strings with variables

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#3449] opened 2020-02-03 13:51 UTC
The new parser (#3076) can tokenize test data to tokens but it doesn't detect variables that are used, for example, in keyword arguments. For example, something like

    Keyword    arg with ${var}

just produces a `KEYWORD` token with value `Keyword` and an `ARGUMENT` token with value `arg with ${var}`. We should have a way to split the later token to strings and variables. We already have `robot.variables.VariableIterator`, but it has a bit strange API and it isn't part of the public API.

**Comment by pekkaklarck** [comment] 2020-02-03 14:03
Possible solutions:

1. Add a function to the `robot.api` package to split a string to literal strings and variables. Could simply return a list (or a generator) of values.

2. Add a new method (or property) to the `Token` class to yield new tokens based on the original token value. For example, if we had an `ARGUMENT` with value `arg with ${var}`, we could do something like `token.tokenize_variables()` and a `STRING` token with value `arg with ` and a `VARIABLE` token with value `${var}`. This new method could be used regardless are tokens got via `get_tokens` or `get_model`.

3. Add a new argument like `tokenize_variables=False` to the `get_tokens` method to control should variables be tokenized or not. This probably wouldn't be that useful alone but could be implemented easily if the option 2. is implemented.

**Comment by pekkaklarck** [comment] 2020-02-03 14:04
Ping @fabioz.

**Comment by fabioz** [comment] 2020-02-03 14:54
I think having it in the token can be a bit weird since those variables aren't really applicable to all the tokens.

Given that, I think a separate api in `robot.api` would be fine, but then, I'd like a way to identify to which tokens it makes sense to try to tokenize in that way (i.e.: which tokens may have variables). 

Or maybe be able to generate custom tokens with a subclass to have a `tokenize_variables` available and do option 2. (but I'm not sure if that's worth it).

**Comment by pekkaklarck** [comment] 2020-02-03 21:43
Yeah, `Token.tokenize_variables` would have a problem that it's not applicable with all token types. We could easily make it an error to call it with invalid token types, though. I think it ought to work only with the `ARGUMENT` type and we could raise `TypeError` with others.

**Comment by pekkaklarck** [comment] 2020-02-06 13:01
Here's my proposed solution as a diff to make it more concrete. First changes to the `Token` class:

```diff
--- a/src/robot/parsing/lexer/tokens.py
+++ b/src/robot/parsing/lexer/tokens.py
@@ -14,6 +14,7 @@
 #  limitations under the License.
 
 from robot.utils import py2to3
+from robot.variables import VariableIterator
 
 
 @py2to3
@@ -116,6 +117,19 @@ class Token(object):
             return -1
         return self.col_offset + len(self.value)
 
+    def tokenize_variables(self):
+        if self.type != Token.ARGUMENT:
+            raise TypeError('Only argument tokens can contain variables.')
+        lineno = self.lineno
+        col_offset = self.col_offset
+        remaining = self.value
+        for before, match, remaining in VariableIterator(self.value):
+            yield Token(Token.ARGUMENT, before, lineno, col_offset)
+            col_offset += len(before)
+            yield Token(Token.VARIABLE, match, lineno, col_offset)
+            col_offset += len(match)
+        yield Token(Token.ARGUMENT, remaining, lineno, col_offset)
+
     def __unicode__(self):
         return self.value
```

Here's how `get_tokens` could be enhanced:

```diff
--- a/src/robot/parsing/lexer/readers.py
+++ b/src/robot/parsing/lexer/readers.py
@@ -24,7 +24,7 @@ from .splitter import Splitter
 from .tokens import EOS, Token
 
 
-def get_tokens(source, data_only=False):
+def get_tokens(source, data_only=False, tokenize_variables=False):
     """Parses the given source to tokens.
 
     :param source: The source where to read the data. Can be a path to
@@ -40,10 +40,13 @@ def get_tokens(source, data_only=False):
     """
     reader = TestCaseFileReader(data_only)
     reader.input(source)
-    return reader.get_tokens()
+    tokens = reader.get_tokens()
+    if tokenize_variables:
+        tokens = _tokenize_variables(tokens)
+    return tokens
 
 
-def get_resource_tokens(source, data_only=False):
+def get_resource_tokens(source, data_only=False, tokenize_variables=False):
     """Parses the given source to resource file tokens.
 
     Otherwise same as :func:`get_tokens` but the source is considered to be
@@ -51,7 +54,20 @@ def get_resource_tokens(source, data_only=False):
     """
     reader = ResourceFileReader(data_only)
     reader.input(source)
-    return reader.get_tokens()
+    tokens = reader.get_tokens()
+    if tokenize_variables:
+        tokens = _tokenize_variables(tokens)
+    return tokens
+
+
+def _tokenize_variables(tokens):
+    argument_type = Token.ARGUMENT
+    for token in tokens:
+        if token.type == argument_type:
+            for t in token.tokenize_variables():
+                yield t
+        else:
+            yield token
 ```

Pretty simple and straightforward. If this would be enough for LSP, I could write some tests and commit changes.

**Comment by pekkaklarck** [comment] 2020-02-09 17:14
Tokenizing settings has been changed as part of #3458 so that some setting values have `NAME` type. Also these values can contain variables, so the code above would need to be adjusted a bit.

**Comment by boakley** [comment] 2020-02-21 23:38
I haven't looked at the code very closely, so take my comments with a grain of salt.

When I first encountered this, my instinct was to see if the token had an attribute that was perhaps itself a list of tokens (eg: token.subtokens). Would something like that be possible?

**Comment by pekkaklarck** [comment] 2020-02-21 23:47
How would that be different from what I proposed above? Robot itself doesn't need this info during parsing, so this would need to be a method in the Token class anyway.

**Comment by boakley** [comment] 2020-02-22 00:14
One way it's different is that it could be used for more than just variables as a way to provide more detailed information for a given token. 

With your method, I have to decide up front whether I want this extra level of information or not. That's not a big deal, but having to choose means I get different tokens depending on my choice which make it hard to create a general purpose library that works with a stream of tokens -- it would need to know whether the stream was generated with or without `tokenize_variables` set to True. With something like I'm suggesting you will always get an ARGUMENT token for an argument, but the additional information is available if you need it.

Part of the problem I'm seeing is that some tokens are overly general, and some seem oddly specific. For example, "ARGUMENT" could mean a string, or a variable, or a combination. It could even mean a keyword (I'm guessing, I haven't tried the lexer on code that calls 'run keyword'). Some are too specific - DOCUMENTATION, SETUP, TAGS are really all the same thing - a setting. Likewise, all of the various headers are pretty much the same from the perspective of a tokenizer. 

So, for a token type of ARGUMENT, `token.subbokens` might return (STRING, VARIABLE) or something like that. A token of type SETTING could have `token.subtokens` return DOCUMENTATION or SETUP. A token type of HEADER could have `token.subtokens` return TESTCASE_HEADER or KEYWORD_HEADER, etc. 

This would allow nice broad categories of token (HEADER, SETTING, ARGUMENT) while giving more detail for those applications that need to distinguish them.

**Comment by pekkaklarck** [comment] 2020-02-22 17:25
I don't understand why something like this would be useful but can tell two things:
- Current token types are needed by the parsee.
- I'm not going to make big changes to the lexer at this point.

**Comment by boakley** [comment] 2020-02-22 19:24
> I don't understand why something like this would be useful

My immediate need is syntax highlighting. I want to know if a token is a variable or not. If both ARGUMENT and ASSIGNMENT could tell me its subtokens, that would be very useful for highlighting.

It could also be used in the implementation of a linter, since a linter both needs to know if something is an argument or an assignment, and also details about what type of argument it is.

In creating a debugger or editor, it could also be useful when a user double-clicks on something to know whether they clicked on a variable, a setting, or something else.  Sometimes it's useful to know the class of something (eg: setting, argument) and sometimes it's useful to know something more specific (a setup setting, a variable argument, etc). 

> I'm not going to make big changes to the lexer at this point.

I understand that. I'm not asking for a big change, I was just offering an idea of how to implement this in a more general-purpose way. By tightly binding the solution to variables, and requiring a special flag be sent when tokenizing, it makes it hard to extend the tokenizer in the future. If instead you use a design that can be extended to other token types, that leaves the door open to similar improvements for other tokens. 

So, my proposal is simply that you do not require an extra flag be set to get this additional information. Instead, a `subtokens` property (or `details` or call it whatever you want) could have (or generate) this information. This only needs to be done for the ARGUMENT token type right now, but it makes it possible to extend the concept for other tokens in the future.

**Comment by pekkaklarck** [comment] 2020-02-22 23:17
What would be the sub token with an argument like `foo ${bar}`?

**Comment by boakley** [comment] 2020-02-23 00:13
Assuming `foo` is a keyword and `${bar}` is an argument, the token would be ARGUMENT as it is now and the subtoken might be a list with a single VARIABLE in it.

**Comment by pekkaklarck** [comment] 2020-02-23 00:19
No, `foo ${bar}` is a single argument with a literal string followed by a variable. Could also be something more complicated like `a${b}c${d}${e}[0]f`.

**Comment by boakley** [comment] 2020-02-23 00:45
I guess it would be whatever your original solution would return. You don't have a token for a string type, but perhaps you create one so it would be a list of STRING and then VARIABLE.

In the case of `a${b}c${d}${e}[0]f` it could be `[STRING, VARIABLE, STRING, VARIABLE, VARIABLE, STRING]`, or whatever your original proposal would return. 

The idea is to take your original implementation, but instead of returning it instead of ARGUMENT, the tokenizer would continue to return ARGUMENT, but with a subtoken or detail or some other attribute that has what your original proposal would return.

**Comment by pekkaklarck** [comment] 2020-02-23 08:09
So you propose same that [I did earlier](https://github.com/robotframework/robotframework/issues/3449#issuecomment-582895349) with these changes:
- Rename `tokenize_variables` to `subtokens`.
- Add new `STRING` type and use it with literal strings instead of `ARGUMENT`.
- Don't enhance `get_tokens` to automatically tokenize variables.

**Comment by boakley** [comment] 2020-02-23 18:22
Not quite. Your proposal seems to make `tokenize_variables` a parameter to be passed in. I don't think the caller should have to call  `get_tokens` any differently than it is now. Instead, the returned tokens should have a method or property that can be used to get an additional level of tokenization.

**Comment by pekkaklarck** [comment] 2020-02-23 19:46
If you look at the code closely, there's `Token.tokenize_variables`. The `tokenize_variables` argument to `get_tokens` is just convenience to call that method automatically. Notice that it is optional and defaults to `False`.

**Comment by boakley** [comment] 2020-02-24 03:57
Your proposed solution seems to return different information depending on the setting of `tokenize_variables`. I think the api would be better if it did not require passing it an extra argument to get the extra data. The data should just always be accessible. 

Perhaps the problem is that `_tokenize_variables` is marked as a private function, so I'm assuming I couldn't (well, _shouldn't_) call it externally. So, the only way to get the extra information is to set `tokenize_variables` to `True`. 

If it were a public function so that with any token I could do `token.tokenize_variables` that would be better, but I still think the API would be better if it weren't so tightly bound to variables. If you renamed `_tokenize_variables` to something like `subtokens` or `details` or something else that's a bit more generic, it would leave the door open to have it do more than just work on variables.

**Comment by pekkaklarck** [comment] 2020-02-24 07:52
Let me try to explain this once more:
- The `Token` class has `tokenize_variables` method. Both the class and the method are public.
- This means that every token instance you'd get from `get_tokens`, regardless how you call it, has it. Basics of object oriented programming.
- Thus this is already true: "If it were a public function so that with any token I could do `token.tokenize_variables` that would be better".
- The argument to `get_tokens` is just extra convenience. You can totally forget about it if it makes it easier to understand the above. You wouldn't need to use it and `token.tokenize_variables` would still work.

The point that `tokenize_variables` could be renamed to `subtokens` is valid. I don't see any other use cases for "sub-tokens" than variables, though, and trying to make the API to more generic in this situation doesn't IMHO make sense. If we'd ever need something similar, we could either add new `tokenize_foobuzz` method or then add generic sub-token support.

**Comment by pekkaklarck** [comment] 2020-02-26 14:22
In some earlier comment @boakley mentioned that some of the tokens are surprisingly detailed (e.g. `SETUP`, `TAGS`) and proposed that tokens would have higher level types (e.g. `SETTING`) and then the "sub-tokens" approach could be used to get more details. Two comments related to that:

- As I mentioned already earlier, the parser uses all the current tokens. It could obviously be changed to use the higher level tokens and then get details via them, but this would be a big change. I don't see any real concrete benefits from it and I'm also worried it would slow down parsing.

- Also tooling using the parsing model (i.e. the `robot.api.get_model` API) benefit from detailed tokens. Tools wanting to modify a certain setting can implement `ast.NodeVisitor` for that setting only, but we also have our own `ModelVisitor` that makes it easy to inspect/modify all settings. This model is just not yet documented adequately, but better docs will be written before RF 3.2 final.

- The `Token` class has `SETTING_TOKENS` attribute that contains all setting tokens. If a tool inspecting tokens wants to handle all settings the same way, it can easily do `if token.type in Token.SETTING_TOKENS: ...`.

**Comment by pekkaklarck** [comment] 2020-02-26 14:42
Below is an updated version my earlier proposal. It takes into account that not only `ARGUMENT` tokens can have variables, returns the token itself (no `TypeError`) with other tokens, and doesn't yield unnecessary empty values.

This time there are only changes to the `Token` class, but I'd also add `tokenize_variables=False` to `get_tokens` to ease tokenizing all variables. If these changes are considered good enough for IDEs and other external tools, I can write some tests and commit changes.

```diff
diff --git a/src/robot/parsing/lexer/tokens.py b/src/robot/parsing/lexer/tokens.py
index d43f2bf..7529239 100644
--- a/src/robot/parsing/lexer/tokens.py
+++ b/src/robot/parsing/lexer/tokens.py
@@ -14,6 +14,7 @@
 #  limitations under the License.
 
 from robot.utils import py2to3
+from robot.variables import VariableIterator
 
 
 @py2to3
@@ -105,6 +106,12 @@ class Token(object):
         KEYWORD_HEADER,
         COMMENT_HEADER
     )
+    ALLOW_VARIABLES = (
+        NAME,
+        ARGUMENT,
+        TESTCASE_NAME,
+        KEYWORD_NAME
+    )
 
     __slots__ = ['type', 'value', 'lineno', 'col_offset', 'error']
 
@@ -125,6 +132,27 @@ class Token(object):
         self.type = Token.ERROR if not fatal else Token.FATAL_ERROR
         self.error = error
 
+    def tokenize_variables(self):
+        if self.type not in Token.ALLOW_VARIABLES:
+            return [self]
+        variables = VariableIterator(self.value)
+        if not variables:
+            return [self]
+        return list(self._tokenize_variables(variables))
+
+    def _tokenize_variables(self, variables):
+        lineno = self.lineno
+        col_offset = self.col_offset
+        remaining = ''
+        for before, match, remaining in variables:
+            if before:
+                yield Token(self.type, before, lineno, col_offset)
+                col_offset += len(before)
+            yield Token(Token.VARIABLE, match, lineno, col_offset)
+            col_offset += len(match)
+        if remaining:
+            yield Token(self.type, remaining, lineno, col_offset)
+
     def __unicode__(self):
         return self.value
```

**Comment by boakley** [comment] 2020-02-26 17:13
I don't understand the need for having to explicitly set `tokenize_variables` to true to get the extra information. Is it because this will noticeably slow down the parsing time and you don't want to take that hit in the default case? 

Whether that parameter is there or not, I think this is definitely a much better solution. Thanks!

**Comment by pekkaklarck** [comment] 2020-02-26 17:52
You don't need to set `tokenize_variables=True` to get this information. You can alternative call `token.tokenize_variables()`. The parser cannot use either of these because it needs the higher level tokens to be able to construct the model. It also isn't interested in variables at all, they are resolved only at the run time.

**Comment by pekkaklarck** [comment] 2020-03-02 13:27
Do you @fabioz have opinion about this from the LSP point of view? If the [latest proposal](https://github.com/robotframework/robotframework/issues/3449#issuecomment-591460786) looks good, I could add some tests and commit it.

**Comment by fabioz** [comment] 2020-03-04 13:01
I think that the current proposal looks good, so, `+1` from me.

One proposed (minor) change is that maybe it could return tuples instead of lists (I can't think of use-cases for using the returned list and tuples are a bit more efficient) -- maybe even having just the generator directly instead of having the intermediary list/tuple would already be ok here.

**Comment by pekkaklarck** [comment] 2020-03-04 13:28
`tokenize_variables` can be easily changed to a generator.

**Closed** 2020-03-04 16:48 UTC
Labels: priority: medium, rc 1, no notes

**Comment by pekkaklarck** [comment] 2020-03-04 16:50
This is now down. I consider this an integral part of the new parser and thus changed issue type from enhancement to task which means it won't be shown in release notes on its own.
