### ISSUE TITLE
Method of Listener-Interface is not called

### ISSUE THREAD

**Issue by lca-afi** [robotframework/robotframework#3010] opened 2018-11-22 10:39 UTC
We have updated our environment to using Java Runtime V11.
Subsequently we had to update the version of org.robotframework.ide.eclipse.main from 0.8.7 to 0.8.9 since we had problems with JAXB-stuff. 

Now, as we have updated the robot framework to V0.8.9 the method "startTest" of the listener interface gets not called anymore.

We are using listener API V3 and our "startTest" method looks like the following:

`public void startTest(final Object testCaseName, final PyObjectDerived result)
    throws Exception
  {
    <our code>
  }`

Is there a problem somewhere in the framework or are we doing something wrong?
Thank you very much for any help!

**Comment by lca-afi** [comment] 2018-11-22 13:19
I also tried to use the newest versions of javalib-core and robotframework itself (1.2.1 resp. 3.0.4) but it still does not work.

**Comment by pekkaklarck** [comment] 2018-11-29 10:15
Did this work with some earlier version? Notice that listener v3 isn't really supported with Java, but if it works that's great. Notice also that the first argument passed to `startTest` isn't the name but the executed test case object itself.

**Comment by lca-afi** [comment] 2018-11-29 10:19
Hi Pekka,

yes, this worked when we used the robot-framework and jython with Java 8 (I don't know the exact versions of robot-framework and jython at the moment).

Listener v3 did work with Java also well in this scenario.
We already found out, what the problem is. It looks like the current version of Jython does not work with Java 11.

So now we are trying the approach to adapt our Keyword library (and so also the listener) to Python, and the first trys with this new lib, showed that it should work. 

Thanks for your hints and help. =)

**Comment by pekkaklarck** [comment] 2018-11-29 10:51
Yeah, there have been lot of changes to Java lately that cause problems with Jython. Jython 2.7.2 ought to fix some of those, but unfortunately Jython project isn't very active at the moment and that version hasn't been released yet. Anyway, because the problem isn't in Robot I close this issue.

**Closed by pekkaklarck** 2018-11-29 10:51 UTC
