### ISSUE TITLE
The way to determine java_match needs to be improved

### ISSUE THREAD

**Issue by ffang** [robotframework/robotframework#4099] opened 2021-09-28 16:47 UTC
Currently in src/robot/utils/platform.py
the way to determine java_match is like
```
java_match = re.match(r'java(\d+)\.(\d+)\.(\d+)', sys.platform)
if java_match:
    JYTHON = True
    JAVA_VERSION = tuple(int(i) for i in java_match.groups())
```
This works while java version is like "11.0.12" or "1.8.0_261". However this doesn't work while java version is "17" (or something like 18-ea), which is the latest JDK17 release version.  This will cause JYTHON = false and hence can't load JYTHON lib when using JAVA

The regex used here needs to be improved to cover more cases.

**Comment by pekkaklarck** [comment] 2021-09-29 21:49
Great analysis @ffang! It's interesting that this issue and #4100 with this exact problem as its root cause were reported the same day. Do you and @csantune who reported the latter issue possibly work together or is this a pure coincidence?

Anyway, I have already fixed #4100 by enhancing Java/Jython detection in c3c20d1403834ad25fe66043ac9c0e77533c0522. Although this issue was actually submitted first, I close this as a duplicate of #4100 because it contains a bit more history.

**Closed by pekkaklarck** 2021-09-29 21:49 UTC

**Comment by ffang** [comment] 2021-09-29 23:42
Hi @pekkaklarck ,

Thanks so much to fix this up very quickly!

And this is just a pure coincidence with #4100, and yes, the root cause and even behaviour are exactly same.
We ran into this issue in Apache Camel(Please see https://issues.apache.org/jira/browse/CAMEL-16967) with JDK17

Cheers
Freeman

**Comment by pekkaklarck** [comment] 2021-09-30 07:05
This was a pretty strange coincidence then! If I had noticed this issue first, I wouldn't have needed to debug it myself as you had already figured out the root cause. I'll create RF 4.1.2 rc 1 today so it will be easy for you to test the fix. If no problems are found, the final release will be next Thursday.

**Comment by ffang** [comment] 2021-09-30 11:41
> This was a pretty strange coincidence then! If I had noticed this issue first, I wouldn't have needed to debug it myself as you had already figured out the root cause. I'll create RF 4.1.2 rc 1 today so it will be easy for you to test the fix. If no problems are found, the final release will be next Thursday.

Thanks @pekkaklarck ! Sure I will test RF 4.1.2 rc1

**Comment by pekkaklarck** [comment] 2021-10-20 22:33
@Hi-Fi told on Slack that he has created the jar. It ought to be available at the Maven Central now as well. Notice that we'll need RF 4.1.3 due to an unfortunate regression. If there are still problems with Java integration, they can be fixed at the same time.
