### ISSUE TITLE
Parsing model: `Documentation.from_params(...).value` doesn't work

### ISSUE THREAD

**Issue by d-biehl** [robotframework/robotframework#4670] opened 2023-03-03 22:17 UTC
Documentation.from_params(...) has problems with multiline values and empty lines.

Must be investigated more closely and there must be more tests about this.

https://github.com/robotframework/robotframework/blob/c80464b98f1efff1d966865eddec6120cf95ad18/src/robot/parsing/model/statements.py#L166

Revert this commit 0c5d7f1fcac4ef9bd0178df27528e985af7dafb6 from "custom parsers" #4614 because it should be fixed independently.

**Comment by pekkaklarck** [comment] 2023-03-06 18:28
Could you clarify the issue? There's a [unit test](https://github.com/robotframework/robotframework/blob/master/utest/parsing/test_statements.py#L402) for `Documentation.from_params` that seems to test it pretty well.

**Comment by d-biehl** [comment] 2023-03-17 18:07
But there is no test case to check the value property of the Documentation, here it fails with multiline values and empty lines.
If you find something, its ok, otherwise I will look at this at sunday.

**Comment by d-biehl** [comment] 2023-03-18 14:50
```python
from robot.api.parsing import Documentation

multiple_lines = """This is a documentation

This is a second line

This is a third line"""

documentation = Documentation.from_params(multiple_lines)
print(documentation.value)
```

throws an `AttributeError? 

```
Traceback (most recent call last):
  File "c:\develop\robot\robotcode\playground\aa.py", line 12, in <module>
    print(documentation.value)
          ^^^^^^^^^^^^^^^^^^^
  File "C:\develop\robot\robotcode\.hatch\devel.py311-rf60\Lib\site-packages\robot\parsing\model\statements.py", line 349, in value
    return self._join_value(tokens)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\develop\robot\robotcode\.hatch\devel.py311-rf60\Lib\site-packages\robot\parsing\model\statements.py", line 156, in _join_value
    lines = self._get_lines(tokens)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\develop\robot\robotcode\.hatch\devel.py311-rf60\Lib\site-packages\robot\parsing\model\statements.py", line 167, in _get_lines
    line.append(t.value)
    ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'append'
```

**Comment by d-biehl** [comment] 2023-03-18 14:54
The tests for from_param only verifies that the tokens are correct, but not the value.

**Comment by d-biehl** [comment] 2023-03-18 15:49
I think this should also work correctly, just an idea for a unittest or a marker to check this out.

```python
from io import StringIO

from robot.api.parsing import Documentation, File, SectionHeader, SettingSection, Token, get_model

documentation_as_str = """This is a    documentation

This is a second line

This is a third line"""


documentation = Documentation.from_params(documentation_as_str)
settings = SettingSection(SectionHeader.from_params(Token.SETTING_HEADER), [documentation])

file = File()
file.sections.append(settings)

with StringIO() as f:
    file.save(f)
    new_file: File = get_model(f.getvalue())

assert (
    documentation_as_str == new_file.sections[0].body[0].value
), f"\n{documentation_as_str}\n!=\n{new_file.sections[0].body[0].value}"
```

the `documentation_as_str` has in the first line a space with multiple following spaces, this is a new argument in RobotFramework and results in a wrong robot file.

**Comment by pekkaklarck** [comment] 2023-03-20 13:31
Ok, I can now reproduce the issue. The problem seems to be in `value` property when tokens don't have proper line numbers set. Need to see can it be fixed in `value` itself or does `from_params` need to be enhanced instead.

I didn't test the latter issue yet. Is the problem that spaces in documentation are collapsed? If yes, that's according to documentation parsing rules.

**Comment by d-biehl** [comment] 2023-03-20 17:09
For the last point the value is taken over 1 to 1 when saving the file. That means if I have 2 spaces in a Token.value, the one token in the saved document becomes 2 tokens.
This also happens if I have line breaks in the Token.value. Under certain circumstances the saved file becomes invalid.

But this is more a problem in the ModelWriter, I think here invalid characters should be escaped when the token is written. That would be 1 solution. 
The other, maybe better, would be to check the tokens for invalid characters when passing them to from_params and then escape them accordingly. This is not only the case for the documentation statement but also for all other statements.

**Comment by pekkaklarck** [comment] 2023-03-21 08:29
Yes, if you create any token with more than two spaces in the value, those spaces will be considered a separator when the data is parsed back. It would probably be easiest to handle this when writing data back to the file system. Changing all `from_params` would be lot of work and wouldn't avoid the issue if `token.value` is set otherwise. Anyway, this is a topic for a separate issue.

**Comment by pekkaklarck** [comment] 2023-03-21 08:38
I got the `Documentation.from_params(...).value` problem solved. There were two issues explained below.

The main problem was that the `value` property didn't work if underlying tokens didn't have line numbers set. It needs them to know on which line documentation parts are to be able to add newlines properly. I fixed this by looking for `EOL` tokens as newline markers in addition to looking for line numbers. Couldn't use only `EOL`s because they aren't available during execution or otherwise when data is parsed with `data_only=True`.

A smaller issue was that `from_params` did handle multiline documentation with empty lines properly. An empty line was represented only by tokens `Token(Token.CONTINUE, '...')` and `Token(Token.EOL, eol)`, but there needs to be `Token(Token.ARGUMENT, '')` between them. Without that the whole line is ignored.

I still need to cleanup the code and possibly add few more tests but I'll commit and push the fix shortly.

**Closed** 2023-03-21 09:02 UTC
Labels: bug, priority: medium, effort: small
