### ISSUE TITLE
"Run Keyword And Ignore Error" does not ignore timeout errors

### ISSUE THREAD

**Issue by dimanhsb** [robotframework/robotframework#2376] opened 2016-05-25 07:02 UTC
Hello,

Consider the following code:

```
*** Test Cases ***
TC
    Run Keyword And Ignore Error  kw
    Log to console  b

*** Keywords ***
kw
    [timeout]  1s
    Log To Console  a
    Sleep  2s

```

The keyword `Log to console  b` is not executed, and the TC is failed. Is there a way around this limitation?

**Comment by dimanhsb** [comment] 2016-05-25 07:10
I did edit the errors.py in my local installation, the dont_continue function, in order to not fail on timeouts, but I was wondering if a "soft timeout" feature or a command line switch should be added.

**Comment by pekkaklarck** [comment] 2016-05-31 10:14
Errors caused by timeouts not being caught by this keyword is a [documented feature](http://robotframework.org/robotframework/latest/libraries/BuiltIn.html#Run%20Keyword%20And%20Ignore%20Error) that cannot be changed. If someone wants to implement a separate keyword `Run Keyword And Ignore Timeout` it can be added.

**Comment by dimanhsb** [comment] 2016-06-02 08:59
I was mostly considering a `Run Keyword And Continue On Timeout` feature, as I want to capture the failure (or maybe both)

**Comment by pekkaklarck** [comment] 2016-06-02 09:06
What would be the semantics of this keyword? Continue execution but in the end fail anyway?

**Comment by dimanhsb** [comment] 2016-06-02 09:24
Yes, I was thinking of a way to revert the timeout failures to the standard handling of KW failures, and let the user control those via keywords like `Run Keyword And Ignore Error` , `Wait Until Keyword Succeeds`, `Run Keyword And Continue On Failure`, `Run Keyword And Expect Error` etc.

**Comment by dimanhsb** [comment] 2016-06-02 09:31
By the way, let me give my specific example:

There is either a bug, or a misconfiguration from my part in Selenium2Library:
The KW `Open Browser` sometimes hangs, without returning any failure (for some reason, maybe the driver for the specific browser has a bug), I would say 1% of the time (or less). Either way, if the browser doesn't start in 20sec or so, I want to "kill" this keyword and retry opening the browser (with the dont_continue hack I've done, this now works succesfully).

**Comment by sameer49** [comment] 2017-01-12 11:32
@dimanhsb can you tell how handled above problem?

**Comment by sameer49** [comment] 2017-01-17 14:33
@dimanhsb
since I am using python binding,  I handled open browser hang issues by writing custom python function which create own browser instance using core selenium library and assign that instance session to robot selenium library.

```
se2lib = BuiltIn().get_library_instance('Selenium2Library')
browser = webdriver.Firefox()
browser.get(url)
se2lib._cache.current = browser
```

**Comment by pekkaklarck** [comment] 2017-01-30 09:00
After thinking this a bit more, I don't think catching Robot's timeout errors is a good approach in general and I close this issue. If I got it correctly, the main use case for it would be stopping execution of a buggy keyword and re-try running it. There are, in my opinion, better solutions to this problem.

First of all, it would be best to handle this problem in the keyword itself. Preferably by fixing the bug, but alternatively the keyword could get some kind of a re-try functionality.

In Robot side it would be clearer to have a separate keyword that executes another keyword but stops it if it takes too long. Something like this:

    Run Keyword With Maximum Time    10 seconds    Some keyword    argument

This keyword should fail if the underlying keyword doesn't return in the specified time, but that should be a normal failure that could then be handled with other BuiltIn keywords if needed. Internally this keyword could use Robot's timeout logic.

**Closed by pekkaklarck** 2017-01-30 09:00 UTC
