### ISSUE TITLE
Unable to run a Test Set that uses Variables from a .py Variable file

### ISSUE THREAD

**Issue by n89rodri** [robotframework/robotframework#2574] opened 2017-04-08 00:36 UTC
Hi,

I created a variable file (.py file) that contains strings and integer variables, I'm using this variables file in a Test Set and the variables are recognize without issues but when I try to run the test cases the execution hangs and finally a got an error message (is an HTTP Request test case). 

`Valid Comment Create Executions                                       | FAIL |
Response Status Code not as expected: 502 != 200`

To troubleshoot the issue I created all the variables inside the Test Set (in the *** Variables *** section) and everything works fine.

Any recommendation?

You can see the attached files for the Variables and the Test Set where the variables are being used.
![variable file](https://cloud.githubusercontent.com/assets/25436892/24824251/2bf7d16e-1bc5-11e7-973e-fded710dfc0e.png)
![test set](https://cloud.githubusercontent.com/assets/25436892/24824257/2ef5a788-1bc5-11e7-9845-ca551fdc3406.png)

**Comment by pekkaklarck** [comment] 2017-04-12 11:12
Variable origin should not affect test execution. If you are certain this happens, please provide a simple example demonstrating the problem that we can use to reproduce it. For instructions see http://sscce.org/.

**Comment by pekkaklarck** [comment] 2018-04-11 09:35
Closing due to lack of information/example.

**Closed by pekkaklarck** 2018-04-11 09:35 UTC
