### ISSUE TITLE
Crash if listener executes library keyword in `end_test` in the dry-run mode

### ISSUE THREAD

**Issue by Panacea729** [robotframework/robotframework#5167] opened 2024-07-18 19:11 UTC
The 'NOT RUN' status is not part of the highlighter causing a `KeyError` to occur if the test case status is being logged to the console.
Missing key here:
https://github.com/robotframework/robotframework/blob/445ea971e43bb974392fe0de8bbcf8be88a6eb08/src/robot/output/console/highlighting.py#L101

Could, for example, be called here:
https://github.com/robotframework/robotframework/blob/445ea971e43bb974392fe0de8bbcf8be88a6eb08/src/robot/output/console/verbose.py#L52
https://github.com/robotframework/robotframework/blob/445ea971e43bb974392fe0de8bbcf8be88a6eb08/src/robot/output/console/verbose.py#L118

**Comment by pekkaklarck** [comment] 2024-07-20 09:02
Has this caused concrete errors somewhere? I'm not sure can tests even have the NOT RUN status.

**Comment by pekkaklarck** [comment] 2024-11-13 22:34
I was able to reproduce the problem by using the following listener in the dry-run mode:
```python
from robot.libraries.BuiltIn import BuiltIn

def end_test(data, result):
    print(result.status)
    builtin = BuiltIn()
    builtin.import_library("Collections")
    builtin.run_keyword("Lists should be equal", [], [])
    print(result.status)
```

The error was this:
```
[ ERROR ] Unexpected error: KeyError: 'NOT RUN'                               
Traceback (most recent call last):
  [snip]
  File "/home/peke/Devel/robotframework/src/robot/output/console/highlighting.py", line 112, in _highlighting
    start = {'PASS': highlighter.green,
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ...<2 lines>...
             'WARN': highlighter.yellow,
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~
             'SKIP': highlighter.yellow}[status]
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'NOT RUN'
```

The reason for the failure seems to be this:
- Test status is automatically updated based on keyword status.
- In the dry-run mode keyword status can be `NOT RUN`.
- Test gets the `NOT RUN` status even though it should never have it.
- Reporting test status on console fails because test has an invalid status.

A simple fix for this is not updating test status if keyword status is `NOT RUN`.

**Comment by pekkaklarck** [comment] 2024-11-13 22:54
Because the whole execution crashes, this is actually a pretty severe bug. Thanks for the report!

In possible future bug reports, please explain what happens and how to reproduce the problem a bit more explicitly. I didn't understand this properly until I reproduced it, and the issue looked so strange that I was about to just close it.

**Closed** 2024-11-13 22:58 UTC
Labels: priority: high, beta 1, effort: small
