### ISSUE TITLE
way to exit a given test if a test case fails and carry on with other test suites 

### ISSUE THREAD

**Issue by luke-h1** [robotframework/robotframework#4049] opened 2021-07-29 10:18 UTC
## description of the problem: 
Currently, the `--exitonfailure` CLI option allows you to exit a test with failures if a test case fails. This however doesn't work when you are running multiple robot tests at once (such as in CI). If you are using the `--exitonfailure` option and a given test fails, the remaining tests will also fail. I want to run a test suite and exit a given test if a test case fails and carry on with the rest of the suites that need to run. This would benefit from finding test failures quicker and reducing the time RF tests take to run in CI. It would be nice to be able to exit a given test if an assertion fails and carry on with any remaining tests in the suite. 

## proposed solution: 
Add a CLI option that allows a user to exit a given test if an assertion fails and carry on with any remaining tests in the suite.

**Comment by pekkaklarck** [comment] 2021-08-02 14:19
It's true there's no way to stop the current suite when tests are running and continue from the next one. If a failure occurs in suite setup, tests in that suite aren't run, but there's no direct way to accomplish this when tests in the suite are already running. `--exitonfailure` stops the whole execution and `Fatal Error` keyword works the same way.

Something like this has been requested already earlier (there may even be an issue about it but I don't have time to search right now). I think the proposal was to add a keyword like ´Fatal Error` that stops the current suite and I think that's a more flexible solution than a command line option. A benefit of a keyword would be that it could be configured to tell from which suite level to continue. For example, if you have a suite structure like below and are running suite1.1, you may want to continue from suite1.2 or from mid suite 2. Possibly we could just enhance `Fatal Error` to accept such configuration.
```
                 root suite
              /              \ 
     mid suite 1             mid suite 2
    /           \           /           \
suite1.1    suite1.2    suite2.1    suite2.2

```

**Comment by luke-h1** [comment] 2021-08-02 16:26
Cool, appreciate the reply. If this has already been requested then I think it's safe to close this issue (no point in duplication). If I get the time to investigate this & figure out a way to implement this logic I'll raise a PR for it (as long as that's alright). Thanks!

**Comment by pekkaklarck** [comment] 2021-08-03 14:58
This has been discussed before but I don't remember is there a concrete issue about this. Could you search for issues and either comment a relevant issue or re-open this one?

**Comment by luke-h1** [comment] 2021-08-03 15:32
I've taken a quick look through closed issues but can't seem to find a similar issue to this. I'll re-open this one and leave a comment if I come across the previous issue.

**Comment by myjniak** [comment] 2021-08-31 11:40
I believe @pekkaklarck remembered my issue:
https://github.com/robotframework/robotframework/issues/3493

**Comment by pekkaklarck** [comment] 2023-11-29 19:40
Closing as a duplicate of #3493.

**Closed by pekkaklarck** 2023-11-29 19:40 UTC
