### ISSUE TITLE
Values of Robot Framework Automatic Variables (${TEST STATUS} and ${SUITE STATUS}) not correct in certain scenarios.

### ISSUE THREAD

**Issue by arunku2x** [robotframework/robotframework#2429] opened 2016-08-24 00:57 UTC
Hi,

I have found that the values of Robot Framework Automatic Variables (${TEST STATUS} and ${SUITE STATUS}) not correct in the following scenarios.

1. Added Test Timeout parameter under Test Suite settings so that it becomes applicable for all test cases under the test suite. Observed that in case a test case is timed out, its status ${TEST STATUS} still return PASS in Test Case Teardown section. This happens if a keyword in Test Case Teardown is timed out.

2. There was a failure in Test Suite Teardown section but its status ${SUITE STATUS} returned PASS.

I want to perform some actions in Test Case and Test Suite teardown sections on the basis of test case and test suite status but due to inconsistent status of these variable, not able to do so.

Could you please look into these issues.

**Comment by pekkaklarck** [comment] 2016-08-24 10:04
This is a variation of #2078. Test timeout occurring during the teardown is a bit more problematic than a normal failure, though, becuase test timeouts are, by design, disabled during the teardown to allow teardowns to run fully. Robot only marks the test failed after the test ended if it in the end took too much time. I'll update #2078 accordingly and close this issue.

Notice that the required changes to actually fix this are pretty large. They cannot be done in RF 3.0.1 release but need to wait for a major version. Unfortunately I cannot give any promises when RF 3.1 would be release nor would these fixes make into that release.

**Closed by pekkaklarck** 2016-08-24 10:04 UTC

**Comment by arunku2x** [comment] 2016-08-25 00:55
Hi Pekka,

As an alternative, I switched to listeners. I have added listener for end_test and end_suite and taking decision on the basis of attrs['status'] field inside these listener functions. Here as well, I have observed one weird issue. I had a test suite containing 7 test cases. Now all the test cases inside this test suite failed and I got correct test case status inside "end_test" listener. The issue which I have observed is that test suite status inside "end_suite" listener shows up as PASS. Wouldn't it be FAIL even if 1 test case inside the test suite fails.

Regards,

Arun Kumar Saini

**Comment by pekkaklarck** [comment] 2016-08-25 08:47
Suite status is PASS if all *critical* tests pass. Most likely cause for your issue is that tests are non-critical. If that's not the case, please submit a separate issue with instructions how to reproduce the problem. An executable example would be best.
