### ISSUE TITLE
Logger API: unable to post HTML message from python

### ISSUE THREAD

**Issue by oleksiybondar** [robotframework/robotframework#2474] opened 2016-11-16 21:26 UTC
html=true option works only from robot side but not from python

I have some piece of code, a library, which performs some operations and in case of NON Critical Error it should post a screen snap, but it doesn't, the message in output.xml just being appended to a current message node and simply ignores that

heres a sample used code inside library:
part of logger class
```
from robot.api import logger
from robot.output import librarylogger
.
.
.
   @staticmethod
    def write_robot(entry, html=False):
        """
        performs console output when runtime is robot framework
        :return: None
        """
        log_entry="{1} {2}".format(entry['time'], entry['message'])
        logger.write(log_entry, Log.ROBOT_LEVELS[entry['level']], html)
        if entry['extended']:
          logger.write(entry['extended'], Log.ROBOT_LEVELS[entry['level']], html)

```
debug lib:
```
import Log

class DebugLib:
    
    def print_message_set(self, set_no=0):
        image_base64 = '<base64 should be here>'
        Log.info('info message 1 from set No {0}'.format(set_no))
        Log.info('info message 2 from set No {0} with escaped HTML'.format(set_no),
                 '<strong>some bold text</strong>')
        Log.info('info message 3 from set No {0}  with HTML'.format(set_no),
                 '<img src="{0}"><br/><strong>Some Image description</>'.format(image_base64),
                 html='yes')
        Log.info('info message 4 from set No {0}'.format(set_no))
```
robot code:
```
*** Settings ***
Library             DebugLib

*** Test Cases ***

HTML Logger test1
    print message set    1
    
HTML Logger test3
    Log   some crap
    Log   <strong>some strong text</strong>
    Log   <img src="<base64 should be here>"><br/><strong>Some Image description</>    html=True
    Log   another crap
```

actual result: 
http://prntscr.com/d86g4o
http://prntscr.com/d86gdv

expected result:
HTML Logger test1 should escape html only in places which should be

additional info:
I've tried to modify my code in a way which would simulate keyword execution like it can be seen in pure robot example on screen snap, but it also didn't worked

```
        log_entry="{1} {2}".format(entry['time'],
                                   entry['message'])
        if html:
            LOGGER.start_keyword('HTML LOG BLOCK')
        logger.write(log_entry, Log.ROBOT_LEVELS[entry['level']], html)
        if entry['extended']:
            logger.write(entry['extended'], Log.ROBOT_LEVELS[entry['level']], html)
        if html:
            LOGGER.end_keyword('HTML LOG BLOCK')
```

**Comment by pekkaklarck** [comment] 2016-11-18 14:13
Your example is fairly complicated and doesn't even seem to show all the actual code. Could you first test can you simply use `logger.write('<b>test</b>', html=True)`? If that works, then the bug is very likely on your code.

If you are convinced that the problem is on Robot side, please provide a simple example demonstrating the problem that others can also run on their machines. Notice also that you shouldn't need to use anything else than `robot.api.logger` in your code for logging purposes. For example, `robot.output` is internal API and subject to change in future versions.

**Comment by pekkaklarck** [comment] 2016-12-22 11:39
Closing due to lack of new information.

**Closed by pekkaklarck** 2016-12-22 11:39 UTC
