### ISSUE TITLE
请教：在VsCode使用RobotCode插件执行时如何配置log.html、output.xml和report.html文件的生成位置

### ISSUE THREAD

**Issue by Emptyio** [robotframework/robotframework#5183] opened 2024-08-15 08:58 UTC
在VsCode使用RobotCode插件执行时如何配置log.html、output.xml和report.html文件的生成位置
我想要让log文件 生成在 ./../results/YY-mm-dd HH:MM:SS /路径下 
如果可以希望可以带上执行用例的名称
希望可以给出方案
谢谢！！

**Comment by LowEQ** [comment] 2024-08-16 23:07
可以使用 .json 设置文件如：`workspace.json` 或者 `task.json` 进行传参 `--outputdir`，因为最终输出报告结果在我的认知中只能使用 `--outputdir` 进行定义（出自([正式文档](https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html))）
![image](https://github.com/user-attachments/assets/3f50a7e2-1051-46f9-87ee-9f250b491561)

比如正常console命令 会直接输出所有报告到 `../../results` 路径
`robot test.robot --outputdir "./../results/"`

[ .json 设置文件](https://forum.robotframework.org/t/how-to-store-output-files-into-specific-folder-based-on-platform-browser-and-its-version-dynamically-after-executing-the-test-script/4184/2)

![image](https://github.com/user-attachments/assets/6be3cfd3-011d-4db2-97ad-5ed8b582b2e0)

[workspace.json 设置文件](https://forum.robotframework.org/t/set-outputdir-in-vscode-workspace/3536)

如 `"args": ["--outputdir", "./../results/"]`

我想要让log文件 生成在 ./../results/YY-mm-dd HH:MM:SS /路径下，这个可能要倒腾下了，但是如果不需要新建日期时间文件夹

可以使用 `--timestampoutputs` 在报告尾部生成 日期时间
如 `robot test.robot --outputdir "./../results/" --timestampoutputs`
出自([功能](https://github.com/robotframework/robotframework/issues/2945))

**Comment by pekkaklarck** [comment] 2024-08-19 14:09
I'm sorry but I don't understand this and GitHub doesn't seem to have any easy translation option. Please submit issues using English.

If the problem is related to the VSCode plugin, please report it to its issue tracker. If you this isn't an actual bug, asking help on Slack or Forum would probably be a better idea.

**Comment by LowEQ** [comment] 2024-08-19 17:19
This is just an asking help ticket relating how to config RobotCode VSCode extension About how to make the log.html, output.xml and report.html outputpath to be under this path `./../results/YY-mm-dd HH:MM:SS/`. not really an bug report, just close this.

**Comment by LowEQ** [comment] 2024-08-19 17:20
> I'm sorry but I don't understand this and GitHub doesn't seem to have any easy translation option. Please submit issues using English.
> 
> If the problem is related to the VSCode plugin, please report it to its issue tracker. If you this isn't an actual bug, asking help on Slack or Forum would probably be a better idea.

This is just an asking help ticket relating how to config RobotCode VSCode extension about how to make the log.html, output.xml and report.html outputpath to be under this path `./../results/YY-mm-dd HH:MM:SS/`. not really an bug report, just close this.

**Comment by LowEQ** [comment] 2024-08-19 17:23
> 在VsCode使用RobotCode插件执行时如何配置log.html、output.xml和report.html文件的生成位置 我想要让log文件 生成在 ./../results/YY-mm-dd HH:MM:SS /路径下 如果可以希望可以带上执行用例的名称 希望可以给出方案 谢谢！！

>If you this isn't an actual bug, asking help on Slack or Forum would probably be a better idea.

这种寻求帮助的请在 Slack 或者 [Forms](https://forum.robotframework.org/) 可能更好

**Comment by LowEQ** [comment] 2024-08-19 17:50
> > 在VsCode使用RobotCode插件执行时如何配置log.html、output.xml和report.html文件的生成位置 我想要让log文件 生成在 ./../results/YY-mm-dd HH:MM:SS /路径下 如果可以希望可以带上执行用例的名称 希望可以给出方案 谢谢！！
> 
> > If you this isn't an actual bug, asking help on Slack or Forum would probably be a better idea.
> 
> 这种寻求帮助的请在 Slack 或者 [Forms](https://forum.robotframework.org/) 可能更好

But for me the solution for this would be creating a .bat file
```
@echo off
for /F "usebackq tokens=1,2 delims==" %%i in (`wmic os get LocalDateTime /VALUE 2^>NUL`) do if '.%%i.'=='.LocalDateTime.' set ldt=%%j
set ldt=%ldt:~0,4%-%ldt:~4,2%-%ldt:~6,2% %ldt:~8,2%:%ldt:~10,2%:%ldt:~12,6%

robot ./tests/*.robot --outputdir ./../results/[%ldt%]
echo %ldt%
```
something like that, I dont know if there way to config RobotCode extention to do this automatically,

**Closed** 2024-08-28 11:34 UTC
