### ISSUE TITLE
Bypass library cache and do full re-import.

### ISSUE THREAD

**Issue by mekerhult** [robotframework/robotframework#2007] opened 2015-06-01 11:34 UTC
Sometimes it is necessary to re-import a library, in my case the Remote library, and bypass the internal RF library and keyword caches.

Lets say that you have a remote server that between testcases gets new keywords loaded, then doing an import of Remote with the same server address and port will not do an import, and RF will not load any new keywords. Thus, it would be a nice feature to either de-register a library, or to re-import it. Maybe both. Preferably as an optional argument (Force import) to Import Library.

What do you think?

Thx for a great framework!

**Comment by pekkaklarck** [comment] 2015-06-01 15:38
This is pretty much a duplicate of #293. We try to finally get that issue resolved in RF 2.9.

**Closed by pekkaklarck** 2015-06-01 15:38 UTC
Labels: duplicate

**Comment by mekerhult** [comment] 2015-06-01 16:00
Grest, thanks Pekka!  I cross my fingers and hope for it to come in 2.9.
